@echo off
setlocal EnableExtensions EnableDelayedExpansion
chcp 65001 >nul
title TTCO - Bat dau vet khi bam Xem kq TTCO_APP - v14

set "CONFIG_DIR=%LOCALAPPDATA%\TTCO_Capture_TTCOAPP_Action"
set "PY_MAIN=%CONFIG_DIR%\TTCO_Capture_TTCOAPP_Action_v14.py"
set "B64_FILE=%CONFIG_DIR%\TTCO_Capture_TTCOAPP_Action_v14.b64"

if not exist "%CONFIG_DIR%" mkdir "%CONFIG_DIR%" >nul 2>&1

call :WRITE_PY
if errorlevel 1 (
    echo [LOI] Khong tao duoc file Python tam.
    pause
    exit /b 1
)

cls
echo ============================================================
echo   TTCO - BAT DAU VET KHI BAM XEM KQ TREN TTCO_APP - V14
echo ============================================================
echo.
echo File nay nhanh hon cach do toan bo:
echo - Chup trang thai SQL truoc khi anh bam Xem kq tren TTCO_APP.
echo - Anh bam Xem kq trong TTCO_APP.
echo - Chup lai trang thai SQL sau do.
echo - Tim bang nao vua thay doi/duoc TTCO_APP tao/cap nhat.
echo.
echo Ket qua xuat ra:
echo   Desktop\TTCO_CAPTURE_TTCOAPP_ACTION
echo.
pause

python "%PY_MAIN%"
echo.
echo Ket qua nam tai:
echo %USERPROFILE%\Desktop\TTCO_CAPTURE_TTCOAPP_ACTION
echo.
start "" "%USERPROFILE%\Desktop\TTCO_CAPTURE_TTCOAPP_ACTION"
pause
exit /b 0

:WRITE_PY
> "%B64_FILE%" echo CiMgLSotIGNvZGluZzogdXRmLTggLSotCmltcG9ydCBjc3YKaW1wb3J0IG9zCmltcG9ydCByZQpp
>> "%B64_FILE%" echo bXBvcnQgc3VicHJvY2VzcwppbXBvcnQgc3lzCmltcG9ydCB0aW1lCmZyb20gZGF0ZXRpbWUgaW1w
>> "%B64_FILE%" echo b3J0IGRhdGV0aW1lCmZyb20gcGF0aGxpYiBpbXBvcnQgUGF0aAoKU0VSVkVSID0gciJ0dXllbnRo
>> "%B64_FILE%" echo YW5jdWFvbmcuY29tLnZuLDUyMzc2IgpEQVRBQkFTRSA9ICJUVENPX1RIT05HS0UiCk1BU1RFUl9E
>> "%B64_FILE%" echo QiA9ICJUVENPX1FUSFQiClRBUkdFVF9LSE8xID0gMTA1Mi42NQoKVVNFUlBST0ZJTEUgPSBQYXRo
>> "%B64_FILE%" echo KG9zLmVudmlyb24uZ2V0KCJVU0VSUFJPRklMRSIsIHN0cihQYXRoLmhvbWUoKSkpKQpERVNLVE9Q
>> "%B64_FILE%" echo ID0gVVNFUlBST0ZJTEUgLyAiRGVza3RvcCIKT1VUX0RJUiA9IERFU0tUT1AgLyAiVFRDT19DQVBU
>> "%B64_FILE%" echo VVJFX1RUQ09BUFBfQUNUSU9OIgpPVVRfRElSLm1rZGlyKHBhcmVudHM9VHJ1ZSwgZXhpc3Rfb2s9
>> "%B64_FILE%" echo VHJ1ZSkKClNUQU1QID0gZGF0ZXRpbWUubm93KCkuc3RyZnRpbWUoIiVZJW0lZF8lSCVNJVMiKQpP
>> "%B64_FILE%" echo VVRfVFhUID0gT1VUX0RJUiAvIGYiY2FwdHVyZV90dGNvYXBwX2FjdGlvbl97U1RBTVB9LnR4dCIK
>> "%B64_FILE%" echo T1VUX0NTViA9IE9VVF9ESVIgLyBmImNhcHR1cmVfdHRjb2FwcF9hY3Rpb25fe1NUQU1QfS5jc3Yi
>> "%B64_FILE%" echo Ck9VVF9ERVRBSUwgPSBPVVRfRElSIC8gZiJjYW5kaWRhdGVfZGV0YWlsX3tTVEFNUH0udHh0IgoK
>> "%B64_FILE%" echo CmRlZiB3cml0ZShsaW5lPSIiKToKICAgIHByaW50KGxpbmUpCiAgICB3aXRoIE9VVF9UWFQub3Bl
>> "%B64_FILE%" echo bigiYSIsIGVuY29kaW5nPSJ1dGYtOCIpIGFzIGY6CiAgICAgICAgZi53cml0ZShzdHIobGluZSkg
>> "%B64_FILE%" echo KyAiXG4iKQoKCmRlZiBkZXRhaWwobGluZT0iIik6CiAgICB3aXRoIE9VVF9ERVRBSUwub3Blbigi
>> "%B64_FILE%" echo YSIsIGVuY29kaW5nPSJ1dGYtOCIpIGFzIGY6CiAgICAgICAgZi53cml0ZShzdHIobGluZSkgKyAi
>> "%B64_FILE%" echo XG4iKQoKCmRlZiBlbnN1cmVfcHlvZGJjKCk6CiAgICB0cnk6CiAgICAgICAgaW1wb3J0IHB5b2Ri
>> "%B64_FILE%" echo YyAgIyBub3FhCiAgICAgICAgcmV0dXJuCiAgICBleGNlcHQgRXhjZXB0aW9uOgogICAgICAgIHdy
>> "%B64_FILE%" echo aXRlKCJDaMawYSBjw7MgcHlvZGJjLiDEkGFuZyB0aOG7rSBjw6BpIHB5b2RiYy4uLiIpCiAgICAg
>> "%B64_FILE%" echo ICAgc3VicHJvY2Vzcy5jaGVja19jYWxsKFtzeXMuZXhlY3V0YWJsZSwgIi1tIiwgInBpcCIsICJp
>> "%B64_FILE%" echo bnN0YWxsIiwgInB5b2RiYyJdKQoKCmRlZiBjb25uZWN0KGRiPURBVEFCQVNFKToKICAgIGltcG9y
>> "%B64_FILE%" echo dCBweW9kYmMKICAgIGNvbm5fc3RyID0gKAogICAgICAgICJEUklWRVI9e09EQkMgRHJpdmVyIDE4
>> "%B64_FILE%" echo IGZvciBTUUwgU2VydmVyfTsiCiAgICAgICAgZiJTRVJWRVI9e1NFUlZFUn07IgogICAgICAgIGYi
>> "%B64_FILE%" echo REFUQUJBU0U9e2RifTsiCiAgICAgICAgIlRydXN0ZWRfQ29ubmVjdGlvbj15ZXM7IgogICAgICAg
>> "%B64_FILE%" echo ICJUcnVzdFNlcnZlckNlcnRpZmljYXRlPXllczsiCiAgICApCiAgICByZXR1cm4gcHlvZGJjLmNv
>> "%B64_FILE%" echo bm5lY3QoY29ubl9zdHIsIHRpbWVvdXQ9MjApCgoKZGVmIHFpZGVudChuYW1lKToKICAgIHJldHVy
>> "%B64_FILE%" echo biAiWyIgKyBzdHIobmFtZSkucmVwbGFjZSgiXSIsICJdXSIpICsgIl0iCgoKZGVmIHNhZmVfZmxv
>> "%B64_FILE%" echo YXQodik6CiAgICB0cnk6CiAgICAgICAgaWYgdiBpcyBOb25lOgogICAgICAgICAgICByZXR1cm4g
>> "%B64_FILE%" echo MC4wCiAgICAgICAgcmV0dXJuIGZsb2F0KHYpCiAgICBleGNlcHQgRXhjZXB0aW9uOgogICAgICAg
>> "%B64_FILE%" echo IHJldHVybiAwLjAKCgpkZWYgbm9ybWFsaXplKHYpOgogICAgaWYgdiBpcyBOb25lOgogICAgICAg
>> "%B64_FILE%" echo IHJldHVybiAiIgogICAgcmV0dXJuIHJlLnN1YihyIlxzKyIsICIgIiwgc3RyKHYpLnJlcGxhY2Uo
>> "%B64_FILE%" echo Ilx4YTAiLCAiICIpLnN0cmlwKCkpCgoKZGVmIGdldF90YWJsZXNfc25hcHNob3QoY3VyKToKICAg
>> "%B64_FILE%" echo IHNxbCA9ICIiIgogICAgU0VMRUNUCiAgICAgICAgcy5uYW1lIEFTIHNjaGVtYV9uYW1lLAogICAg
>> "%B64_FILE%" echo ICAgIHQubmFtZSBBUyB0YWJsZV9uYW1lLAogICAgICAgIHQuY3JlYXRlX2RhdGUsCiAgICAgICAg
>> "%B64_FILE%" echo dC5tb2RpZnlfZGF0ZSwKICAgICAgICBJU05VTEwoU1VNKHAucm93cyksIDApIEFTIHJvd19jb3Vu
>> "%B64_FILE%" echo dAogICAgRlJPTSBzeXMudGFibGVzIHQKICAgIElOTkVSIEpPSU4gc3lzLnNjaGVtYXMgcyBPTiB0
>> "%B64_FILE%" echo LnNjaGVtYV9pZCA9IHMuc2NoZW1hX2lkCiAgICBMRUZUIEpPSU4gc3lzLnBhcnRpdGlvbnMgcAog
>> "%B64_FILE%" echo ICAgICAgIE9OIHQub2JqZWN0X2lkID0gcC5vYmplY3RfaWQKICAgICAgIEFORCBwLmluZGV4X2lk
>> "%B64_FILE%" echo IElOICgwLCAxKQogICAgR1JPVVAgQlkgcy5uYW1lLCB0Lm5hbWUsIHQuY3JlYXRlX2RhdGUsIHQu
>> "%B64_FILE%" echo bW9kaWZ5X2RhdGUKICAgIE9SREVSIEJZIHQubW9kaWZ5X2RhdGUgREVTQywgdC5jcmVhdGVfZGF0
>> "%B64_FILE%" echo ZSBERVNDLCB0Lm5hbWUKICAgICIiIgogICAgcm93cyA9IGN1ci5leGVjdXRlKHNxbCkuZmV0Y2hh
>> "%B64_FILE%" echo bGwoKQogICAgc25hcCA9IHt9CiAgICBmb3IgciBpbiByb3dzOgogICAgICAgIGtleSA9IGYie3Iu
>> "%B64_FILE%" echo c2NoZW1hX25hbWV9LntyLnRhYmxlX25hbWV9IgogICAgICAgIHNuYXBba2V5XSA9IHsKICAgICAg
>> "%B64_FILE%" echo ICAgICAgInNjaGVtYSI6IHIuc2NoZW1hX25hbWUsCiAgICAgICAgICAgICJ0YWJsZSI6IHIudGFi
>> "%B64_FILE%" echo bGVfbmFtZSwKICAgICAgICAgICAgImNyZWF0ZV9kYXRlIjogc3RyKHIuY3JlYXRlX2RhdGUpLAog
>> "%B64_FILE%" echo ICAgICAgICAgICAibW9kaWZ5X2RhdGUiOiBzdHIoci5tb2RpZnlfZGF0ZSksCiAgICAgICAgICAg
>> "%B64_FILE%" echo ICJyb3dfY291bnQiOiBpbnQoci5yb3dfY291bnQgb3IgMCksCiAgICAgICAgfQogICAgcmV0dXJu
>> "%B64_FILE%" echo IHNuYXAKCgpkZWYgZ2V0X2NvbHVtbnMoY3VyLCBzY2hlbWEsIHRhYmxlKToKICAgIHJvd3MgPSBj
>> "%B64_FILE%" echo dXIuZXhlY3V0ZSgiIiIKICAgICAgICBTRUxFQ1QgQ09MVU1OX05BTUUsIERBVEFfVFlQRQogICAg
>> "%B64_FILE%" echo ICAgIEZST00gSU5GT1JNQVRJT05fU0NIRU1BLkNPTFVNTlMKICAgICAgICBXSEVSRSBUQUJMRV9T
>> "%B64_FILE%" echo Q0hFTUE9PyBBTkQgVEFCTEVfTkFNRT0/CiAgICAgICAgT1JERVIgQlkgT1JESU5BTF9QT1NJVElP
>> "%B64_FILE%" echo TgogICAgIiIiLCBzY2hlbWEsIHRhYmxlKS5mZXRjaGFsbCgpCiAgICByZXR1cm4gWyhyLkNPTFVN
>> "%B64_FILE%" echo Tl9OQU1FLCByLkRBVEFfVFlQRSkgZm9yIHIgaW4gcm93c10KCgpkZWYgc2NvcmVfdGFibGUobmFt
>> "%B64_FILE%" echo ZSwgYmVmb3JlX2luZm8sIGFmdGVyX2luZm8pOgogICAgbG93ZXIgPSBuYW1lLmxvd2VyKCkKICAg
>> "%B64_FILE%" echo IHNjb3JlID0gMAogICAga2V5d29yZHMgPSBbImczX2JjMDUiLCAiYmMwNSIsICJ0b24iLCAia2hv
>> "%B64_FILE%" echo IiwgInRoYW4iLCAidG1wIiwgImNkb3RoYW4iLCAibmhhcCIsICJ4dWF0IiwgImdpYW9uaGFuIl0K
>> "%B64_FILE%" echo ICAgIGZvciBrdyBpbiBrZXl3b3JkczoKICAgICAgICBpZiBrdyBpbiBsb3dlcjoKICAgICAgICAg
>> "%B64_FILE%" echo ICAgc2NvcmUgKz0gMTAKICAgIGlmIGJlZm9yZV9pbmZvIGlzIE5vbmU6CiAgICAgICAgc2NvcmUg
>> "%B64_FILE%" echo Kz0gMTAwCiAgICBlbHNlOgogICAgICAgIGlmIGJlZm9yZV9pbmZvLmdldCgibW9kaWZ5X2RhdGUi
>> "%B64_FILE%" echo KSAhPSBhZnRlcl9pbmZvLmdldCgibW9kaWZ5X2RhdGUiKToKICAgICAgICAgICAgc2NvcmUgKz0g
>> "%B64_FILE%" echo NTAKICAgICAgICBpZiBiZWZvcmVfaW5mby5nZXQoInJvd19jb3VudCIpICE9IGFmdGVyX2luZm8u
>> "%B64_FILE%" echo Z2V0KCJyb3dfY291bnQiKToKICAgICAgICAgICAgc2NvcmUgKz0gNTAKICAgIHJldHVybiBzY29y
>> "%B64_FILE%" echo ZQoKCmRlZiBjb21wYXJlX3NuYXBzaG90cyhiZWZvcmUsIGFmdGVyKToKICAgIGNhbmRpZGF0ZXMg
>> "%B64_FILE%" echo PSBbXQogICAga2V5cyA9IHNvcnRlZChzZXQoYmVmb3JlLmtleXMoKSkgfCBzZXQoYWZ0ZXIua2V5
>> "%B64_FILE%" echo cygpKSkKICAgIGZvciBrZXkgaW4ga2V5czoKICAgICAgICBiID0gYmVmb3JlLmdldChrZXkpCiAg
>> "%B64_FILE%" echo ICAgICAgYSA9IGFmdGVyLmdldChrZXkpCiAgICAgICAgaWYgYSBpcyBOb25lOgogICAgICAgICAg
>> "%B64_FILE%" echo ICBjb250aW51ZQoKICAgICAgICBjaGFuZ2VkID0gRmFsc2UKICAgICAgICByZWFzb24gPSBbXQog
>> "%B64_FILE%" echo ICAgICAgIGlmIGIgaXMgTm9uZToKICAgICAgICAgICAgY2hhbmdlZCA9IFRydWUKICAgICAgICAg
>> "%B64_FILE%" echo ICAgcmVhc29uLmFwcGVuZCgiTkVXX1RBQkxFIikKICAgICAgICBlbHNlOgogICAgICAgICAgICBp
>> "%B64_FILE%" echo ZiBiWyJtb2RpZnlfZGF0ZSJdICE9IGFbIm1vZGlmeV9kYXRlIl06CiAgICAgICAgICAgICAgICBj
>> "%B64_FILE%" echo aGFuZ2VkID0gVHJ1ZQogICAgICAgICAgICAgICAgcmVhc29uLmFwcGVuZCgiTU9ESUZZX0RBVEVf
>> "%B64_FILE%" echo Q0hBTkdFRCIpCiAgICAgICAgICAgIGlmIGJbInJvd19jb3VudCJdICE9IGFbInJvd19jb3VudCJd
>> "%B64_FILE%" echo OgogICAgICAgICAgICAgICAgY2hhbmdlZCA9IFRydWUKICAgICAgICAgICAgICAgIHJlYXNvbi5h
>> "%B64_FILE%" echo cHBlbmQoZiJST1dDT1VOVCB7Ylsncm93X2NvdW50J119IC0+IHthWydyb3dfY291bnQnXX0iKQoK
>> "%B64_FILE%" echo ICAgICAgICAjIEzhuqV5IHRow6ptIGPDoWMgYuG6o25nIHTDqm4gY8OzIHbhursgbGnDqm4gcXVh
>> "%B64_FILE%" echo biBuZ2F5IGPhuqMga2hpIG1vZGlmeV9kYXRlIGtow7RuZyDEkeG7lWksCiAgICAgICAgIyB2w6wg
>> "%B64_FILE%" echo U1FMIFNlcnZlciBraMO0bmcgcGjhuqNpIGzDumMgbsOgbyBjxaluZyDEkeG7lWkgbW9kaWZ5X2Rh
>> "%B64_FILE%" echo dGUga2hpIGluc2VydC91cGRhdGUuCiAgICAgICAgbG93ZXIgPSBrZXkubG93ZXIoKQogICAgICAg
>> "%B64_FILE%" echo IGxvb2tzX3JlbGF0ZWQgPSBhbnkoa3cgaW4gbG93ZXIgZm9yIGt3IGluIFsiZzNfYmMwNSIsICJi
>> "%B64_FILE%" echo YzA1IiwgInRvbiIsICJraG8iLCAidGhhbiIsICJ0bXAiXSkKICAgICAgICBpZiBjaGFuZ2VkIG9y
>> "%B64_FILE%" echo IGxvb2tzX3JlbGF0ZWQ6CiAgICAgICAgICAgIGNhbmRpZGF0ZXMuYXBwZW5kKHsKICAgICAgICAg
>> "%B64_FILE%" echo ICAgICAgICJrZXkiOiBrZXksCiAgICAgICAgICAgICAgICAic2NoZW1hIjogYVsic2NoZW1hIl0s
>> "%B64_FILE%" echo CiAgICAgICAgICAgICAgICAidGFibGUiOiBhWyJ0YWJsZSJdLAogICAgICAgICAgICAgICAgImJl
>> "%B64_FILE%" echo Zm9yZV9yb3dfY291bnQiOiBiWyJyb3dfY291bnQiXSBpZiBiIGVsc2UgIiIsCiAgICAgICAgICAg
>> "%B64_FILE%" echo ICAgICAiYWZ0ZXJfcm93X2NvdW50IjogYVsicm93X2NvdW50Il0sCiAgICAgICAgICAgICAgICAi
>> "%B64_FILE%" echo YmVmb3JlX21vZGlmeSI6IGJbIm1vZGlmeV9kYXRlIl0gaWYgYiBlbHNlICIiLAogICAgICAgICAg
>> "%B64_FILE%" echo ICAgICAgImFmdGVyX21vZGlmeSI6IGFbIm1vZGlmeV9kYXRlIl0sCiAgICAgICAgICAgICAgICAi
>> "%B64_FILE%" echo Y3JlYXRlX2RhdGUiOiBhWyJjcmVhdGVfZGF0ZSJdLAogICAgICAgICAgICAgICAgInJlYXNvbiI6
>> "%B64_FILE%" echo ICI7ICIuam9pbihyZWFzb24pIGlmIHJlYXNvbiBlbHNlICJSRUxBVEVEX05BTUUiLAogICAgICAg
>> "%B64_FILE%" echo ICAgICAgICAgInNjb3JlIjogc2NvcmVfdGFibGUoa2V5LCBiLCBhKSwKICAgICAgICAgICAgfSkK
>> "%B64_FILE%" echo CiAgICBjYW5kaWRhdGVzLnNvcnQoa2V5PWxhbWJkYSB4OiAoLXhbInNjb3JlIl0sIHhbImtleSJd
>> "%B64_FILE%" echo KSkKICAgIHJldHVybiBjYW5kaWRhdGVzCgoKZGVmIHRhYmxlX2hhcyhjb2xzLCBuYW1lcyk6CiAg
>> "%B64_FILE%" echo ICBjb2xzZXQgPSB7Yy5sb3dlcigpIGZvciBjLCBfIGluIGNvbHN9CiAgICByZXR1cm4gYWxsKG4u
>> "%B64_FILE%" echo bG93ZXIoKSBpbiBjb2xzZXQgZm9yIG4gaW4gbmFtZXMpCgoKZGVmIHRyeV9hbmFseXplX2NhbmRp
>> "%B64_FILE%" echo ZGF0ZShjdXIsIGNhbmQpOgogICAgc2NoZW1hID0gY2FuZFsic2NoZW1hIl0KICAgIHRhYmxlID0g
>> "%B64_FILE%" echo Y2FuZFsidGFibGUiXQogICAgY29scyA9IGdldF9jb2x1bW5zKGN1ciwgc2NoZW1hLCB0YWJsZSkK
>> "%B64_FILE%" echo ICAgIGNvbF9uYW1lcyA9IFtjIGZvciBjLCBfIGluIGNvbHNdCiAgICBkZXRhaWwoIiIpCiAgICBk
>> "%B64_FILE%" echo ZXRhaWwoIj0iICogMTIwKQogICAgZGV0YWlsKGYie3NjaGVtYX0ue3RhYmxlfSIpCiAgICBkZXRh
>> "%B64_FILE%" echo aWwoZiJSZWFzb246IHtjYW5kWydyZWFzb24nXX0gfCBzY29yZT17Y2FuZFsnc2NvcmUnXX0iKQog
>> "%B64_FILE%" echo ICAgZGV0YWlsKCItIENvbHVtbnM6IikKICAgIGZvciBjLCB0IGluIGNvbHM6CiAgICAgICAgZGV0
>> "%B64_FILE%" echo YWlsKGYiICB7Y30gfCB7dH0iKQoKICAgIHJlc3VsdCA9IHsKICAgICAgICAia2hvMV90b3RhbF9m
>> "%B64_FILE%" echo b3JtdWxhIjogIiIsCiAgICAgICAgImtobzFfdG90YWxfdG9uY2siOiAiIiwKICAgICAgICAiYmVz
>> "%B64_FILE%" echo dF9kaWZmX3RvXzEwNTJfNjUiOiAiIiwKICAgICAgICAiZm9ybXVsYV9ub3RlIjogIiIsCiAgICB9
>> "%B64_FILE%" echo CgogICAgIyBUcsaw4budbmcgaOG7o3AgZ2nhu5FuZyBHM19CQzA1QTogTWFLaG8vTWFUaGFuL1Rv
>> "%B64_FILE%" echo bkRLL05oYXBUSy9YdWF0VEsuCiAgICBpZiB0YWJsZV9oYXMoY29scywgWyJNYUtobyIsICJNYVRo
>> "%B64_FILE%" echo YW4iLCAiVG9uREsiLCAiTmhhcFRLIiwgIlh1YXRUSyJdKToKICAgICAgICB0cnk6CiAgICAgICAg
>> "%B64_FILE%" echo ICAgIHNxbCA9IGYiIiIKICAgICAgICAgICAgU0VMRUNUCiAgICAgICAgICAgICAgICByLk1hS2hv
>> "%B64_FILE%" echo LAogICAgICAgICAgICAgICAgQ09BTEVTQ0Uoay5UZW5LaG8sIHIuTWFLaG8pIEFTIFRlbktobywK
>> "%B64_FILE%" echo ICAgICAgICAgICAgICAgIHIuTWFUaGFuLAogICAgICAgICAgICAgICAgQ09BTEVTQ0UodC5UZW5U
>> "%B64_FILE%" echo aGFuLCByLk1hVGhhbikgQVMgVGVuVGhhbiwKICAgICAgICAgICAgICAgIENPQUxFU0NFKHQuQ29D
>> "%B64_FILE%" echo VCwgLTEpIEFTIENvQ1QsCiAgICAgICAgICAgICAgICBTVU0oQ0FTVChJU05VTEwoci5Ub25ESyww
>> "%B64_FILE%" echo KSBBUyBGTE9BVCkpIEFTIFRvbkRLLAogICAgICAgICAgICAgICAgU1VNKENBU1QoSVNOVUxMKHIu
>> "%B64_FILE%" echo TmhhcFRLLDApIEFTIEZMT0FUKSkgQVMgTmhhcFRLLAogICAgICAgICAgICAgICAgU1VNKENBU1Qo
>> "%B64_FILE%" echo SVNOVUxMKHIuWHVhdFRLLDApIEFTIEZMT0FUKSkgQVMgWHVhdFRLLAogICAgICAgICAgICAgICAg
>> "%B64_FILE%" echo U1VNKENBU1QoSVNOVUxMKHIuVG9uREssMCkgQVMgRkxPQVQpCiAgICAgICAgICAgICAgICAgICsg
>> "%B64_FILE%" echo Q0FTVChJU05VTEwoci5OaGFwVEssMCkgQVMgRkxPQVQpCiAgICAgICAgICAgICAgICAgIC0gQ0FT
>> "%B64_FILE%" echo VChJU05VTEwoci5YdWF0VEssMCkgQVMgRkxPQVQpKSBBUyBUb25DS19Gb3JtdWxhCiAgICAgICAg
>> "%B64_FILE%" echo ICAgIEZST00ge3FpZGVudChzY2hlbWEpfS57cWlkZW50KHRhYmxlKX0gcgogICAgICAgICAgICBM
>> "%B64_FILE%" echo RUZUIEpPSU4ge01BU1RFUl9EQn0uZGJvLkRNS0hPIGsKICAgICAgICAgICAgICAgIE9OIFJUUklN
>> "%B64_FILE%" echo KExUUklNKGsuTWFLaG8pKSA9IFJUUklNKExUUklNKHIuTWFLaG8pKQogICAgICAgICAgICBMRUZU
>> "%B64_FILE%" echo IEpPSU4ge01BU1RFUl9EQn0uZGJvLkRNVEhBTiB0CiAgICAgICAgICAgICAgICBPTiBSVFJJTShM
>> "%B64_FILE%" echo VFJJTSh0Lk1hVGhhbikpID0gUlRSSU0oTFRSSU0oci5NYVRoYW4pKQogICAgICAgICAgICBXSEVS
>> "%B64_FILE%" echo RSBDQVNUKHIuTWFLaG8gQVMgTlZBUkNIQVIoMTAwKSkgSU4gKE4nMScsIE4nMDEnLCBOJ0tobyAx
>> "%B64_FILE%" echo JykKICAgICAgICAgICAgR1JPVVAgQlkKICAgICAgICAgICAgICAgIHIuTWFLaG8sCiAgICAgICAg
>> "%B64_FILE%" echo ICAgICAgICBDT0FMRVNDRShrLlRlbktobywgci5NYUtobyksCiAgICAgICAgICAgICAgICByLk1h
>> "%B64_FILE%" echo VGhhbiwKICAgICAgICAgICAgICAgIENPQUxFU0NFKHQuVGVuVGhhbiwgci5NYVRoYW4pLAogICAg
>> "%B64_FILE%" echo ICAgICAgICAgICAgQ09BTEVTQ0UodC5Db0NULCAtMSkKICAgICAgICAgICAgT1JERVIgQlkgQ09B
>> "%B64_FILE%" echo TEVTQ0UodC5Db0NULCAtMSksIHIuTWFUaGFuCiAgICAgICAgICAgICIiIgogICAgICAgICAgICBy
>> "%B64_FILE%" echo b3dzID0gY3VyLmV4ZWN1dGUoc3FsKS5mZXRjaGFsbCgpCiAgICAgICAgICAgIHRvdGFsX2FsbCA9
>> "%B64_FILE%" echo IDAuMAogICAgICAgICAgICB0b3RhbF9kZXRhaWwgPSAwLjAKICAgICAgICAgICAgZGV0YWlsKCIt
>> "%B64_FILE%" echo IEtobyAxIHJvd3MgYnkgZm9ybXVsYSBUb25ESyArIE5oYXBUSyAtIFh1YXRUSzoiKQogICAgICAg
>> "%B64_FILE%" echo ICAgICBmb3IgciBpbiByb3dzOgogICAgICAgICAgICAgICAgdmFsID0gc2FmZV9mbG9hdChyLlRv
>> "%B64_FILE%" echo bkNLX0Zvcm11bGEpCiAgICAgICAgICAgICAgICB0b3RhbF9hbGwgKz0gdmFsCiAgICAgICAgICAg
>> "%B64_FILE%" echo ICAgICBpZiBpbnQoci5Db0NUIG9yIDApID09IDA6CiAgICAgICAgICAgICAgICAgICAgdG90YWxf
>> "%B64_FILE%" echo ZGV0YWlsICs9IHZhbAogICAgICAgICAgICAgICAgZGV0YWlsKAogICAgICAgICAgICAgICAgICAg
>> "%B64_FILE%" echo IGYiICBNYUtobz17bm9ybWFsaXplKHIuTWFLaG8pfSB8IEtobz17bm9ybWFsaXplKHIuVGVuS2hv
>> "%B64_FILE%" echo KX0gfCAiCiAgICAgICAgICAgICAgICAgICAgZiJNYVRoYW49e25vcm1hbGl6ZShyLk1hVGhhbil9
>> "%B64_FILE%" echo IHwgVGhhbj17bm9ybWFsaXplKHIuVGVuVGhhbil9IHwgIgogICAgICAgICAgICAgICAgICAgIGYi
>> "%B64_FILE%" echo Q29DVD17ci5Db0NUfSB8IFRvbkRLPXtzYWZlX2Zsb2F0KHIuVG9uREspOiwuMmZ9IHwgIgogICAg
>> "%B64_FILE%" echo ICAgICAgICAgICAgICAgIGYiTmhhcFRLPXtzYWZlX2Zsb2F0KHIuTmhhcFRLKTosLjJmfSB8IFh1
>> "%B64_FILE%" echo YXRUSz17c2FmZV9mbG9hdChyLlh1YXRUSyk6LC4yZn0gfCAiCiAgICAgICAgICAgICAgICAgICAg
>> "%B64_FILE%" echo ZiJGb3JtdWxhPXt2YWw6LC4yZn0iCiAgICAgICAgICAgICAgICApCiAgICAgICAgICAgIGRldGFp
>> "%B64_FILE%" echo bChmIiAgVE9UQUwgZm9ybXVsYSBBTEwgICAgPSB7dG90YWxfYWxsOiwuMmZ9IikKICAgICAgICAg
>> "%B64_FILE%" echo ICAgZGV0YWlsKGYiICBUT1RBTCBmb3JtdWxhIENvQ1Q9MCA9IHt0b3RhbF9kZXRhaWw6LC4yZn0i
>> "%B64_FILE%" echo KQoKICAgICAgICAgICAgYmVzdCA9IG1pbihhYnModG90YWxfYWxsIC0gVEFSR0VUX0tITzEpLCBh
>> "%B64_FILE%" echo YnModG90YWxfZGV0YWlsIC0gVEFSR0VUX0tITzEpKQogICAgICAgICAgICByZXN1bHRbImtobzFf
>> "%B64_FILE%" echo dG90YWxfZm9ybXVsYSJdID0gZiJhbGw9e3RvdGFsX2FsbDouMmZ9OyBkZXRhaWw9e3RvdGFsX2Rl
>> "%B64_FILE%" echo dGFpbDouMmZ9IgogICAgICAgICAgICByZXN1bHRbImJlc3RfZGlmZl90b18xMDUyXzY1Il0gPSBm
>> "%B64_FILE%" echo IntiZXN0Oi4yZn0iCiAgICAgICAgICAgIHJlc3VsdFsiZm9ybXVsYV9ub3RlIl0gPSAiaGFzIE1h
>> "%B64_FILE%" echo S2hvL01hVGhhbi9Ub25ESy9OaGFwVEsvWHVhdFRLIgogICAgICAgIGV4Y2VwdCBFeGNlcHRpb24g
>> "%B64_FILE%" echo YXMgZXhjOgogICAgICAgICAgICBkZXRhaWwoZiIgIEVSUk9SIGZvcm11bGEgYW5hbHl6ZToge2V4
>> "%B64_FILE%" echo Y30iKQoKICAgIGlmICJUb25DSyIgaW4gY29sX25hbWVzIGFuZCAiTWFLaG8iIGluIGNvbF9uYW1l
>> "%B64_FILE%" echo czoKICAgICAgICB0cnk6CiAgICAgICAgICAgIHNxbCA9IGYiIiIKICAgICAgICAgICAgU0VMRUNU
>> "%B64_FILE%" echo IFNVTShDQVNUKElTTlVMTChUb25DSywwKSBBUyBGTE9BVCkpIEFTIFRvdGFsVG9uQ0sKICAgICAg
>> "%B64_FILE%" echo ICAgICAgRlJPTSB7cWlkZW50KHNjaGVtYSl9LntxaWRlbnQodGFibGUpfQogICAgICAgICAgICBX
>> "%B64_FILE%" echo SEVSRSBDQVNUKE1hS2hvIEFTIE5WQVJDSEFSKDEwMCkpIElOIChOJzEnLCBOJzAxJywgTidLaG8g
>> "%B64_FILE%" echo MScpCiAgICAgICAgICAgICIiIgogICAgICAgICAgICByb3cgPSBjdXIuZXhlY3V0ZShzcWwpLmZl
>> "%B64_FILE%" echo dGNob25lKCkKICAgICAgICAgICAgdG90YWwgPSBzYWZlX2Zsb2F0KHJvdy5Ub3RhbFRvbkNLKQog
>> "%B64_FILE%" echo ICAgICAgICAgICBkZXRhaWwoZiItIEtobyAxIGRpcmVjdCBTVU0oVG9uQ0spID0ge3RvdGFsOiwu
>> "%B64_FILE%" echo MmZ9IikKICAgICAgICAgICAgcmVzdWx0WyJraG8xX3RvdGFsX3RvbmNrIl0gPSBmInt0b3RhbDou
>> "%B64_FILE%" echo MmZ9IgogICAgICAgICAgICBjdXJyZW50X2Jlc3QgPSByZXN1bHRbImJlc3RfZGlmZl90b18xMDUy
>> "%B64_FILE%" echo XzY1Il0KICAgICAgICAgICAgZGlmZiA9IGFicyh0b3RhbCAtIFRBUkdFVF9LSE8xKQogICAgICAg
>> "%B64_FILE%" echo ICAgICBpZiBjdXJyZW50X2Jlc3QgPT0gIiIgb3IgZGlmZiA8IGZsb2F0KGN1cnJlbnRfYmVzdCk6
>> "%B64_FILE%" echo CiAgICAgICAgICAgICAgICByZXN1bHRbImJlc3RfZGlmZl90b18xMDUyXzY1Il0gPSBmIntkaWZm
>> "%B64_FILE%" echo Oi4yZn0iCiAgICAgICAgICAgICAgICByZXN1bHRbImZvcm11bGFfbm90ZSJdID0gImRpcmVjdCBT
>> "%B64_FILE%" echo VU0oVG9uQ0spIgogICAgICAgIGV4Y2VwdCBFeGNlcHRpb24gYXMgZXhjOgogICAgICAgICAgICBk
>> "%B64_FILE%" echo ZXRhaWwoZiIgIEVSUk9SIGRpcmVjdCBUb25DSyBhbmFseXplOiB7ZXhjfSIpCgogICAgcmV0dXJu
>> "%B64_FILE%" echo IHJlc3VsdAoKCmRlZiBtYWluKCk6CiAgICB3cml0ZSgiPT09PT09PT09PT09PT09PT09PT09PT09
>> "%B64_FILE%" echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09IikKICAgIHdyaXRlKCJUVENPIC0g
>> "%B64_FILE%" echo QuG6rlQgROG6pFUgVuG6vlQgS0hJIEFOSCBC4bqkTSBYRU0gS1EgVFLDik4gVFRDT19BUFAiKQog
>> "%B64_FILE%" echo ICAgd3JpdGUoIj09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
>> "%B64_FILE%" echo PT09PT09PT09PT09PSIpCiAgICB3cml0ZSgiQ8OhY2ggZMO5bmc6IikKICAgIHdyaXRlKCIxLiDE
>> "%B64_FILE%" echo kOG7gyBj4butYSBz4buVIG7DoHkgbeG7ny4iKQogICAgd3JpdGUoIjIuIEtoaSDEkcaw4bujYyB5
>> "%B64_FILE%" echo w6p1IGPhuqd1LCBzYW5nIFRUQ09fQVBQIGLhuqVtIFhlbSBrcSAvIGzhuqV5IGvhur90IHF14bqj
>> "%B64_FILE%" echo IHThu5NuIGtoby4iKQogICAgd3JpdGUoIjMuIMSQ4bujaSBUVENPX0FQUCBoaeG7g24gdGjhu4sg
>> "%B64_FILE%" echo xJHDum5nIHPhu5EsIHbDrSBk4bulIEtobyAxID0gMS4wNTIsNjUuIikKICAgIHdyaXRlKCI0LiBR
>> "%B64_FILE%" echo dWF5IGzhuqFpIGPhu61hIHPhu5UgbsOgeSBi4bqlbSBFbnRlci4iKQogICAgd3JpdGUoIiIpCiAg
>> "%B64_FILE%" echo ICB3cml0ZShmIkvhur90IHF14bqjIHPhur0geHXhuqV0IHThuqFpOiB7T1VUX0RJUn0iKQogICAg
>> "%B64_FILE%" echo d3JpdGUoIiIpCgogICAgZW5zdXJlX3B5b2RiYygpCiAgICBjb25uID0gY29ubmVjdChEQVRBQkFT
>> "%B64_FILE%" echo RSkKICAgIGN1ciA9IGNvbm4uY3Vyc29yKCkKCiAgICB3cml0ZSgixJBhbmcgY2jhu6VwIHRy4bqh
>> "%B64_FILE%" echo bmcgdGjDoWkgU1FMIHRyxrDhu5tjIGtoaSBhbmggYuG6pW0gWGVtIGtxLi4uIikKICAgIGJlZm9y
>> "%B64_FILE%" echo ZSA9IGdldF90YWJsZXNfc25hcHNob3QoY3VyKQogICAgd3JpdGUoZiLEkMOjIGNo4bulcCB0csaw
>> "%B64_FILE%" echo 4bubYzoge2xlbihiZWZvcmUpfSBi4bqjbmcuIikKICAgIHdyaXRlKCIiKQoKICAgIGlucHV0KCJC
>> "%B64_FILE%" echo w4JZIEdJ4bucIGjDo3kgc2FuZyBUVENPX0FQUCBi4bqlbSBYZW0ga3EvbOG6pXkga+G6v3QgcXXh
>> "%B64_FILE%" echo uqMgdOG7k24ga2hvLiBLaGkgVFRDT19BUFAgcmEgc+G7kSDEkcO6bmcgdGjDrCBxdWF5IGzhuqFp
>> "%B64_FILE%" echo IMSRw6J5IGLhuqVtIEVudGVyLi4uICIpCgogICAgd3JpdGUoIiIpCiAgICB3cml0ZSgixJBhbmcg
>> "%B64_FILE%" echo Y2jhu6VwIHRy4bqhbmcgdGjDoWkgU1FMIHNhdSBraGkgVFRDT19BUFAgY2jhuqF5Li4uIikKICAg
>> "%B64_FILE%" echo IGFmdGVyID0gZ2V0X3RhYmxlc19zbmFwc2hvdChjdXIpCiAgICB3cml0ZShmIsSQw6MgY2jhu6Vw
>> "%B64_FILE%" echo IHNhdToge2xlbihhZnRlcil9IGLhuqNuZy4iKQogICAgd3JpdGUoIiIpCgogICAgY2FuZGlkYXRl
>> "%B64_FILE%" echo cyA9IGNvbXBhcmVfc25hcHNob3RzKGJlZm9yZSwgYWZ0ZXIpCiAgICB3cml0ZShmIlPhu5EgYuG6
>> "%B64_FILE%" echo o25nIOG7qW5nIHZpw6puL3RoYXkgxJHhu5VpL2xpw6puIHF1YW46IHtsZW4oY2FuZGlkYXRlcyl9
>> "%B64_FILE%" echo IikKICAgIHdyaXRlKCIiKQoKICAgIGVucmljaGVkID0gW10KICAgIGZvciBjYW5kIGluIGNhbmRp
>> "%B64_FILE%" echo ZGF0ZXNbOjgwXToKICAgICAgICBleHRyYSA9IHRyeV9hbmFseXplX2NhbmRpZGF0ZShjdXIsIGNh
>> "%B64_FILE%" echo bmQpCiAgICAgICAgY2FuZC51cGRhdGUoZXh0cmEpCiAgICAgICAgZW5yaWNoZWQuYXBwZW5kKGNh
>> "%B64_FILE%" echo bmQpCgogICAgY29ubi5jbG9zZSgpCgogICAgd3JpdGUoIlRPUCA1MCBC4bqiTkcgTkdISSBW4bqk
>> "%B64_FILE%" echo TiBOSOG6pFQgU0FVIEtISSBC4bqkTSBUVENPX0FQUCIpCiAgICB3cml0ZSgiLS0tLS0tLS0tLS0t
>> "%B64_FILE%" echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tIikKICAgIGZv
>> "%B64_FILE%" echo ciBpLCBjIGluIGVudW1lcmF0ZShlbnJpY2hlZFs6NTBdLCBzdGFydD0xKToKICAgICAgICB3cml0
>> "%B64_FILE%" echo ZSgKICAgICAgICAgICAgZiJ7aTowMmR9LiB7Y1sna2V5J119IHwgc2NvcmU9e2NbJ3Njb3JlJ119
>> "%B64_FILE%" echo IHwgcmVhc29uPXtjWydyZWFzb24nXX0gfCAiCiAgICAgICAgICAgIGYicm93cz17Y1snYmVmb3Jl
>> "%B64_FILE%" echo X3Jvd19jb3VudCddfS0+e2NbJ2FmdGVyX3Jvd19jb3VudCddfSB8ICIKICAgICAgICAgICAgZiJt
>> "%B64_FILE%" echo b2RpZnk9e2NbJ2JlZm9yZV9tb2RpZnknXX0gLT4ge2NbJ2FmdGVyX21vZGlmeSddfSB8ICIKICAg
>> "%B64_FILE%" echo ICAgICAgICAgZiJraG8xX2Zvcm11bGE9e2MuZ2V0KCdraG8xX3RvdGFsX2Zvcm11bGEnLCcnKX0g
>> "%B64_FILE%" echo fCAiCiAgICAgICAgICAgIGYia2hvMV90b25jaz17Yy5nZXQoJ2tobzFfdG90YWxfdG9uY2snLCcn
>> "%B64_FILE%" echo KX0gfCAiCiAgICAgICAgICAgIGYiZGlmZj17Yy5nZXQoJ2Jlc3RfZGlmZl90b18xMDUyXzY1Jywn
>> "%B64_FILE%" echo Jyl9IHwge2MuZ2V0KCdmb3JtdWxhX25vdGUnLCcnKX0iCiAgICAgICAgKQoKICAgIHdpdGggT1VU
>> "%B64_FILE%" echo X0NTVi5vcGVuKCJ3IiwgbmV3bGluZT0iIiwgZW5jb2Rpbmc9InV0Zi04LXNpZyIpIGFzIGY6CiAg
>> "%B64_FILE%" echo ICAgICAgZmllbGRuYW1lcyA9IFsKICAgICAgICAgICAgImtleSIsICJzY2hlbWEiLCAidGFibGUi
>> "%B64_FILE%" echo LCAic2NvcmUiLCAicmVhc29uIiwKICAgICAgICAgICAgImJlZm9yZV9yb3dfY291bnQiLCAiYWZ0
>> "%B64_FILE%" echo ZXJfcm93X2NvdW50IiwKICAgICAgICAgICAgImJlZm9yZV9tb2RpZnkiLCAiYWZ0ZXJfbW9kaWZ5
>> "%B64_FILE%" echo IiwgImNyZWF0ZV9kYXRlIiwKICAgICAgICAgICAgImtobzFfdG90YWxfZm9ybXVsYSIsICJraG8x
>> "%B64_FILE%" echo X3RvdGFsX3RvbmNrIiwgImJlc3RfZGlmZl90b18xMDUyXzY1IiwgImZvcm11bGFfbm90ZSIsCiAg
>> "%B64_FILE%" echo ICAgICAgXQogICAgICAgIHcgPSBjc3YuRGljdFdyaXRlcihmLCBmaWVsZG5hbWVzPWZpZWxkbmFt
>> "%B64_FILE%" echo ZXMpCiAgICAgICAgdy53cml0ZWhlYWRlcigpCiAgICAgICAgZm9yIGMgaW4gZW5yaWNoZWQ6CiAg
>> "%B64_FILE%" echo ICAgICAgICAgIHcud3JpdGVyb3coe2s6IGMuZ2V0KGssICIiKSBmb3IgayBpbiBmaWVsZG5hbWVz
>> "%B64_FILE%" echo fSkKCiAgICB3cml0ZSgiIikKICAgIHdyaXRlKCI9PT09PT09PT09PT09PT09PT09PT09PT09PT09
>> "%B64_FILE%" echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0iKQogICAgd3JpdGUoIkhPw4BOIFRIw4BO
>> "%B64_FILE%" echo SCIpCiAgICB3cml0ZSgiPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
>> "%B64_FILE%" echo PT09PT09PT09PT09PT09PT09IikKICAgIHdyaXRlKGYiVFhUIGNow61uaCA6IHtPVVRfVFhUfSIp
>> "%B64_FILE%" echo CiAgICB3cml0ZShmIkNTViAgICAgICA6IHtPVVRfQ1NWfSIpCiAgICB3cml0ZShmIkNoaSB0aeG6
>> "%B64_FILE%" echo v3QgIDoge09VVF9ERVRBSUx9IikKICAgIHdyaXRlKCIiKQogICAgd3JpdGUoIkFuaCBn4butaSBs
>> "%B64_FILE%" echo 4bqhaSBUWFQgY2jDrW5oLiBO4bq/dSBj4bqnbiwgZ+G7rWkgdGjDqm0gZmlsZSBDaGkgdGnhur90
>> "%B64_FILE%" echo LiIpCiAgICB3cml0ZSgiVMO0aSBz4bq9IGThu7FhIHbDoG8gYuG6o25nIHbhu6thIHRoYXkgxJHh
>> "%B64_FILE%" echo u5VpIG5nYXkgc2F1IGtoaSBUVENPX0FQUCBjaOG6oXkgxJHhu4Mgc+G7rWEgYmFja2VuZC4iKQoK
>> "%B64_FILE%" echo ICAgIHRyeToKICAgICAgICBzdWJwcm9jZXNzLlBvcGVuKFsiZXhwbG9yZXIuZXhlIiwgc3RyKE9V
>> "%B64_FILE%" echo VF9ESVIpXSkKICAgIGV4Y2VwdCBFeGNlcHRpb246CiAgICAgICAgcGFzcwoKCmlmIF9fbmFtZV9f
>> "%B64_FILE%" echo ID09ICJfX21haW5fXyI6CiAgICB0cnk6CiAgICAgICAgbWFpbigpCiAgICBleGNlcHQgRXhjZXB0
>> "%B64_FILE%" echo aW9uIGFzIGV4YzoKICAgICAgICB3cml0ZSgiIikKICAgICAgICB3cml0ZSgiW0zhu5ZJXSAiICsg
>> "%B64_FILE%" echo c3RyKGV4YykpCiAgICAgICAgd3JpdGUoIk7hur91IGzhu5dpLCBn4butaSBs4bqhaSDhuqNuaCBt
>> "%B64_FILE%" echo w6BuIGjDrG5oIGhv4bq3YyBmaWxlIFRYVCDEkcOjIHThuqFvLiIpCiAgICAgICAgdHJ5OgogICAg
>> "%B64_FILE%" echo ICAgICAgICBzdWJwcm9jZXNzLlBvcGVuKFsiZXhwbG9yZXIuZXhlIiwgc3RyKE9VVF9ESVIpXSkK
>> "%B64_FILE%" echo ICAgICAgICBleGNlcHQgRXhjZXB0aW9uOgogICAgICAgICAgICBwYXNzCiAgICAgICAgc3lzLmV4
>> "%B64_FILE%" echo aXQoMSkK
python -c "import base64, pathlib, os; b=pathlib.Path(os.environ['B64_FILE']).read_text().replace('\n','').replace('\r','').strip(); pathlib.Path(os.environ['PY_MAIN']).write_bytes(base64.b64decode(b))"
exit /b %errorlevel%
