@echo off
setlocal EnableExtensions EnableDelayedExpansion
chcp 65001 >nul
title TTCO LIVE FINAL G3_BC05A_2 to GitHub - v17

set "CONFIG_DIR=%LOCALAPPDATA%\TTCO_TonKho_Live_Final_To_GitHub"
set "PY_MAIN=%CONFIG_DIR%\TTCO_Live_Final_To_GitHub_v17.py"
set "B64_FILE=%CONFIG_DIR%\TTCO_Live_Final_To_GitHub_v17.b64"

if not exist "%CONFIG_DIR%" mkdir "%CONFIG_DIR%" >nul 2>&1

call :WRITE_PY
if errorlevel 1 (
    echo [LOI] Khong tao duoc file Python tam.
    pause
    exit /b 1
)

if /I "%~1"=="--auto" (
    python "%PY_MAIN%" --action live-update --bat "%~f0"
    exit /b %errorlevel%
)

:MENU
cls
echo ============================================================
echo      TTCO - BAT LIVE BANG KET QUA CUOI TTCO_APP v17
echo ============================================================
echo Sua loi v16:
echo   v16 tim bang sau khi TTCO_APP da dong/xoa bang tam nen khong thay.
echo   v17 phai chay TRUOC, sau do anh bam Xem kq trong TTCO_APP.
echo   BAT se bat ngay bang G3_BC05A_2_###### khi TTCO_APP vua tao.
echo.
echo  [1] Bat live va cap nhat GitHub
echo      Chay muc nay, sau do sang TTCO_APP bam Xem kq.
echo.
echo  [2] Bat live va chi kiem tra Kho 1, chua up GitHub
echo.
echo  [3] Chon lai thu muc repo GitHub my-ai-site
echo.
echo  [4] Cai dat tu dong khi dang nhap Windows
echo.
echo  [5] Mo file log
echo.
echo  [0] Thoat
echo.
echo ============================================================
choice /C 123450 /N /M "Chon chuc nang [1/2/3/4/5/0]: "

if errorlevel 6 exit /b 0
if errorlevel 5 (
    python "%PY_MAIN%" --action open-log --bat "%~f0"
    goto MENU
)
if errorlevel 4 (
    python "%PY_MAIN%" --action install --bat "%~f0"
    pause
    goto MENU
)
if errorlevel 3 (
    python "%PY_MAIN%" --action config-repo --bat "%~f0"
    pause
    goto MENU
)
if errorlevel 2 (
    python "%PY_MAIN%" --action live-check --bat "%~f0"
    pause
    goto MENU
)
if errorlevel 1 (
    python "%PY_MAIN%" --action live-update --bat "%~f0"
    pause
    goto MENU
)

goto MENU

:WRITE_PY
> "%B64_FILE%" echo IyAtKi0gY29kaW5nOiB1dGYtOCAtKi0KaW1wb3J0IGFyZ3BhcnNlCmltcG9ydCBqc29uCmltcG9y
>> "%B64_FILE%" echo dCBvcwppbXBvcnQgcmUKaW1wb3J0IHN1YnByb2Nlc3MKaW1wb3J0IHN5cwppbXBvcnQgdGltZQpm
>> "%B64_FILE%" echo cm9tIGRhdGV0aW1lIGltcG9ydCBkYXRldGltZQpmcm9tIHBhdGhsaWIgaW1wb3J0IFBhdGgKClNF
>> "%B64_FILE%" echo UlZFUiA9IHIidHV5ZW50aGFuY3Vhb25nLmNvbS52biw1MjM3NiIKREJfUkVQT1JUID0gIlRUQ09f
>> "%B64_FILE%" echo VEhPTkdLRSIKREJfTUFTVEVSID0gIlRUQ09fUVRIVCIKClJFUE9fVVJMID0gImh0dHBzOi8vZ2l0
>> "%B64_FILE%" echo aHViLmNvbS90dXllbjExMDIvbXktYWktc2l0ZS5naXQiCkJSQU5DSCA9ICJtYWluIgpKU09OX1JF
>> "%B64_FILE%" echo TCA9IG9zLnBhdGguam9pbigicHVibGljIiwgImRhdGEiLCAidG9uX2tob19sYXRlc3QuanNvbiIp
>> "%B64_FILE%" echo ClRBU0tfTkFNRSA9ICJUVENPX1Rvbktob19MaXZlX0ZpbmFsX1RhYmxlX1RvX0dpdEh1YiIKCkNP
>> "%B64_FILE%" echo TkZJR19ESVIgPSBQYXRoKG9zLmVudmlyb24uZ2V0KCJMT0NBTEFQUERBVEEiLCBzdHIoUGF0aC5o
>> "%B64_FILE%" echo b21lKCkpKSkgLyAiVFRDT19Ub25LaG9fTGl2ZV9GaW5hbF9Ub19HaXRIdWIiCkNPTkZJR19GSUxF
>> "%B64_FILE%" echo ID0gQ09ORklHX0RJUiAvICJjb25maWcuanNvbiIKTE9HX0ZJTEUgPSBDT05GSUdfRElSIC8gIlRU
>> "%B64_FILE%" echo Q09fTGl2ZV9GaW5hbF9Ub19HaXRIdWIubG9nIgoKREVTS1RPUCA9IFBhdGgob3MuZW52aXJvbi5n
>> "%B64_FILE%" echo ZXQoIlVTRVJQUk9GSUxFIiwgc3RyKFBhdGguaG9tZSgpKSkpIC8gIkRlc2t0b3AiCkNIRUNLX0RJ
>> "%B64_FILE%" echo UiA9IERFU0tUT1AgLyAiVFRDT19MSVZFX0ZJTkFMX0NBUFRVUkVfQ0hFQ0siCgoKZGVmIGxvZyht
>> "%B64_FILE%" echo c2c6IHN0cikgLT4gTm9uZToKICAgIENPTkZJR19ESVIubWtkaXIocGFyZW50cz1UcnVlLCBleGlz
>> "%B64_FILE%" echo dF9vaz1UcnVlKQogICAgd2l0aCBMT0dfRklMRS5vcGVuKCJhIiwgZW5jb2Rpbmc9InV0Zi04Iikg
>> "%B64_FILE%" echo YXMgZjoKICAgICAgICBmLndyaXRlKGYiW3tkYXRldGltZS5ub3coKTolWS0lbS0lZCAlSDolTTol
>> "%B64_FILE%" echo U31dIHttc2d9XG4iKQoKCmRlZiBydW4oY21kLCBjd2Q9Tm9uZSwgY2hlY2s9VHJ1ZSk6CiAgICBw
>> "%B64_FILE%" echo cmludCgiXG4+ICIgKyAiICIuam9pbihjbWQpKQogICAgcCA9IHN1YnByb2Nlc3MucnVuKGNtZCwg
>> "%B64_FILE%" echo Y3dkPWN3ZCkKICAgIGlmIGNoZWNrIGFuZCBwLnJldHVybmNvZGUgIT0gMDoKICAgICAgICByYWlz
>> "%B64_FILE%" echo ZSBSdW50aW1lRXJyb3IoZiJM4buHbmggbOG7l2kgbcOjIHtwLnJldHVybmNvZGV9OiB7JyAnLmpv
>> "%B64_FILE%" echo aW4oY21kKX0iKQogICAgcmV0dXJuIHAucmV0dXJuY29kZQoKCmRlZiBlbnN1cmVfcHlvZGJjKCk6
>> "%B64_FILE%" echo CiAgICB0cnk6CiAgICAgICAgaW1wb3J0IHB5b2RiYyAgIyBub3FhCiAgICAgICAgcmV0dXJuCiAg
>> "%B64_FILE%" echo ICBleGNlcHQgRXhjZXB0aW9uOgogICAgICAgIHByaW50KCJbSU5GT10gQ2jGsGEgY8OzIHB5b2Ri
>> "%B64_FILE%" echo Yy4gxJBhbmcgY8OgaSBweW9kYmMuLi4iKQogICAgICAgIHN1YnByb2Nlc3MuY2hlY2tfY2FsbChb
>> "%B64_FILE%" echo c3lzLmV4ZWN1dGFibGUsICItbSIsICJwaXAiLCAiaW5zdGFsbCIsICJweW9kYmMiXSkKCgpkZWYg
>> "%B64_FILE%" echo Y29ubmVjdChkYj1EQl9SRVBPUlQpOgogICAgaW1wb3J0IHB5b2RiYwogICAgY29ubl9zdHIgPSAo
>> "%B64_FILE%" echo CiAgICAgICAgIkRSSVZFUj17T0RCQyBEcml2ZXIgMTggZm9yIFNRTCBTZXJ2ZXJ9OyIKICAgICAg
>> "%B64_FILE%" echo ICBmIlNFUlZFUj17U0VSVkVSfTsiCiAgICAgICAgZiJEQVRBQkFTRT17ZGJ9OyIKICAgICAgICAi
>> "%B64_FILE%" echo VHJ1c3RlZF9Db25uZWN0aW9uPXllczsiCiAgICAgICAgIlRydXN0U2VydmVyQ2VydGlmaWNhdGU9
>> "%B64_FILE%" echo eWVzOyIKICAgICkKICAgIHJldHVybiBweW9kYmMuY29ubmVjdChjb25uX3N0ciwgdGltZW91dD0y
>> "%B64_FILE%" echo MCkKCgpkZWYgcWlkZW50KG5hbWU6IHN0cikgLT4gc3RyOgogICAgcmV0dXJuICJbIiArIHN0cihu
>> "%B64_FILE%" echo YW1lKS5yZXBsYWNlKCJdIiwgIl1dIikgKyAiXSIKCgpkZWYgbm9ybWFsaXplX3RleHQodik6CiAg
>> "%B64_FILE%" echo ICBpZiB2IGlzIE5vbmU6CiAgICAgICAgcmV0dXJuICIiCiAgICBzID0gc3RyKHYpLnJlcGxhY2Uo
>> "%B64_FILE%" echo Ilx4YTAiLCAiICIpLnN0cmlwKCkKICAgIHMgPSByZS5zdWIociJccysiLCAiICIsIHMpCiAgICBy
>> "%B64_FILE%" echo ZXR1cm4gcwoKCmRlZiBub3JtYWxpemVfY29hbF9uYW1lKHYpOgogICAgcyA9IG5vcm1hbGl6ZV90
>> "%B64_FILE%" echo ZXh0KHYpCiAgICBzID0gcmUuc3ViKHIiKD9pKVxiMWNcYiIsICIxQyIsIHMpCiAgICBzID0gcmUu
>> "%B64_FILE%" echo c3ViKHIiKD9pKVxiOGNcYiIsICI4QyIsIHMpCiAgICByZXR1cm4gcwoKCmRlZiBjbGVhbl9udW1i
>> "%B64_FILE%" echo ZXIodik6CiAgICBpZiB2IGlzIE5vbmU6CiAgICAgICAgcmV0dXJuIDAuMAogICAgdHJ5OgogICAg
>> "%B64_FILE%" echo ICAgIHJldHVybiBmbG9hdCh2KQogICAgZXhjZXB0IEV4Y2VwdGlvbjoKICAgICAgICByZXR1cm4g
>> "%B64_FILE%" echo MC4wCgoKZGVmIGtob19zb3J0X2tleSh0ZW5fa2hvLCBtYV9raG8pOgogICAgdGV4dCA9IHRlbl9r
>> "%B64_FILE%" echo aG8gb3IgbWFfa2hvIG9yICIiCiAgICBtID0gcmUuc2VhcmNoKHIiKFxkKykiLCB0ZXh0KQogICAg
>> "%B64_FILE%" echo biA9IGludChtLmdyb3VwKDEpKSBpZiBtIGVsc2UgOTk5OQogICAgdDQgPSAxIGlmICJUNCIgaW4g
>> "%B64_FILE%" echo dGV4dC51cHBlcigpIGVsc2UgMAogICAgcmV0dXJuIChuLCB0NCwgdGV4dCkKCgpkZWYgbG9hZF9j
>> "%B64_FILE%" echo b25maWcoKToKICAgIENPTkZJR19ESVIubWtkaXIocGFyZW50cz1UcnVlLCBleGlzdF9vaz1UcnVl
>> "%B64_FILE%" echo KQogICAgaWYgQ09ORklHX0ZJTEUuZXhpc3RzKCk6CiAgICAgICAgdHJ5OgogICAgICAgICAgICBy
>> "%B64_FILE%" echo ZXR1cm4ganNvbi5sb2FkcyhDT05GSUdfRklMRS5yZWFkX3RleHQoZW5jb2Rpbmc9InV0Zi04Iikp
>> "%B64_FILE%" echo CiAgICAgICAgZXhjZXB0IEV4Y2VwdGlvbjoKICAgICAgICAgICAgcGFzcwogICAgcmV0dXJuIHsK
>> "%B64_FILE%" echo ICAgICAgICAicmVwb19kaXIiOiByIkQ6XFRUQ09fVG9uS2hvX0FwcF9SZXBvIiwKICAgIH0KCgpk
>> "%B64_FILE%" echo ZWYgc2F2ZV9jb25maWcoY2ZnKToKICAgIENPTkZJR19ESVIubWtkaXIocGFyZW50cz1UcnVlLCBl
>> "%B64_FILE%" echo eGlzdF9vaz1UcnVlKQogICAgQ09ORklHX0ZJTEUud3JpdGVfdGV4dChqc29uLmR1bXBzKGNmZywg
>> "%B64_FILE%" echo ZW5zdXJlX2FzY2lpPUZhbHNlLCBpbmRlbnQ9MiksIGVuY29kaW5nPSJ1dGYtOCIpCiAgICBsb2co
>> "%B64_FILE%" echo ZiJTQVZFX0NPTkZJRyB7Y2ZnfSIpCgoKZGVmIHBpY2tfZm9sZGVyKHRpdGxlOiBzdHIsIGluaXRp
>> "%B64_FILE%" echo YWw6IHN0ciA9ICIiKSAtPiBzdHI6CiAgICB0cnk6CiAgICAgICAgaW1wb3J0IHRraW50ZXIgYXMg
>> "%B64_FILE%" echo dGsKICAgICAgICBmcm9tIHRraW50ZXIgaW1wb3J0IGZpbGVkaWFsb2cKICAgICAgICByb290ID0g
>> "%B64_FILE%" echo dGsuVGsoKQogICAgICAgIHJvb3Qud2l0aGRyYXcoKQogICAgICAgIHJvb3QuYXR0cmlidXRlcygi
>> "%B64_FILE%" echo LXRvcG1vc3QiLCBUcnVlKQogICAgICAgIGlmIG5vdCBpbml0aWFsIG9yIG5vdCBvcy5wYXRoLmlz
>> "%B64_FILE%" echo ZGlyKGluaXRpYWwpOgogICAgICAgICAgICBpbml0aWFsID0gciJEOlxUVENPX1Rvbktob19BcHBf
>> "%B64_FILE%" echo UmVwbyIgaWYgb3MucGF0aC5pc2RpcihyIkQ6XFRUQ09fVG9uS2hvX0FwcF9SZXBvIikgZWxzZSBz
>> "%B64_FILE%" echo dHIoUGF0aC5ob21lKCkpCiAgICAgICAgZm9sZGVyID0gZmlsZWRpYWxvZy5hc2tkaXJlY3Rvcnko
>> "%B64_FILE%" echo dGl0bGU9dGl0bGUsIGluaXRpYWxkaXI9aW5pdGlhbCwgbXVzdGV4aXN0PUZhbHNlKQogICAgICAg
>> "%B64_FILE%" echo IHJvb3QuZGVzdHJveSgpCiAgICAgICAgcmV0dXJuIGZvbGRlciBvciAiIgogICAgZXhjZXB0IEV4
>> "%B64_FILE%" echo Y2VwdGlvbiBhcyBleGM6CiAgICAgICAgcHJpbnQoZiJbQ+G6ok5IIELDgU9dIEtow7RuZyBt4buf
>> "%B64_FILE%" echo IMSRxrDhu6NjIHBvcHVwIGNo4buNbiB0aMawIG3hu6VjOiB7ZXhjfSIpCiAgICAgICAgcmV0dXJu
>> "%B64_FILE%" echo IGlucHV0KCJOaOG6rXAgxJHGsOG7nW5nIGThuqtuIHRoxrAgbeG7pWMgcmVwbzogIikuc3RyaXAo
>> "%B64_FILE%" echo KS5zdHJpcCgnIicpCgoKZGVmIGNvbW1hbmRfZXhpc3RzKG5hbWU6IHN0cikgLT4gYm9vbDoKICAg
>> "%B64_FILE%" echo IHRyeToKICAgICAgICBzdWJwcm9jZXNzLnJ1bihbbmFtZSwgIi0tdmVyc2lvbiJdLCBzdGRvdXQ9
>> "%B64_FILE%" echo c3VicHJvY2Vzcy5ERVZOVUxMLCBzdGRlcnI9c3VicHJvY2Vzcy5ERVZOVUxMKQogICAgICAgIHJl
>> "%B64_FILE%" echo dHVybiBUcnVlCiAgICBleGNlcHQgRXhjZXB0aW9uOgogICAgICAgIHJldHVybiBGYWxzZQoKCmRl
>> "%B64_FILE%" echo ZiBlbnN1cmVfZ2l0KCkgLT4gTm9uZToKICAgIGlmIGNvbW1hbmRfZXhpc3RzKCJnaXQiKToKICAg
>> "%B64_FILE%" echo ICAgICByZXR1cm4KICAgIHByaW50KCJbQ+G6ok5IIELDgU9dIEtow7RuZyB0w6xtIHRo4bqleSBH
>> "%B64_FILE%" echo aXQuIMSQYW5nIHRo4butIGPDoGkgR2l0IGLhurFuZyB3aW5nZXQuLi4iKQogICAgaWYgY29tbWFu
>> "%B64_FILE%" echo ZF9leGlzdHMoIndpbmdldCIpOgogICAgICAgIHN1YnByb2Nlc3MucnVuKFsKICAgICAgICAgICAg
>> "%B64_FILE%" echo IndpbmdldCIsICJpbnN0YWxsIiwgIi0taWQiLCAiR2l0LkdpdCIsICItZSIsICItLXNvdXJjZSIs
>> "%B64_FILE%" echo ICJ3aW5nZXQiLAogICAgICAgICAgICAiLS1zaWxlbnQiLCAiLS1hY2NlcHQtcGFja2FnZS1hZ3Jl
>> "%B64_FILE%" echo ZW1lbnRzIiwgIi0tYWNjZXB0LXNvdXJjZS1hZ3JlZW1lbnRzIgogICAgICAgIF0pCiAgICBpZiBu
>> "%B64_FILE%" echo b3QgY29tbWFuZF9leGlzdHMoImdpdCIpOgogICAgICAgIHJhaXNlIFJ1bnRpbWVFcnJvcigiS2jD
>> "%B64_FILE%" echo tG5nIHTDrG0gdGjhuqV5IEdpdC4gSMOjeSBjw6BpIEdpdCBmb3IgV2luZG93cyBy4buTaSBjaOG6
>> "%B64_FILE%" echo oXkgbOG6oWkuIikKCgpkZWYgZW5zdXJlX3JlcG8ocmVwb19kaXI6IHN0cikgLT4gTm9uZToKICAg
>> "%B64_FILE%" echo IHJlcG8gPSBQYXRoKHJlcG9fZGlyKQogICAgaWYgKHJlcG8gLyAiLmdpdCIpLmlzX2RpcigpOgog
>> "%B64_FILE%" echo ICAgICAgIHByaW50KGYiW09LXSBSZXBvIEdpdEh1YiBo4bujcCBs4buHOiB7cmVwb30iKQogICAg
>> "%B64_FILE%" echo ICAgIHJldHVybgogICAgcmVwby5ta2RpcihwYXJlbnRzPVRydWUsIGV4aXN0X29rPVRydWUpCiAg
>> "%B64_FILE%" echo ICBpZiBhbnkocmVwby5pdGVyZGlyKCkpOgogICAgICAgIHJhaXNlIFJ1bnRpbWVFcnJvcihmIlRo
>> "%B64_FILE%" echo xrAgbeG7pWMgxJHDoyBjw7MgZmlsZSBuaMawbmcga2jDtG5nIGPDsyAuZ2l0OiB7cmVwb30uIEjD
>> "%B64_FILE%" echo o3kgY2jhu41uIMSRw7puZyByZXBvIGhv4bq3YyB0aMawIG3hu6VjIHLhu5duZy4iKQogICAgcnVu
>> "%B64_FILE%" echo KFsiZ2l0IiwgImNsb25lIiwgUkVQT19VUkwsIHN0cihyZXBvKV0pCgoKZGVmIGdldF9leGlzdGlu
>> "%B64_FILE%" echo Z19maW5hbF90YWJsZXMoY3VyKToKICAgIHJvd3MgPSBjdXIuZXhlY3V0ZSgiIiIKICAgICAgICBT
>> "%B64_FILE%" echo RUxFQ1QgbmFtZQogICAgICAgIEZST00gc3lzLnRhYmxlcwogICAgICAgIFdIRVJFIG5hbWUgTElL
>> "%B64_FILE%" echo RSAnRzNfQkMwNUFfMl8lJwogICAgIiIiKS5mZXRjaGFsbCgpCiAgICBuYW1lcyA9IHNldCgpCiAg
>> "%B64_FILE%" echo ICBmb3IgciBpbiByb3dzOgogICAgICAgIG5hbWUgPSBzdHIoci5uYW1lKQogICAgICAgIGlmIHJl
>> "%B64_FILE%" echo Lm1hdGNoKHIiXkczX0JDMDVBXzJfXGQrJCIsIG5hbWUpOgogICAgICAgICAgICBuYW1lcy5hZGQo
>> "%B64_FILE%" echo bmFtZSkKICAgIHJldHVybiBuYW1lcwoKCmRlZiBsaXN0X2ZpbmFsX3RhYmxlX2NhbmRpZGF0ZXMo
>> "%B64_FILE%" echo Y3VyKToKICAgIHJvd3MgPSBjdXIuZXhlY3V0ZSgiIiIKICAgICAgICBTRUxFQ1QKICAgICAgICAg
>> "%B64_FILE%" echo ICAgdC5uYW1lLAogICAgICAgICAgICB0LmNyZWF0ZV9kYXRlLAogICAgICAgICAgICB0Lm1vZGlm
>> "%B64_FILE%" echo eV9kYXRlCiAgICAgICAgRlJPTSBzeXMudGFibGVzIHQKICAgICAgICBXSEVSRSB0Lm5hbWUgTElL
>> "%B64_FILE%" echo RSAnRzNfQkMwNUFfMl8lJwogICAgICAgIE9SREVSIEJZIHQuY3JlYXRlX2RhdGUgREVTQywgdC5t
>> "%B64_FILE%" echo b2RpZnlfZGF0ZSBERVNDLCB0Lm5hbWUgREVTQwogICAgIiIiKS5mZXRjaGFsbCgpCgogICAgb3V0
>> "%B64_FILE%" echo ID0gW10KICAgIGZvciByIGluIHJvd3M6CiAgICAgICAgbmFtZSA9IHN0cihyLm5hbWUpCiAgICAg
>> "%B64_FILE%" echo ICAgaWYgbm90IHJlLm1hdGNoKHIiXkczX0JDMDVBXzJfXGQrJCIsIG5hbWUpOgogICAgICAgICAg
>> "%B64_FILE%" echo ICBjb250aW51ZQogICAgICAgIG91dC5hcHBlbmQocikKICAgIHJldHVybiBvdXQKCgpkZWYgdGFi
>> "%B64_FILE%" echo bGVfaGFzX3JlcXVpcmVkX2NvbHMoY3VyLCB0YWJsZV9uYW1lKToKICAgIHJvd3MgPSBjdXIuZXhl
>> "%B64_FILE%" echo Y3V0ZSgiIiIKICAgICAgICBTRUxFQ1QgQ09MVU1OX05BTUUKICAgICAgICBGUk9NIElORk9STUFU
>> "%B64_FILE%" echo SU9OX1NDSEVNQS5DT0xVTU5TCiAgICAgICAgV0hFUkUgVEFCTEVfU0NIRU1BPSdkYm8nIEFORCBU
>> "%B64_FILE%" echo QUJMRV9OQU1FPT8KICAgICIiIiwgdGFibGVfbmFtZSkuZmV0Y2hhbGwoKQogICAgY29scyA9IHtz
>> "%B64_FILE%" echo dHIoci5DT0xVTU5fTkFNRSkgZm9yIHIgaW4gcm93c30KICAgIHJlcXVpcmVkID0geyJNYUtobyIs
>> "%B64_FILE%" echo ICJNYVRoYW4iLCAiVG9uREsiLCAiTmhhcFRLIiwgIlh1YXRUSyIsICJUb25DSyJ9CiAgICByZXR1
>> "%B64_FILE%" echo cm4gcmVxdWlyZWQuaXNzdWJzZXQoY29scykKCgpkZWYgcmVhZF9maW5hbF9yb3dzKHRhYmxlX25h
>> "%B64_FILE%" echo bWU6IHN0cik6CiAgICBjb25uID0gY29ubmVjdChEQl9SRVBPUlQpCiAgICBjdXIgPSBjb25uLmN1
>> "%B64_FILE%" echo cnNvcigpCgogICAgc3FsID0gZiIiIgogICAgU0VMRUNUCiAgICAgICAgci5NYUtobywKICAgICAg
>> "%B64_FILE%" echo ICBDT0FMRVNDRShrLlRlbktob01vaSwgay5UZW5LaG8sIHIuTWFLaG8pIEFTIFRlbktobywKICAg
>> "%B64_FILE%" echo ICAgICByLk1hVGhhbiwKICAgICAgICBDT0FMRVNDRSh0LlRlblhLLCB0LlRlblRoYW4sIHIuTWFU
>> "%B64_FILE%" echo aGFuKSBBUyBUZW5UaGFuLAogICAgICAgIENBU1QoSVNOVUxMKHIuVG9uREssIDApIEFTIEZMT0FU
>> "%B64_FILE%" echo KSBBUyBUb25ESywKICAgICAgICBDQVNUKElTTlVMTChyLk5oYXBUSywgMCkgQVMgRkxPQVQpIEFT
>> "%B64_FILE%" echo IE5oYXBUSywKICAgICAgICBDQVNUKElTTlVMTChyLlh1YXRUSywgMCkgQVMgRkxPQVQpIEFTIFh1
>> "%B64_FILE%" echo YXRUSywKICAgICAgICBDQVNUKElTTlVMTChyLlRvbkNLLCAwKSBBUyBGTE9BVCkgQVMgVG9uQ0ss
>> "%B64_FILE%" echo CiAgICAgICAgQ09BTEVTQ0UodC5UVElOLCBOJycpIEFTIFRUSU5fVGhhbiwKICAgICAgICBDT0FM
>> "%B64_FILE%" echo RVNDRShrLlRUSU4sIE4nJykgQVMgVFRJTl9LaG8KICAgIEZST00gZGJvLntxaWRlbnQodGFibGVf
>> "%B64_FILE%" echo bmFtZSl9IHIKICAgIExFRlQgSk9JTiB7REJfTUFTVEVSfS5kYm8uRE1USEFOIHQKICAgICAgICBP
>> "%B64_FILE%" echo TiBSVFJJTShMVFJJTSh0Lk1hVGhhbikpID0gUlRSSU0oTFRSSU0oci5NYVRoYW4pKQogICAgTEVG
>> "%B64_FILE%" echo VCBKT0lOIHtEQl9NQVNURVJ9LmRiby5ETUtITyBrCiAgICAgICAgT04gUlRSSU0oTFRSSU0oay5N
>> "%B64_FILE%" echo YUtobykpID0gUlRSSU0oTFRSSU0oci5NYUtobykpCiAgICBXSEVSRQogICAgICAgIElTTlVMTChy
>> "%B64_FILE%" echo Lk1hS2hvLCBOJycpIDw+IE4nJwogICAgICAgIEFORCBJU05VTEwoci5NYVRoYW4sIE4nJykgPD4g
>> "%B64_FILE%" echo TicnCiAgICAgICAgQU5EIEFCUyhDQVNUKElTTlVMTChyLlRvbkNLLCAwKSBBUyBGTE9BVCkpID4g
>> "%B64_FILE%" echo MC4wMDAxCiAgICBPUkRFUiBCWQogICAgICAgIENPQUxFU0NFKGsuVFRJTiwgTicnKSwKICAgICAg
>> "%B64_FILE%" echo ICBDT0FMRVNDRSh0LlRUSU4sIE4nJyksCiAgICAgICAgci5NYUtobywKICAgICAgICByLk1hVGhh
>> "%B64_FILE%" echo bgogICAgIiIiCgogICAgcm93cyA9IGN1ci5leGVjdXRlKHNxbCkuZmV0Y2hhbGwoKQogICAgY29u
>> "%B64_FILE%" echo bi5jbG9zZSgpCgogICAgZGF0YSA9IFtdCiAgICBmb3Igcm93IGluIHJvd3M6CiAgICAgICAgbWFf
>> "%B64_FILE%" echo a2hvID0gbm9ybWFsaXplX3RleHQocm93Lk1hS2hvKQogICAgICAgIHRlbl9raG8gPSBub3JtYWxp
>> "%B64_FILE%" echo emVfdGV4dChyb3cuVGVuS2hvKSBvciBtYV9raG8KICAgICAgICBtYV90aGFuID0gbm9ybWFsaXpl
>> "%B64_FILE%" echo X3RleHQocm93Lk1hVGhhbikKICAgICAgICB0ZW5fdGhhbiA9IG5vcm1hbGl6ZV9jb2FsX25hbWUo
>> "%B64_FILE%" echo cm93LlRlblRoYW4pIG9yIG1hX3RoYW4KCiAgICAgICAgdG9uX2RrID0gcm91bmQoY2xlYW5fbnVt
>> "%B64_FILE%" echo YmVyKHJvdy5Ub25ESyksIDIpCiAgICAgICAgbmhhcF90ayA9IHJvdW5kKGNsZWFuX251bWJlcihy
>> "%B64_FILE%" echo b3cuTmhhcFRLKSwgMikKICAgICAgICB4dWF0X3RrID0gcm91bmQoY2xlYW5fbnVtYmVyKHJvdy5Y
>> "%B64_FILE%" echo dWF0VEspLCAyKQogICAgICAgIHRvbl9jayA9IHJvdW5kKGNsZWFuX251bWJlcihyb3cuVG9uQ0sp
>> "%B64_FILE%" echo LCAyKQoKICAgICAgICBkYXRhLmFwcGVuZCh7CiAgICAgICAgICAgICJNYUtobyI6IG1hX2tobywK
>> "%B64_FILE%" echo ICAgICAgICAgICAgIlRlbktobyI6IHRlbl9raG8sCiAgICAgICAgICAgICJraG8iOiB0ZW5fa2hv
>> "%B64_FILE%" echo LAogICAgICAgICAgICAiTWFUaGFuIjogbWFfdGhhbiwKICAgICAgICAgICAgIlRlblRoYW4iOiB0
>> "%B64_FILE%" echo ZW5fdGhhbiwKICAgICAgICAgICAgImNvYWwiOiB0ZW5fdGhhbiwKICAgICAgICAgICAgIlRvbkRL
>> "%B64_FILE%" echo IjogdG9uX2RrLAogICAgICAgICAgICAiTmhhcFRLIjogbmhhcF90aywKICAgICAgICAgICAgIlh1
>> "%B64_FILE%" echo YXRUSyI6IHh1YXRfdGssCiAgICAgICAgICAgICJUb25DSyI6IHRvbl9jaywKICAgICAgICAgICAg
>> "%B64_FILE%" echo InRvbiI6IHRvbl9jaywKICAgICAgICAgICAgInR0Y29BcHAiOiB0b25fY2ssCiAgICAgICAgICAg
>> "%B64_FILE%" echo ICJzb3VyY2VGb3JtdWxhIjogIlRUQ09fQVBQIGxpdmUgZmluYWwgdGFibGU6IFRvbkNLIiwKICAg
>> "%B64_FILE%" echo ICAgICAgICAgInR0aW5LaG8iOiBub3JtYWxpemVfdGV4dChyb3cuVFRJTl9LaG8pLAogICAgICAg
>> "%B64_FILE%" echo ICAgICAidHRpblRoYW4iOiBub3JtYWxpemVfdGV4dChyb3cuVFRJTl9UaGFuKSwKICAgICAgICB9
>> "%B64_FILE%" echo KQoKICAgIGRhdGEuc29ydChrZXk9bGFtYmRhIHg6IChraG9fc29ydF9rZXkoeFsiVGVuS2hvIl0s
>> "%B64_FILE%" echo IHhbIk1hS2hvIl0pLCB4WyJ0dGluVGhhbiJdLCB4WyJUZW5UaGFuIl0pKQogICAgcmV0dXJuIGRh
>> "%B64_FILE%" echo dGEKCgpkZWYgYnVpbGRfcGF5bG9hZF9mcm9tX3RhYmxlKHRhYmxlX25hbWU6IHN0cik6CiAgICBk
>> "%B64_FILE%" echo YXRhID0gcmVhZF9maW5hbF9yb3dzKHRhYmxlX25hbWUpCiAgICBpZiBub3QgZGF0YToKICAgICAg
>> "%B64_FILE%" echo ICByYWlzZSBSdW50aW1lRXJyb3IoZiJC4bqjbmcge3RhYmxlX25hbWV9IGtow7RuZyBjw7MgZMOy
>> "%B64_FILE%" echo bmcgVG9uQ0sgaOG7o3AgbOG7hy4iKQoKICAgIHRvdGFsID0gcm91bmQoc3VtKGZsb2F0KHJbIlRv
>> "%B64_FILE%" echo bkNLIl0pIGZvciByIGluIGRhdGEpLCAyKQogICAga2hvMV9yb3dzID0gWwogICAgICAgIHIgZm9y
>> "%B64_FILE%" echo IHIgaW4gZGF0YQogICAgICAgIGlmIHJbIlRlbktobyJdLnN0cmlwKCkubG93ZXIoKSA9PSAia2hv
>> "%B64_FILE%" echo IDEiIG9yIHJbIk1hS2hvIl0uc3RyaXAoKSBpbiAoIjEiLCAiMDEiKQogICAgXQogICAga2hvMV90
>> "%B64_FILE%" echo b3RhbCA9IHJvdW5kKHN1bShmbG9hdChyWyJUb25DSyJdKSBmb3IgciBpbiBraG8xX3Jvd3MpLCAy
>> "%B64_FILE%" echo KQoKICAgIHBheWxvYWQgPSB7CiAgICAgICAgIm9rIjogVHJ1ZSwKICAgICAgICAibWV0YSI6IHsK
>> "%B64_FILE%" echo ICAgICAgICAgICAgInNvdXJjZSI6ICJUVENPX0FQUF9TUUxfTElWRV9GSU5BTF9HM19CQzA1QV8y
>> "%B64_FILE%" echo IiwKICAgICAgICAgICAgImRhdGFiYXNlIjogREJfUkVQT1JULAogICAgICAgICAgICAic291cmNl
>> "%B64_FILE%" echo VGFibGUiOiB0YWJsZV9uYW1lLAogICAgICAgICAgICAibWFzdGVyRGF0YWJhc2UiOiBEQl9NQVNU
>> "%B64_FILE%" echo RVIsCiAgICAgICAgICAgICJ2ZXJzaW9uIjogInNxbC1saXZlLWZpbmFsLWczYmMwNWEtdjE3IiwK
>> "%B64_FILE%" echo ICAgICAgICAgICAgInVwZGF0ZWRBdCI6IGRhdGV0aW1lLm5vdygpLnN0cmZ0aW1lKCIlWS0lbS0l
>> "%B64_FILE%" echo ZCAlSDolTTolUyIpLAogICAgICAgICAgICAicm93Q291bnQiOiBsZW4oZGF0YSksCiAgICAgICAg
>> "%B64_FILE%" echo ICAgICJ0b3RhbFRvbiI6IHRvdGFsLAogICAgICAgICAgICAia2hvMVRvdGFsIjoga2hvMV90b3Rh
>> "%B64_FILE%" echo bCwKICAgICAgICAgICAgImZvcm11bGEiOiAiVXNlIFRUQ09fQVBQIGxpdmUgZmluYWwgcmVzdWx0
>> "%B64_FILE%" echo IHRhYmxlIFRvbkNLIGZyb20gRzNfQkMwNUFfMl8jIyMjIyMiLAogICAgICAgICAgICAibm90ZSI6
>> "%B64_FILE%" echo ICJCQVQgYuG6r3QgYuG6o25nIGvhur90IHF14bqjIGN14buRaSBuZ2F5IGzDumMgVFRDT19BUFAg
>> "%B64_FILE%" echo duG7q2EgYuG6pW0gWGVtIGtxOyBkw7luZyBUb25DSyB04burIEczX0JDMDVBXzJfIyMjIyMjIHRy
>> "%B64_FILE%" echo xrDhu5tjIGtoaSBi4bqjbmcgdOG6oW0gYuG7iyB4w7NhLiIsCiAgICAgICAgfSwKICAgICAgICAi
>> "%B64_FILE%" echo ZGF0YSI6IGRhdGEsCiAgICAgICAgInJvd3MiOiBkYXRhLAogICAgfQogICAgcmV0dXJuIHBheWxv
>> "%B64_FILE%" echo YWQsIGtobzFfcm93cwoKCmRlZiBjYXB0dXJlX2xpdmVfZmluYWxfdGFibGUodGltZW91dF9zZWNv
>> "%B64_FILE%" echo bmRzPTE4MCk6CiAgICBwcmludCgixJBhbmcga+G6v3QgbuG7kWkgU1FMLi4uIikKICAgIGNvbm4g
>> "%B64_FILE%" echo PSBjb25uZWN0KERCX1JFUE9SVCkKICAgIGN1ciA9IGNvbm4uY3Vyc29yKCkKCiAgICBiZWZvcmUg
>> "%B64_FILE%" echo PSBnZXRfZXhpc3RpbmdfZmluYWxfdGFibGVzKGN1cikKICAgIHByaW50KGYiW09LXSBUcsaw4bub
>> "%B64_FILE%" echo YyBraGkgYuG6pW0gWGVtIGtxIGPDsyB7bGVuKGJlZm9yZSl9IGLhuqNuZyBHM19CQzA1QV8yXyMj
>> "%B64_FILE%" echo IyMjIyBjxakuIikKICAgIHByaW50KCIiKQogICAgcHJpbnQoIkLDglkgR0nhu5wgYW5oIGjDo3kg
>> "%B64_FILE%" echo c2FuZyBUVENPX0FQUCB2w6AgYuG6pW0gWGVtIGtxLiIpCiAgICBwcmludCgiQkFUIHPhur0gdOG7
>> "%B64_FILE%" echo sSBi4bqvdCBi4bqjbmcgRzNfQkMwNUFfMl8jIyMjIyMgbeG7m2kgbmdheSBraGkgVFRDT19BUFAg
>> "%B64_FILE%" echo dOG6oW8gcmEuIikKICAgIHByaW50KCIiKQoKICAgIHN0YXJ0ID0gdGltZS50aW1lKCkKICAgIGxh
>> "%B64_FILE%" echo c3RfcGF5bG9hZCA9IE5vbmUKICAgIGxhc3Rfa2hvMV9yb3dzID0gW10KICAgIGxhc3RfdGFibGUg
>> "%B64_FILE%" echo PSAiIgogICAgc2VlbiA9IHNldChiZWZvcmUpCiAgICBsYXN0X3ByaW50ID0gMAoKICAgIHdoaWxl
>> "%B64_FILE%" echo IHRpbWUudGltZSgpIC0gc3RhcnQgPCB0aW1lb3V0X3NlY29uZHM6CiAgICAgICAgdHJ5OgogICAg
>> "%B64_FILE%" echo ICAgICAgICBjYW5kaWRhdGVzID0gbGlzdF9maW5hbF90YWJsZV9jYW5kaWRhdGVzKGN1cikKICAg
>> "%B64_FILE%" echo ICAgICAgICAgZm9yIHIgaW4gY2FuZGlkYXRlczoKICAgICAgICAgICAgICAgIHRhYmxlX25hbWUg
>> "%B64_FILE%" echo PSBzdHIoci5uYW1lKQoKICAgICAgICAgICAgICAgICMgxq91IHRpw6puIGLhuqNuZyBt4bubaSB0
>> "%B64_FILE%" echo 4bqhbyBzYXUga2hpIEJBVCBi4bqvdCDEkeG6p3UuCiAgICAgICAgICAgICAgICBpZiB0YWJsZV9u
>> "%B64_FILE%" echo YW1lIGluIHNlZW46CiAgICAgICAgICAgICAgICAgICAgY29udGludWUKCiAgICAgICAgICAgICAg
>> "%B64_FILE%" echo ICBzZWVuLmFkZCh0YWJsZV9uYW1lKQoKICAgICAgICAgICAgICAgIGlmIG5vdCB0YWJsZV9oYXNf
>> "%B64_FILE%" echo cmVxdWlyZWRfY29scyhjdXIsIHRhYmxlX25hbWUpOgogICAgICAgICAgICAgICAgICAgIHByaW50
>> "%B64_FILE%" echo KGYiW1NLSVBdIHt0YWJsZV9uYW1lfTogY2jGsGEgxJHhu6cgY+G7mXQgTWFLaG8vTWFUaGFuL1Rv
>> "%B64_FILE%" echo bkRLL05oYXBUSy9YdWF0VEsvVG9uQ0siKQogICAgICAgICAgICAgICAgICAgIGNvbnRpbnVlCgog
>> "%B64_FILE%" echo ICAgICAgICAgICAgICAgcHJpbnQoZiJbQuG6rlQgxJDGr+G7okNdIELhuqNuZyBr4bq/dCBxdeG6
>> "%B64_FILE%" echo oyBjdeG7kWkgbeG7m2k6IHt0YWJsZV9uYW1lfSIpCiAgICAgICAgICAgICAgICBwcmludCgixJBh
>> "%B64_FILE%" echo bmcgxJHhu41jIG5oYW5oIFRvbkNLIHRyxrDhu5tjIGtoaSBUVENPX0FQUCBjw7MgdGjhu4MgeMOz
>> "%B64_FILE%" echo YSBi4bqjbmcgdOG6oW0uLi4iKQoKICAgICAgICAgICAgICAgIHRyeToKICAgICAgICAgICAgICAg
>> "%B64_FILE%" echo ICAgICBwYXlsb2FkLCBraG8xX3Jvd3MgPSBidWlsZF9wYXlsb2FkX2Zyb21fdGFibGUodGFibGVf
>> "%B64_FILE%" echo bmFtZSkKICAgICAgICAgICAgICAgICAgICBsYXN0X3BheWxvYWQgPSBwYXlsb2FkCiAgICAgICAg
>> "%B64_FILE%" echo ICAgICAgICAgICAgbGFzdF9raG8xX3Jvd3MgPSBraG8xX3Jvd3MKICAgICAgICAgICAgICAgICAg
>> "%B64_FILE%" echo ICBsYXN0X3RhYmxlID0gdGFibGVfbmFtZQoKICAgICAgICAgICAgICAgICAgICBwcmludChmIltP
>> "%B64_FILE%" echo S10gxJDhu41jIMSRxrDhu6NjIHtwYXlsb2FkWydtZXRhJ11bJ3Jvd0NvdW50J119IGTDsm5nIHTh
>> "%B64_FILE%" echo u6sge3RhYmxlX25hbWV9IikKICAgICAgICAgICAgICAgICAgICBwcmludChmIlThu5VuZyB04buT
>> "%B64_FILE%" echo biAgIDoge3BheWxvYWRbJ21ldGEnXVsndG90YWxUb24nXTosLjJmfSIpCiAgICAgICAgICAgICAg
>> "%B64_FILE%" echo ICAgICAgcHJpbnQoZiJU4buVbmcgS2hvIDEgOiB7cGF5bG9hZFsnbWV0YSddWydraG8xVG90YWwn
>> "%B64_FILE%" echo XTosLjJmfSIpCgogICAgICAgICAgICAgICAgICAgICMgU2F1IGtoaSBi4bqvdCDEkcaw4bujYyBi
>> "%B64_FILE%" echo 4bqjbmcgaOG7o3AgbOG7hywgY2jhu50gdGjDqm0gMiBnacOieSBy4buTaSB0aOG7rSDEkeG7jWMg
>> "%B64_FILE%" echo bOG6oWkgY8O5bmcgYuG6o25nIG7hur91IGPDsm4gdOG7k24gdOG6oWksCiAgICAgICAgICAgICAg
>> "%B64_FILE%" echo ICAgICAgIyDEkeG7gyBs4bqleSBi4bqjbiBzYXUgbOG7h25oIERFTEVURSBkw7JuZyAwL1VQREFU
>> "%B64_FILE%" echo RSBDMSBu4bq/dSBTUUwgU2VydmVyIGNoxrBhIHjDs2EgYuG6o25nLgogICAgICAgICAgICAgICAg
>> "%B64_FILE%" echo ICAgIHRpbWUuc2xlZXAoMikKICAgICAgICAgICAgICAgICAgICB0cnk6CiAgICAgICAgICAgICAg
>> "%B64_FILE%" echo ICAgICAgICAgIHBheWxvYWQyLCBraG8xX3Jvd3MyID0gYnVpbGRfcGF5bG9hZF9mcm9tX3RhYmxl
>> "%B64_FILE%" echo KHRhYmxlX25hbWUpCiAgICAgICAgICAgICAgICAgICAgICAgIGlmIHBheWxvYWQyWyJtZXRhIl1b
>> "%B64_FILE%" echo InJvd0NvdW50Il0gPj0gcGF5bG9hZFsibWV0YSJdWyJyb3dDb3VudCJdOgogICAgICAgICAgICAg
>> "%B64_FILE%" echo ICAgICAgICAgICAgICAgbGFzdF9wYXlsb2FkID0gcGF5bG9hZDIKICAgICAgICAgICAgICAgICAg
>> "%B64_FILE%" echo ICAgICAgICAgIGxhc3Rfa2hvMV9yb3dzID0ga2hvMV9yb3dzMgogICAgICAgICAgICAgICAgICAg
>> "%B64_FILE%" echo ICAgICAgICAgcHJpbnQoZiJbT0tdIMSQ4buNYyBs4bqhaSBzYXUgMiBnacOieToge3BheWxvYWQy
>> "%B64_FILE%" echo WydtZXRhJ11bJ3Jvd0NvdW50J119IGTDsm5nLCBLaG8gMT17cGF5bG9hZDJbJ21ldGEnXVsna2hv
>> "%B64_FILE%" echo MVRvdGFsJ106LC4yZn0iKQogICAgICAgICAgICAgICAgICAgIGV4Y2VwdCBFeGNlcHRpb246CiAg
>> "%B64_FILE%" echo ICAgICAgICAgICAgICAgICAgICAgIHBhc3MKCiAgICAgICAgICAgICAgICAgICAgY29ubi5jbG9z
>> "%B64_FILE%" echo ZSgpCiAgICAgICAgICAgICAgICAgICAgcmV0dXJuIGxhc3RfdGFibGUsIGxhc3RfcGF5bG9hZCwg
>> "%B64_FILE%" echo bGFzdF9raG8xX3Jvd3MKCiAgICAgICAgICAgICAgICBleGNlcHQgRXhjZXB0aW9uIGFzIGV4YzoK
>> "%B64_FILE%" echo ICAgICAgICAgICAgICAgICAgICBwcmludChmIltXQVJOXSBLaMO0bmcgxJHhu41jIMSRxrDhu6Nj
>> "%B64_FILE%" echo IHt0YWJsZV9uYW1lfToge2V4Y30iKQoKICAgICAgICBleGNlcHQgRXhjZXB0aW9uIGFzIGV4YzoK
>> "%B64_FILE%" echo ICAgICAgICAgICAgcHJpbnQoZiJbV0FSTl0gTOG7l2kga2hpIGTDsiBi4bqjbmcgbGl2ZToge2V4
>> "%B64_FILE%" echo Y30iKQoKICAgICAgICBub3cgPSB0aW1lLnRpbWUoKQogICAgICAgIGlmIG5vdyAtIGxhc3RfcHJp
>> "%B64_FILE%" echo bnQgPj0gNToKICAgICAgICAgICAgcmVtYWluID0gaW50KHRpbWVvdXRfc2Vjb25kcyAtIChub3cg
>> "%B64_FILE%" echo LSBzdGFydCkpCiAgICAgICAgICAgIHByaW50KGYiLi4uIMSRYW5nIGNo4budIFRUQ09fQVBQIHTh
>> "%B64_FILE%" echo uqFvIGLhuqNuZyBr4bq/dCBxdeG6oyBjdeG7kWksIGPDsm4ge3JlbWFpbn0gZ2nDonkiKQogICAg
>> "%B64_FILE%" echo ICAgICAgICBsYXN0X3ByaW50ID0gbm93CgogICAgICAgIHRpbWUuc2xlZXAoMC4yKQoKICAgIGNv
>> "%B64_FILE%" echo bm4uY2xvc2UoKQoKICAgIGlmIGxhc3RfcGF5bG9hZDoKICAgICAgICByZXR1cm4gbGFzdF90YWJs
>> "%B64_FILE%" echo ZSwgbGFzdF9wYXlsb2FkLCBsYXN0X2tobzFfcm93cwoKICAgIHJhaXNlIFJ1bnRpbWVFcnJvcigK
>> "%B64_FILE%" echo ICAgICAgICAiS2jDtG5nIGLhuq90IMSRxrDhu6NjIGLhuqNuZyBr4bq/dCBxdeG6oyBjdeG7kWkg
>> "%B64_FILE%" echo dHJvbmcgdGjhu51pIGdpYW4gY2jhu50uICIKICAgICAgICAiSMOjeSBjaOG6oXkgbOG6oWkgQkFU
>> "%B64_FILE%" echo LCBi4bqlbSBt4bulYyAxLzIgcuG7k2kgYuG6pW0gWGVtIGtxIHRyw6puIFRUQ09fQVBQIG5nYXkg
>> "%B64_FILE%" echo a2hpIEJBVCBi4bqvdCDEkeG6p3UgY2jhu50uIgogICAgKQoKCmRlZiB3cml0ZV9jaGVja19mcm9t
>> "%B64_FILE%" echo X3BheWxvYWQodGFibGVfbmFtZSwgcGF5bG9hZCwga2hvMV9yb3dzKToKICAgIENIRUNLX0RJUi5t
>> "%B64_FILE%" echo a2RpcihwYXJlbnRzPVRydWUsIGV4aXN0X29rPVRydWUpCiAgICBvdXQgPSBDSEVDS19ESVIgLyBm
>> "%B64_FILE%" echo ImNoZWNrX2xpdmVfZmluYWxfZzNiYzA1YV92MTdfe2RhdGV0aW1lLm5vdygpOiVZJW0lZF8lSCVN
>> "%B64_FILE%" echo JVN9LnR4dCIKCiAgICB3aXRoIG91dC5vcGVuKCJ3IiwgZW5jb2Rpbmc9InV0Zi04IikgYXMgZjoK
>> "%B64_FILE%" echo ICAgICAgICBmLndyaXRlKCJUVENPIC0gS0nhu4JNIFRSQSBMSVZFIELhuqJORyBL4bq+VCBRVeG6
>> "%B64_FILE%" echo oiBDVeG7kEkgRzNfQkMwNUEgLSBWMTdcbiIpCiAgICAgICAgZi53cml0ZSgiPSIgKiA5MCArICJc
>> "%B64_FILE%" echo biIpCiAgICAgICAgZi53cml0ZShmIlNvdXJjZSB0YWJsZSA6IHt0YWJsZV9uYW1lfVxuIikKICAg
>> "%B64_FILE%" echo ICAgICBmLndyaXRlKGYiUm93IGNvdW50ICAgIDoge3BheWxvYWRbJ21ldGEnXVsncm93Q291bnQn
>> "%B64_FILE%" echo XX1cbiIpCiAgICAgICAgZi53cml0ZShmIlRvdGFsIHRvbiAgICA6IHtwYXlsb2FkWydtZXRhJ11b
>> "%B64_FILE%" echo J3RvdGFsVG9uJ106LC4yZn1cbiIpCiAgICAgICAgZi53cml0ZShmIktobyAxIHRvdGFsICA6IHtw
>> "%B64_FILE%" echo YXlsb2FkWydtZXRhJ11bJ2tobzFUb3RhbCddOiwuMmZ9XG4iKQogICAgICAgIGYud3JpdGUoZiJV
>> "%B64_FILE%" echo cGRhdGVkIGF0ICAgOiB7cGF5bG9hZFsnbWV0YSddWyd1cGRhdGVkQXQnXX1cbiIpCiAgICAgICAg
>> "%B64_FILE%" echo Zi53cml0ZSgiXG5LaG8gMSByb3dzOlxuIikKICAgICAgICBmb3IgciBpbiBraG8xX3Jvd3M6CiAg
>> "%B64_FILE%" echo ICAgICAgICAgIGYud3JpdGUoCiAgICAgICAgICAgICAgICBmIk1hS2hvPXtyWydNYUtobyddfSB8
>> "%B64_FILE%" echo IEtobz17clsnVGVuS2hvJ119IHwgIgogICAgICAgICAgICAgICAgZiJNYVRoYW49e3JbJ01hVGhh
>> "%B64_FILE%" echo biddfSB8IFRoYW49e3JbJ1RlblRoYW4nXX0gfCAiCiAgICAgICAgICAgICAgICBmIlRvbkRLPXty
>> "%B64_FILE%" echo WydUb25ESyddOiwuMmZ9IHwgTmhhcFRLPXtyWydOaGFwVEsnXTosLjJmfSB8ICIKICAgICAgICAg
>> "%B64_FILE%" echo ICAgICAgIGYiWHVhdFRLPXtyWydYdWF0VEsnXTosLjJmfSB8IFRvbkNLPXtyWydUb25DSyddOiwu
>> "%B64_FILE%" echo MmZ9XG4iCiAgICAgICAgICAgICkKCiAgICBwcmludChmIltPS10gxJDDoyB4deG6pXQgZmlsZSBr
>> "%B64_FILE%" echo aeG7g20gdHJhOiB7b3V0fSIpCiAgICB0cnk6CiAgICAgICAgc3VicHJvY2Vzcy5Qb3BlbihbImV4
>> "%B64_FILE%" echo cGxvcmVyLmV4ZSIsIHN0cihDSEVDS19ESVIpXSkKICAgIGV4Y2VwdCBFeGNlcHRpb246CiAgICAg
>> "%B64_FILE%" echo ICAgcGFzcwogICAgcmV0dXJuIG91dAoKCmRlZiB3cml0ZV9qc29uKHJlcG9fZGlyOiBzdHIsIHBh
>> "%B64_FILE%" echo eWxvYWQpOgogICAgZGVzdCA9IFBhdGgocmVwb19kaXIpIC8gSlNPTl9SRUwKICAgIGRlc3QucGFy
>> "%B64_FILE%" echo ZW50Lm1rZGlyKHBhcmVudHM9VHJ1ZSwgZXhpc3Rfb2s9VHJ1ZSkKICAgIGRlc3Qud3JpdGVfdGV4
>> "%B64_FILE%" echo dChqc29uLmR1bXBzKHBheWxvYWQsIGVuc3VyZV9hc2NpaT1GYWxzZSwgaW5kZW50PTIpLCBlbmNv
>> "%B64_FILE%" echo ZGluZz0idXRmLTgiKQogICAgcHJpbnQoZiJbT0tdIMSQw6MgdOG6oW8gSlNPTjoge2Rlc3R9IikK
>> "%B64_FILE%" echo ICAgIHJldHVybiBkZXN0CgoKZGVmIHB1c2hfZ2l0aHViKHJlcG9fZGlyOiBzdHIsIHBheWxvYWQp
>> "%B64_FILE%" echo OgogICAgZW5zdXJlX2dpdCgpCiAgICBlbnN1cmVfcmVwbyhyZXBvX2RpcikKCiAgICB3cml0ZV9q
>> "%B64_FILE%" echo c29uKHJlcG9fZGlyLCBwYXlsb2FkKQoKICAgIHByaW50KCJcbsSQYW5nIGNvbW1pdC9wdXNoIGzD
>> "%B64_FILE%" echo qm4gR2l0SHViLi4uIikKICAgIHJ1bihbImdpdCIsICJjaGVja291dCIsIEJSQU5DSF0sIGN3ZD1y
>> "%B64_FILE%" echo ZXBvX2RpciwgY2hlY2s9RmFsc2UpCiAgICBydW4oWyJnaXQiLCAicHVsbCIsICItLXJlYmFzZSIs
>> "%B64_FILE%" echo ICJvcmlnaW4iLCBCUkFOQ0hdLCBjd2Q9cmVwb19kaXIsIGNoZWNrPUZhbHNlKQogICAgcnVuKFsi
>> "%B64_FILE%" echo Z2l0IiwgImFkZCIsIEpTT05fUkVMXSwgY3dkPXJlcG9fZGlyKQoKICAgIGRpZmZfY29kZSA9IHN1
>> "%B64_FILE%" echo YnByb2Nlc3MucnVuKFsiZ2l0IiwgImRpZmYiLCAiLS1jYWNoZWQiLCAiLS1xdWlldCJdLCBjd2Q9
>> "%B64_FILE%" echo cmVwb19kaXIpLnJldHVybmNvZGUKICAgIGlmIGRpZmZfY29kZSA9PSAwOgogICAgICAgIHByaW50
>> "%B64_FILE%" echo KCJbT0tdIEpTT04ga2jDtG5nIHRoYXkgxJHhu5VpLCBraMO0bmcgY+G6p24gcHVzaC4iKQogICAg
>> "%B64_FILE%" echo ICAgIGxvZygiTm8gY2hhbmdlcy4iKQogICAgICAgIHJldHVybgoKICAgIG1zZyA9ICJVcGRhdGUg
>> "%B64_FILE%" echo VFRDTyB0b24ga2hvIGZyb20gbGl2ZSBmaW5hbCBTUUwgdGFibGUgIiArIGRhdGV0aW1lLm5vdygp
>> "%B64_FILE%" echo LnN0cmZ0aW1lKCIlWS0lbS0lZCAlSDolTTolUyIpCiAgICBydW4oWyJnaXQiLCAiY29tbWl0Iiwg
>> "%B64_FILE%" echo Ii1tIiwgbXNnXSwgY3dkPXJlcG9fZGlyKQogICAgcnVuKFsiZ2l0IiwgInB1c2giLCAib3JpZ2lu
>> "%B64_FILE%" echo IiwgQlJBTkNIXSwgY3dkPXJlcG9fZGlyKQoKICAgIHByaW50KCJcbj09PT09PT09PT09PT09PT09
>> "%B64_FILE%" echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PSIpCiAgICBwcmludCgi
>> "%B64_FILE%" echo W09LXSDEkMODIEPhuqxQIE5I4bqsVCBHSVRIVUIgVEjDgE5IIEPDlE5HIikKICAgIHByaW50KCI9
>> "%B64_FILE%" echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
>> "%B64_FILE%" echo PT0iKQogICAgbG9nKCJQdXNoIHN1Y2Nlc3MuIikKCgpkZWYgZG9fbGl2ZV9jaGVja19vbmx5KCk6
>> "%B64_FILE%" echo CiAgICB0YWJsZV9uYW1lLCBwYXlsb2FkLCBraG8xX3Jvd3MgPSBjYXB0dXJlX2xpdmVfZmluYWxf
>> "%B64_FILE%" echo dGFibGUoKQogICAgd3JpdGVfY2hlY2tfZnJvbV9wYXlsb2FkKHRhYmxlX25hbWUsIHBheWxvYWQs
>> "%B64_FILE%" echo IGtobzFfcm93cykKICAgIHByaW50KCIiKQogICAgcHJpbnQoIktp4buDbSB0cmEgbmhhbmg6IikK
>> "%B64_FILE%" echo ICAgIHByaW50KGYiQuG6o25nIG5ndeG7k24gOiB7dGFibGVfbmFtZX0iKQogICAgcHJpbnQoZiJT
>> "%B64_FILE%" echo 4buRIGTDsm5nICAgIDoge3BheWxvYWRbJ21ldGEnXVsncm93Q291bnQnXX0iKQogICAgcHJpbnQo
>> "%B64_FILE%" echo ZiJU4buVbmcgdOG7k24gICA6IHtwYXlsb2FkWydtZXRhJ11bJ3RvdGFsVG9uJ106LC4yZn0iKQog
>> "%B64_FILE%" echo ICAgcHJpbnQoZiJU4buVbmcgS2hvIDEgOiB7cGF5bG9hZFsnbWV0YSddWydraG8xVG90YWwnXTos
>> "%B64_FILE%" echo LjJmfSIpCgoKZGVmIGRvX2xpdmVfdXBkYXRlKHJlcG9fZGlyKToKICAgIHRhYmxlX25hbWUsIHBh
>> "%B64_FILE%" echo eWxvYWQsIGtobzFfcm93cyA9IGNhcHR1cmVfbGl2ZV9maW5hbF90YWJsZSgpCiAgICB3cml0ZV9j
>> "%B64_FILE%" echo aGVja19mcm9tX3BheWxvYWQodGFibGVfbmFtZSwgcGF5bG9hZCwga2hvMV9yb3dzKQoKICAgIHBy
>> "%B64_FILE%" echo aW50KCIiKQogICAgcHJpbnQoIktp4buDbSB0cmEgbmhhbmggdHLGsOG7m2Mga2hpIHVwOiIpCiAg
>> "%B64_FILE%" echo ICBwcmludChmIkLhuqNuZyBuZ3Xhu5NuIDoge3RhYmxlX25hbWV9IikKICAgIHByaW50KGYiU+G7
>> "%B64_FILE%" echo kSBkw7JuZyAgICA6IHtwYXlsb2FkWydtZXRhJ11bJ3Jvd0NvdW50J119IikKICAgIHByaW50KGYi
>> "%B64_FILE%" echo VOG7lW5nIHThu5NuICAgOiB7cGF5bG9hZFsnbWV0YSddWyd0b3RhbFRvbiddOiwuMmZ9IikKICAg
>> "%B64_FILE%" echo IHByaW50KGYiVOG7lW5nIEtobyAxIDoge3BheWxvYWRbJ21ldGEnXVsna2hvMVRvdGFsJ106LC4y
>> "%B64_FILE%" echo Zn0iKQogICAgcHJpbnQoIiIpCgogICAgcHVzaF9naXRodWIocmVwb19kaXIsIHBheWxvYWQpCgoK
>> "%B64_FILE%" echo ZGVmIGluc3RhbGxfdGFzayhiYXRfcGF0aDogc3RyKToKICAgIGlmIG5vdCBiYXRfcGF0aCBvciBu
>> "%B64_FILE%" echo b3Qgb3MucGF0aC5pc2ZpbGUoYmF0X3BhdGgpOgogICAgICAgIHJhaXNlIFJ1bnRpbWVFcnJvcigi
>> "%B64_FILE%" echo S2jDtG5nIHjDoWMgxJHhu4tuaCDEkcaw4bujYyBmaWxlIEJBVCDEkeG7gyBjw6BpIHThu7EgxJHh
>> "%B64_FILE%" echo u5luZy4iKQogICAgdGFza19jbWQgPSBmJyJ7YmF0X3BhdGh9IiAtLWF1dG8nCiAgICBydW4oWyJz
>> "%B64_FILE%" echo Y2h0YXNrcyIsICIvQ3JlYXRlIiwgIi9UTiIsIFRBU0tfTkFNRSwgIi9UUiIsIHRhc2tfY21kLCAi
>> "%B64_FILE%" echo L1NDIiwgIk9OTE9HT04iLCAiL0RFTEFZIiwgIjAwMDE6MDAiLCAiL0YiXSkKICAgIHByaW50KCJb
>> "%B64_FILE%" echo T0tdIMSQw6MgY8OgaSB04buxIMSR4buZbmcga2hpIMSRxINuZyBuaOG6rXAgV2luZG93cy4iKQog
>> "%B64_FILE%" echo ICAgcHJpbnQoIkzGsHUgw706IGNo4bq/IMSR4buZIHThu7EgxJHhu5luZyBz4bq9IGNo4budIFRU
>> "%B64_FILE%" echo Q09fQVBQIHThuqFvIGLhuqNuZyBr4bq/dCBxdeG6oyBjdeG7kWkgdHJvbmcgMTgwIGdpw6J5LiIp
>> "%B64_FILE%" echo CiAgICBsb2coZiJJbnN0YWxsIHRhc2s6IHt0YXNrX2NtZH0iKQoKCmRlZiBvcGVuX2xvZygpOgog
>> "%B64_FILE%" echo ICAgQ09ORklHX0RJUi5ta2RpcihwYXJlbnRzPVRydWUsIGV4aXN0X29rPVRydWUpCiAgICBpZiBu
>> "%B64_FILE%" echo b3QgTE9HX0ZJTEUuZXhpc3RzKCk6CiAgICAgICAgTE9HX0ZJTEUud3JpdGVfdGV4dCgiQ2jGsGEg
>> "%B64_FILE%" echo Y8OzIGxvZy5cbiIsIGVuY29kaW5nPSJ1dGYtOCIpCiAgICBzdWJwcm9jZXNzLlBvcGVuKFsibm90
>> "%B64_FILE%" echo ZXBhZC5leGUiLCBzdHIoTE9HX0ZJTEUpXSkKCgpkZWYgbWFpbigpOgogICAgcGFyc2VyID0gYXJn
>> "%B64_FILE%" echo cGFyc2UuQXJndW1lbnRQYXJzZXIoKQogICAgcGFyc2VyLmFkZF9hcmd1bWVudCgiLS1hY3Rpb24i
>> "%B64_FILE%" echo LCBjaG9pY2VzPVsibGl2ZS11cGRhdGUiLCAibGl2ZS1jaGVjayIsICJjb25maWctcmVwbyIsICJp
>> "%B64_FILE%" echo bnN0YWxsIiwgIm9wZW4tbG9nIl0sIHJlcXVpcmVkPVRydWUpCiAgICBwYXJzZXIuYWRkX2FyZ3Vt
>> "%B64_FILE%" echo ZW50KCItLWJhdCIsIGRlZmF1bHQ9IiIpCiAgICBhcmdzID0gcGFyc2VyLnBhcnNlX2FyZ3MoKQoK
>> "%B64_FILE%" echo ICAgIHRyeToKICAgICAgICBjZmcgPSBsb2FkX2NvbmZpZygpCgogICAgICAgIGlmIGFyZ3MuYWN0
>> "%B64_FILE%" echo aW9uID09ICJvcGVuLWxvZyI6CiAgICAgICAgICAgIG9wZW5fbG9nKCkKICAgICAgICAgICAgcmV0
>> "%B64_FILE%" echo dXJuIDAKCiAgICAgICAgaWYgYXJncy5hY3Rpb24gPT0gImNvbmZpZy1yZXBvIjoKICAgICAgICAg
>> "%B64_FILE%" echo ICAgZm9sZGVyID0gcGlja19mb2xkZXIoIkNo4buNbiB0aMawIG3hu6VjIHJlcG8gR2l0SHViIG15
>> "%B64_FILE%" echo LWFpLXNpdGUiLCBjZmcuZ2V0KCJyZXBvX2RpciIpIG9yIHIiRDpcVFRDT19Ub25LaG9fQXBwX1Jl
>> "%B64_FILE%" echo cG8iKQogICAgICAgICAgICBpZiBub3QgZm9sZGVyOgogICAgICAgICAgICAgICAgcmFpc2UgUnVu
>> "%B64_FILE%" echo dGltZUVycm9yKCJDaMawYSBjaOG7jW4gdGjGsCBt4bulYyByZXBvLiIpCiAgICAgICAgICAgIGNm
>> "%B64_FILE%" echo Z1sicmVwb19kaXIiXSA9IGZvbGRlcgogICAgICAgICAgICBzYXZlX2NvbmZpZyhjZmcpCiAgICAg
>> "%B64_FILE%" echo ICAgICAgIHByaW50KGYiW09LXSDEkMOjIGzGsHUgcmVwbzoge2ZvbGRlcn0iKQogICAgICAgICAg
>> "%B64_FILE%" echo ICByZXR1cm4gMAoKICAgICAgICByZXBvX2RpciA9IGNmZy5nZXQoInJlcG9fZGlyIikgb3IgciJE
>> "%B64_FILE%" echo OlxUVENPX1Rvbktob19BcHBfUmVwbyIKICAgICAgICBpZiBhcmdzLmFjdGlvbiBpbiAoImxpdmUt
>> "%B64_FILE%" echo dXBkYXRlIiwgImluc3RhbGwiKToKICAgICAgICAgICAgaWYgbm90IG9zLnBhdGguaXNkaXIocmVw
>> "%B64_FILE%" echo b19kaXIpOgogICAgICAgICAgICAgICAgZm9sZGVyID0gcGlja19mb2xkZXIoIkNo4buNbiB0aMaw
>> "%B64_FILE%" echo IG3hu6VjIHJlcG8gR2l0SHViIG15LWFpLXNpdGUiLCByZXBvX2RpcikKICAgICAgICAgICAgICAg
>> "%B64_FILE%" echo IGlmIG5vdCBmb2xkZXI6CiAgICAgICAgICAgICAgICAgICAgcmFpc2UgUnVudGltZUVycm9yKCJD
>> "%B64_FILE%" echo aMawYSBjaOG7jW4gdGjGsCBt4bulYyByZXBvLiIpCiAgICAgICAgICAgICAgICBjZmdbInJlcG9f
>> "%B64_FILE%" echo ZGlyIl0gPSBmb2xkZXIKICAgICAgICAgICAgICAgIHJlcG9fZGlyID0gZm9sZGVyCiAgICAgICAg
>> "%B64_FILE%" echo ICAgICAgICBzYXZlX2NvbmZpZyhjZmcpCgogICAgICAgIGlmIGFyZ3MuYWN0aW9uID09ICJpbnN0
>> "%B64_FILE%" echo YWxsIjoKICAgICAgICAgICAgaW5zdGFsbF90YXNrKGFyZ3MuYmF0KQogICAgICAgICAgICByZXR1
>> "%B64_FILE%" echo cm4gMAoKICAgICAgICBpZiBhcmdzLmFjdGlvbiA9PSAibGl2ZS1jaGVjayI6CiAgICAgICAgICAg
>> "%B64_FILE%" echo IGRvX2xpdmVfY2hlY2tfb25seSgpCiAgICAgICAgICAgIHJldHVybiAwCgogICAgICAgIGlmIGFy
>> "%B64_FILE%" echo Z3MuYWN0aW9uID09ICJsaXZlLXVwZGF0ZSI6CiAgICAgICAgICAgIGRvX2xpdmVfdXBkYXRlKHJl
>> "%B64_FILE%" echo cG9fZGlyKQogICAgICAgICAgICByZXR1cm4gMAoKICAgICAgICByZXR1cm4gMAogICAgZXhjZXB0
>> "%B64_FILE%" echo IEV4Y2VwdGlvbiBhcyBleGM6CiAgICAgICAgcHJpbnQoIlxuW0zhu5ZJXSIsIGV4YykKICAgICAg
>> "%B64_FILE%" echo ICBwcmludCgiTG9nOiIsIExPR19GSUxFKQogICAgICAgIGxvZyhmIkVSUk9SOiB7ZXhjfSIpCiAg
>> "%B64_FILE%" echo ICAgICAgcmV0dXJuIDEKCgppZiBfX25hbWVfXyA9PSAiX19tYWluX18iOgogICAgc3lzLmV4aXQo
>> "%B64_FILE%" echo bWFpbigpKQo=
python -c "import base64, pathlib, os; b=pathlib.Path(os.environ['B64_FILE']).read_text().replace('\n','').replace('\r','').strip(); pathlib.Path(os.environ['PY_MAIN']).write_bytes(base64.b64decode(b))"
exit /b %errorlevel%
