@echo off
setlocal EnableExtensions EnableDelayedExpansion
chcp 65001 >nul
title TTCO Direct DB To GitHub - v23

set "CONFIG_DIR=%LOCALAPPDATA%\TTCO_TonKho_DirectDB_V23"
set "PY_MAIN=%CONFIG_DIR%\TTCO_DirectDB_To_GitHub_v23.py"
set "B64_FILE=%CONFIG_DIR%\TTCO_DirectDB_To_GitHub_v23.b64"

if not exist "%CONFIG_DIR%" mkdir "%CONFIG_DIR%" >nul 2>&1

call :WRITE_PY
if errorlevel 1 (
    echo [LOI] Khong tao duoc file Python tam.
    pause
    exit /b 1
)

if /I "%~1"=="--auto" (
    python "%PY_MAIN%" --action update --bat "%~f0"
    exit /b %errorlevel%
)

:MENU
cls
echo ============================================================
echo      TTCO - DO TRUC TIEP DU LIEU TU DB LEN GITHUB v23
echo ============================================================
echo Can cu ket qua anh xac nhan:
echo   - v21 TonDK dung
echo   - v19 NhapTK va XuatTK dung
echo.
echo Cong thuc v23:
echo   TonCK = TonDK tu CDOTHAN thang truoc + NhapTK logic v19 - XuatTK logic v19
echo.
echo  [1] Kiem tra truc tiep DB thang hien tai, chua up GitHub
echo.
echo  [2] Cap nhat GitHub truc tiep DB thang hien tai
echo.
echo  [3] Kiem tra truc tiep DB thang tuy chon, chua up GitHub
echo.
echo  [4] Cap nhat GitHub truc tiep DB thang tuy chon
echo.
echo  [5] Chon lai thu muc repo GitHub my-ai-site
echo.
echo  [6] Cai dat tu dong khi dang nhap Windows
echo.
echo  [7] Mo file log
echo.
echo  [0] Thoat
echo.
echo ============================================================
choice /C 12345670 /N /M "Chon chuc nang [1/2/3/4/5/6/7/0]: "

if errorlevel 8 exit /b 0
if errorlevel 7 (
    python "%PY_MAIN%" --action open-log --bat "%~f0"
    goto MENU
)
if errorlevel 6 (
    python "%PY_MAIN%" --action install --bat "%~f0"
    pause
    goto MENU
)
if errorlevel 5 (
    python "%PY_MAIN%" --action config-repo --bat "%~f0"
    pause
    goto MENU
)
if errorlevel 4 (
    python "%PY_MAIN%" --action update-custom --bat "%~f0"
    pause
    goto MENU
)
if errorlevel 3 (
    python "%PY_MAIN%" --action check-custom --bat "%~f0"
    pause
    goto MENU
)
if errorlevel 2 (
    python "%PY_MAIN%" --action update --bat "%~f0"
    pause
    goto MENU
)
if errorlevel 1 (
    python "%PY_MAIN%" --action check --bat "%~f0"
    pause
    goto MENU
)

goto MENU

:WRITE_PY
> "%B64_FILE%" echo CiMgLSotIGNvZGluZzogdXRmLTggLSotCmltcG9ydCBhcmdwYXJzZQppbXBvcnQganNvbgppbXBv
>> "%B64_FILE%" echo cnQgb3MKaW1wb3J0IHJlCmltcG9ydCBzdWJwcm9jZXNzCmltcG9ydCBzeXMKZnJvbSBkYXRldGlt
>> "%B64_FILE%" echo ZSBpbXBvcnQgZGF0ZXRpbWUKZnJvbSBwYXRobGliIGltcG9ydCBQYXRoCgpTRVJWRVIgPSByInR1
>> "%B64_FILE%" echo eWVudGhhbmN1YW9uZy5jb20udm4sNTIzNzYiCkRBVEFCQVNFID0gIlRUQ09fVEhPTkdLRSIKTUFT
>> "%B64_FILE%" echo VEVSX0RCID0gIlRUQ09fUVRIVCIKClJFUE9fVVJMID0gImh0dHBzOi8vZ2l0aHViLmNvbS90dXll
>> "%B64_FILE%" echo bjExMDIvbXktYWktc2l0ZS5naXQiCkJSQU5DSCA9ICJtYWluIgpKU09OX1JFTCA9IG9zLnBhdGgu
>> "%B64_FILE%" echo am9pbigicHVibGljIiwgImRhdGEiLCAidG9uX2tob19sYXRlc3QuanNvbiIpClRBU0tfTkFNRSA9
>> "%B64_FILE%" echo ICJUVENPX1Rvbktob19EaXJlY3REQl9WMjNfT25Mb2dvbiIKCkNPTkZJR19ESVIgPSBQYXRoKG9z
>> "%B64_FILE%" echo LmVudmlyb24uZ2V0KCJMT0NBTEFQUERBVEEiLCBzdHIoUGF0aC5ob21lKCkpKSkgLyAiVFRDT19U
>> "%B64_FILE%" echo b25LaG9fRGlyZWN0REJfVjIzIgpDT05GSUdfRklMRSA9IENPTkZJR19ESVIgLyAiY29uZmlnLmpz
>> "%B64_FILE%" echo b24iCkxPR19GSUxFID0gQ09ORklHX0RJUiAvICJUVENPX0RpcmVjdERCX1YyMy5sb2ciCgpERVNL
>> "%B64_FILE%" echo VE9QID0gUGF0aChvcy5lbnZpcm9uLmdldCgiVVNFUlBST0ZJTEUiLCBzdHIoUGF0aC5ob21lKCkp
>> "%B64_FILE%" echo KSkgLyAiRGVza3RvcCIKQ0hFQ0tfRElSID0gREVTS1RPUCAvICJUVENPX0RJUkVDVF9EQl9DSEVD
>> "%B64_FILE%" echo S19WMjMiCgoKZGVmIGxvZyhtc2c6IHN0cikgLT4gTm9uZToKICAgIENPTkZJR19ESVIubWtkaXIo
>> "%B64_FILE%" echo cGFyZW50cz1UcnVlLCBleGlzdF9vaz1UcnVlKQogICAgd2l0aCBMT0dfRklMRS5vcGVuKCJhIiwg
>> "%B64_FILE%" echo ZW5jb2Rpbmc9InV0Zi04IikgYXMgZjoKICAgICAgICBmLndyaXRlKGYiW3tkYXRldGltZS5ub3co
>> "%B64_FILE%" echo KTolWS0lbS0lZCAlSDolTTolU31dIHttc2d9XG4iKQoKCmRlZiBydW4oY21kLCBjd2Q9Tm9uZSwg
>> "%B64_FILE%" echo Y2hlY2s9VHJ1ZSk6CiAgICBwcmludCgiXG4+ICIgKyAiICIuam9pbihjbWQpLCBmbHVzaD1UcnVl
>> "%B64_FILE%" echo KQogICAgcCA9IHN1YnByb2Nlc3MucnVuKGNtZCwgY3dkPWN3ZCkKICAgIGlmIGNoZWNrIGFuZCBw
>> "%B64_FILE%" echo LnJldHVybmNvZGUgIT0gMDoKICAgICAgICByYWlzZSBSdW50aW1lRXJyb3IoZiJM4buHbmggbOG7
>> "%B64_FILE%" echo l2kgbcOjIHtwLnJldHVybmNvZGV9OiB7JyAnLmpvaW4oY21kKX0iKQogICAgcmV0dXJuIHAucmV0
>> "%B64_FILE%" echo dXJuY29kZQoKCmRlZiBlbnN1cmVfcHlvZGJjKCk6CiAgICB0cnk6CiAgICAgICAgaW1wb3J0IHB5
>> "%B64_FILE%" echo b2RiYyAgIyBub3FhCiAgICAgICAgcmV0dXJuCiAgICBleGNlcHQgRXhjZXB0aW9uOgogICAgICAg
>> "%B64_FILE%" echo IHByaW50KCJbSU5GT10gQ2jGsGEgY8OzIHB5b2RiYy4gxJBhbmcgY8OgaSBweW9kYmMuLi4iLCBm
>> "%B64_FILE%" echo bHVzaD1UcnVlKQogICAgICAgIHN1YnByb2Nlc3MuY2hlY2tfY2FsbChbc3lzLmV4ZWN1dGFibGUs
>> "%B64_FILE%" echo ICItbSIsICJwaXAiLCAiaW5zdGFsbCIsICJweW9kYmMiXSkKCgpkZWYgY29ubmVjdChkYj1EQVRB
>> "%B64_FILE%" echo QkFTRSk6CiAgICBpbXBvcnQgcHlvZGJjCiAgICBjb25uX3N0ciA9ICgKICAgICAgICAiRFJJVkVS
>> "%B64_FILE%" echo PXtPREJDIERyaXZlciAxOCBmb3IgU1FMIFNlcnZlcn07IgogICAgICAgIGYiU0VSVkVSPXtTRVJW
>> "%B64_FILE%" echo RVJ9OyIKICAgICAgICBmIkRBVEFCQVNFPXtkYn07IgogICAgICAgICJUcnVzdGVkX0Nvbm5lY3Rp
>> "%B64_FILE%" echo b249eWVzOyIKICAgICAgICAiVHJ1c3RTZXJ2ZXJDZXJ0aWZpY2F0ZT15ZXM7IgogICAgKQogICAg
>> "%B64_FILE%" echo cmV0dXJuIHB5b2RiYy5jb25uZWN0KGNvbm5fc3RyLCB0aW1lb3V0PTMwLCBhdXRvY29tbWl0PVRy
>> "%B64_FILE%" echo dWUpCgoKZGVmIHFpZGVudChuYW1lOiBzdHIpIC0+IHN0cjoKICAgIHJldHVybiAiWyIgKyBzdHIo
>> "%B64_FILE%" echo bmFtZSkucmVwbGFjZSgiXSIsICJdXSIpICsgIl0iCgoKZGVmIG5vcm1hbGl6ZV90ZXh0KHYpOgog
>> "%B64_FILE%" echo ICAgaWYgdiBpcyBOb25lOgogICAgICAgIHJldHVybiAiIgogICAgcmV0dXJuIHJlLnN1YihyIlxz
>> "%B64_FILE%" echo KyIsICIgIiwgc3RyKHYpLnJlcGxhY2UoIlx4YTAiLCAiICIpLnN0cmlwKCkpCgoKZGVmIG5vcm1h
>> "%B64_FILE%" echo bGl6ZV9jb2FsX25hbWUodik6CiAgICBzID0gbm9ybWFsaXplX3RleHQodikKICAgIHMgPSByZS5z
>> "%B64_FILE%" echo dWIociIoP2kpXGIxY1xiIiwgIjFDIiwgcykKICAgIHMgPSByZS5zdWIociIoP2kpXGI4Y1xiIiwg
>> "%B64_FILE%" echo IjhDIiwgcykKICAgIHJldHVybiBzCgoKZGVmIGNsZWFuX251bWJlcih2KToKICAgIHRyeToKICAg
>> "%B64_FILE%" echo ICAgICByZXR1cm4gZmxvYXQodiBvciAwKQogICAgZXhjZXB0IEV4Y2VwdGlvbjoKICAgICAgICBy
>> "%B64_FILE%" echo ZXR1cm4gMC4wCgoKZGVmIGtob19zb3J0X2tleSh0ZW5fa2hvLCBtYV9raG8pOgogICAgdGV4dCA9
>> "%B64_FILE%" echo IHRlbl9raG8gb3IgbWFfa2hvIG9yICIiCiAgICBtID0gcmUuc2VhcmNoKHIiKFxkKykiLCB0ZXh0
>> "%B64_FILE%" echo KQogICAgbiA9IGludChtLmdyb3VwKDEpKSBpZiBtIGVsc2UgOTk5OQogICAgdDQgPSAxIGlmICJU
>> "%B64_FILE%" echo NCIgaW4gdGV4dC51cHBlcigpIGVsc2UgMAogICAgcmV0dXJuIChuLCB0NCwgdGV4dCkKCgpkZWYg
>> "%B64_FILE%" echo cHJldmlvdXNfcGVyaW9kKHllYXIsIG1vbnRoKToKICAgIHllYXIgPSBpbnQoeWVhcikKICAgIG1v
>> "%B64_FILE%" echo bnRoID0gaW50KG1vbnRoKQogICAgaWYgbW9udGggPT0gMToKICAgICAgICByZXR1cm4geWVhciAt
>> "%B64_FILE%" echo IDEsIDEyCiAgICByZXR1cm4geWVhciwgbW9udGggLSAxCgoKZGVmIGxvYWRfY29uZmlnKCk6CiAg
>> "%B64_FILE%" echo ICBDT05GSUdfRElSLm1rZGlyKHBhcmVudHM9VHJ1ZSwgZXhpc3Rfb2s9VHJ1ZSkKICAgIGlmIENP
>> "%B64_FILE%" echo TkZJR19GSUxFLmV4aXN0cygpOgogICAgICAgIHRyeToKICAgICAgICAgICAgcmV0dXJuIGpzb24u
>> "%B64_FILE%" echo bG9hZHMoQ09ORklHX0ZJTEUucmVhZF90ZXh0KGVuY29kaW5nPSJ1dGYtOCIpKQogICAgICAgIGV4
>> "%B64_FILE%" echo Y2VwdCBFeGNlcHRpb246CiAgICAgICAgICAgIHBhc3MKICAgIHJldHVybiB7InJlcG9fZGlyIjog
>> "%B64_FILE%" echo ciJEOlxUVENPX1Rvbktob19BcHBfUmVwbyJ9CgoKZGVmIHNhdmVfY29uZmlnKGNmZyk6CiAgICBD
>> "%B64_FILE%" echo T05GSUdfRElSLm1rZGlyKHBhcmVudHM9VHJ1ZSwgZXhpc3Rfb2s9VHJ1ZSkKICAgIENPTkZJR19G
>> "%B64_FILE%" echo SUxFLndyaXRlX3RleHQoanNvbi5kdW1wcyhjZmcsIGVuc3VyZV9hc2NpaT1GYWxzZSwgaW5kZW50
>> "%B64_FILE%" echo PTIpLCBlbmNvZGluZz0idXRmLTgiKQogICAgbG9nKGYiU0FWRV9DT05GSUcge2NmZ30iKQoKCmRl
>> "%B64_FILE%" echo ZiBwaWNrX2ZvbGRlcih0aXRsZTogc3RyLCBpbml0aWFsOiBzdHIgPSAiIikgLT4gc3RyOgogICAg
>> "%B64_FILE%" echo dHJ5OgogICAgICAgIGltcG9ydCB0a2ludGVyIGFzIHRrCiAgICAgICAgZnJvbSB0a2ludGVyIGlt
>> "%B64_FILE%" echo cG9ydCBmaWxlZGlhbG9nCiAgICAgICAgcm9vdCA9IHRrLlRrKCkKICAgICAgICByb290LndpdGhk
>> "%B64_FILE%" echo cmF3KCkKICAgICAgICByb290LmF0dHJpYnV0ZXMoIi10b3Btb3N0IiwgVHJ1ZSkKICAgICAgICBp
>> "%B64_FILE%" echo ZiBub3QgaW5pdGlhbCBvciBub3Qgb3MucGF0aC5pc2Rpcihpbml0aWFsKToKICAgICAgICAgICAg
>> "%B64_FILE%" echo aW5pdGlhbCA9IHIiRDpcVFRDT19Ub25LaG9fQXBwX1JlcG8iIGlmIG9zLnBhdGguaXNkaXIociJE
>> "%B64_FILE%" echo OlxUVENPX1Rvbktob19BcHBfUmVwbyIpIGVsc2Ugc3RyKFBhdGguaG9tZSgpKQogICAgICAgIGZv
>> "%B64_FILE%" echo bGRlciA9IGZpbGVkaWFsb2cuYXNrZGlyZWN0b3J5KHRpdGxlPXRpdGxlLCBpbml0aWFsZGlyPWlu
>> "%B64_FILE%" echo aXRpYWwsIG11c3RleGlzdD1GYWxzZSkKICAgICAgICByb290LmRlc3Ryb3koKQogICAgICAgIHJl
>> "%B64_FILE%" echo dHVybiBmb2xkZXIgb3IgIiIKICAgIGV4Y2VwdCBFeGNlcHRpb24gYXMgZXhjOgogICAgICAgIHBy
>> "%B64_FILE%" echo aW50KGYiW0PhuqJOSCBCw4FPXSBLaMO0bmcgbeG7nyDEkcaw4bujYyBwb3B1cCBjaOG7jW4gdGjG
>> "%B64_FILE%" echo sCBt4bulYzoge2V4Y30iLCBmbHVzaD1UcnVlKQogICAgICAgIHJldHVybiBpbnB1dCgiTmjhuq1w
>> "%B64_FILE%" echo IMSRxrDhu51uZyBk4bqrbiB0aMawIG3hu6VjIHJlcG86ICIpLnN0cmlwKCkuc3RyaXAoJyInKQoK
>> "%B64_FILE%" echo CmRlZiBjb21tYW5kX2V4aXN0cyhuYW1lOiBzdHIpIC0+IGJvb2w6CiAgICB0cnk6CiAgICAgICAg
>> "%B64_FILE%" echo c3VicHJvY2Vzcy5ydW4oW25hbWUsICItLXZlcnNpb24iXSwgc3Rkb3V0PXN1YnByb2Nlc3MuREVW
>> "%B64_FILE%" echo TlVMTCwgc3RkZXJyPXN1YnByb2Nlc3MuREVWTlVMTCkKICAgICAgICByZXR1cm4gVHJ1ZQogICAg
>> "%B64_FILE%" echo ZXhjZXB0IEV4Y2VwdGlvbjoKICAgICAgICByZXR1cm4gRmFsc2UKCgpkZWYgZW5zdXJlX2dpdCgp
>> "%B64_FILE%" echo IC0+IE5vbmU6CiAgICBpZiBjb21tYW5kX2V4aXN0cygiZ2l0Iik6CiAgICAgICAgcmV0dXJuCiAg
>> "%B64_FILE%" echo ICBwcmludCgiW0PhuqJOSCBCw4FPXSBLaMO0bmcgdMOsbSB0aOG6pXkgR2l0LiDEkGFuZyB0aOG7
>> "%B64_FILE%" echo rSBjw6BpIEdpdCBi4bqxbmcgd2luZ2V0Li4uIiwgZmx1c2g9VHJ1ZSkKICAgIGlmIGNvbW1hbmRf
>> "%B64_FILE%" echo ZXhpc3RzKCJ3aW5nZXQiKToKICAgICAgICBzdWJwcm9jZXNzLnJ1bihbCiAgICAgICAgICAgICJ3
>> "%B64_FILE%" echo aW5nZXQiLCAiaW5zdGFsbCIsICItLWlkIiwgIkdpdC5HaXQiLCAiLWUiLCAiLS1zb3VyY2UiLCAi
>> "%B64_FILE%" echo d2luZ2V0IiwKICAgICAgICAgICAgIi0tc2lsZW50IiwgIi0tYWNjZXB0LXBhY2thZ2UtYWdyZWVt
>> "%B64_FILE%" echo ZW50cyIsICItLWFjY2VwdC1zb3VyY2UtYWdyZWVtZW50cyIKICAgICAgICBdKQogICAgaWYgbm90
>> "%B64_FILE%" echo IGNvbW1hbmRfZXhpc3RzKCJnaXQiKToKICAgICAgICByYWlzZSBSdW50aW1lRXJyb3IoIktow7Ru
>> "%B64_FILE%" echo ZyB0w6xtIHRo4bqleSBHaXQuIEjDo3kgY8OgaSBHaXQgZm9yIFdpbmRvd3MgcuG7k2kgY2jhuqF5
>> "%B64_FILE%" echo IGzhuqFpLiIpCgoKZGVmIGVuc3VyZV9yZXBvKHJlcG9fZGlyOiBzdHIpIC0+IE5vbmU6CiAgICBy
>> "%B64_FILE%" echo ZXBvID0gUGF0aChyZXBvX2RpcikKICAgIGlmIChyZXBvIC8gIi5naXQiKS5pc19kaXIoKToKICAg
>> "%B64_FILE%" echo ICAgICBwcmludChmIltPS10gUmVwbyBHaXRIdWIgaOG7o3AgbOG7hzoge3JlcG99IiwgZmx1c2g9
>> "%B64_FILE%" echo VHJ1ZSkKICAgICAgICByZXR1cm4KICAgIHJlcG8ubWtkaXIocGFyZW50cz1UcnVlLCBleGlzdF9v
>> "%B64_FILE%" echo az1UcnVlKQogICAgaWYgYW55KHJlcG8uaXRlcmRpcigpKToKICAgICAgICByYWlzZSBSdW50aW1l
>> "%B64_FILE%" echo RXJyb3IoZiJUaMawIG3hu6VjIMSRw6MgY8OzIGZpbGUgbmjGsG5nIGtow7RuZyBjw7MgLmdpdDog
>> "%B64_FILE%" echo e3JlcG99LiBIw6N5IGNo4buNbiDEkcO6bmcgcmVwby4iKQogICAgcnVuKFsiZ2l0IiwgImNsb25l
>> "%B64_FILE%" echo IiwgUkVQT19VUkwsIHN0cihyZXBvKV0pCgoKZGVmIHRhYmxlX2NvbHVtbnMoY3VyLCB0YWJsZSk6
>> "%B64_FILE%" echo CiAgICByb3dzID0gY3VyLmV4ZWN1dGUoIiIiCiAgICAgICAgU0VMRUNUIENPTFVNTl9OQU1FCiAg
>> "%B64_FILE%" echo ICAgICAgRlJPTSBJTkZPUk1BVElPTl9TQ0hFTUEuQ09MVU1OUwogICAgICAgIFdIRVJFIFRBQkxF
>> "%B64_FILE%" echo X1NDSEVNQT0nZGJvJyBBTkQgVEFCTEVfTkFNRT0/CiAgICAiIiIsIHRhYmxlKS5mZXRjaGFsbCgp
>> "%B64_FILE%" echo CiAgICByZXR1cm4ge3IuQ09MVU1OX05BTUUgZm9yIHIgaW4gcm93c30KCgpkZWYgZHJvcF9pZl9l
>> "%B64_FILE%" echo eGlzdHMoY3VyLCB0YWJsZV9uYW1lKToKICAgIGN1ci5leGVjdXRlKGYiSUYgT0JKRUNUX0lEKE4n
>> "%B64_FILE%" echo ZGJvLnt0YWJsZV9uYW1lfScsIE4nVScpIElTIE5PVCBOVUxMIERST1AgVEFCTEUgZGJvLntxaWRl
>> "%B64_FILE%" echo bnQodGFibGVfbmFtZSl9IikKCgpkZWYgY3JlYXRlX3N0YWdlX3RhYmxlKGN1ciwgc3RhZ2UpOgog
>> "%B64_FILE%" echo ICAgZHJvcF9pZl9leGlzdHMoY3VyLCBzdGFnZSkKICAgIGN1ci5leGVjdXRlKGYiIiIKICAgIENS
>> "%B64_FILE%" echo RUFURSBUQUJMRSBkYm8ue3FpZGVudChzdGFnZSl9ICgKICAgICAgICBNYUtobyBudmFyY2hhcigy
>> "%B64_FILE%" echo NCkgTlVMTCwKICAgICAgICBNYVRoYW4gbnZhcmNoYXIoMjQpIE5VTEwsCiAgICAgICAgVG9uREsg
>> "%B64_FILE%" echo bnVtZXJpYygyNCwzKSBOVUxMIERFRkFVTFQgMCwKICAgICAgICBOaGFwVEsgbnVtZXJpYygyNCwz
>> "%B64_FILE%" echo KSBOVUxMIERFRkFVTFQgMCwKICAgICAgICBYdWF0VEsgbnVtZXJpYygyNCwzKSBOVUxMIERFRkFV
>> "%B64_FILE%" echo TFQgMAogICAgKQogICAgIiIiKQoKCmRlZiBjcmVhdGVfZmluYWxfdGFibGUoY3VyLCBmaW5hbCwg
>> "%B64_FILE%" echo c3RhZ2UpOgogICAgZHJvcF9pZl9leGlzdHMoY3VyLCBmaW5hbCkKICAgIGN1ci5leGVjdXRlKGYi
>> "%B64_FILE%" echo IiIKICAgIFNFTEVDVAogICAgICAgIE1hS2hvLAogICAgICAgIE1hVGhhbiwKICAgICAgICBTVU0o
>> "%B64_FILE%" echo SVNOVUxMKFRvbkRLLDApKSBBUyBUb25ESywKICAgICAgICBTVU0oSVNOVUxMKE5oYXBUSywwKSkg
>> "%B64_FILE%" echo QVMgTmhhcFRLLAogICAgICAgIFNVTShJU05VTEwoWHVhdFRLLDApKSBBUyBYdWF0VEssCiAgICAg
>> "%B64_FILE%" echo ICAgU1VNKElTTlVMTChUb25ESywwKSArIElTTlVMTChOaGFwVEssMCkgLSBJU05VTEwoWHVhdFRL
>> "%B64_FILE%" echo LDApKSBBUyBUb25DSwogICAgSU5UTyBkYm8ue3FpZGVudChmaW5hbCl9CiAgICBGUk9NIGRiby57
>> "%B64_FILE%" echo cWlkZW50KHN0YWdlKX0KICAgIEdST1VQIEJZIE1hS2hvLCBNYVRoYW4KICAgIEhBVklORyBBQlMo
>> "%B64_FILE%" echo U1VNKElTTlVMTChUb25ESywwKSArIElTTlVMTChOaGFwVEssMCkgLSBJU05VTEwoWHVhdFRLLDAp
>> "%B64_FILE%" echo KSkgPiAwLjAwMDEKICAgICIiIikKCgpkZWYgaW5zZXJ0X3RvbmRrX3ByZXZpb3VzX3BlcmlvZChj
>> "%B64_FILE%" echo dXIsIHN0YWdlLCB5ZWFyLCBtb250aCk6CiAgICBwcmV2X3llYXIsIHByZXZfbW9udGggPSBwcmV2
>> "%B64_FILE%" echo aW91c19wZXJpb2QoeWVhciwgbW9udGgpCiAgICBwcmludChmIlsyLzVdIE7huqFwIFThu5NuIMSR
>> "%B64_FILE%" echo 4bqndSBr4buzIHThu6sgQ0RPVEhBTiB0aMOhbmcgdHLGsOG7m2M6IHtwcmV2X21vbnRoOjAyZH0v
>> "%B64_FILE%" echo e3ByZXZfeWVhcn0iLCBmbHVzaD1UcnVlKQoKICAgIGN1ci5leGVjdXRlKGYiIiIKICAgIElOU0VS
>> "%B64_FILE%" echo VCBJTlRPIGRiby57cWlkZW50KHN0YWdlKX0gKE1hS2hvLCBNYVRoYW4sIFRvbkRLLCBOaGFwVEss
>> "%B64_FILE%" echo IFh1YXRUSykKICAgIFNFTEVDVAogICAgICAgIENBU1QoTWFLaG8gQVMgbnZhcmNoYXIoMjQpKSwK
>> "%B64_FILE%" echo ICAgICAgICBDQVNUKE1hVGhhbiBBUyBudmFyY2hhcigyNCkpLAogICAgICAgIFNVTShDQVNUKElT
>> "%B64_FILE%" echo TlVMTChUb25DSywwKSBBUyBudW1lcmljKDI0LDMpKSkgQVMgVG9uREssCiAgICAgICAgMCwKICAg
>> "%B64_FILE%" echo ICAgICAwCiAgICBGUk9NIGRiby5DRE9USEFOCiAgICBXSEVSRSBOYW1IVCA9ID8gQU5EIFRoYW5n
>> "%B64_FILE%" echo SFQgPSA/CiAgICBHUk9VUCBCWSBNYUtobywgTWFUaGFuCiAgICAiIiIsIGludChwcmV2X3llYXIp
>> "%B64_FILE%" echo LCBpbnQocHJldl9tb250aCkpCgoKZGVmIGluc2VydF9mcm9tX3RhYmxlKGN1ciwgc3RhZ2UsIHRh
>> "%B64_FILE%" echo YmxlLCBxdHlfY29sLCB0YXJnZXQsIHllYXIsIG1vbnRoLCBraG9fY29sPSJNYUtobyIsIG1hdGhh
>> "%B64_FILE%" echo bl9jb2w9Ik1hVGhhbiIpOgogICAgaWYgdGFyZ2V0IG5vdCBpbiAoIk5oYXBUSyIsICJYdWF0VEsi
>> "%B64_FILE%" echo KToKICAgICAgICByYWlzZSBWYWx1ZUVycm9yKCJ0YXJnZXQgbXVzdCBiZSBOaGFwVEsgb3IgWHVh
>> "%B64_FILE%" echo dFRLIikKCiAgICBjdXIuZXhlY3V0ZShmIiIiCiAgICBJTlNFUlQgSU5UTyBkYm8ue3FpZGVudChz
>> "%B64_FILE%" echo dGFnZSl9IChNYUtobywgTWFUaGFuLCBUb25ESywgTmhhcFRLLCBYdWF0VEspCiAgICBTRUxFQ1QK
>> "%B64_FILE%" echo ICAgICAgICBDQVNUKHtxaWRlbnQoa2hvX2NvbCl9IEFTIG52YXJjaGFyKDI0KSksCiAgICAgICAg
>> "%B64_FILE%" echo Q0FTVCh7cWlkZW50KG1hdGhhbl9jb2wpfSBBUyBudmFyY2hhcigyNCkpLAogICAgICAgIDAsCiAg
>> "%B64_FILE%" echo ICAgICAgQ0FTRSBXSEVOID8gPSAnTmhhcFRLJyBUSEVOIFNVTShDQVNUKElTTlVMTCh7cWlkZW50
>> "%B64_FILE%" echo KHF0eV9jb2wpfSwwKSBBUyBudW1lcmljKDI0LDMpKSkgRUxTRSAwIEVORCwKICAgICAgICBDQVNF
>> "%B64_FILE%" echo IFdIRU4gPyA9ICdYdWF0VEsnIFRIRU4gU1VNKENBU1QoSVNOVUxMKHtxaWRlbnQocXR5X2NvbCl9
>> "%B64_FILE%" echo LDApIEFTIG51bWVyaWMoMjQsMykpKSBFTFNFIDAgRU5ECiAgICBGUk9NIGRiby57cWlkZW50KHRh
>> "%B64_FILE%" echo YmxlKX0KICAgIFdIRVJFIE5hbUhUID0gPyBBTkQgVGhhbmdIVCA9ID8KICAgIEdST1VQIEJZIHtx
>> "%B64_FILE%" echo aWRlbnQoa2hvX2NvbCl9LCB7cWlkZW50KG1hdGhhbl9jb2wpfQogICAgIiIiLCB0YXJnZXQsIHRh
>> "%B64_FILE%" echo cmdldCwgaW50KHllYXIpLCBpbnQobW9udGgpKQoKCmRlZiBpbnNlcnRfY3VycmVudF9tb3ZlbWVu
>> "%B64_FILE%" echo dHNfbGlrZV92MTkoY3VyLCBzdGFnZSwgeWVhciwgbW9udGgpOgogICAgIiIiCiAgICBWMjM6IGdp
>> "%B64_FILE%" echo 4buvIHBo4bqnbiBwaMOhdCBzaW5oIGPhu6dhIHYxOSB2w6wgYW5oIHjDoWMgbmjhuq1uIHYxOSDE
>> "%B64_FILE%" echo kcOjIGzhuqV5IMSRw7puZyBOaGFwVEsvWHVhdFRLLgogICAgS2jDtG5nIGTDuW5nIHBow6JuIGxv
>> "%B64_FILE%" echo 4bqhaSB2MjEgdGhlbyBUaGFuVmFvU2FuZy9UaGFuUmFTYW5nIG7hu69hLgogICAgxq91IHRpw6pu
>> "%B64_FILE%" echo IHLDtSByw6BuZzoKICAgICAgLSBUaGFuTmhhcCAtPiBOaGFwVEsKICAgICAgLSBUaGFuWHVhdCAt
>> "%B64_FILE%" echo PiBYdWF0VEsKICAgIENo4buJIGZhbGxiYWNrIHNhbmcgYuG6o25nIGtow6FjIG7hur91IFRoYW5O
>> "%B64_FILE%" echo aGFwL1RoYW5YdWF0IGtow7RuZyB04buTbiB04bqhaSBob+G6t2MgdGhp4bq/dSBj4buZdC4KICAg
>> "%B64_FILE%" echo ICIiIgogICAgcHJpbnQoZiJbMy81XSBO4bqhcCBOaGFwVEsvWHVhdFRLIHRoZW8gbG9naWMgdjE5
>> "%B64_FILE%" echo IGNobyBr4buzIHttb250aDowMmR9L3t5ZWFyfSIsIGZsdXNoPVRydWUpCiAgICBub3RlcyA9IFtd
>> "%B64_FILE%" echo CgogICAgIyDGr3UgdGnDqm4gdHV54buHdCDEkeG7kWkgMiBi4bqjbmcgdjE5IMSRw6MgY2hvIHPh
>> "%B64_FILE%" echo u5EgxJHDum5nLgogICAgcHJlZmVycmVkID0gWwogICAgICAgICgiVGhhbk5oYXAiLCAiTmhhcFRL
>> "%B64_FILE%" echo IiksCiAgICAgICAgKCJUaGFuWHVhdCIsICJYdWF0VEsiKSwKICAgIF0KCiAgICBmb3IgdGFibGUs
>> "%B64_FILE%" echo IHRhcmdldCBpbiBwcmVmZXJyZWQ6CiAgICAgICAgdHJ5OgogICAgICAgICAgICBjb2xzID0gdGFi
>> "%B64_FILE%" echo bGVfY29sdW1ucyhjdXIsIHRhYmxlKQogICAgICAgIGV4Y2VwdCBFeGNlcHRpb24gYXMgZXhjOgog
>> "%B64_FILE%" echo ICAgICAgICAgICBwcmludChmIiAgW1NLSVBdIEtow7RuZyB0aOG6pXkgYuG6o25nIHt0YWJsZX06
>> "%B64_FILE%" echo IHtleGN9IiwgZmx1c2g9VHJ1ZSkKICAgICAgICAgICAgY29udGludWUKCiAgICAgICAgaWYgbm90
>> "%B64_FILE%" echo IHsiTWFLaG8iLCAiTWFUaGFuIiwgIk5hbUhUIiwgIlRoYW5nSFQifS5pc3N1YnNldChjb2xzKToK
>> "%B64_FILE%" echo ICAgICAgICAgICAgcHJpbnQoZiIgIFtTS0lQXSB7dGFibGV9OiB0aGnhur91IE1hS2hvL01hVGhh
>> "%B64_FILE%" echo bi9OYW1IVC9UaGFuZ0hUIiwgZmx1c2g9VHJ1ZSkKICAgICAgICAgICAgY29udGludWUKCiAgICAg
>> "%B64_FILE%" echo ICAgcXR5X2NvbCA9IE5vbmUKICAgICAgICBmb3IgYyBpbiBbIktsZ19UYW4iLCAiS2xnIiwgIkto
>> "%B64_FILE%" echo b2lMdW9uZyIsICJTb0x1b25nIiwgIlNMIiwgIktMIiwgIlRhbiJdOgogICAgICAgICAgICBpZiBj
>> "%B64_FILE%" echo IGluIGNvbHM6CiAgICAgICAgICAgICAgICBxdHlfY29sID0gYwogICAgICAgICAgICAgICAgYnJl
>> "%B64_FILE%" echo YWsKCiAgICAgICAgaWYgbm90IHF0eV9jb2w6CiAgICAgICAgICAgIHByaW50KGYiICBbU0tJUF0g
>> "%B64_FILE%" echo e3RhYmxlfToga2jDtG5nIHRo4bqleSBj4buZdCBraOG7kWkgbMaw4bujbmciLCBmbHVzaD1UcnVl
>> "%B64_FILE%" echo KQogICAgICAgICAgICBjb250aW51ZQoKICAgICAgICB0cnk6CiAgICAgICAgICAgIGluc2VydF9m
>> "%B64_FILE%" echo cm9tX3RhYmxlKGN1ciwgc3RhZ2UsIHRhYmxlLCBxdHlfY29sLCB0YXJnZXQsIHllYXIsIG1vbnRo
>> "%B64_FILE%" echo KQogICAgICAgICAgICBub3Rlcy5hcHBlbmQoZiJ7dGFibGV9LntxdHlfY29sfS0+e3RhcmdldH0i
>> "%B64_FILE%" echo KQogICAgICAgICAgICBwcmludChmIiAgW09LXSB7dGFibGV9LntxdHlfY29sfSAtPiB7dGFyZ2V0
>> "%B64_FILE%" echo fSIsIGZsdXNoPVRydWUpCiAgICAgICAgZXhjZXB0IEV4Y2VwdGlvbiBhcyBleGM6CiAgICAgICAg
>> "%B64_FILE%" echo ICAgIHByaW50KGYiICBbTOG7lkldIHt0YWJsZX0ue3F0eV9jb2x9OiB7ZXhjfSIsIGZsdXNoPVRy
>> "%B64_FILE%" echo dWUpCgogICAgaWYgbm90ZXM6CiAgICAgICAgcmV0dXJuIG5vdGVzCgogICAgIyBGYWxsYmFjayBh
>> "%B64_FILE%" echo biB0b8OgbjogZMO5bmcgbG9naWMgdjE5IMSRxqFuIGdp4bqjbiB0aGVvIHTDqm4gYuG6o25nLCBu
>> "%B64_FILE%" echo aMawbmcga2jDtG5nIGTDuW5nIFRoYW5WYW9TYW5nL1RoYW5SYVNhbmcgdHLGsOG7m2MuCiAgICBw
>> "%B64_FILE%" echo cmludCgiICBbQ+G6ok5IIELDgU9dIENoxrBhIG7huqFwIMSRxrDhu6NjIHThu6sgVGhhbk5oYXAv
>> "%B64_FILE%" echo VGhhblh1YXQsIHRo4butIGZhbGxiYWNrLiIsIGZsdXNoPVRydWUpCiAgICBmYWxsYmFjayA9IFsK
>> "%B64_FILE%" echo ICAgICAgICAoIlRoYW5HaWFvTmhhbiIsICJOaGFwVEsiKSwKICAgICAgICAoIlRoYW5NdWFNbyIs
>> "%B64_FILE%" echo ICJOaGFwVEsiKSwKICAgICAgICAoIlRoYW5WYW9TYW5nIiwgIk5oYXBUSyIpLAogICAgICAgICgi
>> "%B64_FILE%" echo VGhhblJhU2FuZyIsICJYdWF0VEsiKSwKICAgIF0KCiAgICBmb3IgdGFibGUsIHRhcmdldCBpbiBm
>> "%B64_FILE%" echo YWxsYmFjazoKICAgICAgICB0cnk6CiAgICAgICAgICAgIGNvbHMgPSB0YWJsZV9jb2x1bW5zKGN1
>> "%B64_FILE%" echo ciwgdGFibGUpCiAgICAgICAgZXhjZXB0IEV4Y2VwdGlvbjoKICAgICAgICAgICAgY29udGludWUK
>> "%B64_FILE%" echo ICAgICAgICBpZiBub3QgeyJNYUtobyIsICJNYVRoYW4iLCAiTmFtSFQiLCAiVGhhbmdIVCJ9Lmlz
>> "%B64_FILE%" echo c3Vic2V0KGNvbHMpOgogICAgICAgICAgICBjb250aW51ZQogICAgICAgIHF0eV9jb2wgPSBOb25l
>> "%B64_FILE%" echo CiAgICAgICAgZm9yIGMgaW4gWyJLbGdfVGFuIiwgIktsZyIsICJLaG9pTHVvbmciLCAiU29MdW9u
>> "%B64_FILE%" echo ZyIsICJTTCIsICJLTCIsICJUYW4iXToKICAgICAgICAgICAgaWYgYyBpbiBjb2xzOgogICAgICAg
>> "%B64_FILE%" echo ICAgICAgICAgcXR5X2NvbCA9IGMKICAgICAgICAgICAgICAgIGJyZWFrCiAgICAgICAgaWYgbm90
>> "%B64_FILE%" echo IHF0eV9jb2w6CiAgICAgICAgICAgIGNvbnRpbnVlCiAgICAgICAgdHJ5OgogICAgICAgICAgICBp
>> "%B64_FILE%" echo bnNlcnRfZnJvbV90YWJsZShjdXIsIHN0YWdlLCB0YWJsZSwgcXR5X2NvbCwgdGFyZ2V0LCB5ZWFy
>> "%B64_FILE%" echo LCBtb250aCkKICAgICAgICAgICAgbm90ZXMuYXBwZW5kKGYie3RhYmxlfS57cXR5X2NvbH0tPnt0
>> "%B64_FILE%" echo YXJnZXR9IikKICAgICAgICAgICAgcHJpbnQoZiIgIFtPSyBmYWxsYmFja10ge3RhYmxlfS57cXR5
>> "%B64_FILE%" echo X2NvbH0gLT4ge3RhcmdldH0iLCBmbHVzaD1UcnVlKQogICAgICAgIGV4Y2VwdCBFeGNlcHRpb24g
>> "%B64_FILE%" echo YXMgZXhjOgogICAgICAgICAgICBwcmludChmIiAgW1NLSVAgZmFsbGJhY2tdIHt0YWJsZX06IHtl
>> "%B64_FILE%" echo eGN9IiwgZmx1c2g9VHJ1ZSkKCiAgICByZXR1cm4gbm90ZXMKCgpkZWYgZGlyZWN0X2NvbXB1dGUo
>> "%B64_FILE%" echo eWVhciwgbW9udGgpOgogICAgZW5zdXJlX3B5b2RiYygpCiAgICBjb25uID0gY29ubmVjdChEQVRB
>> "%B64_FILE%" echo QkFTRSkKICAgIGN1ciA9IGNvbm4uY3Vyc29yKCkKCiAgICBzdWZmaXggPSBmIntkYXRldGltZS5u
>> "%B64_FILE%" echo b3coKTolSCVNJVN9e29zLmdldHBpZCgpfSIKICAgIHN0YWdlID0gZiJHM19CQzA1QV8xX0RJUkVD
>> "%B64_FILE%" echo VDIzX3tzdWZmaXh9IgogICAgZmluYWwgPSBmIkczX0JDMDVBXzJfRElSRUNUMjNfe3N1ZmZpeH0i
>> "%B64_FILE%" echo CgogICAgcHJpbnQoIj09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
>> "%B64_FILE%" echo PT09PT09PT09PT09PT09PSIsIGZsdXNoPVRydWUpCiAgICBwcmludCgiVFRDTyBESVJFQ1QgREIg
>> "%B64_FILE%" echo RU5HSU5FIFYyMyAtIEtIw5RORyBN4bueIFRUQ09fQVBQIiwgZmx1c2g9VHJ1ZSkKICAgIHByaW50
>> "%B64_FILE%" echo KCI9PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
>> "%B64_FILE%" echo PT09PT0iLCBmbHVzaD1UcnVlKQogICAgcHJpbnQoZiJL4buzIGThu68gbGnhu4d1OiB7bW9udGg6
>> "%B64_FILE%" echo MDJkfS97eWVhcn0iLCBmbHVzaD1UcnVlKQogICAgcHJpbnQoIlYyMyA9IFRvbkRLIMSRw7puZyB0
>> "%B64_FILE%" echo 4burIENET1RIQU4gdGjDoW5nIHRyxrDhu5tjICsgTmhhcC9YdWF0IMSRw7puZyB0aGVvIGxvZ2lj
>> "%B64_FILE%" echo IHYxOS4iLCBmbHVzaD1UcnVlKQogICAgcHJpbnQoIiIsIGZsdXNoPVRydWUpCgogICAgcHJpbnQo
>> "%B64_FILE%" echo IlsxLzVdIFThuqFvIGLhuqNuZyBzdGFnZS4uLiIsIGZsdXNoPVRydWUpCiAgICBjcmVhdGVfc3Rh
>> "%B64_FILE%" echo Z2VfdGFibGUoY3VyLCBzdGFnZSkKCiAgICBpbnNlcnRfdG9uZGtfcHJldmlvdXNfcGVyaW9kKGN1
>> "%B64_FILE%" echo ciwgc3RhZ2UsIHllYXIsIG1vbnRoKQogICAgbm90ZXMgPSBpbnNlcnRfY3VycmVudF9tb3ZlbWVu
>> "%B64_FILE%" echo dHNfbGlrZV92MTkoY3VyLCBzdGFnZSwgeWVhciwgbW9udGgpCgogICAgcHJpbnQoIls0LzVdIFTh
>> "%B64_FILE%" echo uqFvIGLhuqNuZyBr4bq/dCBxdeG6oyBjdeG7kWkuLi4iLCBmbHVzaD1UcnVlKQogICAgY3JlYXRl
>> "%B64_FILE%" echo X2ZpbmFsX3RhYmxlKGN1ciwgZmluYWwsIHN0YWdlKQoKICAgIHByaW50KCJbNS81XSBIb8OgbiB0
>> "%B64_FILE%" echo 4bqldC4iLCBmbHVzaD1UcnVlKQogICAgY29ubi5jbG9zZSgpCiAgICByZXR1cm4gZmluYWwsIG5v
>> "%B64_FILE%" echo dGVzCgoKZGVmIHJlYWRfZmluYWxfcm93cyh0YWJsZV9uYW1lKToKICAgIGNvbm4gPSBjb25uZWN0
>> "%B64_FILE%" echo KERBVEFCQVNFKQogICAgY3VyID0gY29ubi5jdXJzb3IoKQogICAgc3FsID0gZiIiIgogICAgU0VM
>> "%B64_FILE%" echo RUNUCiAgICAgICAgci5NYUtobywKICAgICAgICBDT0FMRVNDRShrLlRlbktob01vaSwgay5UZW5L
>> "%B64_FILE%" echo aG8sIHIuTWFLaG8pIEFTIFRlbktobywKICAgICAgICByLk1hVGhhbiwKICAgICAgICBDT0FMRVND
>> "%B64_FILE%" echo RSh0LlRlblhLLCB0LlRlblRoYW4sIHIuTWFUaGFuKSBBUyBUZW5UaGFuLAogICAgICAgIENBU1Qo
>> "%B64_FILE%" echo SVNOVUxMKHIuVG9uREssIDApIEFTIEZMT0FUKSBBUyBUb25ESywKICAgICAgICBDQVNUKElTTlVM
>> "%B64_FILE%" echo TChyLk5oYXBUSywgMCkgQVMgRkxPQVQpIEFTIE5oYXBUSywKICAgICAgICBDQVNUKElTTlVMTChy
>> "%B64_FILE%" echo Llh1YXRUSywgMCkgQVMgRkxPQVQpIEFTIFh1YXRUSywKICAgICAgICBDQVNUKElTTlVMTChyLlRv
>> "%B64_FILE%" echo bkNLLCAwKSBBUyBGTE9BVCkgQVMgVG9uQ0ssCiAgICAgICAgQ09BTEVTQ0UodC5UVElOLCBOJycp
>> "%B64_FILE%" echo IEFTIFRUSU5fVGhhbiwKICAgICAgICBDT0FMRVNDRShrLlRUSU4sIE4nJykgQVMgVFRJTl9LaG8K
>> "%B64_FILE%" echo ICAgIEZST00gZGJvLntxaWRlbnQodGFibGVfbmFtZSl9IHIKICAgIExFRlQgSk9JTiB7TUFTVEVS
>> "%B64_FILE%" echo X0RCfS5kYm8uRE1USEFOIHQKICAgICAgICBPTiBSVFJJTShMVFJJTSh0Lk1hVGhhbikpID0gUlRS
>> "%B64_FILE%" echo SU0oTFRSSU0oci5NYVRoYW4pKQogICAgTEVGVCBKT0lOIHtNQVNURVJfREJ9LmRiby5ETUtITyBr
>> "%B64_FILE%" echo CiAgICAgICAgT04gUlRSSU0oTFRSSU0oay5NYUtobykpID0gUlRSSU0oTFRSSU0oci5NYUtobykp
>> "%B64_FILE%" echo CiAgICBXSEVSRQogICAgICAgIElTTlVMTChyLk1hS2hvLCBOJycpIDw+IE4nJwogICAgICAgIEFO
>> "%B64_FILE%" echo RCBJU05VTEwoci5NYVRoYW4sIE4nJykgPD4gTicnCiAgICAgICAgQU5EIEFCUyhDQVNUKElTTlVM
>> "%B64_FILE%" echo TChyLlRvbkNLLCAwKSBBUyBGTE9BVCkpID4gMC4wMDAxCiAgICBPUkRFUiBCWSBDT0FMRVNDRShr
>> "%B64_FILE%" echo LlRUSU4sIE4nJyksIENPQUxFU0NFKHQuVFRJTiwgTicnKSwgci5NYUtobywgci5NYVRoYW4KICAg
>> "%B64_FILE%" echo ICIiIgogICAgcm93cyA9IGN1ci5leGVjdXRlKHNxbCkuZmV0Y2hhbGwoKQogICAgY29ubi5jbG9z
>> "%B64_FILE%" echo ZSgpCgogICAgZGF0YV9yb3dzID0gW10KICAgIGZvciByb3cgaW4gcm93czoKICAgICAgICBtYV9r
>> "%B64_FILE%" echo aG8gPSBub3JtYWxpemVfdGV4dChyb3cuTWFLaG8pCiAgICAgICAgdGVuX2tobyA9IG5vcm1hbGl6
>> "%B64_FILE%" echo ZV90ZXh0KHJvdy5UZW5LaG8pIG9yIG1hX2tobwogICAgICAgIG1hX3RoYW4gPSBub3JtYWxpemVf
>> "%B64_FILE%" echo dGV4dChyb3cuTWFUaGFuKQogICAgICAgIHRlbl90aGFuID0gbm9ybWFsaXplX2NvYWxfbmFtZShy
>> "%B64_FILE%" echo b3cuVGVuVGhhbikgb3IgbWFfdGhhbgoKICAgICAgICB0b25fZGsgPSByb3VuZChjbGVhbl9udW1i
>> "%B64_FILE%" echo ZXIocm93LlRvbkRLKSwgMikKICAgICAgICBuaGFwX3RrID0gcm91bmQoY2xlYW5fbnVtYmVyKHJv
>> "%B64_FILE%" echo dy5OaGFwVEspLCAyKQogICAgICAgIHh1YXRfdGsgPSByb3VuZChjbGVhbl9udW1iZXIocm93Llh1
>> "%B64_FILE%" echo YXRUSyksIDIpCiAgICAgICAgdG9uX2NrID0gcm91bmQoY2xlYW5fbnVtYmVyKHJvdy5Ub25DSyks
>> "%B64_FILE%" echo IDIpCgogICAgICAgIGRhdGFfcm93cy5hcHBlbmQoewogICAgICAgICAgICAiTWFLaG8iOiBtYV9r
>> "%B64_FILE%" echo aG8sCiAgICAgICAgICAgICJUZW5LaG8iOiB0ZW5fa2hvLAogICAgICAgICAgICAia2hvIjogdGVu
>> "%B64_FILE%" echo X2tobywKICAgICAgICAgICAgIk1hVGhhbiI6IG1hX3RoYW4sCiAgICAgICAgICAgICJUZW5UaGFu
>> "%B64_FILE%" echo IjogdGVuX3RoYW4sCiAgICAgICAgICAgICJjb2FsIjogdGVuX3RoYW4sCiAgICAgICAgICAgICJU
>> "%B64_FILE%" echo b25ESyI6IHRvbl9kaywKICAgICAgICAgICAgIk5oYXBUSyI6IG5oYXBfdGssCiAgICAgICAgICAg
>> "%B64_FILE%" echo ICJYdWF0VEsiOiB4dWF0X3RrLAogICAgICAgICAgICAiVG9uQ0siOiB0b25fY2ssCiAgICAgICAg
>> "%B64_FILE%" echo ICAgICJ0b24iOiB0b25fY2ssCiAgICAgICAgICAgICJ0dGNvQXBwIjogdG9uX2NrLAogICAgICAg
>> "%B64_FILE%" echo ICAgICAic291cmNlRm9ybXVsYSI6ICJUb25DSyA9IENET1RIQU4gcHJldmlvdXMgbW9udGggVG9u
>> "%B64_FILE%" echo Q0sgKyB2MTkgbW92ZW1lbnRzIiwKICAgICAgICAgICAgInR0aW5LaG8iOiBub3JtYWxpemVfdGV4
>> "%B64_FILE%" echo dChyb3cuVFRJTl9LaG8pLAogICAgICAgICAgICAidHRpblRoYW4iOiBub3JtYWxpemVfdGV4dChy
>> "%B64_FILE%" echo b3cuVFRJTl9UaGFuKSwKICAgICAgICB9KQoKICAgIGRhdGFfcm93cy5zb3J0KGtleT1sYW1iZGEg
>> "%B64_FILE%" echo eDogKGtob19zb3J0X2tleSh4WyJUZW5LaG8iXSwgeFsiTWFLaG8iXSksIHhbInR0aW5UaGFuIl0s
>> "%B64_FILE%" echo IHhbIlRlblRoYW4iXSkpCiAgICByZXR1cm4gZGF0YV9yb3dzCgoKZGVmIGJ1aWxkX3BheWxvYWQo
>> "%B64_FILE%" echo ZmluYWxfdGFibGUsIHllYXIsIG1vbnRoLCBub3Rlcyk6CiAgICBkYXRhX3Jvd3MgPSByZWFkX2Zp
>> "%B64_FILE%" echo bmFsX3Jvd3MoZmluYWxfdGFibGUpCiAgICBpZiBub3QgZGF0YV9yb3dzOgogICAgICAgIHJhaXNl
>> "%B64_FILE%" echo IFJ1bnRpbWVFcnJvcihmIkLhuqNuZyBr4bq/dCBxdeG6oyB7ZmluYWxfdGFibGV9IGtow7RuZyBj
>> "%B64_FILE%" echo w7MgZOG7ryBsaeG7h3UgVG9uQ0sgaOG7o3AgbOG7hy4iKQoKICAgIHRvdGFsID0gcm91bmQoc3Vt
>> "%B64_FILE%" echo KGZsb2F0KHJbIlRvbkNLIl0pIGZvciByIGluIGRhdGFfcm93cyksIDIpCiAgICBraG8xX3Jvd3Mg
>> "%B64_FILE%" echo PSBbCiAgICAgICAgciBmb3IgciBpbiBkYXRhX3Jvd3MKICAgICAgICBpZiByWyJUZW5LaG8iXS5z
>> "%B64_FILE%" echo dHJpcCgpLmxvd2VyKCkgPT0gImtobyAxIiBvciByWyJNYUtobyJdLnN0cmlwKCkgaW4gKCIxIiwg
>> "%B64_FILE%" echo IjAxIikKICAgIF0KICAgIGtobzFfdG90YWwgPSByb3VuZChzdW0oZmxvYXQoclsiVG9uQ0siXSkg
>> "%B64_FILE%" echo Zm9yIHIgaW4ga2hvMV9yb3dzKSwgMikKCiAgICByZXR1cm4gewogICAgICAgICJvayI6IFRydWUs
>> "%B64_FILE%" echo CiAgICAgICAgIm1ldGEiOiB7CiAgICAgICAgICAgICJzb3VyY2UiOiAiVFRDT19ESVJFQ1RfREJf
>> "%B64_FILE%" echo RU5HSU5FIiwKICAgICAgICAgICAgImRhdGFiYXNlIjogREFUQUJBU0UsCiAgICAgICAgICAgICJz
>> "%B64_FILE%" echo b3VyY2VUYWJsZSI6IGZpbmFsX3RhYmxlLAogICAgICAgICAgICAibWFzdGVyRGF0YWJhc2UiOiBN
>> "%B64_FILE%" echo QVNURVJfREIsCiAgICAgICAgICAgICJ2ZXJzaW9uIjogImRpcmVjdC1kYi12MjMtdG9uZGstcGx1
>> "%B64_FILE%" echo cy12MTktbW92ZW1lbnQiLAogICAgICAgICAgICAidXBkYXRlZEF0IjogZGF0ZXRpbWUubm93KCku
>> "%B64_FILE%" echo c3RyZnRpbWUoIiVZLSVtLSVkICVIOiVNOiVTIiksCiAgICAgICAgICAgICJOYW1IVCI6IHN0cih5
>> "%B64_FILE%" echo ZWFyKSwKICAgICAgICAgICAgIlRoYW5nSFQiOiBzdHIobW9udGgpLAogICAgICAgICAgICAicm93
>> "%B64_FILE%" echo Q291bnQiOiBsZW4oZGF0YV9yb3dzKSwKICAgICAgICAgICAgInRvdGFsVG9uIjogdG90YWwsCiAg
>> "%B64_FILE%" echo ICAgICAgICAgICJraG8xVG90YWwiOiBraG8xX3RvdGFsLAogICAgICAgICAgICAiZm9ybXVsYSI6
>> "%B64_FILE%" echo ICJUb25DSyA9IFRvbkRLKHByZXZpb3VzIG1vbnRoIENET1RIQU4uVG9uQ0spICsgTmhhcFRLKHYx
>> "%B64_FILE%" echo OSBsb2dpYykgLSBYdWF0VEsodjE5IGxvZ2ljKSIsCiAgICAgICAgICAgICJtb3ZlbWVudFNvdXJj
>> "%B64_FILE%" echo ZXMiOiBub3RlcywKICAgICAgICAgICAgIm5vdGUiOiAiS2jDtG5nIG3hu58gVFRDT19BUFAsIGto
>> "%B64_FILE%" echo w7RuZyBkw7luZyBFeGNlbC4gVjIzIGTDuW5nIFRvbkRLIMSRw7puZyB04burIENET1RIQU4gdGjD
>> "%B64_FILE%" echo oW5nIHRyxrDhu5tjIHbDoCBOaGFwL1h1YXQgxJHDum5nIHRoZW8gbG9naWMgdjE5IMSRw6MgeMOh
>> "%B64_FILE%" echo YyBuaOG6rW4uIiwKICAgICAgICB9LAogICAgICAgICJkYXRhIjogZGF0YV9yb3dzLAogICAgICAg
>> "%B64_FILE%" echo ICJyb3dzIjogZGF0YV9yb3dzLAogICAgfSwga2hvMV9yb3dzCgoKZGVmIHdyaXRlX2NoZWNrKHBh
>> "%B64_FILE%" echo eWxvYWQsIGtobzFfcm93cyk6CiAgICBDSEVDS19ESVIubWtkaXIocGFyZW50cz1UcnVlLCBleGlz
>> "%B64_FILE%" echo dF9vaz1UcnVlKQogICAgb3V0ID0gQ0hFQ0tfRElSIC8gZiJjaGVja19kaXJlY3RfZGJfdjIzX3tk
>> "%B64_FILE%" echo YXRldGltZS5ub3coKTolWSVtJWRfJUglTSVTfS50eHQiCiAgICB3aXRoIG91dC5vcGVuKCJ3Iiwg
>> "%B64_FILE%" echo ZW5jb2Rpbmc9InV0Zi04IikgYXMgZjoKICAgICAgICBmLndyaXRlKCJUVENPIC0gS0nhu4JNIFRS
>> "%B64_FILE%" echo QSBESVJFQ1QgREIgRU5HSU5FIC0gVjIzXG4iKQogICAgICAgIGYud3JpdGUoIj0iICogOTAgKyAi
>> "%B64_FILE%" echo XG4iKQogICAgICAgIGYud3JpdGUoZiJTb3VyY2UgdGFibGUgOiB7cGF5bG9hZFsnbWV0YSddWydz
>> "%B64_FILE%" echo b3VyY2VUYWJsZSddfVxuIikKICAgICAgICBmLndyaXRlKGYiUGVyaW9kICAgICAgIDoge3BheWxv
>> "%B64_FILE%" echo YWRbJ21ldGEnXVsnVGhhbmdIVCddfS97cGF5bG9hZFsnbWV0YSddWydOYW1IVCddfVxuIikKICAg
>> "%B64_FILE%" echo ICAgICBmLndyaXRlKGYiUm93IGNvdW50ICAgIDoge3BheWxvYWRbJ21ldGEnXVsncm93Q291bnQn
>> "%B64_FILE%" echo XX1cbiIpCiAgICAgICAgZi53cml0ZShmIlRvdGFsIHRvbiAgICA6IHtwYXlsb2FkWydtZXRhJ11b
>> "%B64_FILE%" echo J3RvdGFsVG9uJ106LC4yZn1cbiIpCiAgICAgICAgZi53cml0ZShmIktobyAxIHRvdGFsICA6IHtw
>> "%B64_FILE%" echo YXlsb2FkWydtZXRhJ11bJ2tobzFUb3RhbCddOiwuMmZ9XG4iKQogICAgICAgIGYud3JpdGUoZiJG
>> "%B64_FILE%" echo b3JtdWxhICAgICAgOiB7cGF5bG9hZFsnbWV0YSddWydmb3JtdWxhJ119XG4iKQogICAgICAgIGYu
>> "%B64_FILE%" echo d3JpdGUoIlxuTW92ZW1lbnQgc291cmNlczpcbiIpCiAgICAgICAgZm9yIG5vdGUgaW4gcGF5bG9h
>> "%B64_FILE%" echo ZFsibWV0YSJdLmdldCgibW92ZW1lbnRTb3VyY2VzIiwgW10pOgogICAgICAgICAgICBmLndyaXRl
>> "%B64_FILE%" echo KGYiLSB7bm90ZX1cbiIpCiAgICAgICAgZi53cml0ZSgiXG5LaG8gMSByb3dzOlxuIikKICAgICAg
>> "%B64_FILE%" echo ICBmb3IgciBpbiBraG8xX3Jvd3M6CiAgICAgICAgICAgIGYud3JpdGUoCiAgICAgICAgICAgICAg
>> "%B64_FILE%" echo ICBmIk1hS2hvPXtyWydNYUtobyddfSB8IEtobz17clsnVGVuS2hvJ119IHwgIgogICAgICAgICAg
>> "%B64_FILE%" echo ICAgICAgZiJNYVRoYW49e3JbJ01hVGhhbiddfSB8IFRoYW49e3JbJ1RlblRoYW4nXX0gfCAiCiAg
>> "%B64_FILE%" echo ICAgICAgICAgICAgICBmIlRvbkRLPXtyWydUb25ESyddOiwuMmZ9IHwgTmhhcFRLPXtyWydOaGFw
>> "%B64_FILE%" echo VEsnXTosLjJmfSB8ICIKICAgICAgICAgICAgICAgIGYiWHVhdFRLPXtyWydYdWF0VEsnXTosLjJm
>> "%B64_FILE%" echo fSB8IFRvbkNLPXtyWydUb25DSyddOiwuMmZ9XG4iCiAgICAgICAgICAgICkKICAgIHByaW50KGYi
>> "%B64_FILE%" echo W09LXSDEkMOjIHh14bqldCBraeG7g20gdHJhOiB7b3V0fSIsIGZsdXNoPVRydWUpCiAgICB0cnk6
>> "%B64_FILE%" echo CiAgICAgICAgc3VicHJvY2Vzcy5Qb3BlbihbImV4cGxvcmVyLmV4ZSIsIHN0cihDSEVDS19ESVIp
>> "%B64_FILE%" echo XSkKICAgIGV4Y2VwdCBFeGNlcHRpb246CiAgICAgICAgcGFzcwoKCmRlZiB3cml0ZV9qc29uKHJl
>> "%B64_FILE%" echo cG9fZGlyLCBwYXlsb2FkKToKICAgIGRlc3QgPSBQYXRoKHJlcG9fZGlyKSAvIEpTT05fUkVMCiAg
>> "%B64_FILE%" echo ICBkZXN0LnBhcmVudC5ta2RpcihwYXJlbnRzPVRydWUsIGV4aXN0X29rPVRydWUpCiAgICBkZXN0
>> "%B64_FILE%" echo LndyaXRlX3RleHQoanNvbi5kdW1wcyhwYXlsb2FkLCBlbnN1cmVfYXNjaWk9RmFsc2UsIGluZGVu
>> "%B64_FILE%" echo dD0yKSwgZW5jb2Rpbmc9InV0Zi04IikKICAgIHByaW50KGYiW09LXSDEkMOjIHThuqFvIEpTT046
>> "%B64_FILE%" echo IHtkZXN0fSIsIGZsdXNoPVRydWUpCgoKZGVmIGRpcmVjdF9jaGVjayh5ZWFyLCBtb250aCk6CiAg
>> "%B64_FILE%" echo ICBmaW5hbF90YWJsZSwgbm90ZXMgPSBkaXJlY3RfY29tcHV0ZSh5ZWFyLCBtb250aCkKICAgIHBh
>> "%B64_FILE%" echo eWxvYWQsIGtobzFfcm93cyA9IGJ1aWxkX3BheWxvYWQoZmluYWxfdGFibGUsIHllYXIsIG1vbnRo
>> "%B64_FILE%" echo LCBub3RlcykKICAgIHByaW50KCIiLCBmbHVzaD1UcnVlKQogICAgcHJpbnQoIktp4buDbSB0cmEg
>> "%B64_FILE%" echo bmhhbmg6IiwgZmx1c2g9VHJ1ZSkKICAgIHByaW50KGYiQuG6o25nIGvhur90IHF14bqjIDoge3Bh
>> "%B64_FILE%" echo eWxvYWRbJ21ldGEnXVsnc291cmNlVGFibGUnXX0iLCBmbHVzaD1UcnVlKQogICAgcHJpbnQoZiJL
>> "%B64_FILE%" echo 4buzIGThu68gbGnhu4d1ICAgOiB7bW9udGg6MDJkfS97eWVhcn0iLCBmbHVzaD1UcnVlKQogICAg
>> "%B64_FILE%" echo cHJpbnQoZiJT4buRIGTDsm5nICAgICAgOiB7cGF5bG9hZFsnbWV0YSddWydyb3dDb3VudCddfSIs
>> "%B64_FILE%" echo IGZsdXNoPVRydWUpCiAgICBwcmludChmIlThu5VuZyB04buTbiAgICAgOiB7cGF5bG9hZFsnbWV0
>> "%B64_FILE%" echo YSddWyd0b3RhbFRvbiddOiwuMmZ9IiwgZmx1c2g9VHJ1ZSkKICAgIHByaW50KGYiVOG7lW5nIEto
>> "%B64_FILE%" echo byAxICAgOiB7cGF5bG9hZFsnbWV0YSddWydraG8xVG90YWwnXTosLjJmfSIsIGZsdXNoPVRydWUp
>> "%B64_FILE%" echo CiAgICB3cml0ZV9jaGVjayhwYXlsb2FkLCBraG8xX3Jvd3MpCgoKZGVmIGRpcmVjdF91cGRhdGUo
>> "%B64_FILE%" echo cmVwb19kaXIsIHllYXIsIG1vbnRoKToKICAgIGVuc3VyZV9naXQoKQogICAgZW5zdXJlX3JlcG8o
>> "%B64_FILE%" echo cmVwb19kaXIpCiAgICBmaW5hbF90YWJsZSwgbm90ZXMgPSBkaXJlY3RfY29tcHV0ZSh5ZWFyLCBt
>> "%B64_FILE%" echo b250aCkKICAgIHBheWxvYWQsIGtobzFfcm93cyA9IGJ1aWxkX3BheWxvYWQoZmluYWxfdGFibGUs
>> "%B64_FILE%" echo IHllYXIsIG1vbnRoLCBub3RlcykKCiAgICBwcmludCgiIiwgZmx1c2g9VHJ1ZSkKICAgIHByaW50
>> "%B64_FILE%" echo KCJLaeG7g20gdHJhIG5oYW5oIHRyxrDhu5tjIGtoaSB1cDoiLCBmbHVzaD1UcnVlKQogICAgcHJp
>> "%B64_FILE%" echo bnQoZiJC4bqjbmcga+G6v3QgcXXhuqMgOiB7cGF5bG9hZFsnbWV0YSddWydzb3VyY2VUYWJsZSdd
>> "%B64_FILE%" echo fSIsIGZsdXNoPVRydWUpCiAgICBwcmludChmIkvhu7MgZOG7ryBsaeG7h3UgICA6IHttb250aDow
>> "%B64_FILE%" echo MmR9L3t5ZWFyfSIsIGZsdXNoPVRydWUpCiAgICBwcmludChmIlPhu5EgZMOybmcgICAgICA6IHtw
>> "%B64_FILE%" echo YXlsb2FkWydtZXRhJ11bJ3Jvd0NvdW50J119IiwgZmx1c2g9VHJ1ZSkKICAgIHByaW50KGYiVOG7
>> "%B64_FILE%" echo lW5nIHThu5NuICAgICA6IHtwYXlsb2FkWydtZXRhJ11bJ3RvdGFsVG9uJ106LC4yZn0iLCBmbHVz
>> "%B64_FILE%" echo aD1UcnVlKQogICAgcHJpbnQoZiJU4buVbmcgS2hvIDEgICA6IHtwYXlsb2FkWydtZXRhJ11bJ2to
>> "%B64_FILE%" echo bzFUb3RhbCddOiwuMmZ9IiwgZmx1c2g9VHJ1ZSkKICAgIHdyaXRlX2NoZWNrKHBheWxvYWQsIGto
>> "%B64_FILE%" echo bzFfcm93cykKICAgIHdyaXRlX2pzb24ocmVwb19kaXIsIHBheWxvYWQpCgogICAgcHJpbnQoIlxu
>> "%B64_FILE%" echo xJBhbmcgY29tbWl0L3B1c2ggbMOqbiBHaXRIdWIuLi4iLCBmbHVzaD1UcnVlKQogICAgcnVuKFsi
>> "%B64_FILE%" echo Z2l0IiwgImNoZWNrb3V0IiwgQlJBTkNIXSwgY3dkPXJlcG9fZGlyLCBjaGVjaz1GYWxzZSkKICAg
>> "%B64_FILE%" echo IHJ1bihbImdpdCIsICJwdWxsIiwgIi0tcmViYXNlIiwgIm9yaWdpbiIsIEJSQU5DSF0sIGN3ZD1y
>> "%B64_FILE%" echo ZXBvX2RpciwgY2hlY2s9RmFsc2UpCiAgICBydW4oWyJnaXQiLCAiYWRkIiwgSlNPTl9SRUxdLCBj
>> "%B64_FILE%" echo d2Q9cmVwb19kaXIpCgogICAgZGlmZl9jb2RlID0gc3VicHJvY2Vzcy5ydW4oWyJnaXQiLCAiZGlm
>> "%B64_FILE%" echo ZiIsICItLWNhY2hlZCIsICItLXF1aWV0Il0sIGN3ZD1yZXBvX2RpcikucmV0dXJuY29kZQogICAg
>> "%B64_FILE%" echo aWYgZGlmZl9jb2RlID09IDA6CiAgICAgICAgcHJpbnQoIltPS10gSlNPTiBraMO0bmcgdGhheSDE
>> "%B64_FILE%" echo keG7lWksIGtow7RuZyBj4bqnbiBwdXNoLiIsIGZsdXNoPVRydWUpCiAgICAgICAgbG9nKCJObyBj
>> "%B64_FILE%" echo aGFuZ2VzLiIpCiAgICAgICAgcmV0dXJuCgogICAgbXNnID0gZiJVcGRhdGUgVFRDTyB0b24ga2hv
>> "%B64_FILE%" echo IGRpcmVjdCBEQiB2MjMge3llYXJ9LXttb250aDowMmR9ICIgKyBkYXRldGltZS5ub3coKS5zdHJm
>> "%B64_FILE%" echo dGltZSgiJVktJW0tJWQgJUg6JU06JVMiKQogICAgcnVuKFsiZ2l0IiwgImNvbW1pdCIsICItbSIs
>> "%B64_FILE%" echo IG1zZ10sIGN3ZD1yZXBvX2RpcikKICAgIHJ1bihbImdpdCIsICJwdXNoIiwgIm9yaWdpbiIsIEJS
>> "%B64_FILE%" echo QU5DSF0sIGN3ZD1yZXBvX2RpcikKCiAgICBwcmludCgiXG49PT09PT09PT09PT09PT09PT09PT09
>> "%B64_FILE%" echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0iLCBmbHVzaD1UcnVlKQogICAg
>> "%B64_FILE%" echo cHJpbnQoIltPS10gxJDDgyBD4bqsUCBOSOG6rFQgR0lUSFVCIFRIw4BOSCBDw5RORyIsIGZsdXNo
>> "%B64_FILE%" echo PVRydWUpCiAgICBwcmludCgiPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
>> "%B64_FILE%" echo PT09PT09PT09PT09PT09PT09PT09IiwgZmx1c2g9VHJ1ZSkKICAgIGxvZygiUHVzaCBzdWNjZXNz
>> "%B64_FILE%" echo LiIpCgoKZGVmIGluc3RhbGxfdGFzayhiYXRfcGF0aDogc3RyKToKICAgIGlmIG5vdCBiYXRfcGF0
>> "%B64_FILE%" echo aCBvciBub3Qgb3MucGF0aC5pc2ZpbGUoYmF0X3BhdGgpOgogICAgICAgIHJhaXNlIFJ1bnRpbWVF
>> "%B64_FILE%" echo cnJvcigiS2jDtG5nIHjDoWMgxJHhu4tuaCDEkcaw4bujYyBmaWxlIEJBVCDEkeG7gyBjw6BpIHTh
>> "%B64_FILE%" echo u7EgxJHhu5luZy4iKQogICAgdGFza19jbWQgPSBmJyJ7YmF0X3BhdGh9IiAtLWF1dG8nCiAgICBy
>> "%B64_FILE%" echo dW4oWyJzY2h0YXNrcyIsICIvQ3JlYXRlIiwgIi9UTiIsIFRBU0tfTkFNRSwgIi9UUiIsIHRhc2tf
>> "%B64_FILE%" echo Y21kLCAiL1NDIiwgIk9OTE9HT04iLCAiL0RFTEFZIiwgIjAwMDE6MDAiLCAiL0YiXSkKICAgIHBy
>> "%B64_FILE%" echo aW50KCJbT0tdIMSQw6MgY8OgaSB04buxIMSR4buZbmcga2hpIMSRxINuZyBuaOG6rXAgV2luZG93
>> "%B64_FILE%" echo cy4iLCBmbHVzaD1UcnVlKQogICAgcHJpbnQoIkNo4bq/IMSR4buZIHThu7EgxJHhu5luZyBkw7lu
>> "%B64_FILE%" echo ZyB0aMOhbmcvbsSDbSBoaeG7h24gdOG6oWkgY+G7p2EgV2luZG93cy4iLCBmbHVzaD1UcnVlKQog
>> "%B64_FILE%" echo ICAgbG9nKGYiSW5zdGFsbCB0YXNrOiB7dGFza19jbWR9IikKCgpkZWYgb3Blbl9sb2coKToKICAg
>> "%B64_FILE%" echo IENPTkZJR19ESVIubWtkaXIocGFyZW50cz1UcnVlLCBleGlzdF9vaz1UcnVlKQogICAgaWYgbm90
>> "%B64_FILE%" echo IExPR19GSUxFLmV4aXN0cygpOgogICAgICAgIExPR19GSUxFLndyaXRlX3RleHQoIkNoxrBhIGPD
>> "%B64_FILE%" echo syBsb2cuXG4iLCBlbmNvZGluZz0idXRmLTgiKQogICAgc3VicHJvY2Vzcy5Qb3BlbihbIm5vdGVw
>> "%B64_FILE%" echo YWQuZXhlIiwgc3RyKExPR19GSUxFKV0pCgoKZGVmIGN1cnJlbnRfcGVyaW9kKCk6CiAgICBub3cg
>> "%B64_FILE%" echo PSBkYXRldGltZS5ub3coKQogICAgcmV0dXJuIG5vdy55ZWFyLCBub3cubW9udGgKCgpkZWYgYXNr
>> "%B64_FILE%" echo X3BlcmlvZCgpOgogICAgeSwgbSA9IGN1cnJlbnRfcGVyaW9kKCkKICAgIHRleHQgPSBpbnB1dChm
>> "%B64_FILE%" echo Ik5o4bqtcCB0aMOhbmcvbsSDbSBk4bqhbmcgTU0vWVlZWSwgRW50ZXIgxJHhu4MgZMO5bmcge206
>> "%B64_FILE%" echo MDJkfS97eX06ICIpLnN0cmlwKCkKICAgIGlmIG5vdCB0ZXh0OgogICAgICAgIHJldHVybiB5LCBt
>> "%B64_FILE%" echo CiAgICBtbSwgeXkgPSB0ZXh0LnJlcGxhY2UoIi0iLCAiLyIpLnNwbGl0KCIvIikKICAgIHJldHVy
>> "%B64_FILE%" echo biBpbnQoeXkpLCBpbnQobW0pCgoKZGVmIG1haW4oKToKICAgIHBhcnNlciA9IGFyZ3BhcnNlLkFy
>> "%B64_FILE%" echo Z3VtZW50UGFyc2VyKCkKICAgIHBhcnNlci5hZGRfYXJndW1lbnQoIi0tYWN0aW9uIiwgY2hvaWNl
>> "%B64_FILE%" echo cz1bImNoZWNrIiwgInVwZGF0ZSIsICJjaGVjay1jdXN0b20iLCAidXBkYXRlLWN1c3RvbSIsICJj
>> "%B64_FILE%" echo b25maWctcmVwbyIsICJpbnN0YWxsIiwgIm9wZW4tbG9nIl0sIHJlcXVpcmVkPVRydWUpCiAgICBw
>> "%B64_FILE%" echo YXJzZXIuYWRkX2FyZ3VtZW50KCItLWJhdCIsIGRlZmF1bHQ9IiIpCiAgICBhcmdzID0gcGFyc2Vy
>> "%B64_FILE%" echo LnBhcnNlX2FyZ3MoKQoKICAgIHRyeToKICAgICAgICBjZmcgPSBsb2FkX2NvbmZpZygpCgogICAg
>> "%B64_FILE%" echo ICAgIGlmIGFyZ3MuYWN0aW9uID09ICJvcGVuLWxvZyI6CiAgICAgICAgICAgIG9wZW5fbG9nKCkK
>> "%B64_FILE%" echo ICAgICAgICAgICAgcmV0dXJuIDAKCiAgICAgICAgaWYgYXJncy5hY3Rpb24gPT0gImNvbmZpZy1y
>> "%B64_FILE%" echo ZXBvIjoKICAgICAgICAgICAgZm9sZGVyID0gcGlja19mb2xkZXIoIkNo4buNbiB0aMawIG3hu6Vj
>> "%B64_FILE%" echo IHJlcG8gR2l0SHViIG15LWFpLXNpdGUiLCBjZmcuZ2V0KCJyZXBvX2RpciIpIG9yIHIiRDpcVFRD
>> "%B64_FILE%" echo T19Ub25LaG9fQXBwX1JlcG8iKQogICAgICAgICAgICBpZiBub3QgZm9sZGVyOgogICAgICAgICAg
>> "%B64_FILE%" echo ICAgICAgcmFpc2UgUnVudGltZUVycm9yKCJDaMawYSBjaOG7jW4gdGjGsCBt4bulYyByZXBvLiIp
>> "%B64_FILE%" echo CiAgICAgICAgICAgIGNmZ1sicmVwb19kaXIiXSA9IGZvbGRlcgogICAgICAgICAgICBzYXZlX2Nv
>> "%B64_FILE%" echo bmZpZyhjZmcpCiAgICAgICAgICAgIHByaW50KGYiW09LXSDEkMOjIGzGsHUgcmVwbzoge2ZvbGRl
>> "%B64_FILE%" echo cn0iLCBmbHVzaD1UcnVlKQogICAgICAgICAgICByZXR1cm4gMAoKICAgICAgICByZXBvX2RpciA9
>> "%B64_FILE%" echo IGNmZy5nZXQoInJlcG9fZGlyIikgb3IgciJEOlxUVENPX1Rvbktob19BcHBfUmVwbyIKICAgICAg
>> "%B64_FILE%" echo ICBpZiBhcmdzLmFjdGlvbiBpbiAoInVwZGF0ZSIsICJ1cGRhdGUtY3VzdG9tIiwgImluc3RhbGwi
>> "%B64_FILE%" echo KToKICAgICAgICAgICAgaWYgbm90IG9zLnBhdGguaXNkaXIocmVwb19kaXIpOgogICAgICAgICAg
>> "%B64_FILE%" echo ICAgICAgZm9sZGVyID0gcGlja19mb2xkZXIoIkNo4buNbiB0aMawIG3hu6VjIHJlcG8gR2l0SHVi
>> "%B64_FILE%" echo IG15LWFpLXNpdGUiLCByZXBvX2RpcikKICAgICAgICAgICAgICAgIGlmIG5vdCBmb2xkZXI6CiAg
>> "%B64_FILE%" echo ICAgICAgICAgICAgICAgICAgcmFpc2UgUnVudGltZUVycm9yKCJDaMawYSBjaOG7jW4gdGjGsCBt
>> "%B64_FILE%" echo 4bulYyByZXBvLiIpCiAgICAgICAgICAgICAgICBjZmdbInJlcG9fZGlyIl0gPSBmb2xkZXIKICAg
>> "%B64_FILE%" echo ICAgICAgICAgICAgIHJlcG9fZGlyID0gZm9sZGVyCiAgICAgICAgICAgICAgICBzYXZlX2NvbmZp
>> "%B64_FILE%" echo ZyhjZmcpCgogICAgICAgIGlmIGFyZ3MuYWN0aW9uID09ICJpbnN0YWxsIjoKICAgICAgICAgICAg
>> "%B64_FILE%" echo aW5zdGFsbF90YXNrKGFyZ3MuYmF0KQogICAgICAgICAgICByZXR1cm4gMAoKICAgICAgICBpZiBh
>> "%B64_FILE%" echo cmdzLmFjdGlvbiBpbiAoImNoZWNrIiwgInVwZGF0ZSIpOgogICAgICAgICAgICB5ZWFyLCBtb250
>> "%B64_FILE%" echo aCA9IGN1cnJlbnRfcGVyaW9kKCkKICAgICAgICBlbHNlOgogICAgICAgICAgICB5ZWFyLCBtb250
>> "%B64_FILE%" echo aCA9IGFza19wZXJpb2QoKQoKICAgICAgICBpZiBhcmdzLmFjdGlvbiBpbiAoImNoZWNrIiwgImNo
>> "%B64_FILE%" echo ZWNrLWN1c3RvbSIpOgogICAgICAgICAgICBkaXJlY3RfY2hlY2soeWVhciwgbW9udGgpCiAgICAg
>> "%B64_FILE%" echo ICAgICAgIHJldHVybiAwCgogICAgICAgIGlmIGFyZ3MuYWN0aW9uIGluICgidXBkYXRlIiwgInVw
>> "%B64_FILE%" echo ZGF0ZS1jdXN0b20iKToKICAgICAgICAgICAgZGlyZWN0X3VwZGF0ZShyZXBvX2RpciwgeWVhciwg
>> "%B64_FILE%" echo bW9udGgpCiAgICAgICAgICAgIHJldHVybiAwCgogICAgICAgIHJldHVybiAwCiAgICBleGNlcHQg
>> "%B64_FILE%" echo RXhjZXB0aW9uIGFzIGV4YzoKICAgICAgICBwcmludCgiXG5bTOG7lkldIiwgZXhjLCBmbHVzaD1U
>> "%B64_FILE%" echo cnVlKQogICAgICAgIHByaW50KCJMb2c6IiwgTE9HX0ZJTEUsIGZsdXNoPVRydWUpCiAgICAgICAg
>> "%B64_FILE%" echo bG9nKGYiRVJST1I6IHtleGN9IikKICAgICAgICByZXR1cm4gMQoKCmlmIF9fbmFtZV9fID09ICJf
>> "%B64_FILE%" echo X21haW5fXyI6CiAgICBzeXMuZXhpdChtYWluKCkpCg==
python -c "import base64, pathlib, os; b=pathlib.Path(os.environ['B64_FILE']).read_text().replace('\n','').replace('\r','').strip(); pathlib.Path(os.environ['PY_MAIN']).write_bytes(base64.b64decode(b))"
exit /b %errorlevel%
