@echo off
setlocal EnableExtensions EnableDelayedExpansion
chcp 65001 >nul
title TTCO - Tim dung nguon ton kho TTCO_APP - v6

set "WORK_DIR=%~dp0"
set "PY_FILE=%WORK_DIR%ttco_find_true_tonkho_source_v6.py"
set "B64_FILE=%WORK_DIR%ttco_find_true_tonkho_source_v6.b64"

echo ============================================================
echo   TTCO - TIM DUNG NGUON TON KHO TTCO_APP - V6
echo ============================================================
echo.
echo Ban v6 se quet nhieu database TTCO, tim object va cong thuc:
echo - Tong gan 1.052,65
echo - Phan chenh 380,90
echo - Phan chenh 542,70
echo - CDOTHAN + phat sinh = 1.052,65
echo.
echo Ket qua xuat ra Desktop\TTCO_FIND_TRUE_TONKHO_SOURCE
echo.
pause

:WRITE_PY
> "%B64_FILE%" echo CiMgLSotIGNvZGluZzogdXRmLTggLSotCmltcG9ydCBjc3YKaW1wb3J0IG9zCmltcG9ydCByZQpp
>> "%B64_FILE%" echo bXBvcnQgc3VicHJvY2VzcwppbXBvcnQgc3lzCmZyb20gZGF0ZXRpbWUgaW1wb3J0IGRhdGV0aW1l
>> "%B64_FILE%" echo CmZyb20gcGF0aGxpYiBpbXBvcnQgUGF0aAoKU0VSVkVSID0gciJ0dXllbnRoYW5jdWFvbmcuY29t
>> "%B64_FILE%" echo LnZuLDUyMzc2IgpERUZBVUxUX0RCID0gIlRUQ09fVEhPTkdLRSIKClRBUkdFVF9BUFAgPSAxMDUy
>> "%B64_FILE%" echo LjY1CkNET1RIQU5fTk9XID0gNjcxLjc1CkNET1RIQU5fUFJFViA9IDUwOS45NQpERUxUQV9GUk9N
>> "%B64_FILE%" echo X05PVyA9IHJvdW5kKFRBUkdFVF9BUFAgLSBDRE9USEFOX05PVywgMikgICAjIDM4MC45MApERUxU
>> "%B64_FILE%" echo QV9GUk9NX1BSRVYgPSByb3VuZChUQVJHRVRfQVBQIC0gQ0RPVEhBTl9QUkVWLCAyKSAjIDU0Mi43
>> "%B64_FILE%" echo MAoKVVNFUlBST0ZJTEUgPSBQYXRoKG9zLmVudmlyb24uZ2V0KCJVU0VSUFJPRklMRSIsIHN0cihQ
>> "%B64_FILE%" echo YXRoLmhvbWUoKSkpKQpERVNLVE9QID0gVVNFUlBST0ZJTEUgLyAiRGVza3RvcCIKT1VUX0RJUiA9
>> "%B64_FILE%" echo IERFU0tUT1AgLyAiVFRDT19GSU5EX1RSVUVfVE9OS0hPX1NPVVJDRSIKT1VUX0RJUi5ta2Rpcihw
>> "%B64_FILE%" echo YXJlbnRzPVRydWUsIGV4aXN0X29rPVRydWUpCgpTVEFNUCA9IGRhdGV0aW1lLm5vdygpLnN0cmZ0
>> "%B64_FILE%" echo aW1lKCIlWSVtJWRfJUglTSVTIikKT1VUX1RYVCA9IE9VVF9ESVIgLyBmImZpbmRfdHJ1ZV90b25r
>> "%B64_FILE%" echo aG9fc291cmNlX3Y2X3tTVEFNUH0udHh0IgpPVVRfQ1NWID0gT1VUX0RJUiAvIGYiZmluZF90cnVl
>> "%B64_FILE%" echo X3Rvbmtob19zb3VyY2VfdjZfe1NUQU1QfS5jc3YiCk9VVF9TQ0hFTUEgPSBPVVRfRElSIC8gZiJz
>> "%B64_FILE%" echo Y2hlbWFfY2FuZGlkYXRlX3RhYmxlc192Nl97U1RBTVB9LnR4dCIKT1VUX09CSkVDVFMgPSBPVVRf
>> "%B64_FILE%" echo RElSIC8gZiJzcWxfb2JqZWN0c19hbGxfZGJfdjZfe1NUQU1QfS50eHQiCk9VVF9FUlJPUlMgPSBP
>> "%B64_FILE%" echo VVRfRElSIC8gZiJlcnJvcnNfdjZfe1NUQU1QfS50eHQiCgoKZGVmIHdyaXRlKGxpbmU9IiIpOgog
>> "%B64_FILE%" echo ICAgcHJpbnQobGluZSkKICAgIHdpdGggT1VUX1RYVC5vcGVuKCJhIiwgZW5jb2Rpbmc9InV0Zi04
>> "%B64_FILE%" echo IikgYXMgZjoKICAgICAgICBmLndyaXRlKHN0cihsaW5lKSArICJcbiIpCgoKZGVmIHdyaXRlX2Zp
>> "%B64_FILE%" echo bGUocGF0aCwgbGluZT0iIik6CiAgICB3aXRoIHBhdGgub3BlbigiYSIsIGVuY29kaW5nPSJ1dGYt
>> "%B64_FILE%" echo OCIpIGFzIGY6CiAgICAgICAgZi53cml0ZShzdHIobGluZSkgKyAiXG4iKQoKCmRlZiBsb2dfZXJy
>> "%B64_FILE%" echo b3IobGluZSk6CiAgICB3cml0ZV9maWxlKE9VVF9FUlJPUlMsIGxpbmUpCgoKZGVmIGVuc3VyZV9w
>> "%B64_FILE%" echo eW9kYmMoKToKICAgIHRyeToKICAgICAgICBpbXBvcnQgcHlvZGJjICAjIG5vcWEKICAgICAgICBy
>> "%B64_FILE%" echo ZXR1cm4KICAgIGV4Y2VwdCBFeGNlcHRpb246CiAgICAgICAgd3JpdGUoIkNoxrBhIGPDsyBweW9k
>> "%B64_FILE%" echo YmMuIMSQYW5nIHRo4butIGPDoGkgcHlvZGJjLi4uIikKICAgICAgICBzdWJwcm9jZXNzLmNoZWNr
>> "%B64_FILE%" echo X2NhbGwoW3N5cy5leGVjdXRhYmxlLCAiLW0iLCAicGlwIiwgImluc3RhbGwiLCAicHlvZGJjIl0p
>> "%B64_FILE%" echo CgoKZGVmIGNvbm5lY3QoZGIpOgogICAgaW1wb3J0IHB5b2RiYwogICAgY29ubl9zdHIgPSAoCiAg
>> "%B64_FILE%" echo ICAgICAgIkRSSVZFUj17T0RCQyBEcml2ZXIgMTggZm9yIFNRTCBTZXJ2ZXJ9OyIKICAgICAgICBm
>> "%B64_FILE%" echo IlNFUlZFUj17U0VSVkVSfTsiCiAgICAgICAgZiJEQVRBQkFTRT17ZGJ9OyIKICAgICAgICAiVHJ1
>> "%B64_FILE%" echo c3RlZF9Db25uZWN0aW9uPXllczsiCiAgICAgICAgIlRydXN0U2VydmVyQ2VydGlmaWNhdGU9eWVz
>> "%B64_FILE%" echo OyIKICAgICkKICAgIHJldHVybiBweW9kYmMuY29ubmVjdChjb25uX3N0ciwgdGltZW91dD0yMCkK
>> "%B64_FILE%" echo CgpkZWYgcWlkZW50KG5hbWUpOgogICAgcmV0dXJuICJbIiArIHN0cihuYW1lKS5yZXBsYWNlKCJd
>> "%B64_FILE%" echo IiwgIl1dIikgKyAiXSIKCgpkZWYgc2FmZV9mbG9hdCh2KToKICAgIHRyeToKICAgICAgICBpZiB2
>> "%B64_FILE%" echo IGlzIE5vbmU6CiAgICAgICAgICAgIHJldHVybiBOb25lCiAgICAgICAgcmV0dXJuIGZsb2F0KHYp
>> "%B64_FILE%" echo CiAgICBleGNlcHQgRXhjZXB0aW9uOgogICAgICAgIHJldHVybiBOb25lCgoKZGVmIGlzX251bWVy
>> "%B64_FILE%" echo aWNfdHlwZShkdHlwZSk6CiAgICByZXR1cm4gc3RyKGR0eXBlKS5sb3dlcigpIGluIHsKICAgICAg
>> "%B64_FILE%" echo ICAiaW50IiwgImJpZ2ludCIsICJzbWFsbGludCIsICJ0aW55aW50IiwgImRlY2ltYWwiLCAibnVt
>> "%B64_FILE%" echo ZXJpYyIsCiAgICAgICAgImZsb2F0IiwgInJlYWwiLCAibW9uZXkiLCAic21hbGxtb25leSIKICAg
>> "%B64_FILE%" echo IH0KCgpkZWYgZmV0Y2hfYWxsKGN1ciwgc3FsLCBwYXJhbXM9Tm9uZSk6CiAgICBpZiBwYXJhbXMg
>> "%B64_FILE%" echo aXMgTm9uZToKICAgICAgICBwYXJhbXMgPSBbXQogICAgcmV0dXJuIGN1ci5leGVjdXRlKHNxbCwg
>> "%B64_FILE%" echo cGFyYW1zKS5mZXRjaGFsbCgpCgoKZGVmIGdldF9hY2Nlc3NpYmxlX2RhdGFiYXNlcygpOgogICAg
>> "%B64_FILE%" echo ZGJzID0gW10KICAgIHRyeToKICAgICAgICBjb25uID0gY29ubmVjdChERUZBVUxUX0RCKQogICAg
>> "%B64_FILE%" echo ICAgIGN1ciA9IGNvbm4uY3Vyc29yKCkKICAgICAgICBzcWwgPSAiIiIKICAgICAgICBTRUxFQ1Qg
>> "%B64_FILE%" echo bmFtZQogICAgICAgIEZST00gc3lzLmRhdGFiYXNlcwogICAgICAgIFdIRVJFIHN0YXRlX2Rlc2Mg
>> "%B64_FILE%" echo PSAnT05MSU5FJwogICAgICAgICAgQU5EICgKICAgICAgICAgICAgICAgIG5hbWUgTElLRSAnVFRD
>> "%B64_FILE%" echo TyUnCiAgICAgICAgICAgICBPUiBuYW1lIExJS0UgJyVUSE9OR0tFJScKICAgICAgICAgICAgIE9S
>> "%B64_FILE%" echo IG5hbWUgTElLRSAnJURIU1glJwogICAgICAgICAgICAgT1IgbmFtZSBMSUtFICclQ0FOJScKICAg
>> "%B64_FILE%" echo ICAgICAgICAgIE9SIG5hbWUgTElLRSAnJUtITyUnCiAgICAgICAgICApCiAgICAgICAgT1JERVIg
>> "%B64_FILE%" echo QlkgbmFtZQogICAgICAgICIiIgogICAgICAgIHJvd3MgPSBmZXRjaF9hbGwoY3VyLCBzcWwpCiAg
>> "%B64_FILE%" echo ICAgICAgZGJzID0gW3IubmFtZSBmb3IgciBpbiByb3dzXQogICAgICAgIGNvbm4uY2xvc2UoKQog
>> "%B64_FILE%" echo ICAgZXhjZXB0IEV4Y2VwdGlvbiBhcyBleGM6CiAgICAgICAgbG9nX2Vycm9yKCJnZXRfYWNjZXNz
>> "%B64_FILE%" echo aWJsZV9kYXRhYmFzZXM6ICIgKyBzdHIoZXhjKSkKCiAgICBpZiBERUZBVUxUX0RCIG5vdCBpbiBk
>> "%B64_FILE%" echo YnM6CiAgICAgICAgZGJzLmluc2VydCgwLCBERUZBVUxUX0RCKQogICAgcmV0dXJuIGRicwoKCmRl
>> "%B64_FILE%" echo ZiBsaXN0X21vZHVsZXNfYWxsX2RicyhkYnMpOgogICAgd3JpdGUoIkEpIFTDjE0gU1RPUkVEIFBS
>> "%B64_FILE%" echo T0NFRFVSRSAvIFZJRVcgLyBGVU5DVElPTiBUUk9ORyBU4bqkVCBD4bqiIERCIFRSVVkgQ+G6rFAg
>> "%B64_FILE%" echo xJDGr+G7okMiKQogICAgd3JpdGUoIi0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
>> "%B64_FILE%" echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLSIpCiAgICB0b3RhbCA9IDAKICAgIGtleXdvcmRzID0g
>> "%B64_FILE%" echo WwogICAgICAgICJHM19CQzA1IiwgIkJDMDVBIiwgIkNET1RIQU4iLCAiVG9uQ0siLCAiVG9uREsi
>> "%B64_FILE%" echo LCAiTWFLaG8iLCAiVG9uS2hvIiwKICAgICAgICAiVG9uQ3VvaSIsICJOaGFwIiwgIlh1YXQiLCAi
>> "%B64_FILE%" echo VEtlIiwgIktobyIsICJUaGFuTmhhcCIsICJUaGFuWHVhdCIsICJHaWFvTmhhbiIKICAgIF0KCiAg
>> "%B64_FILE%" echo ICBmb3IgZGIgaW4gZGJzOgogICAgICAgIHRyeToKICAgICAgICAgICAgY29ubiA9IGNvbm5lY3Qo
>> "%B64_FILE%" echo ZGIpCiAgICAgICAgICAgIGN1ciA9IGNvbm4uY3Vyc29yKCkKICAgICAgICAgICAgY29uZGl0aW9u
>> "%B64_FILE%" echo cyA9ICIgT1IgIi5qb2luKFtmIm0uZGVmaW5pdGlvbiBMSUtFIE4nJXtrd30lJyIgZm9yIGt3IGlu
>> "%B64_FILE%" echo IGtleXdvcmRzXSkKICAgICAgICAgICAgc3FsID0gZiIiIgogICAgICAgICAgICBTRUxFQ1QKICAg
>> "%B64_FILE%" echo ICAgICAgICAgICAgIERCX05BTUUoKSBBUyBkYl9uYW1lLAogICAgICAgICAgICAgICAgby50eXBl
>> "%B64_FILE%" echo X2Rlc2MsCiAgICAgICAgICAgICAgICBTQ0hFTUFfTkFNRShvLnNjaGVtYV9pZCkgQVMgc2NoZW1h
>> "%B64_FILE%" echo X25hbWUsCiAgICAgICAgICAgICAgICBvLm5hbWUsCiAgICAgICAgICAgICAgICBtLmRlZmluaXRp
>> "%B64_FILE%" echo b24KICAgICAgICAgICAgRlJPTSBzeXMuc3FsX21vZHVsZXMgbQogICAgICAgICAgICBJTk5FUiBK
>> "%B64_FILE%" echo T0lOIHN5cy5vYmplY3RzIG8gT04gbS5vYmplY3RfaWQgPSBvLm9iamVjdF9pZAogICAgICAgICAg
>> "%B64_FILE%" echo ICBXSEVSRSB7Y29uZGl0aW9uc30KICAgICAgICAgICAgT1JERVIgQlkgby50eXBlX2Rlc2MsIFND
>> "%B64_FILE%" echo SEVNQV9OQU1FKG8uc2NoZW1hX2lkKSwgby5uYW1lCiAgICAgICAgICAgICIiIgogICAgICAgICAg
>> "%B64_FILE%" echo ICByb3dzID0gZmV0Y2hfYWxsKGN1ciwgc3FsKQogICAgICAgICAgICB3cml0ZShmIkRCIHtkYn06
>> "%B64_FILE%" echo IHTDrG0gxJHGsOG7o2Mge2xlbihyb3dzKX0gb2JqZWN0IikKICAgICAgICAgICAgZm9yIGksIHIg
>> "%B64_FILE%" echo aW4gZW51bWVyYXRlKHJvd3NbOjgwXSwgc3RhcnQ9MSk6CiAgICAgICAgICAgICAgICB0b3RhbCAr
>> "%B64_FILE%" echo PSAxCiAgICAgICAgICAgICAgICBmdWxsbmFtZSA9IGYie3IuZGJfbmFtZX0ue3Iuc2NoZW1hX25h
>> "%B64_FILE%" echo bWV9LntyLm5hbWV9IgogICAgICAgICAgICAgICAgZGVmbiA9IHIuZGVmaW5pdGlvbiBvciAiIgog
>> "%B64_FILE%" echo ICAgICAgICAgICAgICAgbG93ZXIgPSAoZnVsbG5hbWUgKyAiICIgKyBkZWZuKS5sb3dlcigpCiAg
>> "%B64_FILE%" echo ICAgICAgICAgICAgICBzY29yZSA9IHN1bSgxIGZvciBrdyBpbiBrZXl3b3JkcyBpZiBrdy5sb3dl
>> "%B64_FILE%" echo cigpIGluIGxvd2VyKQogICAgICAgICAgICAgICAgd3JpdGUoZiIgIHt0b3RhbDowM2R9LiB7ci50
>> "%B64_FILE%" echo eXBlX2Rlc2N9IHwge2Z1bGxuYW1lfSB8IHNjb3JlPXtzY29yZX0iKQogICAgICAgICAgICAgICAg
>> "%B64_FILE%" echo d3JpdGVfZmlsZShPVVRfT0JKRUNUUywgIj0iICogMTQwKQogICAgICAgICAgICAgICAgd3JpdGVf
>> "%B64_FILE%" echo ZmlsZShPVVRfT0JKRUNUUywgZiJ7dG90YWw6MDNkfS4ge3IudHlwZV9kZXNjfSB8IHtmdWxsbmFt
>> "%B64_FILE%" echo ZX0gfCBzY29yZT17c2NvcmV9IikKICAgICAgICAgICAgICAgIHdyaXRlX2ZpbGUoT1VUX09CSkVD
>> "%B64_FILE%" echo VFMsICItIiAqIDE0MCkKICAgICAgICAgICAgICAgIHdyaXRlX2ZpbGUoT1VUX09CSkVDVFMsIGRl
>> "%B64_FILE%" echo Zm4pCiAgICAgICAgICAgICAgICB3cml0ZV9maWxlKE9VVF9PQkpFQ1RTLCAiIikKICAgICAgICAg
>> "%B64_FILE%" echo ICAgY29ubi5jbG9zZSgpCiAgICAgICAgZXhjZXB0IEV4Y2VwdGlvbiBhcyBleGM6CiAgICAgICAg
>> "%B64_FILE%" echo ICAgIHdyaXRlKGYiREIge2RifTogbOG7l2kgdMOsbSBvYmplY3Q6IHtleGN9IikKICAgICAgICAg
>> "%B64_FILE%" echo ICAgbG9nX2Vycm9yKGYibGlzdF9tb2R1bGVzX2FsbF9kYnMgZGI9e2RifToge2V4Y30iKQoKICAg
>> "%B64_FILE%" echo IHdyaXRlKGYiVOG7lW5nIG9iamVjdCBsacOqbiBxdWFuOiB7dG90YWx9IikKICAgIHdyaXRlKCIi
>> "%B64_FILE%" echo KQoKCmRlZiBnZXRfY29sdW1ucyhjdXIpOgogICAgc3FsID0gIiIiCiAgICBTRUxFQ1QKICAgICAg
>> "%B64_FILE%" echo ICBjLlRBQkxFX1NDSEVNQSwKICAgICAgICBjLlRBQkxFX05BTUUsCiAgICAgICAgYy5DT0xVTU5f
>> "%B64_FILE%" echo TkFNRSwKICAgICAgICBjLkRBVEFfVFlQRQogICAgRlJPTSBJTkZPUk1BVElPTl9TQ0hFTUEuQ09M
>> "%B64_FILE%" echo VU1OUyBjCiAgICBJTk5FUiBKT0lOIElORk9STUFUSU9OX1NDSEVNQS5UQUJMRVMgdAogICAgICAg
>> "%B64_FILE%" echo IE9OIGMuVEFCTEVfU0NIRU1BID0gdC5UQUJMRV9TQ0hFTUEKICAgICAgIEFORCBjLlRBQkxFX05B
>> "%B64_FILE%" echo TUUgPSB0LlRBQkxFX05BTUUKICAgIFdIRVJFIHQuVEFCTEVfVFlQRSA9ICdCQVNFIFRBQkxFJwog
>> "%B64_FILE%" echo ICAgT1JERVIgQlkgYy5UQUJMRV9TQ0hFTUEsIGMuVEFCTEVfTkFNRSwgYy5PUkRJTkFMX1BPU0lU
>> "%B64_FILE%" echo SU9OCiAgICAiIiIKICAgIHJldHVybiBmZXRjaF9hbGwoY3VyLCBzcWwpCgoKZGVmIGRpcmVjdF9j
>> "%B64_FILE%" echo ZG90aGFuX2NoZWNrKCk6CiAgICB3cml0ZSgiQikgS0nhu4JNIFRSQSBUUuG7sEMgVEnhur5QIENE
>> "%B64_FILE%" echo T1RIQU4iKQogICAgd3JpdGUoIi0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
>> "%B64_FILE%" echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLSIpCiAgICB0cnk6CiAgICAgICAgY29ubiA9IGNvbm5lY3Qo
>> "%B64_FILE%" echo REVGQVVMVF9EQikKICAgICAgICBjdXIgPSBjb25uLmN1cnNvcigpCiAgICAgICAgc3FsID0gIiIi
>> "%B64_FILE%" echo CiAgICAgICAgU0VMRUNUIE5hbUhULCBUaGFuZ0hULCBNYUtobywgTWFUaGFuLCBTVU0oQ0FTVChU
>> "%B64_FILE%" echo b25DSyBBUyBGTE9BVCkpIEFTIFRvbkNLCiAgICAgICAgRlJPTSBkYm8uQ0RPVEhBTgogICAgICAg
>> "%B64_FILE%" echo IFdIRVJFIENBU1QoTWFLaG8gQVMgTlZBUkNIQVIoMTAwKSkgSU4gKE4nMScsIE4nMDEnLCBOJ0to
>> "%B64_FILE%" echo byAxJykKICAgICAgICBHUk9VUCBCWSBOYW1IVCwgVGhhbmdIVCwgTWFLaG8sIE1hVGhhbgogICAg
>> "%B64_FILE%" echo ICAgIE9SREVSIEJZIE5hbUhUIERFU0MsIFRoYW5nSFQgREVTQywgTWFUaGFuCiAgICAgICAgIiIi
>> "%B64_FILE%" echo CiAgICAgICAgcm93cyA9IGZldGNoX2FsbChjdXIsIHNxbCkKICAgICAgICBmb3IgciBpbiByb3dz
>> "%B64_FILE%" echo WzoyMF06CiAgICAgICAgICAgIHdyaXRlKGYiQ0RPVEhBTiB8IE5hbT17ci5OYW1IVH0gfCBUaGFu
>> "%B64_FILE%" echo Zz17ci5UaGFuZ0hUfSB8IE1hS2hvPXtyLk1hS2hvfSB8IE1hVGhhbj17ci5NYVRoYW59IHwgVG9u
>> "%B64_FILE%" echo Q0s9e2Zsb2F0KHIuVG9uQ0sgb3IgMCk6LC4yZn0iKQogICAgICAgIGNvbm4uY2xvc2UoKQogICAg
>> "%B64_FILE%" echo ZXhjZXB0IEV4Y2VwdGlvbiBhcyBleGM6CiAgICAgICAgd3JpdGUoIkzhu5dpIENET1RIQU46ICIg
>> "%B64_FILE%" echo KyBzdHIoZXhjKSkKICAgICAgICBsb2dfZXJyb3IoImRpcmVjdF9jZG90aGFuX2NoZWNrOiAiICsg
>> "%B64_FILE%" echo c3RyKGV4YykpCiAgICB3cml0ZSgiIikKCgpkZWYgc2Nhbl9zdW1zX2FsbF9kYnMoZGJzKToKICAg
>> "%B64_FILE%" echo IHdyaXRlKCJDKSBRVcOJVCBC4bqiTkcvQ+G7mFQgxJDhu4IgVMOMTSBDw5RORyBUSOG7qEMgS0jh
>> "%B64_FILE%" echo u5pQIFRUQ09fQVBQIikKICAgIHdyaXRlKCItLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
>> "%B64_FILE%" echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0iKQogICAgd3JpdGUoZiJN4bulYyB0acOqdSBU
>> "%B64_FILE%" echo VENPX0FQUCAgICAgICAgOiB7VEFSR0VUX0FQUDosLjJmfSIpCiAgICB3cml0ZShmIkNET1RIQU4g
>> "%B64_FILE%" echo dGjDoW5nIGhp4buHbiB04bqhaSAgIDoge0NET1RIQU5fTk9XOiwuMmZ9IikKICAgIHdyaXRlKGYi
>> "%B64_FILE%" echo Q0RPVEhBTiB0aMOhbmcgdHLGsOG7m2MgICAgICA6IHtDRE9USEFOX1BSRVY6LC4yZn0iKQogICAg
>> "%B64_FILE%" echo d3JpdGUoZiJDaMOqbmggduG7m2kgaGnhu4duIHThuqFpICAgICAgIDoge0RFTFRBX0ZST01fTk9X
>> "%B64_FILE%" echo OiwuMmZ9IikKICAgIHdyaXRlKGYiQ2jDqm5oIHbhu5tpIHRow6FuZyB0csaw4bubYyAgICA6IHtE
>> "%B64_FILE%" echo RUxUQV9GUk9NX1BSRVY6LC4yZn0iKQogICAgd3JpdGUoIiIpCgogICAga2hvX3JlID0gcmUuY29t
>> "%B64_FILE%" echo cGlsZShyIiheTWFLaG8kfF5LaG8kfEtob3xNYV9LaG98SURLaG98S2hvSUR8TWFEVnxNYURvblZp
>> "%B64_FILE%" echo KSIsIHJlLkkpCiAgICB2YWxfcmUgPSByZS5jb21waWxlKHIiKFRvbnxLbGd8S0x8S2hvaUx1b25n
>> "%B64_FILE%" echo fEx1b25nfFRhbnxTTHxTb0x1b25nfEN1b2l8Q0t8RGF1fERLfE5oYXB8WHVhdHxUYW5nfEdpYW18
>> "%B64_FILE%" echo S2xnX1RhbikiLCByZS5JKQogICAgdGhhbl9yZSA9IHJlLmNvbXBpbGUociIoTWFUaGFufFRlblRo
>> "%B64_FILE%" echo YW58TG9haVRoYW58VGhhbikiLCByZS5JKQogICAgZGF0ZV9yZSA9IHJlLmNvbXBpbGUociIoTmFt
>> "%B64_FILE%" echo SFR8VGhhbmdIVHxOZ2F5SFR8TmdheXxOZ2F5Q1R8VGhhbmd8TmFtfENhfEtpcHxUdU5nYXl8RGVu
>> "%B64_FILE%" echo TmdheSkiLCByZS5JKQoKICAgIHJlc3VsdHMgPSBbXQogICAgZXJyb3JfY291bnQgPSAwCiAgICBz
>> "%B64_FILE%" echo Y2FuX2NvdW50ID0gMAoKICAgIGZvciBkYiBpbiBkYnM6CiAgICAgICAgdHJ5OgogICAgICAgICAg
>> "%B64_FILE%" echo ICBjb25uID0gY29ubmVjdChkYikKICAgICAgICAgICAgY3VyID0gY29ubi5jdXJzb3IoKQogICAg
>> "%B64_FILE%" echo ICAgICAgICBjb2xzID0gZ2V0X2NvbHVtbnMoY3VyKQogICAgICAgIGV4Y2VwdCBFeGNlcHRpb24g
>> "%B64_FILE%" echo YXMgZXhjOgogICAgICAgICAgICBsb2dfZXJyb3IoZiJnZXRfY29sdW1ucyBkYj17ZGJ9OiB7ZXhj
>> "%B64_FILE%" echo fSIpCiAgICAgICAgICAgIGNvbnRpbnVlCgogICAgICAgIHRhYmxlcyA9IHt9CiAgICAgICAgZm9y
>> "%B64_FILE%" echo IHNjaGVtYSwgdGFibGUsIGNvbCwgZHR5cGUgaW4gY29sczoKICAgICAgICAgICAgdGFibGVzLnNl
>> "%B64_FILE%" echo dGRlZmF1bHQoKHNjaGVtYSwgdGFibGUpLCBbXSkuYXBwZW5kKChjb2wsIGR0eXBlKSkKCiAgICAg
>> "%B64_FILE%" echo ICAgIyBHaGkgc2NoZW1hIGPDoWMgYuG6o25nIGPDsyBsacOqbiBxdWFuIMSR4buDIMSR4buNYyB0
>> "%B64_FILE%" echo aOG7pyBjw7RuZy4KICAgICAgICBmb3IgKHNjaGVtYSwgdGFibGUpLCB0YWJsZV9jb2xzIGluIHRh
>> "%B64_FILE%" echo Ymxlcy5pdGVtcygpOgogICAgICAgICAgICB0YWJsZV9uYW1lX2xvd2VyID0gdGFibGUubG93ZXIo
>> "%B64_FILE%" echo KQogICAgICAgICAgICBpbnRlcmVzdGluZ190YWJsZSA9IGFueShrIGluIHRhYmxlX25hbWVfbG93
>> "%B64_FILE%" echo ZXIgZm9yIGsgaW4gWwogICAgICAgICAgICAgICAgInRoYW4iLCAia2hvIiwgImdpYW8iLCAibmhh
>> "%B64_FILE%" echo cCIsICJ4dWF0IiwgImNkb3RoYW4iLCAia3FzeCIsICJ0ayIsICJ0bXAiCiAgICAgICAgICAgIF0p
>> "%B64_FILE%" echo CiAgICAgICAgICAgIGhhc19raG8gPSBhbnkoa2hvX3JlLnNlYXJjaChjKSBmb3IgYywgXyBpbiB0
>> "%B64_FILE%" echo YWJsZV9jb2xzKQogICAgICAgICAgICBoYXNfdmFsID0gYW55KGlzX251bWVyaWNfdHlwZSh0KSBh
>> "%B64_FILE%" echo bmQgdmFsX3JlLnNlYXJjaChjKSBmb3IgYywgdCBpbiB0YWJsZV9jb2xzKQogICAgICAgICAgICBp
>> "%B64_FILE%" echo ZiBpbnRlcmVzdGluZ190YWJsZSBvciAoaGFzX2tobyBhbmQgaGFzX3ZhbCk6CiAgICAgICAgICAg
>> "%B64_FILE%" echo ICAgICB3cml0ZV9maWxlKE9VVF9TQ0hFTUEsICI9IiAqIDEyMCkKICAgICAgICAgICAgICAgIHdy
>> "%B64_FILE%" echo aXRlX2ZpbGUoT1VUX1NDSEVNQSwgZiJ7ZGJ9LntzY2hlbWF9Lnt0YWJsZX0iKQogICAgICAgICAg
>> "%B64_FILE%" echo ICAgICAgd3JpdGVfZmlsZShPVVRfU0NIRU1BLCAiLSIgKiAxMjApCiAgICAgICAgICAgICAgICBm
>> "%B64_FILE%" echo b3IgYywgdCBpbiB0YWJsZV9jb2xzOgogICAgICAgICAgICAgICAgICAgIHdyaXRlX2ZpbGUoT1VU
>> "%B64_FILE%" echo X1NDSEVNQSwgZiJ7Y30gfCB7dH0iKQogICAgICAgICAgICAgICAgd3JpdGVfZmlsZShPVVRfU0NI
>> "%B64_FILE%" echo RU1BLCAiIikKCiAgICAgICAgZm9yIChzY2hlbWEsIHRhYmxlKSwgdGFibGVfY29scyBpbiB0YWJs
>> "%B64_FILE%" echo ZXMuaXRlbXMoKToKICAgICAgICAgICAgY29sX25hbWVzID0gW2MgZm9yIGMsIF8gaW4gdGFibGVf
>> "%B64_FILE%" echo Y29sc10KICAgICAgICAgICAga2hvX2NvbHMgPSBbYyBmb3IgYyBpbiBjb2xfbmFtZXMgaWYga2hv
>> "%B64_FILE%" echo X3JlLnNlYXJjaChjKV0KICAgICAgICAgICAgdmFsX2NvbHMgPSBbYyBmb3IgYywgdCBpbiB0YWJs
>> "%B64_FILE%" echo ZV9jb2xzIGlmIGlzX251bWVyaWNfdHlwZSh0KSBhbmQgdmFsX3JlLnNlYXJjaChjKV0KICAgICAg
>> "%B64_FILE%" echo ICAgICAgdGhhbl9jb2xzID0gW2MgZm9yIGMgaW4gY29sX25hbWVzIGlmIHRoYW5fcmUuc2VhcmNo
>> "%B64_FILE%" echo KGMpXQogICAgICAgICAgICBkYXRlX2NvbHMgPSBbYyBmb3IgYyBpbiBjb2xfbmFtZXMgaWYgZGF0
>> "%B64_FILE%" echo ZV9yZS5zZWFyY2goYyldCgogICAgICAgICAgICBpZiBub3Qga2hvX2NvbHMgb3Igbm90IHZhbF9j
>> "%B64_FILE%" echo b2xzOgogICAgICAgICAgICAgICAgY29udGludWUKCiAgICAgICAgICAgICMgxq91IHRpw6puIGPD
>> "%B64_FILE%" echo oWMgYuG6o25nIGPDsyB0w6puIGxpw6puIHF1YW4uCiAgICAgICAgICAgIHRhYmxlX3ByaW9yaXR5
>> "%B64_FILE%" echo ID0gYW55KGsgaW4gdGFibGUubG93ZXIoKSBmb3IgayBpbiBbInRoYW4iLCAia2hvIiwgIm5oYXAi
>> "%B64_FILE%" echo LCAieHVhdCIsICJnaWFvIiwgImNkb3RoYW4iLCAia3FzeCIsICJ0bXAiXSkKICAgICAgICAgICAg
>> "%B64_FILE%" echo bWF4X3ZhbF9jb2xzID0gNDAgaWYgdGFibGVfcHJpb3JpdHkgZWxzZSAxMgoKICAgICAgICAgICAg
>> "%B64_FILE%" echo Zm9yIGtob19jb2wgaW4ga2hvX2NvbHNbOjVdOgogICAgICAgICAgICAgICAga2hvX2V4cHIgPSBm
>> "%B64_FILE%" echo IkNBU1Qoe3FpZGVudChraG9fY29sKX0gQVMgTlZBUkNIQVIoMTAwKSkiCiAgICAgICAgICAgICAg
>> "%B64_FILE%" echo ICBraG9fZmlsdGVyID0gZiJ7a2hvX2V4cHJ9IElOIChOJzEnLCBOJzAxJywgTidLaG8gMScpIgoK
>> "%B64_FILE%" echo ICAgICAgICAgICAgICAgIGZpbHRlcnMgPSBbKCJhbGwiLCBraG9fZmlsdGVyKV0KCiAgICAgICAg
>> "%B64_FILE%" echo ICAgICAgICBpZiAiTmFtSFQiIGluIGNvbF9uYW1lcyBhbmQgIlRoYW5nSFQiIGluIGNvbF9uYW1l
>> "%B64_FILE%" echo czoKICAgICAgICAgICAgICAgICAgICBmaWx0ZXJzLmFwcGVuZCgoIk5hbUhUPTIwMjYgVGhhbmdI
>> "%B64_FILE%" echo VD01Iiwga2hvX2ZpbHRlciArICIgQU5EIFtOYW1IVF09MjAyNiBBTkQgW1RoYW5nSFRdPTUiKSkK
>> "%B64_FILE%" echo ICAgICAgICAgICAgICAgICAgICBmaWx0ZXJzLmFwcGVuZCgoIk5hbUhUPTIwMjYiLCBraG9fZmls
>> "%B64_FILE%" echo dGVyICsgIiBBTkQgW05hbUhUXT0yMDI2IikpCgogICAgICAgICAgICAgICAgZm9yIHZhbF9jb2wg
>> "%B64_FILE%" echo aW4gdmFsX2NvbHNbOm1heF92YWxfY29sc106CiAgICAgICAgICAgICAgICAgICAgdmFsX2V4cHIg
>> "%B64_FILE%" echo PSBmIkNBU1Qoe3FpZGVudCh2YWxfY29sKX0gQVMgRkxPQVQpIgoKICAgICAgICAgICAgICAgICAg
>> "%B64_FILE%" echo ICBmb3IgZmlsdGVyX25hbWUsIHdoZXJlX3NxbCBpbiBmaWx0ZXJzOgogICAgICAgICAgICAgICAg
>> "%B64_FILE%" echo ICAgICAgICBzY2FuX2NvdW50ICs9IDEKICAgICAgICAgICAgICAgICAgICAgICAgdHJ5OgogICAg
>> "%B64_FILE%" echo ICAgICAgICAgICAgICAgICAgICAgICAgc3FsID0gKAogICAgICAgICAgICAgICAgICAgICAgICAg
>> "%B64_FILE%" echo ICAgICAgICJTRUxFQ1QgIgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIGYiU1VNKHt2
>> "%B64_FILE%" echo YWxfZXhwcn0pIEFTIFN1bVZhbHVlLCAiCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
>> "%B64_FILE%" echo IkNPVU5UKCopIEFTIFJvd0NvdW50LCAiCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
>> "%B64_FILE%" echo ZiJNSU4oe3ZhbF9leHByfSkgQVMgTWluVmFsdWUsICIKICAgICAgICAgICAgICAgICAgICAgICAg
>> "%B64_FILE%" echo ICAgICAgICBmIk1BWCh7dmFsX2V4cHJ9KSBBUyBNYXhWYWx1ZSAiCiAgICAgICAgICAgICAgICAg
>> "%B64_FILE%" echo ICAgICAgICAgICAgICAgZiJGUk9NIHtxaWRlbnQoc2NoZW1hKX0ue3FpZGVudCh0YWJsZSl9ICIK
>> "%B64_FILE%" echo ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICBmIldIRVJFIHt3aGVyZV9zcWx9IgogICAg
>> "%B64_FILE%" echo ICAgICAgICAgICAgICAgICAgICAgICAgKQogICAgICAgICAgICAgICAgICAgICAgICAgICAgcm93
>> "%B64_FILE%" echo ID0gY3VyLmV4ZWN1dGUoc3FsKS5mZXRjaG9uZSgpCiAgICAgICAgICAgICAgICAgICAgICAgICAg
>> "%B64_FILE%" echo ICBpZiBub3Qgcm93OgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIGNvbnRpbnVlCgog
>> "%B64_FILE%" echo ICAgICAgICAgICAgICAgICAgICAgICAgICAgdmFsID0gc2FmZV9mbG9hdChyb3cuU3VtVmFsdWUp
>> "%B64_FILE%" echo CiAgICAgICAgICAgICAgICAgICAgICAgICAgICBpZiB2YWwgaXMgTm9uZToKICAgICAgICAgICAg
>> "%B64_FILE%" echo ICAgICAgICAgICAgICAgICAgICBjb250aW51ZQoKICAgICAgICAgICAgICAgICAgICAgICAgICAg
>> "%B64_FILE%" echo IGRpZmZfYXBwID0gYWJzKHZhbCAtIFRBUkdFVF9BUFApCiAgICAgICAgICAgICAgICAgICAgICAg
>> "%B64_FILE%" echo ICAgICBkaWZmX25vdyA9IGFicyh2YWwgLSBERUxUQV9GUk9NX05PVykKICAgICAgICAgICAgICAg
>> "%B64_FILE%" echo ICAgICAgICAgICAgIGRpZmZfcHJldiA9IGFicyh2YWwgLSBERUxUQV9GUk9NX1BSRVYpCgogICAg
>> "%B64_FILE%" echo ICAgICAgICAgICAgICAgICAgICAgICAgZm9ybXVsYV9ub3cgPSBDRE9USEFOX05PVyArIHZhbAog
>> "%B64_FILE%" echo ICAgICAgICAgICAgICAgICAgICAgICAgICAgZm9ybXVsYV9wcmV2ID0gQ0RPVEhBTl9QUkVWICsg
>> "%B64_FILE%" echo dmFsCiAgICAgICAgICAgICAgICAgICAgICAgICAgICBkaWZmX2Zvcm11bGFfbm93ID0gYWJzKGZv
>> "%B64_FILE%" echo cm11bGFfbm93IC0gVEFSR0VUX0FQUCkKICAgICAgICAgICAgICAgICAgICAgICAgICAgIGRpZmZf
>> "%B64_FILE%" echo Zm9ybXVsYV9wcmV2ID0gYWJzKGZvcm11bGFfcHJldiAtIFRBUkdFVF9BUFApCgogICAgICAgICAg
>> "%B64_FILE%" echo ICAgICAgICAgICAgICAgICAga2VlcCA9IEZhbHNlCiAgICAgICAgICAgICAgICAgICAgICAgICAg
>> "%B64_FILE%" echo ICBpZiBkaWZmX2FwcCA8PSAxMDAwIG9yIGRpZmZfbm93IDw9IDEwMDAgb3IgZGlmZl9wcmV2IDw9
>> "%B64_FILE%" echo IDEwMDA6CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAga2VlcCA9IFRydWUKICAgICAg
>> "%B64_FILE%" echo ICAgICAgICAgICAgICAgICAgICAgIGlmIGRpZmZfZm9ybXVsYV9ub3cgPD0gMTAwMCBvciBkaWZm
>> "%B64_FILE%" echo X2Zvcm11bGFfcHJldiA8PSAxMDAwOgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIGtl
>> "%B64_FILE%" echo ZXAgPSBUcnVlCiAgICAgICAgICAgICAgICAgICAgICAgICAgICBpZiB0YWJsZV9wcmlvcml0eSBh
>> "%B64_FILE%" echo bmQgMCA8IGFicyh2YWwpIDwgMzAwMDAwOgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
>> "%B64_FILE%" echo IGtlZXAgPSBUcnVlCgogICAgICAgICAgICAgICAgICAgICAgICAgICAgaWYga2VlcDoKICAgICAg
>> "%B64_FILE%" echo ICAgICAgICAgICAgICAgICAgICAgICAgICByZXN1bHRzLmFwcGVuZCh7CiAgICAgICAgICAgICAg
>> "%B64_FILE%" echo ICAgICAgICAgICAgICAgICAgICAgICJkYiI6IGRiLAogICAgICAgICAgICAgICAgICAgICAgICAg
>> "%B64_FILE%" echo ICAgICAgICAgICAic2NoZW1hIjogc2NoZW1hLAogICAgICAgICAgICAgICAgICAgICAgICAgICAg
>> "%B64_FILE%" echo ICAgICAgICAidGFibGUiOiB0YWJsZSwKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
>> "%B64_FILE%" echo ICAgImZpbHRlciI6IGZpbHRlcl9uYW1lLAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
>> "%B64_FILE%" echo ICAgICAia2hvX2NvbCI6IGtob19jb2wsCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
>> "%B64_FILE%" echo ICAgICJ2YWx1ZV9jb2wiOiB2YWxfY29sLAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
>> "%B64_FILE%" echo ICAgICAic3VtX3ZhbHVlIjogdmFsLAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
>> "%B64_FILE%" echo ICAiZGlmZl90b19hcHAiOiBkaWZmX2FwcCwKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
>> "%B64_FILE%" echo ICAgICAgImRpZmZfdG9fZGVsdGFfbm93XzM4MF85MCI6IGRpZmZfbm93LAogICAgICAgICAgICAg
>> "%B64_FILE%" echo ICAgICAgICAgICAgICAgICAgICAgICAiZGlmZl90b19kZWx0YV9wcmV2XzU0Ml83MCI6IGRpZmZf
>> "%B64_FILE%" echo cHJldiwKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgImNkb3RoYW5fbm93X3Bs
>> "%B64_FILE%" echo dXNfdmFsdWUiOiBmb3JtdWxhX25vdywKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
>> "%B64_FILE%" echo ICAgImRpZmZfZm9ybXVsYV9ub3ciOiBkaWZmX2Zvcm11bGFfbm93LAogICAgICAgICAgICAgICAg
>> "%B64_FILE%" echo ICAgICAgICAgICAgICAgICAgICAiY2RvdGhhbl9wcmV2X3BsdXNfdmFsdWUiOiBmb3JtdWxhX3By
>> "%B64_FILE%" echo ZXYsCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICJkaWZmX2Zvcm11bGFfcHJl
>> "%B64_FILE%" echo diI6IGRpZmZfZm9ybXVsYV9wcmV2LAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
>> "%B64_FILE%" echo ICAidGhhbl9jb2xzIjogIiwiLmpvaW4odGhhbl9jb2xzWzo2XSksCiAgICAgICAgICAgICAgICAg
>> "%B64_FILE%" echo ICAgICAgICAgICAgICAgICAgICJkYXRlX2NvbHMiOiAiLCIuam9pbihkYXRlX2NvbHNbOjhdKSwK
>> "%B64_FILE%" echo ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIm5vdGUiOiBmInJvd3M9e3Jvdy5S
>> "%B64_FILE%" echo b3dDb3VudH07IG1pbj17c2FmZV9mbG9hdChyb3cuTWluVmFsdWUpfTsgbWF4PXtzYWZlX2Zsb2F0
>> "%B64_FILE%" echo KHJvdy5NYXhWYWx1ZSl9IiwKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICB9KQogICAg
>> "%B64_FILE%" echo ICAgICAgICAgICAgICAgICAgICBleGNlcHQgRXhjZXB0aW9uIGFzIGV4YzoKICAgICAgICAgICAg
>> "%B64_FILE%" echo ICAgICAgICAgICAgICAgIGVycm9yX2NvdW50ICs9IDEKICAgICAgICAgICAgICAgICAgICAgICAg
>> "%B64_FILE%" echo ICAgIGlmIGVycm9yX2NvdW50IDw9IDEyMDoKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
>> "%B64_FILE%" echo ICBsb2dfZXJyb3IoZiJTQ0FOIEVSUk9SIGRiPXtkYn0gdGFibGU9e3NjaGVtYX0ue3RhYmxlfSBr
>> "%B64_FILE%" echo aG89e2tob19jb2x9IHZhbD17dmFsX2NvbH0gZmlsdGVyPXtmaWx0ZXJfbmFtZX06IHtleGN9IikK
>> "%B64_FILE%" echo CiAgICAgICAgY29ubi5jbG9zZSgpCgogICAgd3JpdGUoZiJT4buRIHBow6lwIHF1w6l0OiB7c2Nh
>> "%B64_FILE%" echo bl9jb3VudH0iKQogICAgd3JpdGUoZiJT4buRIGzhu5dpIHF1w6l0OiB7ZXJyb3JfY291bnR9IikK
>> "%B64_FILE%" echo ICAgIHdyaXRlKGYiU+G7kSBr4bq/dCBxdeG6oyBsxrB1OiB7bGVuKHJlc3VsdHMpfSIpCiAgICB3
>> "%B64_FILE%" echo cml0ZSgiIikKCiAgICBkZWYgcHJpbnRfdG9wKHRpdGxlLCByb3dzLCBrZXksIGxpbWl0PTYwKToK
>> "%B64_FILE%" echo ICAgICAgICB3cml0ZSh0aXRsZSkKICAgICAgICB3cml0ZSgiLS0tLS0tLS0tLS0tLS0tLS0tLS0t
>> "%B64_FILE%" echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tIikKICAgICAgICBmb3IgaSwg
>> "%B64_FILE%" echo ciBpbiBlbnVtZXJhdGUoc29ydGVkKHJvd3MsIGtleT1rZXkpWzpsaW1pdF0sIHN0YXJ0PTEpOgog
>> "%B64_FILE%" echo ICAgICAgICAgICB3cml0ZSgKICAgICAgICAgICAgICAgIGYie2k6MDJkfS4ge3JbJ2RiJ119Lnty
>> "%B64_FILE%" echo WydzY2hlbWEnXX0ue3JbJ3RhYmxlJ119IHwgZmlsdGVyPXtyWydmaWx0ZXInXX0gfCAiCiAgICAg
>> "%B64_FILE%" echo ICAgICAgICAgICBmIntyWydraG9fY29sJ119IHwge3JbJ3ZhbHVlX2NvbCddfSBTVU09e3JbJ3N1
>> "%B64_FILE%" echo bV92YWx1ZSddOiwuMmZ9IHwgIgogICAgICAgICAgICAgICAgZiJkaWZmX2FwcD17clsnZGlmZl90
>> "%B64_FILE%" echo b19hcHAnXTosLjJmfSB8ICIKICAgICAgICAgICAgICAgIGYiZGlmZl8zODA9e3JbJ2RpZmZfdG9f
>> "%B64_FILE%" echo ZGVsdGFfbm93XzM4MF85MCddOiwuMmZ9IHwgIgogICAgICAgICAgICAgICAgZiJkaWZmXzU0Mj17
>> "%B64_FILE%" echo clsnZGlmZl90b19kZWx0YV9wcmV2XzU0Ml83MCddOiwuMmZ9IHwgIgogICAgICAgICAgICAgICAg
>> "%B64_FILE%" echo ZiJDRE9USEFOX25vdytTVU09e3JbJ2Nkb3RoYW5fbm93X3BsdXNfdmFsdWUnXTosLjJmfSBkaWZm
>> "%B64_FILE%" echo PXtyWydkaWZmX2Zvcm11bGFfbm93J106LC4yZn0gfCAiCiAgICAgICAgICAgICAgICBmIkNET1RI
>> "%B64_FILE%" echo QU5fcHJlditTVU09e3JbJ2Nkb3RoYW5fcHJldl9wbHVzX3ZhbHVlJ106LC4yZn0gZGlmZj17clsn
>> "%B64_FILE%" echo ZGlmZl9mb3JtdWxhX3ByZXYnXTosLjJmfSB8ICIKICAgICAgICAgICAgICAgIGYidGhhbl9jb2xz
>> "%B64_FILE%" echo PXtyWyd0aGFuX2NvbHMnXX0gfCBkYXRlX2NvbHM9e3JbJ2RhdGVfY29scyddfSB8IHtyWydub3Rl
>> "%B64_FILE%" echo J119IgogICAgICAgICAgICApCiAgICAgICAgd3JpdGUoIiIpCgogICAgcHJpbnRfdG9wKCJEKSBU
>> "%B64_FILE%" echo T1AgR+G6pk4gVFLhu7BDIFRJ4bq+UCAxLjA1Miw2NSIsIHJlc3VsdHMsIGxhbWJkYSB4OiB4WyJk
>> "%B64_FILE%" echo aWZmX3RvX2FwcCJdKQogICAgcHJpbnRfdG9wKCJFKSBUT1AgR+G6pk4gQ0jDik5IIDM4MCw5MCA9
>> "%B64_FILE%" echo IDEuMDUyLDY1IC0gNjcxLDc1IiwgcmVzdWx0cywgbGFtYmRhIHg6IHhbImRpZmZfdG9fZGVsdGFf
>> "%B64_FILE%" echo bm93XzM4MF85MCJdKQogICAgcHJpbnRfdG9wKCJGKSBUT1AgR+G6pk4gQ0jDik5IIDU0Miw3MCA9
>> "%B64_FILE%" echo IDEuMDUyLDY1IC0gNTA5LDk1IiwgcmVzdWx0cywgbGFtYmRhIHg6IHhbImRpZmZfdG9fZGVsdGFf
>> "%B64_FILE%" echo cHJldl81NDJfNzAiXSkKICAgIHByaW50X3RvcCgiRykgVE9QIEPDlE5HIFRI4buoQyBDRE9USEFO
>> "%B64_FILE%" echo IFRIw4FORyA1ICsgU1VNID0gMS4wNTIsNjUiLCByZXN1bHRzLCBsYW1iZGEgeDogeFsiZGlmZl9m
>> "%B64_FILE%" echo b3JtdWxhX25vdyJdKQogICAgcHJpbnRfdG9wKCJIKSBUT1AgQ8OUTkcgVEjhu6hDIENET1RIQU4g
>> "%B64_FILE%" echo VEjDgU5HIDQgKyBTVU0gPSAxLjA1Miw2NSIsIHJlc3VsdHMsIGxhbWJkYSB4OiB4WyJkaWZmX2Zv
>> "%B64_FILE%" echo cm11bGFfcHJldiJdKQoKICAgIHdpdGggT1VUX0NTVi5vcGVuKCJ3IiwgbmV3bGluZT0iIiwgZW5j
>> "%B64_FILE%" echo b2Rpbmc9InV0Zi04LXNpZyIpIGFzIGY6CiAgICAgICAgZmllbGRuYW1lcyA9IFsKICAgICAgICAg
>> "%B64_FILE%" echo ICAgImRiIiwgInNjaGVtYSIsICJ0YWJsZSIsICJmaWx0ZXIiLCAia2hvX2NvbCIsICJ2YWx1ZV9j
>> "%B64_FILE%" echo b2wiLCAic3VtX3ZhbHVlIiwKICAgICAgICAgICAgImRpZmZfdG9fYXBwIiwgImRpZmZfdG9fZGVs
>> "%B64_FILE%" echo dGFfbm93XzM4MF85MCIsICJkaWZmX3RvX2RlbHRhX3ByZXZfNTQyXzcwIiwKICAgICAgICAgICAg
>> "%B64_FILE%" echo ImNkb3RoYW5fbm93X3BsdXNfdmFsdWUiLCAiZGlmZl9mb3JtdWxhX25vdyIsCiAgICAgICAgICAg
>> "%B64_FILE%" echo ICJjZG90aGFuX3ByZXZfcGx1c192YWx1ZSIsICJkaWZmX2Zvcm11bGFfcHJldiIsCiAgICAgICAg
>> "%B64_FILE%" echo ICAgICJ0aGFuX2NvbHMiLCAiZGF0ZV9jb2xzIiwgIm5vdGUiCiAgICAgICAgXQogICAgICAgIHcg
>> "%B64_FILE%" echo PSBjc3YuRGljdFdyaXRlcihmLCBmaWVsZG5hbWVzPWZpZWxkbmFtZXMpCiAgICAgICAgdy53cml0
>> "%B64_FILE%" echo ZWhlYWRlcigpCiAgICAgICAgZm9yIHIgaW4gc29ydGVkKHJlc3VsdHMsIGtleT1sYW1iZGEgeDog
>> "%B64_FILE%" echo bWluKAogICAgICAgICAgICB4WyJkaWZmX3RvX2FwcCJdLAogICAgICAgICAgICB4WyJkaWZmX3Rv
>> "%B64_FILE%" echo X2RlbHRhX25vd18zODBfOTAiXSwKICAgICAgICAgICAgeFsiZGlmZl90b19kZWx0YV9wcmV2XzU0
>> "%B64_FILE%" echo Ml83MCJdLAogICAgICAgICAgICB4WyJkaWZmX2Zvcm11bGFfbm93Il0sCiAgICAgICAgICAgIHhb
>> "%B64_FILE%" echo ImRpZmZfZm9ybXVsYV9wcmV2Il0sCiAgICAgICAgKSk6CiAgICAgICAgICAgIHcud3JpdGVyb3co
>> "%B64_FILE%" echo cikKCgpkZWYgbWFpbigpOgogICAgd3JpdGUoIj09PT09PT09PT09PT09PT09PT09PT09PT09PT09
>> "%B64_FILE%" echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PSIpCiAgICB3cml0ZSgiVFRDTyAtIFTDjE0g
>> "%B64_FILE%" echo xJDDmk5HIE5HVeG7kk4gVOG7kk4gS0hPIFRUQ09fQVBQIC0gVjYiKQogICAgd3JpdGUoIj09PT09
>> "%B64_FILE%" echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PSIp
>> "%B64_FILE%" echo CiAgICB3cml0ZShmIlNlcnZlciAgICAgICA6IHtTRVJWRVJ9IikKICAgIHdyaXRlKGYiRGVmYXVs
>> "%B64_FILE%" echo dCBEQiAgIDoge0RFRkFVTFRfREJ9IikKICAgIHdyaXRlKGYiVFRDT19BUFAgICAgIDoge1RBUkdF
>> "%B64_FILE%" echo VF9BUFA6LC4yZn0iKQogICAgd3JpdGUoZiJDRE9USEFOIG5vdyAgOiB7Q0RPVEhBTl9OT1c6LC4y
>> "%B64_FILE%" echo Zn0iKQogICAgd3JpdGUoZiJDRE9USEFOIHByZXYgOiB7Q0RPVEhBTl9QUkVWOiwuMmZ9IikKICAg
>> "%B64_FILE%" echo IHdyaXRlKGYiRGVsdGEgbm93ICAgIDoge0RFTFRBX0ZST01fTk9XOiwuMmZ9IikKICAgIHdyaXRl
>> "%B64_FILE%" echo KGYiRGVsdGEgcHJldiAgIDoge0RFTFRBX0ZST01fUFJFVjosLjJmfSIpCiAgICB3cml0ZSgiIikK
>> "%B64_FILE%" echo ICAgIHdyaXRlKCJL4bq/dCBxdeG6ozoiKQogICAgd3JpdGUoZiJGb2xkZXIgOiB7T1VUX0RJUn0i
>> "%B64_FILE%" echo KQogICAgd3JpdGUoZiJUWFQgICAgOiB7T1VUX1RYVH0iKQogICAgd3JpdGUoZiJDU1YgICAgOiB7
>> "%B64_FILE%" echo T1VUX0NTVn0iKQogICAgd3JpdGUoZiJTY2hlbWEgOiB7T1VUX1NDSEVNQX0iKQogICAgd3JpdGUo
>> "%B64_FILE%" echo ZiJPYmplY3RzOiB7T1VUX09CSkVDVFN9IikKICAgIHdyaXRlKGYiRXJyb3JzIDoge09VVF9FUlJP
>> "%B64_FILE%" echo UlN9IikKICAgIHdyaXRlKCIiKQoKICAgIGVuc3VyZV9weW9kYmMoKQogICAgZGJzID0gZ2V0X2Fj
>> "%B64_FILE%" echo Y2Vzc2libGVfZGF0YWJhc2VzKCkKICAgIHdyaXRlKCJEQiB0cnV5IGPhuq1wIMSRxrDhu6NjOiAi
>> "%B64_FILE%" echo ICsgIiwgIi5qb2luKGRicykpCiAgICB3cml0ZSgiIikKCiAgICBsaXN0X21vZHVsZXNfYWxsX2Ri
>> "%B64_FILE%" echo cyhkYnMpCiAgICBkaXJlY3RfY2RvdGhhbl9jaGVjaygpCiAgICBzY2FuX3N1bXNfYWxsX2Ricyhk
>> "%B64_FILE%" echo YnMpCgogICAgd3JpdGUoIj09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
>> "%B64_FILE%" echo PT09PT09PT09PT09PT09PT09PSIpCiAgICB3cml0ZSgiSE/DgE4gVEjDgE5IIikKICAgIHdyaXRl
>> "%B64_FILE%" echo KCI9PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
>> "%B64_FILE%" echo PT09PT0iKQogICAgd3JpdGUoIkFuaCBn4butaSBs4bqhaSBmaWxlIFRYVCBjaMOtbmggdsOgIG7h
>> "%B64_FILE%" echo ur91IGPhuqduIGfhu61pIHRow6ptIGVycm9yc192NiDEkeG7gyB0w7RpIHPhu61hIGJhY2tlbmQv
>> "%B64_FILE%" echo c2VydmVyLnB5LiIpCiAgICB0cnk6CiAgICAgICAgc3VicHJvY2Vzcy5Qb3BlbihbImV4cGxvcmVy
>> "%B64_FILE%" echo LmV4ZSIsIHN0cihPVVRfRElSKV0pCiAgICBleGNlcHQgRXhjZXB0aW9uOgogICAgICAgIHBhc3MK
>> "%B64_FILE%" echo CgppZiBfX25hbWVfXyA9PSAiX19tYWluX18iOgogICAgdHJ5OgogICAgICAgIG1haW4oKQogICAg
>> "%B64_FILE%" echo ZXhjZXB0IEV4Y2VwdGlvbiBhcyBleGM6CiAgICAgICAgd3JpdGUoIiIpCiAgICAgICAgd3JpdGUo
>> "%B64_FILE%" echo IltM4buWSV0gIiArIHN0cihleGMpKQogICAgICAgIHdyaXRlKCJH4butaSBs4bqhaSBmaWxlIFRY
>> "%B64_FILE%" echo VC9lcnJvcnMgxJHhu4Mga2nhu4NtIHRyYSB0aeG6v3AuIikKICAgICAgICB0cnk6CiAgICAgICAg
>> "%B64_FILE%" echo ICAgIHN1YnByb2Nlc3MuUG9wZW4oWyJleHBsb3Jlci5leGUiLCBzdHIoT1VUX0RJUildKQogICAg
>> "%B64_FILE%" echo ICAgIGV4Y2VwdCBFeGNlcHRpb246CiAgICAgICAgICAgIHBhc3MKICAgICAgICBzeXMuZXhpdCgx
>> "%B64_FILE%" echo KQo=
python -c "import base64, pathlib, os; b=pathlib.Path(os.environ['B64_FILE']).read_text().replace('\n','').replace('\r','').strip(); pathlib.Path(os.environ['PY_FILE']).write_bytes(base64.b64decode(b))"
if errorlevel 1 (
    echo [LOI] Khong tao duoc file Python tam.
    pause
    exit /b 1
)

python "%PY_FILE%"
echo.
echo Ket qua nam tai:
echo %USERPROFILE%\Desktop\TTCO_FIND_TRUE_TONKHO_SOURCE
echo.
start "" "%USERPROFILE%\Desktop\TTCO_FIND_TRUE_TONKHO_SOURCE"
pause
