@echo off
setlocal EnableExtensions EnableDelayedExpansion
chcp 65001 >nul
title TTCO Direct DB To GitHub - v21

set "CONFIG_DIR=%LOCALAPPDATA%\TTCO_TonKho_DirectDB_V21"
set "PY_MAIN=%CONFIG_DIR%\TTCO_DirectDB_To_GitHub_v21.py"
set "B64_FILE=%CONFIG_DIR%\TTCO_DirectDB_To_GitHub_v21.b64"

if not exist "%CONFIG_DIR%" mkdir "%CONFIG_DIR%" >nul 2>&1

call :WRITE_PY
if errorlevel 1 (
    echo [LOI] Khong tao duoc file Python tam.
    pause
    exit /b 1
)

if /I "%~1"=="--auto" (
    python "%PY_MAIN%" --action update --bat "%~f0"
    exit /b %errorlevel%
)

:MENU
cls
echo ============================================================
echo      TTCO - DO TRUC TIEP DU LIEU TU DB LEN GITHUB v21
echo ============================================================
echo Sua loi v19:
echo   v19 bi thieu TonDK nen Kho 1 chi ra 542,70.
echo   v21 lay TonDK tu CDOTHAN thang truoc.
echo.
echo Cong thuc v21:
echo   TonCK = TonDK thang truoc + NhapTK thang hien tai - XuatTK thang hien tai
echo.
echo  [1] Kiem tra truc tiep DB thang hien tai, chua up GitHub
echo.
echo  [2] Cap nhat GitHub truc tiep DB thang hien tai
echo.
echo  [3] Kiem tra truc tiep DB thang tuy chon, chua up GitHub
echo.
echo  [4] Cap nhat GitHub truc tiep DB thang tuy chon
echo.
echo  [5] Chon lai thu muc repo GitHub my-ai-site
echo.
echo  [6] Cai dat tu dong khi dang nhap Windows
echo.
echo  [7] Mo file log
echo.
echo  [0] Thoat
echo.
echo ============================================================
choice /C 12345670 /N /M "Chon chuc nang [1/2/3/4/5/6/7/0]: "

if errorlevel 8 exit /b 0
if errorlevel 7 (
    python "%PY_MAIN%" --action open-log --bat "%~f0"
    goto MENU
)
if errorlevel 6 (
    python "%PY_MAIN%" --action install --bat "%~f0"
    pause
    goto MENU
)
if errorlevel 5 (
    python "%PY_MAIN%" --action config-repo --bat "%~f0"
    pause
    goto MENU
)
if errorlevel 4 (
    python "%PY_MAIN%" --action update-custom --bat "%~f0"
    pause
    goto MENU
)
if errorlevel 3 (
    python "%PY_MAIN%" --action check-custom --bat "%~f0"
    pause
    goto MENU
)
if errorlevel 2 (
    python "%PY_MAIN%" --action update --bat "%~f0"
    pause
    goto MENU
)
if errorlevel 1 (
    python "%PY_MAIN%" --action check --bat "%~f0"
    pause
    goto MENU
)

goto MENU

:WRITE_PY
> "%B64_FILE%" echo CiMgLSotIGNvZGluZzogdXRmLTggLSotCmltcG9ydCBhcmdwYXJzZQppbXBvcnQganNvbgppbXBv
>> "%B64_FILE%" echo cnQgb3MKaW1wb3J0IHJlCmltcG9ydCBzdWJwcm9jZXNzCmltcG9ydCBzeXMKZnJvbSBkYXRldGlt
>> "%B64_FILE%" echo ZSBpbXBvcnQgZGF0ZXRpbWUKZnJvbSBwYXRobGliIGltcG9ydCBQYXRoCgpTRVJWRVIgPSByInR1
>> "%B64_FILE%" echo eWVudGhhbmN1YW9uZy5jb20udm4sNTIzNzYiCkRBVEFCQVNFID0gIlRUQ09fVEhPTkdLRSIKTUFT
>> "%B64_FILE%" echo VEVSX0RCID0gIlRUQ09fUVRIVCIKClJFUE9fVVJMID0gImh0dHBzOi8vZ2l0aHViLmNvbS90dXll
>> "%B64_FILE%" echo bjExMDIvbXktYWktc2l0ZS5naXQiCkJSQU5DSCA9ICJtYWluIgpKU09OX1JFTCA9IG9zLnBhdGgu
>> "%B64_FILE%" echo am9pbigicHVibGljIiwgImRhdGEiLCAidG9uX2tob19sYXRlc3QuanNvbiIpClRBU0tfTkFNRSA9
>> "%B64_FILE%" echo ICJUVENPX1Rvbktob19EaXJlY3REQl9WMjFfT25Mb2dvbiIKCkNPTkZJR19ESVIgPSBQYXRoKG9z
>> "%B64_FILE%" echo LmVudmlyb24uZ2V0KCJMT0NBTEFQUERBVEEiLCBzdHIoUGF0aC5ob21lKCkpKSkgLyAiVFRDT19U
>> "%B64_FILE%" echo b25LaG9fRGlyZWN0REJfVjIxIgpDT05GSUdfRklMRSA9IENPTkZJR19ESVIgLyAiY29uZmlnLmpz
>> "%B64_FILE%" echo b24iCkxPR19GSUxFID0gQ09ORklHX0RJUiAvICJUVENPX0RpcmVjdERCX1YyMS5sb2ciCgpERVNL
>> "%B64_FILE%" echo VE9QID0gUGF0aChvcy5lbnZpcm9uLmdldCgiVVNFUlBST0ZJTEUiLCBzdHIoUGF0aC5ob21lKCkp
>> "%B64_FILE%" echo KSkgLyAiRGVza3RvcCIKQ0hFQ0tfRElSID0gREVTS1RPUCAvICJUVENPX0RJUkVDVF9EQl9DSEVD
>> "%B64_FILE%" echo S19WMjEiCgoKZGVmIGxvZyhtc2c6IHN0cikgLT4gTm9uZToKICAgIENPTkZJR19ESVIubWtkaXIo
>> "%B64_FILE%" echo cGFyZW50cz1UcnVlLCBleGlzdF9vaz1UcnVlKQogICAgd2l0aCBMT0dfRklMRS5vcGVuKCJhIiwg
>> "%B64_FILE%" echo ZW5jb2Rpbmc9InV0Zi04IikgYXMgZjoKICAgICAgICBmLndyaXRlKGYiW3tkYXRldGltZS5ub3co
>> "%B64_FILE%" echo KTolWS0lbS0lZCAlSDolTTolU31dIHttc2d9XG4iKQoKCmRlZiBydW4oY21kLCBjd2Q9Tm9uZSwg
>> "%B64_FILE%" echo Y2hlY2s9VHJ1ZSk6CiAgICBwcmludCgiXG4+ICIgKyAiICIuam9pbihjbWQpLCBmbHVzaD1UcnVl
>> "%B64_FILE%" echo KQogICAgcCA9IHN1YnByb2Nlc3MucnVuKGNtZCwgY3dkPWN3ZCkKICAgIGlmIGNoZWNrIGFuZCBw
>> "%B64_FILE%" echo LnJldHVybmNvZGUgIT0gMDoKICAgICAgICByYWlzZSBSdW50aW1lRXJyb3IoZiJM4buHbmggbOG7
>> "%B64_FILE%" echo l2kgbcOjIHtwLnJldHVybmNvZGV9OiB7JyAnLmpvaW4oY21kKX0iKQogICAgcmV0dXJuIHAucmV0
>> "%B64_FILE%" echo dXJuY29kZQoKCmRlZiBlbnN1cmVfcHlvZGJjKCk6CiAgICB0cnk6CiAgICAgICAgaW1wb3J0IHB5
>> "%B64_FILE%" echo b2RiYyAgIyBub3FhCiAgICAgICAgcmV0dXJuCiAgICBleGNlcHQgRXhjZXB0aW9uOgogICAgICAg
>> "%B64_FILE%" echo IHByaW50KCJbSU5GT10gQ2jGsGEgY8OzIHB5b2RiYy4gxJBhbmcgY8OgaSBweW9kYmMuLi4iLCBm
>> "%B64_FILE%" echo bHVzaD1UcnVlKQogICAgICAgIHN1YnByb2Nlc3MuY2hlY2tfY2FsbChbc3lzLmV4ZWN1dGFibGUs
>> "%B64_FILE%" echo ICItbSIsICJwaXAiLCAiaW5zdGFsbCIsICJweW9kYmMiXSkKCgpkZWYgY29ubmVjdChkYj1EQVRB
>> "%B64_FILE%" echo QkFTRSk6CiAgICBpbXBvcnQgcHlvZGJjCiAgICBjb25uX3N0ciA9ICgKICAgICAgICAiRFJJVkVS
>> "%B64_FILE%" echo PXtPREJDIERyaXZlciAxOCBmb3IgU1FMIFNlcnZlcn07IgogICAgICAgIGYiU0VSVkVSPXtTRVJW
>> "%B64_FILE%" echo RVJ9OyIKICAgICAgICBmIkRBVEFCQVNFPXtkYn07IgogICAgICAgICJUcnVzdGVkX0Nvbm5lY3Rp
>> "%B64_FILE%" echo b249eWVzOyIKICAgICAgICAiVHJ1c3RTZXJ2ZXJDZXJ0aWZpY2F0ZT15ZXM7IgogICAgKQogICAg
>> "%B64_FILE%" echo cmV0dXJuIHB5b2RiYy5jb25uZWN0KGNvbm5fc3RyLCB0aW1lb3V0PTMwLCBhdXRvY29tbWl0PVRy
>> "%B64_FILE%" echo dWUpCgoKZGVmIHFpZGVudChuYW1lOiBzdHIpIC0+IHN0cjoKICAgIHJldHVybiAiWyIgKyBzdHIo
>> "%B64_FILE%" echo bmFtZSkucmVwbGFjZSgiXSIsICJdXSIpICsgIl0iCgoKZGVmIG5vcm1hbGl6ZV90ZXh0KHYpOgog
>> "%B64_FILE%" echo ICAgaWYgdiBpcyBOb25lOgogICAgICAgIHJldHVybiAiIgogICAgcmV0dXJuIHJlLnN1YihyIlxz
>> "%B64_FILE%" echo KyIsICIgIiwgc3RyKHYpLnJlcGxhY2UoIlx4YTAiLCAiICIpLnN0cmlwKCkpCgoKZGVmIG5vcm1h
>> "%B64_FILE%" echo bGl6ZV9jb2FsX25hbWUodik6CiAgICBzID0gbm9ybWFsaXplX3RleHQodikKICAgIHMgPSByZS5z
>> "%B64_FILE%" echo dWIociIoP2kpXGIxY1xiIiwgIjFDIiwgcykKICAgIHMgPSByZS5zdWIociIoP2kpXGI4Y1xiIiwg
>> "%B64_FILE%" echo IjhDIiwgcykKICAgIHJldHVybiBzCgoKZGVmIGNsZWFuX251bWJlcih2KToKICAgIHRyeToKICAg
>> "%B64_FILE%" echo ICAgICByZXR1cm4gZmxvYXQodiBvciAwKQogICAgZXhjZXB0IEV4Y2VwdGlvbjoKICAgICAgICBy
>> "%B64_FILE%" echo ZXR1cm4gMC4wCgoKZGVmIGtob19zb3J0X2tleSh0ZW5fa2hvLCBtYV9raG8pOgogICAgdGV4dCA9
>> "%B64_FILE%" echo IHRlbl9raG8gb3IgbWFfa2hvIG9yICIiCiAgICBtID0gcmUuc2VhcmNoKHIiKFxkKykiLCB0ZXh0
>> "%B64_FILE%" echo KQogICAgbiA9IGludChtLmdyb3VwKDEpKSBpZiBtIGVsc2UgOTk5OQogICAgdDQgPSAxIGlmICJU
>> "%B64_FILE%" echo NCIgaW4gdGV4dC51cHBlcigpIGVsc2UgMAogICAgcmV0dXJuIChuLCB0NCwgdGV4dCkKCgpkZWYg
>> "%B64_FILE%" echo cHJldmlvdXNfcGVyaW9kKHllYXIsIG1vbnRoKToKICAgIHllYXIgPSBpbnQoeWVhcikKICAgIG1v
>> "%B64_FILE%" echo bnRoID0gaW50KG1vbnRoKQogICAgaWYgbW9udGggPT0gMToKICAgICAgICByZXR1cm4geWVhciAt
>> "%B64_FILE%" echo IDEsIDEyCiAgICByZXR1cm4geWVhciwgbW9udGggLSAxCgoKZGVmIGxvYWRfY29uZmlnKCk6CiAg
>> "%B64_FILE%" echo ICBDT05GSUdfRElSLm1rZGlyKHBhcmVudHM9VHJ1ZSwgZXhpc3Rfb2s9VHJ1ZSkKICAgIGlmIENP
>> "%B64_FILE%" echo TkZJR19GSUxFLmV4aXN0cygpOgogICAgICAgIHRyeToKICAgICAgICAgICAgcmV0dXJuIGpzb24u
>> "%B64_FILE%" echo bG9hZHMoQ09ORklHX0ZJTEUucmVhZF90ZXh0KGVuY29kaW5nPSJ1dGYtOCIpKQogICAgICAgIGV4
>> "%B64_FILE%" echo Y2VwdCBFeGNlcHRpb246CiAgICAgICAgICAgIHBhc3MKICAgIHJldHVybiB7InJlcG9fZGlyIjog
>> "%B64_FILE%" echo ciJEOlxUVENPX1Rvbktob19BcHBfUmVwbyJ9CgoKZGVmIHNhdmVfY29uZmlnKGNmZyk6CiAgICBD
>> "%B64_FILE%" echo T05GSUdfRElSLm1rZGlyKHBhcmVudHM9VHJ1ZSwgZXhpc3Rfb2s9VHJ1ZSkKICAgIENPTkZJR19G
>> "%B64_FILE%" echo SUxFLndyaXRlX3RleHQoanNvbi5kdW1wcyhjZmcsIGVuc3VyZV9hc2NpaT1GYWxzZSwgaW5kZW50
>> "%B64_FILE%" echo PTIpLCBlbmNvZGluZz0idXRmLTgiKQogICAgbG9nKGYiU0FWRV9DT05GSUcge2NmZ30iKQoKCmRl
>> "%B64_FILE%" echo ZiBwaWNrX2ZvbGRlcih0aXRsZTogc3RyLCBpbml0aWFsOiBzdHIgPSAiIikgLT4gc3RyOgogICAg
>> "%B64_FILE%" echo dHJ5OgogICAgICAgIGltcG9ydCB0a2ludGVyIGFzIHRrCiAgICAgICAgZnJvbSB0a2ludGVyIGlt
>> "%B64_FILE%" echo cG9ydCBmaWxlZGlhbG9nCiAgICAgICAgcm9vdCA9IHRrLlRrKCkKICAgICAgICByb290LndpdGhk
>> "%B64_FILE%" echo cmF3KCkKICAgICAgICByb290LmF0dHJpYnV0ZXMoIi10b3Btb3N0IiwgVHJ1ZSkKICAgICAgICBp
>> "%B64_FILE%" echo ZiBub3QgaW5pdGlhbCBvciBub3Qgb3MucGF0aC5pc2Rpcihpbml0aWFsKToKICAgICAgICAgICAg
>> "%B64_FILE%" echo aW5pdGlhbCA9IHIiRDpcVFRDT19Ub25LaG9fQXBwX1JlcG8iIGlmIG9zLnBhdGguaXNkaXIociJE
>> "%B64_FILE%" echo OlxUVENPX1Rvbktob19BcHBfUmVwbyIpIGVsc2Ugc3RyKFBhdGguaG9tZSgpKQogICAgICAgIGZv
>> "%B64_FILE%" echo bGRlciA9IGZpbGVkaWFsb2cuYXNrZGlyZWN0b3J5KHRpdGxlPXRpdGxlLCBpbml0aWFsZGlyPWlu
>> "%B64_FILE%" echo aXRpYWwsIG11c3RleGlzdD1GYWxzZSkKICAgICAgICByb290LmRlc3Ryb3koKQogICAgICAgIHJl
>> "%B64_FILE%" echo dHVybiBmb2xkZXIgb3IgIiIKICAgIGV4Y2VwdCBFeGNlcHRpb24gYXMgZXhjOgogICAgICAgIHBy
>> "%B64_FILE%" echo aW50KGYiW0PhuqJOSCBCw4FPXSBLaMO0bmcgbeG7nyDEkcaw4bujYyBwb3B1cCBjaOG7jW4gdGjG
>> "%B64_FILE%" echo sCBt4bulYzoge2V4Y30iLCBmbHVzaD1UcnVlKQogICAgICAgIHJldHVybiBpbnB1dCgiTmjhuq1w
>> "%B64_FILE%" echo IMSRxrDhu51uZyBk4bqrbiB0aMawIG3hu6VjIHJlcG86ICIpLnN0cmlwKCkuc3RyaXAoJyInKQoK
>> "%B64_FILE%" echo CmRlZiBjb21tYW5kX2V4aXN0cyhuYW1lOiBzdHIpIC0+IGJvb2w6CiAgICB0cnk6CiAgICAgICAg
>> "%B64_FILE%" echo c3VicHJvY2Vzcy5ydW4oW25hbWUsICItLXZlcnNpb24iXSwgc3Rkb3V0PXN1YnByb2Nlc3MuREVW
>> "%B64_FILE%" echo TlVMTCwgc3RkZXJyPXN1YnByb2Nlc3MuREVWTlVMTCkKICAgICAgICByZXR1cm4gVHJ1ZQogICAg
>> "%B64_FILE%" echo ZXhjZXB0IEV4Y2VwdGlvbjoKICAgICAgICByZXR1cm4gRmFsc2UKCgpkZWYgZW5zdXJlX2dpdCgp
>> "%B64_FILE%" echo IC0+IE5vbmU6CiAgICBpZiBjb21tYW5kX2V4aXN0cygiZ2l0Iik6CiAgICAgICAgcmV0dXJuCiAg
>> "%B64_FILE%" echo ICBwcmludCgiW0PhuqJOSCBCw4FPXSBLaMO0bmcgdMOsbSB0aOG6pXkgR2l0LiDEkGFuZyB0aOG7
>> "%B64_FILE%" echo rSBjw6BpIEdpdCBi4bqxbmcgd2luZ2V0Li4uIiwgZmx1c2g9VHJ1ZSkKICAgIGlmIGNvbW1hbmRf
>> "%B64_FILE%" echo ZXhpc3RzKCJ3aW5nZXQiKToKICAgICAgICBzdWJwcm9jZXNzLnJ1bihbCiAgICAgICAgICAgICJ3
>> "%B64_FILE%" echo aW5nZXQiLCAiaW5zdGFsbCIsICItLWlkIiwgIkdpdC5HaXQiLCAiLWUiLCAiLS1zb3VyY2UiLCAi
>> "%B64_FILE%" echo d2luZ2V0IiwKICAgICAgICAgICAgIi0tc2lsZW50IiwgIi0tYWNjZXB0LXBhY2thZ2UtYWdyZWVt
>> "%B64_FILE%" echo ZW50cyIsICItLWFjY2VwdC1zb3VyY2UtYWdyZWVtZW50cyIKICAgICAgICBdKQogICAgaWYgbm90
>> "%B64_FILE%" echo IGNvbW1hbmRfZXhpc3RzKCJnaXQiKToKICAgICAgICByYWlzZSBSdW50aW1lRXJyb3IoIktow7Ru
>> "%B64_FILE%" echo ZyB0w6xtIHRo4bqleSBHaXQuIEjDo3kgY8OgaSBHaXQgZm9yIFdpbmRvd3MgcuG7k2kgY2jhuqF5
>> "%B64_FILE%" echo IGzhuqFpLiIpCgoKZGVmIGVuc3VyZV9yZXBvKHJlcG9fZGlyOiBzdHIpIC0+IE5vbmU6CiAgICBy
>> "%B64_FILE%" echo ZXBvID0gUGF0aChyZXBvX2RpcikKICAgIGlmIChyZXBvIC8gIi5naXQiKS5pc19kaXIoKToKICAg
>> "%B64_FILE%" echo ICAgICBwcmludChmIltPS10gUmVwbyBHaXRIdWIgaOG7o3AgbOG7hzoge3JlcG99IiwgZmx1c2g9
>> "%B64_FILE%" echo VHJ1ZSkKICAgICAgICByZXR1cm4KICAgIHJlcG8ubWtkaXIocGFyZW50cz1UcnVlLCBleGlzdF9v
>> "%B64_FILE%" echo az1UcnVlKQogICAgaWYgYW55KHJlcG8uaXRlcmRpcigpKToKICAgICAgICByYWlzZSBSdW50aW1l
>> "%B64_FILE%" echo RXJyb3IoZiJUaMawIG3hu6VjIMSRw6MgY8OzIGZpbGUgbmjGsG5nIGtow7RuZyBjw7MgLmdpdDog
>> "%B64_FILE%" echo e3JlcG99LiBIw6N5IGNo4buNbiDEkcO6bmcgcmVwby4iKQogICAgcnVuKFsiZ2l0IiwgImNsb25l
>> "%B64_FILE%" echo IiwgUkVQT19VUkwsIHN0cihyZXBvKV0pCgoKZGVmIHRhYmxlX2NvbHVtbnMoY3VyLCB0YWJsZSk6
>> "%B64_FILE%" echo CiAgICByb3dzID0gY3VyLmV4ZWN1dGUoIiIiCiAgICAgICAgU0VMRUNUIENPTFVNTl9OQU1FCiAg
>> "%B64_FILE%" echo ICAgICAgRlJPTSBJTkZPUk1BVElPTl9TQ0hFTUEuQ09MVU1OUwogICAgICAgIFdIRVJFIFRBQkxF
>> "%B64_FILE%" echo X1NDSEVNQT0nZGJvJyBBTkQgVEFCTEVfTkFNRT0/CiAgICAiIiIsIHRhYmxlKS5mZXRjaGFsbCgp
>> "%B64_FILE%" echo CiAgICByZXR1cm4ge3IuQ09MVU1OX05BTUUgZm9yIHIgaW4gcm93c30KCgpkZWYgZHJvcF9pZl9l
>> "%B64_FILE%" echo eGlzdHMoY3VyLCB0YWJsZV9uYW1lKToKICAgIGN1ci5leGVjdXRlKGYiSUYgT0JKRUNUX0lEKE4n
>> "%B64_FILE%" echo ZGJvLnt0YWJsZV9uYW1lfScsIE4nVScpIElTIE5PVCBOVUxMIERST1AgVEFCTEUgZGJvLntxaWRl
>> "%B64_FILE%" echo bnQodGFibGVfbmFtZSl9IikKCgpkZWYgY3JlYXRlX3N0YWdlX3RhYmxlKGN1ciwgc3RhZ2UpOgog
>> "%B64_FILE%" echo ICAgZHJvcF9pZl9leGlzdHMoY3VyLCBzdGFnZSkKICAgIGN1ci5leGVjdXRlKGYiIiIKICAgIENS
>> "%B64_FILE%" echo RUFURSBUQUJMRSBkYm8ue3FpZGVudChzdGFnZSl9ICgKICAgICAgICBNYUtobyBudmFyY2hhcigy
>> "%B64_FILE%" echo NCkgTlVMTCwKICAgICAgICBNYVRoYW4gbnZhcmNoYXIoMjQpIE5VTEwsCiAgICAgICAgVG9uREsg
>> "%B64_FILE%" echo bnVtZXJpYygyNCwzKSBOVUxMIERFRkFVTFQgMCwKICAgICAgICBOaGFwVEsgbnVtZXJpYygyNCwz
>> "%B64_FILE%" echo KSBOVUxMIERFRkFVTFQgMCwKICAgICAgICBYdWF0VEsgbnVtZXJpYygyNCwzKSBOVUxMIERFRkFV
>> "%B64_FILE%" echo TFQgMAogICAgKQogICAgIiIiKQoKCmRlZiBjcmVhdGVfZmluYWxfdGFibGUoY3VyLCBmaW5hbCwg
>> "%B64_FILE%" echo c3RhZ2UpOgogICAgZHJvcF9pZl9leGlzdHMoY3VyLCBmaW5hbCkKICAgIGN1ci5leGVjdXRlKGYi
>> "%B64_FILE%" echo IiIKICAgIFNFTEVDVAogICAgICAgIE1hS2hvLAogICAgICAgIE1hVGhhbiwKICAgICAgICBTVU0o
>> "%B64_FILE%" echo SVNOVUxMKFRvbkRLLDApKSBBUyBUb25ESywKICAgICAgICBTVU0oSVNOVUxMKE5oYXBUSywwKSkg
>> "%B64_FILE%" echo QVMgTmhhcFRLLAogICAgICAgIFNVTShJU05VTEwoWHVhdFRLLDApKSBBUyBYdWF0VEssCiAgICAg
>> "%B64_FILE%" echo ICAgU1VNKElTTlVMTChUb25ESywwKSArIElTTlVMTChOaGFwVEssMCkgLSBJU05VTEwoWHVhdFRL
>> "%B64_FILE%" echo LDApKSBBUyBUb25DSwogICAgSU5UTyBkYm8ue3FpZGVudChmaW5hbCl9CiAgICBGUk9NIGRiby57
>> "%B64_FILE%" echo cWlkZW50KHN0YWdlKX0KICAgIEdST1VQIEJZIE1hS2hvLCBNYVRoYW4KICAgIEhBVklORyBBQlMo
>> "%B64_FILE%" echo U1VNKElTTlVMTChUb25ESywwKSArIElTTlVMTChOaGFwVEssMCkgLSBJU05VTEwoWHVhdFRLLDAp
>> "%B64_FILE%" echo KSkgPiAwLjAwMDEKICAgICIiIikKCgpkZWYgaW5zZXJ0X3RvbmRrX3ByZXZpb3VzX3BlcmlvZChj
>> "%B64_FILE%" echo dXIsIHN0YWdlLCB5ZWFyLCBtb250aCk6CiAgICBwcmV2X3llYXIsIHByZXZfbW9udGggPSBwcmV2
>> "%B64_FILE%" echo aW91c19wZXJpb2QoeWVhciwgbW9udGgpCiAgICBwcmludChmIlsyLzVdIE7huqFwIFThu5JOIMSQ
>> "%B64_FILE%" echo 4bqmVSBL4buyIHThu6sgQ0RPVEhBTiB0aMOhbmcgdHLGsOG7m2M6IHtwcmV2X21vbnRoOjAyZH0v
>> "%B64_FILE%" echo e3ByZXZfeWVhcn0iLCBmbHVzaD1UcnVlKQoKICAgIGN1ci5leGVjdXRlKGYiIiIKICAgIElOU0VS
>> "%B64_FILE%" echo VCBJTlRPIGRiby57cWlkZW50KHN0YWdlKX0gKE1hS2hvLCBNYVRoYW4sIFRvbkRLLCBOaGFwVEss
>> "%B64_FILE%" echo IFh1YXRUSykKICAgIFNFTEVDVAogICAgICAgIENBU1QoTWFLaG8gQVMgbnZhcmNoYXIoMjQpKSwK
>> "%B64_FILE%" echo ICAgICAgICBDQVNUKE1hVGhhbiBBUyBudmFyY2hhcigyNCkpLAogICAgICAgIFNVTShDQVNUKElT
>> "%B64_FILE%" echo TlVMTChUb25DSywwKSBBUyBudW1lcmljKDI0LDMpKSkgQVMgVG9uREssCiAgICAgICAgMCwKICAg
>> "%B64_FILE%" echo ICAgICAwCiAgICBGUk9NIGRiby5DRE9USEFOCiAgICBXSEVSRSBOYW1IVCA9ID8gQU5EIFRoYW5n
>> "%B64_FILE%" echo SFQgPSA/CiAgICBHUk9VUCBCWSBNYUtobywgTWFUaGFuCiAgICAiIiIsIGludChwcmV2X3llYXIp
>> "%B64_FILE%" echo LCBpbnQocHJldl9tb250aCkpCgoKZGVmIGluc2VydF9jdXJyZW50X21vdmVtZW50cyhjdXIsIHN0
>> "%B64_FILE%" echo YWdlLCB5ZWFyLCBtb250aCk6CiAgICBwcmludChmIlszLzVdIE7huqFwIHBow6F0IHNpbmggTkjh
>> "%B64_FILE%" echo uqxQL1hV4bqkVCB0cm9uZyBr4buzOiB7bW9udGg6MDJkfS97eWVhcn0iLCBmbHVzaD1UcnVlKQoK
>> "%B64_FILE%" echo ICAgICMgxq91IHRpw6puIGPDoWMgYuG6o25nIHBow6F0IHNpbmggxJHDoyB4deG6pXQgaGnhu4du
>> "%B64_FILE%" echo IHRyb25nIERCIFRUQ08uCiAgICBjYW5kaWRhdGVfdGFibGVzID0gWwogICAgICAgICJUaGFuTmhh
>> "%B64_FILE%" echo cCIsCiAgICAgICAgIlRoYW5YdWF0IiwKICAgICAgICAiVGhhbkdpYW9OaGFuIiwKICAgICAgICAi
>> "%B64_FILE%" echo VGhhblZhb1NhbmciLAogICAgICAgICJUaGFuUmFTYW5nIiwKICAgICAgICAiVGhhbk11YU1vIiwK
>> "%B64_FILE%" echo ICAgIF0KCiAgICBub3RlcyA9IFtdCiAgICBmb3IgdGFibGUgaW4gY2FuZGlkYXRlX3RhYmxlczoK
>> "%B64_FILE%" echo ICAgICAgICB0cnk6CiAgICAgICAgICAgIGNvbHMgPSB0YWJsZV9jb2x1bW5zKGN1ciwgdGFibGUp
>> "%B64_FILE%" echo CiAgICAgICAgZXhjZXB0IEV4Y2VwdGlvbjoKICAgICAgICAgICAgY29udGludWUKCiAgICAgICAg
>> "%B64_FILE%" echo aWYgbm90IHsiTWFLaG8iLCAiTWFUaGFuIiwgIk5hbUhUIiwgIlRoYW5nSFQifS5pc3N1YnNldChj
>> "%B64_FILE%" echo b2xzKToKICAgICAgICAgICAgY29udGludWUKCiAgICAgICAgcXR5X2NvbCA9IE5vbmUKICAgICAg
>> "%B64_FILE%" echo ICBmb3IgYyBpbiBbIktsZ19UYW4iLCAiS2xnIiwgIktob2lMdW9uZyIsICJTb0x1b25nIiwgIlNM
>> "%B64_FILE%" echo IiwgIktMIiwgIlRhbiJdOgogICAgICAgICAgICBpZiBjIGluIGNvbHM6CiAgICAgICAgICAgICAg
>> "%B64_FILE%" echo ICBxdHlfY29sID0gYwogICAgICAgICAgICAgICAgYnJlYWsKICAgICAgICBpZiBub3QgcXR5X2Nv
>> "%B64_FILE%" echo bDoKICAgICAgICAgICAgY29udGludWUKCiAgICAgICAgbG93ID0gdGFibGUubG93ZXIoKQogICAg
>> "%B64_FILE%" echo ICAgICMgQuG6o25nIHbDoG8vbmjhuq1wL3TEg25nIHTDrW5oIE5oYXBUSzsgYuG6o25nIHJhL3h1
>> "%B64_FILE%" echo 4bqldC9naeG6o20gdMOtbmggWHVhdFRLLgogICAgICAgIGlmICJ4dWF0IiBpbiBsb3cgb3IgInJh
>> "%B64_FILE%" echo c2FuZyIgaW4gbG93OgogICAgICAgICAgICB0YXJnZXQgPSAiWHVhdFRLIgogICAgICAgIGVsaWYg
>> "%B64_FILE%" echo Im5oYXAiIGluIGxvdyBvciAiZ2lhb25oYW4iIGluIGxvdyBvciAidmFvc2FuZyIgaW4gbG93IG9y
>> "%B64_FILE%" echo ICJtdWFtbyIgaW4gbG93OgogICAgICAgICAgICB0YXJnZXQgPSAiTmhhcFRLIgogICAgICAgIGVs
>> "%B64_FILE%" echo c2U6CiAgICAgICAgICAgIGNvbnRpbnVlCgogICAgICAgIHRyeToKICAgICAgICAgICAgY3VyLmV4
>> "%B64_FILE%" echo ZWN1dGUoZiIiIgogICAgICAgICAgICBJTlNFUlQgSU5UTyBkYm8ue3FpZGVudChzdGFnZSl9IChN
>> "%B64_FILE%" echo YUtobywgTWFUaGFuLCBUb25ESywgTmhhcFRLLCBYdWF0VEspCiAgICAgICAgICAgIFNFTEVDVAog
>> "%B64_FILE%" echo ICAgICAgICAgICAgICAgQ0FTVChNYUtobyBBUyBudmFyY2hhcigyNCkpLAogICAgICAgICAgICAg
>> "%B64_FILE%" echo ICAgQ0FTVChNYVRoYW4gQVMgbnZhcmNoYXIoMjQpKSwKICAgICAgICAgICAgICAgIDAsCiAgICAg
>> "%B64_FILE%" echo ICAgICAgICAgICBDQVNFIFdIRU4gPyA9ICdOaGFwVEsnIFRIRU4gU1VNKENBU1QoSVNOVUxMKHtx
>> "%B64_FILE%" echo aWRlbnQocXR5X2NvbCl9LDApIEFTIG51bWVyaWMoMjQsMykpKSBFTFNFIDAgRU5ELAogICAgICAg
>> "%B64_FILE%" echo ICAgICAgICAgQ0FTRSBXSEVOID8gPSAnWHVhdFRLJyBUSEVOIFNVTShDQVNUKElTTlVMTCh7cWlk
>> "%B64_FILE%" echo ZW50KHF0eV9jb2wpfSwwKSBBUyBudW1lcmljKDI0LDMpKSkgRUxTRSAwIEVORAogICAgICAgICAg
>> "%B64_FILE%" echo ICBGUk9NIGRiby57cWlkZW50KHRhYmxlKX0KICAgICAgICAgICAgV0hFUkUgTmFtSFQgPSA/IEFO
>> "%B64_FILE%" echo RCBUaGFuZ0hUID0gPwogICAgICAgICAgICBHUk9VUCBCWSBNYUtobywgTWFUaGFuCiAgICAgICAg
>> "%B64_FILE%" echo ICAgICIiIiwgdGFyZ2V0LCB0YXJnZXQsIGludCh5ZWFyKSwgaW50KG1vbnRoKSkKICAgICAgICAg
>> "%B64_FILE%" echo ICAgbm90ZXMuYXBwZW5kKGYie3RhYmxlfS57cXR5X2NvbH0tPnt0YXJnZXR9IikKICAgICAgICAg
>> "%B64_FILE%" echo ICAgcHJpbnQoZiIgIFtPS10ge3RhYmxlfS57cXR5X2NvbH0gLT4ge3RhcmdldH0iLCBmbHVzaD1U
>> "%B64_FILE%" echo cnVlKQogICAgICAgIGV4Y2VwdCBFeGNlcHRpb24gYXMgZXhjOgogICAgICAgICAgICBwcmludChm
>> "%B64_FILE%" echo IiAgW1NLSVBdIHt0YWJsZX06IHtleGN9IiwgZmx1c2g9VHJ1ZSkKCiAgICByZXR1cm4gbm90ZXMK
>> "%B64_FILE%" echo CgpkZWYgZGlyZWN0X2NvbXB1dGUoeWVhciwgbW9udGgpOgogICAgZW5zdXJlX3B5b2RiYygpCiAg
>> "%B64_FILE%" echo ICBjb25uID0gY29ubmVjdChEQVRBQkFTRSkKICAgIGN1ciA9IGNvbm4uY3Vyc29yKCkKCiAgICBz
>> "%B64_FILE%" echo dWZmaXggPSBmIntkYXRldGltZS5ub3coKTolSCVNJVN9e29zLmdldHBpZCgpfSIKICAgIHN0YWdl
>> "%B64_FILE%" echo ID0gZiJHM19CQzA1QV8xX0RJUkVDVDIxX3tzdWZmaXh9IgogICAgZmluYWwgPSBmIkczX0JDMDVB
>> "%B64_FILE%" echo XzJfRElSRUNUMjFfe3N1ZmZpeH0iCgogICAgcHJpbnQoIj09PT09PT09PT09PT09PT09PT09PT09
>> "%B64_FILE%" echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PSIsIGZsdXNoPVRydWUpCiAgICBw
>> "%B64_FILE%" echo cmludCgiVFRDTyBESVJFQ1QgREIgRU5HSU5FIFYyMSAtIEtIw5RORyBN4bueIFRUQ09fQVBQIiwg
>> "%B64_FILE%" echo Zmx1c2g9VHJ1ZSkKICAgIHByaW50KCI9PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
>> "%B64_FILE%" echo PT09PT09PT09PT09PT09PT09PT09PT09PT0iLCBmbHVzaD1UcnVlKQogICAgcHJpbnQoZiJL4buz
>> "%B64_FILE%" echo IGThu68gbGnhu4d1OiB7bW9udGg6MDJkfS97eWVhcn0iLCBmbHVzaD1UcnVlKQogICAgcHJpbnQo
>> "%B64_FILE%" echo IlPhu61hIGNow61uaCB2MjE6IFRvbkRLIGzhuqV5IHThu6sgQ0RPVEhBTiB0aMOhbmcgdHLGsOG7
>> "%B64_FILE%" echo m2MsIGtow7RuZyDEkeG7gyBUb25ESz0wLiIsIGZsdXNoPVRydWUpCiAgICBwcmludCgiIiwgZmx1
>> "%B64_FILE%" echo c2g9VHJ1ZSkKCiAgICBwcmludCgiWzEvNV0gVOG6oW8gYuG6o25nIHN0YWdlLi4uIiwgZmx1c2g9
>> "%B64_FILE%" echo VHJ1ZSkKICAgIGNyZWF0ZV9zdGFnZV90YWJsZShjdXIsIHN0YWdlKQoKICAgIGluc2VydF90b25k
>> "%B64_FILE%" echo a19wcmV2aW91c19wZXJpb2QoY3VyLCBzdGFnZSwgeWVhciwgbW9udGgpCiAgICBub3RlcyA9IGlu
>> "%B64_FILE%" echo c2VydF9jdXJyZW50X21vdmVtZW50cyhjdXIsIHN0YWdlLCB5ZWFyLCBtb250aCkKCiAgICBwcmlu
>> "%B64_FILE%" echo dCgiWzQvNV0gVOG6oW8gYuG6o25nIGvhur90IHF14bqjIGN14buRaS4uLiIsIGZsdXNoPVRydWUp
>> "%B64_FILE%" echo CiAgICBjcmVhdGVfZmluYWxfdGFibGUoY3VyLCBmaW5hbCwgc3RhZ2UpCgogICAgcHJpbnQoIls1
>> "%B64_FILE%" echo LzVdIEhvw6BuIHThuqV0LiIsIGZsdXNoPVRydWUpCiAgICBjb25uLmNsb3NlKCkKICAgIHJldHVy
>> "%B64_FILE%" echo biBmaW5hbCwgbm90ZXMKCgpkZWYgcmVhZF9maW5hbF9yb3dzKHRhYmxlX25hbWUpOgogICAgY29u
>> "%B64_FILE%" echo biA9IGNvbm5lY3QoREFUQUJBU0UpCiAgICBjdXIgPSBjb25uLmN1cnNvcigpCiAgICBzcWwgPSBm
>> "%B64_FILE%" echo IiIiCiAgICBTRUxFQ1QKICAgICAgICByLk1hS2hvLAogICAgICAgIENPQUxFU0NFKGsuVGVuS2hv
>> "%B64_FILE%" echo TW9pLCBrLlRlbktobywgci5NYUtobykgQVMgVGVuS2hvLAogICAgICAgIHIuTWFUaGFuLAogICAg
>> "%B64_FILE%" echo ICAgIENPQUxFU0NFKHQuVGVuWEssIHQuVGVuVGhhbiwgci5NYVRoYW4pIEFTIFRlblRoYW4sCiAg
>> "%B64_FILE%" echo ICAgICAgQ0FTVChJU05VTEwoci5Ub25ESywgMCkgQVMgRkxPQVQpIEFTIFRvbkRLLAogICAgICAg
>> "%B64_FILE%" echo IENBU1QoSVNOVUxMKHIuTmhhcFRLLCAwKSBBUyBGTE9BVCkgQVMgTmhhcFRLLAogICAgICAgIENB
>> "%B64_FILE%" echo U1QoSVNOVUxMKHIuWHVhdFRLLCAwKSBBUyBGTE9BVCkgQVMgWHVhdFRLLAogICAgICAgIENBU1Qo
>> "%B64_FILE%" echo SVNOVUxMKHIuVG9uQ0ssIDApIEFTIEZMT0FUKSBBUyBUb25DSywKICAgICAgICBDT0FMRVNDRSh0
>> "%B64_FILE%" echo LlRUSU4sIE4nJykgQVMgVFRJTl9UaGFuLAogICAgICAgIENPQUxFU0NFKGsuVFRJTiwgTicnKSBB
>> "%B64_FILE%" echo UyBUVElOX0tobwogICAgRlJPTSBkYm8ue3FpZGVudCh0YWJsZV9uYW1lKX0gcgogICAgTEVGVCBK
>> "%B64_FILE%" echo T0lOIHtNQVNURVJfREJ9LmRiby5ETVRIQU4gdAogICAgICAgIE9OIFJUUklNKExUUklNKHQuTWFU
>> "%B64_FILE%" echo aGFuKSkgPSBSVFJJTShMVFJJTShyLk1hVGhhbikpCiAgICBMRUZUIEpPSU4ge01BU1RFUl9EQn0u
>> "%B64_FILE%" echo ZGJvLkRNS0hPIGsKICAgICAgICBPTiBSVFJJTShMVFJJTShrLk1hS2hvKSkgPSBSVFJJTShMVFJJ
>> "%B64_FILE%" echo TShyLk1hS2hvKSkKICAgIFdIRVJFCiAgICAgICAgSVNOVUxMKHIuTWFLaG8sIE4nJykgPD4gTicn
>> "%B64_FILE%" echo CiAgICAgICAgQU5EIElTTlVMTChyLk1hVGhhbiwgTicnKSA8PiBOJycKICAgICAgICBBTkQgQUJT
>> "%B64_FILE%" echo KENBU1QoSVNOVUxMKHIuVG9uQ0ssIDApIEFTIEZMT0FUKSkgPiAwLjAwMDEKICAgIE9SREVSIEJZ
>> "%B64_FILE%" echo IENPQUxFU0NFKGsuVFRJTiwgTicnKSwgQ09BTEVTQ0UodC5UVElOLCBOJycpLCByLk1hS2hvLCBy
>> "%B64_FILE%" echo Lk1hVGhhbgogICAgIiIiCiAgICByb3dzID0gY3VyLmV4ZWN1dGUoc3FsKS5mZXRjaGFsbCgpCiAg
>> "%B64_FILE%" echo ICBjb25uLmNsb3NlKCkKCiAgICBkYXRhX3Jvd3MgPSBbXQogICAgZm9yIHJvdyBpbiByb3dzOgog
>> "%B64_FILE%" echo ICAgICAgIG1hX2tobyA9IG5vcm1hbGl6ZV90ZXh0KHJvdy5NYUtobykKICAgICAgICB0ZW5fa2hv
>> "%B64_FILE%" echo ID0gbm9ybWFsaXplX3RleHQocm93LlRlbktobykgb3IgbWFfa2hvCiAgICAgICAgbWFfdGhhbiA9
>> "%B64_FILE%" echo IG5vcm1hbGl6ZV90ZXh0KHJvdy5NYVRoYW4pCiAgICAgICAgdGVuX3RoYW4gPSBub3JtYWxpemVf
>> "%B64_FILE%" echo Y29hbF9uYW1lKHJvdy5UZW5UaGFuKSBvciBtYV90aGFuCgogICAgICAgIHRvbl9kayA9IHJvdW5k
>> "%B64_FILE%" echo KGNsZWFuX251bWJlcihyb3cuVG9uREspLCAyKQogICAgICAgIG5oYXBfdGsgPSByb3VuZChjbGVh
>> "%B64_FILE%" echo bl9udW1iZXIocm93Lk5oYXBUSyksIDIpCiAgICAgICAgeHVhdF90ayA9IHJvdW5kKGNsZWFuX251
>> "%B64_FILE%" echo bWJlcihyb3cuWHVhdFRLKSwgMikKICAgICAgICB0b25fY2sgPSByb3VuZChjbGVhbl9udW1iZXIo
>> "%B64_FILE%" echo cm93LlRvbkNLKSwgMikKCiAgICAgICAgZGF0YV9yb3dzLmFwcGVuZCh7CiAgICAgICAgICAgICJN
>> "%B64_FILE%" echo YUtobyI6IG1hX2tobywKICAgICAgICAgICAgIlRlbktobyI6IHRlbl9raG8sCiAgICAgICAgICAg
>> "%B64_FILE%" echo ICJraG8iOiB0ZW5fa2hvLAogICAgICAgICAgICAiTWFUaGFuIjogbWFfdGhhbiwKICAgICAgICAg
>> "%B64_FILE%" echo ICAgIlRlblRoYW4iOiB0ZW5fdGhhbiwKICAgICAgICAgICAgImNvYWwiOiB0ZW5fdGhhbiwKICAg
>> "%B64_FILE%" echo ICAgICAgICAgIlRvbkRLIjogdG9uX2RrLAogICAgICAgICAgICAiTmhhcFRLIjogbmhhcF90aywK
>> "%B64_FILE%" echo ICAgICAgICAgICAgIlh1YXRUSyI6IHh1YXRfdGssCiAgICAgICAgICAgICJUb25DSyI6IHRvbl9j
>> "%B64_FILE%" echo aywKICAgICAgICAgICAgInRvbiI6IHRvbl9jaywKICAgICAgICAgICAgInR0Y29BcHAiOiB0b25f
>> "%B64_FILE%" echo Y2ssCiAgICAgICAgICAgICJzb3VyY2VGb3JtdWxhIjogIlRvbkNLID0gQ0RPVEhBTiBwcmV2aW91
>> "%B64_FILE%" echo cyBtb250aCBUb25DSyArIGN1cnJlbnQgbW92ZW1lbnRzIiwKICAgICAgICAgICAgInR0aW5LaG8i
>> "%B64_FILE%" echo OiBub3JtYWxpemVfdGV4dChyb3cuVFRJTl9LaG8pLAogICAgICAgICAgICAidHRpblRoYW4iOiBu
>> "%B64_FILE%" echo b3JtYWxpemVfdGV4dChyb3cuVFRJTl9UaGFuKSwKICAgICAgICB9KQoKICAgIGRhdGFfcm93cy5z
>> "%B64_FILE%" echo b3J0KGtleT1sYW1iZGEgeDogKGtob19zb3J0X2tleSh4WyJUZW5LaG8iXSwgeFsiTWFLaG8iXSks
>> "%B64_FILE%" echo IHhbInR0aW5UaGFuIl0sIHhbIlRlblRoYW4iXSkpCiAgICByZXR1cm4gZGF0YV9yb3dzCgoKZGVm
>> "%B64_FILE%" echo IGJ1aWxkX3BheWxvYWQoZmluYWxfdGFibGUsIHllYXIsIG1vbnRoLCBub3Rlcyk6CiAgICBkYXRh
>> "%B64_FILE%" echo X3Jvd3MgPSByZWFkX2ZpbmFsX3Jvd3MoZmluYWxfdGFibGUpCiAgICBpZiBub3QgZGF0YV9yb3dz
>> "%B64_FILE%" echo OgogICAgICAgIHJhaXNlIFJ1bnRpbWVFcnJvcihmIkLhuqNuZyBr4bq/dCBxdeG6oyB7ZmluYWxf
>> "%B64_FILE%" echo dGFibGV9IGtow7RuZyBjw7MgZOG7ryBsaeG7h3UgVG9uQ0sgaOG7o3AgbOG7hy4iKQoKICAgIHRv
>> "%B64_FILE%" echo dGFsID0gcm91bmQoc3VtKGZsb2F0KHJbIlRvbkNLIl0pIGZvciByIGluIGRhdGFfcm93cyksIDIp
>> "%B64_FILE%" echo CiAgICBraG8xX3Jvd3MgPSBbCiAgICAgICAgciBmb3IgciBpbiBkYXRhX3Jvd3MKICAgICAgICBp
>> "%B64_FILE%" echo ZiByWyJUZW5LaG8iXS5zdHJpcCgpLmxvd2VyKCkgPT0gImtobyAxIiBvciByWyJNYUtobyJdLnN0
>> "%B64_FILE%" echo cmlwKCkgaW4gKCIxIiwgIjAxIikKICAgIF0KICAgIGtobzFfdG90YWwgPSByb3VuZChzdW0oZmxv
>> "%B64_FILE%" echo YXQoclsiVG9uQ0siXSkgZm9yIHIgaW4ga2hvMV9yb3dzKSwgMikKCiAgICByZXR1cm4gewogICAg
>> "%B64_FILE%" echo ICAgICJvayI6IFRydWUsCiAgICAgICAgIm1ldGEiOiB7CiAgICAgICAgICAgICJzb3VyY2UiOiAi
>> "%B64_FILE%" echo VFRDT19ESVJFQ1RfREJfRU5HSU5FIiwKICAgICAgICAgICAgImRhdGFiYXNlIjogREFUQUJBU0Us
>> "%B64_FILE%" echo CiAgICAgICAgICAgICJzb3VyY2VUYWJsZSI6IGZpbmFsX3RhYmxlLAogICAgICAgICAgICAibWFz
>> "%B64_FILE%" echo dGVyRGF0YWJhc2UiOiBNQVNURVJfREIsCiAgICAgICAgICAgICJ2ZXJzaW9uIjogImRpcmVjdC1k
>> "%B64_FILE%" echo Yi12MjEtcHJldi1jZG90aGFuIiwKICAgICAgICAgICAgInVwZGF0ZWRBdCI6IGRhdGV0aW1lLm5v
>> "%B64_FILE%" echo dygpLnN0cmZ0aW1lKCIlWS0lbS0lZCAlSDolTTolUyIpLAogICAgICAgICAgICAiTmFtSFQiOiBz
>> "%B64_FILE%" echo dHIoeWVhciksCiAgICAgICAgICAgICJUaGFuZ0hUIjogc3RyKG1vbnRoKSwKICAgICAgICAgICAg
>> "%B64_FILE%" echo InJvd0NvdW50IjogbGVuKGRhdGFfcm93cyksCiAgICAgICAgICAgICJ0b3RhbFRvbiI6IHRvdGFs
>> "%B64_FILE%" echo LAogICAgICAgICAgICAia2hvMVRvdGFsIjoga2hvMV90b3RhbCwKICAgICAgICAgICAgImZvcm11
>> "%B64_FILE%" echo bGEiOiAiVG9uQ0sgPSBUb25ESyhwcmV2aW91cyBtb250aCBDRE9USEFOLlRvbkNLKSArIE5oYXBU
>> "%B64_FILE%" echo SyhjdXJyZW50IG1vbnRoKSAtIFh1YXRUSyhjdXJyZW50IG1vbnRoKSIsCiAgICAgICAgICAgICJt
>> "%B64_FILE%" echo b3ZlbWVudFNvdXJjZXMiOiBub3RlcywKICAgICAgICAgICAgIm5vdGUiOiAiS2jDtG5nIG3hu58g
>> "%B64_FILE%" echo VFRDT19BUFAsIGtow7RuZyBkw7luZyBFeGNlbC4gVjIxIHPhu61hIGzhu5dpIFRvbkRLPTAgYuG6
>> "%B64_FILE%" echo sW5nIGPDoWNoIGzhuqV5IHThu5NuIMSR4bqndSBr4buzIHThu6sgQ0RPVEhBTiB0aMOhbmcgdHLG
>> "%B64_FILE%" echo sOG7m2MuIiwKICAgICAgICB9LAogICAgICAgICJkYXRhIjogZGF0YV9yb3dzLAogICAgICAgICJy
>> "%B64_FILE%" echo b3dzIjogZGF0YV9yb3dzLAogICAgfSwga2hvMV9yb3dzCgoKZGVmIHdyaXRlX2NoZWNrKHBheWxv
>> "%B64_FILE%" echo YWQsIGtobzFfcm93cyk6CiAgICBDSEVDS19ESVIubWtkaXIocGFyZW50cz1UcnVlLCBleGlzdF9v
>> "%B64_FILE%" echo az1UcnVlKQogICAgb3V0ID0gQ0hFQ0tfRElSIC8gZiJjaGVja19kaXJlY3RfZGJfdjIxX3tkYXRl
>> "%B64_FILE%" echo dGltZS5ub3coKTolWSVtJWRfJUglTSVTfS50eHQiCiAgICB3aXRoIG91dC5vcGVuKCJ3IiwgZW5j
>> "%B64_FILE%" echo b2Rpbmc9InV0Zi04IikgYXMgZjoKICAgICAgICBmLndyaXRlKCJUVENPIC0gS0nhu4JNIFRSQSBE
>> "%B64_FILE%" echo SVJFQ1QgREIgRU5HSU5FIC0gVjIxXG4iKQogICAgICAgIGYud3JpdGUoIj0iICogOTAgKyAiXG4i
>> "%B64_FILE%" echo KQogICAgICAgIGYud3JpdGUoZiJTb3VyY2UgdGFibGUgOiB7cGF5bG9hZFsnbWV0YSddWydzb3Vy
>> "%B64_FILE%" echo Y2VUYWJsZSddfVxuIikKICAgICAgICBmLndyaXRlKGYiUGVyaW9kICAgICAgIDoge3BheWxvYWRb
>> "%B64_FILE%" echo J21ldGEnXVsnVGhhbmdIVCddfS97cGF5bG9hZFsnbWV0YSddWydOYW1IVCddfVxuIikKICAgICAg
>> "%B64_FILE%" echo ICBmLndyaXRlKGYiUm93IGNvdW50ICAgIDoge3BheWxvYWRbJ21ldGEnXVsncm93Q291bnQnXX1c
>> "%B64_FILE%" echo biIpCiAgICAgICAgZi53cml0ZShmIlRvdGFsIHRvbiAgICA6IHtwYXlsb2FkWydtZXRhJ11bJ3Rv
>> "%B64_FILE%" echo dGFsVG9uJ106LC4yZn1cbiIpCiAgICAgICAgZi53cml0ZShmIktobyAxIHRvdGFsICA6IHtwYXls
>> "%B64_FILE%" echo b2FkWydtZXRhJ11bJ2tobzFUb3RhbCddOiwuMmZ9XG4iKQogICAgICAgIGYud3JpdGUoZiJGb3Jt
>> "%B64_FILE%" echo dWxhICAgICAgOiB7cGF5bG9hZFsnbWV0YSddWydmb3JtdWxhJ119XG4iKQogICAgICAgIGYud3Jp
>> "%B64_FILE%" echo dGUoIlxuTW92ZW1lbnQgc291cmNlczpcbiIpCiAgICAgICAgZm9yIG5vdGUgaW4gcGF5bG9hZFsi
>> "%B64_FILE%" echo bWV0YSJdLmdldCgibW92ZW1lbnRTb3VyY2VzIiwgW10pOgogICAgICAgICAgICBmLndyaXRlKGYi
>> "%B64_FILE%" echo LSB7bm90ZX1cbiIpCiAgICAgICAgZi53cml0ZSgiXG5LaG8gMSByb3dzOlxuIikKICAgICAgICBm
>> "%B64_FILE%" echo b3IgciBpbiBraG8xX3Jvd3M6CiAgICAgICAgICAgIGYud3JpdGUoCiAgICAgICAgICAgICAgICBm
>> "%B64_FILE%" echo Ik1hS2hvPXtyWydNYUtobyddfSB8IEtobz17clsnVGVuS2hvJ119IHwgIgogICAgICAgICAgICAg
>> "%B64_FILE%" echo ICAgZiJNYVRoYW49e3JbJ01hVGhhbiddfSB8IFRoYW49e3JbJ1RlblRoYW4nXX0gfCAiCiAgICAg
>> "%B64_FILE%" echo ICAgICAgICAgICBmIlRvbkRLPXtyWydUb25ESyddOiwuMmZ9IHwgTmhhcFRLPXtyWydOaGFwVEsn
>> "%B64_FILE%" echo XTosLjJmfSB8ICIKICAgICAgICAgICAgICAgIGYiWHVhdFRLPXtyWydYdWF0VEsnXTosLjJmfSB8
>> "%B64_FILE%" echo IFRvbkNLPXtyWydUb25DSyddOiwuMmZ9XG4iCiAgICAgICAgICAgICkKICAgIHByaW50KGYiW09L
>> "%B64_FILE%" echo XSDEkMOjIHh14bqldCBraeG7g20gdHJhOiB7b3V0fSIsIGZsdXNoPVRydWUpCiAgICB0cnk6CiAg
>> "%B64_FILE%" echo ICAgICAgc3VicHJvY2Vzcy5Qb3BlbihbImV4cGxvcmVyLmV4ZSIsIHN0cihDSEVDS19ESVIpXSkK
>> "%B64_FILE%" echo ICAgIGV4Y2VwdCBFeGNlcHRpb246CiAgICAgICAgcGFzcwoKCmRlZiB3cml0ZV9qc29uKHJlcG9f
>> "%B64_FILE%" echo ZGlyLCBwYXlsb2FkKToKICAgIGRlc3QgPSBQYXRoKHJlcG9fZGlyKSAvIEpTT05fUkVMCiAgICBk
>> "%B64_FILE%" echo ZXN0LnBhcmVudC5ta2RpcihwYXJlbnRzPVRydWUsIGV4aXN0X29rPVRydWUpCiAgICBkZXN0Lndy
>> "%B64_FILE%" echo aXRlX3RleHQoanNvbi5kdW1wcyhwYXlsb2FkLCBlbnN1cmVfYXNjaWk9RmFsc2UsIGluZGVudD0y
>> "%B64_FILE%" echo KSwgZW5jb2Rpbmc9InV0Zi04IikKICAgIHByaW50KGYiW09LXSDEkMOjIHThuqFvIEpTT046IHtk
>> "%B64_FILE%" echo ZXN0fSIsIGZsdXNoPVRydWUpCgoKZGVmIGRpcmVjdF9jaGVjayh5ZWFyLCBtb250aCk6CiAgICBm
>> "%B64_FILE%" echo aW5hbF90YWJsZSwgbm90ZXMgPSBkaXJlY3RfY29tcHV0ZSh5ZWFyLCBtb250aCkKICAgIHBheWxv
>> "%B64_FILE%" echo YWQsIGtobzFfcm93cyA9IGJ1aWxkX3BheWxvYWQoZmluYWxfdGFibGUsIHllYXIsIG1vbnRoLCBu
>> "%B64_FILE%" echo b3RlcykKICAgIHByaW50KCIiLCBmbHVzaD1UcnVlKQogICAgcHJpbnQoIktp4buDbSB0cmEgbmhh
>> "%B64_FILE%" echo bmg6IiwgZmx1c2g9VHJ1ZSkKICAgIHByaW50KGYiQuG6o25nIGvhur90IHF14bqjIDoge3BheWxv
>> "%B64_FILE%" echo YWRbJ21ldGEnXVsnc291cmNlVGFibGUnXX0iLCBmbHVzaD1UcnVlKQogICAgcHJpbnQoZiJL4buz
>> "%B64_FILE%" echo IGThu68gbGnhu4d1ICAgOiB7bW9udGg6MDJkfS97eWVhcn0iLCBmbHVzaD1UcnVlKQogICAgcHJp
>> "%B64_FILE%" echo bnQoZiJT4buRIGTDsm5nICAgICAgOiB7cGF5bG9hZFsnbWV0YSddWydyb3dDb3VudCddfSIsIGZs
>> "%B64_FILE%" echo dXNoPVRydWUpCiAgICBwcmludChmIlThu5VuZyB04buTbiAgICAgOiB7cGF5bG9hZFsnbWV0YSdd
>> "%B64_FILE%" echo Wyd0b3RhbFRvbiddOiwuMmZ9IiwgZmx1c2g9VHJ1ZSkKICAgIHByaW50KGYiVOG7lW5nIEtobyAx
>> "%B64_FILE%" echo ICAgOiB7cGF5bG9hZFsnbWV0YSddWydraG8xVG90YWwnXTosLjJmfSIsIGZsdXNoPVRydWUpCiAg
>> "%B64_FILE%" echo ICB3cml0ZV9jaGVjayhwYXlsb2FkLCBraG8xX3Jvd3MpCgoKZGVmIGRpcmVjdF91cGRhdGUocmVw
>> "%B64_FILE%" echo b19kaXIsIHllYXIsIG1vbnRoKToKICAgIGVuc3VyZV9naXQoKQogICAgZW5zdXJlX3JlcG8ocmVw
>> "%B64_FILE%" echo b19kaXIpCiAgICBmaW5hbF90YWJsZSwgbm90ZXMgPSBkaXJlY3RfY29tcHV0ZSh5ZWFyLCBtb250
>> "%B64_FILE%" echo aCkKICAgIHBheWxvYWQsIGtobzFfcm93cyA9IGJ1aWxkX3BheWxvYWQoZmluYWxfdGFibGUsIHll
>> "%B64_FILE%" echo YXIsIG1vbnRoLCBub3RlcykKCiAgICBwcmludCgiIiwgZmx1c2g9VHJ1ZSkKICAgIHByaW50KCJL
>> "%B64_FILE%" echo aeG7g20gdHJhIG5oYW5oIHRyxrDhu5tjIGtoaSB1cDoiLCBmbHVzaD1UcnVlKQogICAgcHJpbnQo
>> "%B64_FILE%" echo ZiJC4bqjbmcga+G6v3QgcXXhuqMgOiB7cGF5bG9hZFsnbWV0YSddWydzb3VyY2VUYWJsZSddfSIs
>> "%B64_FILE%" echo IGZsdXNoPVRydWUpCiAgICBwcmludChmIkvhu7MgZOG7ryBsaeG7h3UgICA6IHttb250aDowMmR9
>> "%B64_FILE%" echo L3t5ZWFyfSIsIGZsdXNoPVRydWUpCiAgICBwcmludChmIlPhu5EgZMOybmcgICAgICA6IHtwYXls
>> "%B64_FILE%" echo b2FkWydtZXRhJ11bJ3Jvd0NvdW50J119IiwgZmx1c2g9VHJ1ZSkKICAgIHByaW50KGYiVOG7lW5n
>> "%B64_FILE%" echo IHThu5NuICAgICA6IHtwYXlsb2FkWydtZXRhJ11bJ3RvdGFsVG9uJ106LC4yZn0iLCBmbHVzaD1U
>> "%B64_FILE%" echo cnVlKQogICAgcHJpbnQoZiJU4buVbmcgS2hvIDEgICA6IHtwYXlsb2FkWydtZXRhJ11bJ2tobzFU
>> "%B64_FILE%" echo b3RhbCddOiwuMmZ9IiwgZmx1c2g9VHJ1ZSkKICAgIHdyaXRlX2NoZWNrKHBheWxvYWQsIGtobzFf
>> "%B64_FILE%" echo cm93cykKICAgIHdyaXRlX2pzb24ocmVwb19kaXIsIHBheWxvYWQpCgogICAgcHJpbnQoIlxuxJBh
>> "%B64_FILE%" echo bmcgY29tbWl0L3B1c2ggbMOqbiBHaXRIdWIuLi4iLCBmbHVzaD1UcnVlKQogICAgcnVuKFsiZ2l0
>> "%B64_FILE%" echo IiwgImNoZWNrb3V0IiwgQlJBTkNIXSwgY3dkPXJlcG9fZGlyLCBjaGVjaz1GYWxzZSkKICAgIHJ1
>> "%B64_FILE%" echo bihbImdpdCIsICJwdWxsIiwgIi0tcmViYXNlIiwgIm9yaWdpbiIsIEJSQU5DSF0sIGN3ZD1yZXBv
>> "%B64_FILE%" echo X2RpciwgY2hlY2s9RmFsc2UpCiAgICBydW4oWyJnaXQiLCAiYWRkIiwgSlNPTl9SRUxdLCBjd2Q9
>> "%B64_FILE%" echo cmVwb19kaXIpCgogICAgZGlmZl9jb2RlID0gc3VicHJvY2Vzcy5ydW4oWyJnaXQiLCAiZGlmZiIs
>> "%B64_FILE%" echo ICItLWNhY2hlZCIsICItLXF1aWV0Il0sIGN3ZD1yZXBvX2RpcikucmV0dXJuY29kZQogICAgaWYg
>> "%B64_FILE%" echo ZGlmZl9jb2RlID09IDA6CiAgICAgICAgcHJpbnQoIltPS10gSlNPTiBraMO0bmcgdGhheSDEkeG7
>> "%B64_FILE%" echo lWksIGtow7RuZyBj4bqnbiBwdXNoLiIsIGZsdXNoPVRydWUpCiAgICAgICAgbG9nKCJObyBjaGFu
>> "%B64_FILE%" echo Z2VzLiIpCiAgICAgICAgcmV0dXJuCgogICAgbXNnID0gZiJVcGRhdGUgVFRDTyB0b24ga2hvIGRp
>> "%B64_FILE%" echo cmVjdCBEQiB2MjEge3llYXJ9LXttb250aDowMmR9ICIgKyBkYXRldGltZS5ub3coKS5zdHJmdGlt
>> "%B64_FILE%" echo ZSgiJVktJW0tJWQgJUg6JU06JVMiKQogICAgcnVuKFsiZ2l0IiwgImNvbW1pdCIsICItbSIsIG1z
>> "%B64_FILE%" echo Z10sIGN3ZD1yZXBvX2RpcikKICAgIHJ1bihbImdpdCIsICJwdXNoIiwgIm9yaWdpbiIsIEJSQU5D
>> "%B64_FILE%" echo SF0pCiAgICBwcmludCgiXG49PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
>> "%B64_FILE%" echo PT09PT09PT09PT09PT09PT09PT0iLCBmbHVzaD1UcnVlKQogICAgcHJpbnQoIltPS10gxJDDgyBD
>> "%B64_FILE%" echo 4bqsUCBOSOG6rFQgR0lUSFVCIFRIw4BOSCBDw5RORyIsIGZsdXNoPVRydWUpCiAgICBwcmludCgi
>> "%B64_FILE%" echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
>> "%B64_FILE%" echo PT09IiwgZmx1c2g9VHJ1ZSkKICAgIGxvZygiUHVzaCBzdWNjZXNzLiIpCgoKZGVmIGluc3RhbGxf
>> "%B64_FILE%" echo dGFzayhiYXRfcGF0aDogc3RyKToKICAgIGlmIG5vdCBiYXRfcGF0aCBvciBub3Qgb3MucGF0aC5p
>> "%B64_FILE%" echo c2ZpbGUoYmF0X3BhdGgpOgogICAgICAgIHJhaXNlIFJ1bnRpbWVFcnJvcigiS2jDtG5nIHjDoWMg
>> "%B64_FILE%" echo xJHhu4tuaCDEkcaw4bujYyBmaWxlIEJBVCDEkeG7gyBjw6BpIHThu7EgxJHhu5luZy4iKQogICAg
>> "%B64_FILE%" echo dGFza19jbWQgPSBmJyJ7YmF0X3BhdGh9IiAtLWF1dG8nCiAgICBydW4oWyJzY2h0YXNrcyIsICIv
>> "%B64_FILE%" echo Q3JlYXRlIiwgIi9UTiIsIFRBU0tfTkFNRSwgIi9UUiIsIHRhc2tfY21kLCAiL1NDIiwgIk9OTE9H
>> "%B64_FILE%" echo T04iLCAiL0RFTEFZIiwgIjAwMDE6MDAiLCAiL0YiXSkKICAgIHByaW50KCJbT0tdIMSQw6MgY8Og
>> "%B64_FILE%" echo aSB04buxIMSR4buZbmcga2hpIMSRxINuZyBuaOG6rXAgV2luZG93cy4iLCBmbHVzaD1UcnVlKQog
>> "%B64_FILE%" echo ICAgcHJpbnQoIkNo4bq/IMSR4buZIHThu7EgxJHhu5luZyBkw7luZyB0aMOhbmcvbsSDbSBoaeG7
>> "%B64_FILE%" echo h24gdOG6oWkgY+G7p2EgV2luZG93cy4iLCBmbHVzaD1UcnVlKQogICAgbG9nKGYiSW5zdGFsbCB0
>> "%B64_FILE%" echo YXNrOiB7dGFza19jbWR9IikKCgpkZWYgb3Blbl9sb2coKToKICAgIENPTkZJR19ESVIubWtkaXIo
>> "%B64_FILE%" echo cGFyZW50cz1UcnVlLCBleGlzdF9vaz1UcnVlKQogICAgaWYgbm90IExPR19GSUxFLmV4aXN0cygp
>> "%B64_FILE%" echo OgogICAgICAgIExPR19GSUxFLndyaXRlX3RleHQoIkNoxrBhIGPDsyBsb2cuXG4iLCBlbmNvZGlu
>> "%B64_FILE%" echo Zz0idXRmLTgiKQogICAgc3VicHJvY2Vzcy5Qb3BlbihbIm5vdGVwYWQuZXhlIiwgc3RyKExPR19G
>> "%B64_FILE%" echo SUxFKV0pCgoKZGVmIGN1cnJlbnRfcGVyaW9kKCk6CiAgICBub3cgPSBkYXRldGltZS5ub3coKQog
>> "%B64_FILE%" echo ICAgcmV0dXJuIG5vdy55ZWFyLCBub3cubW9udGgKCgpkZWYgYXNrX3BlcmlvZCgpOgogICAgeSwg
>> "%B64_FILE%" echo bSA9IGN1cnJlbnRfcGVyaW9kKCkKICAgIHRleHQgPSBpbnB1dChmIk5o4bqtcCB0aMOhbmcvbsSD
>> "%B64_FILE%" echo bSBk4bqhbmcgTU0vWVlZWSwgRW50ZXIgxJHhu4MgZMO5bmcge206MDJkfS97eX06ICIpLnN0cmlw
>> "%B64_FILE%" echo KCkKICAgIGlmIG5vdCB0ZXh0OgogICAgICAgIHJldHVybiB5LCBtCiAgICBtbSwgeXkgPSB0ZXh0
>> "%B64_FILE%" echo LnJlcGxhY2UoIi0iLCAiLyIpLnNwbGl0KCIvIikKICAgIHJldHVybiBpbnQoeXkpLCBpbnQobW0p
>> "%B64_FILE%" echo CgoKZGVmIG1haW4oKToKICAgIHBhcnNlciA9IGFyZ3BhcnNlLkFyZ3VtZW50UGFyc2VyKCkKICAg
>> "%B64_FILE%" echo IHBhcnNlci5hZGRfYXJndW1lbnQoIi0tYWN0aW9uIiwgY2hvaWNlcz1bImNoZWNrIiwgInVwZGF0
>> "%B64_FILE%" echo ZSIsICJjaGVjay1jdXN0b20iLCAidXBkYXRlLWN1c3RvbSIsICJjb25maWctcmVwbyIsICJpbnN0
>> "%B64_FILE%" echo YWxsIiwgIm9wZW4tbG9nIl0sIHJlcXVpcmVkPVRydWUpCiAgICBwYXJzZXIuYWRkX2FyZ3VtZW50
>> "%B64_FILE%" echo KCItLWJhdCIsIGRlZmF1bHQ9IiIpCiAgICBhcmdzID0gcGFyc2VyLnBhcnNlX2FyZ3MoKQoKICAg
>> "%B64_FILE%" echo IHRyeToKICAgICAgICBjZmcgPSBsb2FkX2NvbmZpZygpCgogICAgICAgIGlmIGFyZ3MuYWN0aW9u
>> "%B64_FILE%" echo ID09ICJvcGVuLWxvZyI6CiAgICAgICAgICAgIG9wZW5fbG9nKCkKICAgICAgICAgICAgcmV0dXJu
>> "%B64_FILE%" echo IDAKCiAgICAgICAgaWYgYXJncy5hY3Rpb24gPT0gImNvbmZpZy1yZXBvIjoKICAgICAgICAgICAg
>> "%B64_FILE%" echo Zm9sZGVyID0gcGlja19mb2xkZXIoIkNo4buNbiB0aMawIG3hu6VjIHJlcG8gR2l0SHViIG15LWFp
>> "%B64_FILE%" echo LXNpdGUiLCBjZmcuZ2V0KCJyZXBvX2RpciIpIG9yIHIiRDpcVFRDT19Ub25LaG9fQXBwX1JlcG8i
>> "%B64_FILE%" echo KQogICAgICAgICAgICBpZiBub3QgZm9sZGVyOgogICAgICAgICAgICAgICAgcmFpc2UgUnVudGlt
>> "%B64_FILE%" echo ZUVycm9yKCJDaMawYSBjaOG7jW4gdGjGsCBt4bulYyByZXBvLiIpCiAgICAgICAgICAgIGNmZ1si
>> "%B64_FILE%" echo cmVwb19kaXIiXSA9IGZvbGRlcgogICAgICAgICAgICBzYXZlX2NvbmZpZyhjZmcpCiAgICAgICAg
>> "%B64_FILE%" echo ICAgIHByaW50KGYiW09LXSDEkMOjIGzGsHUgcmVwbzoge2ZvbGRlcn0iLCBmbHVzaD1UcnVlKQog
>> "%B64_FILE%" echo ICAgICAgICAgICByZXR1cm4gMAoKICAgICAgICByZXBvX2RpciA9IGNmZy5nZXQoInJlcG9fZGly
>> "%B64_FILE%" echo Iikgb3IgciJEOlxUVENPX1Rvbktob19BcHBfUmVwbyIKICAgICAgICBpZiBhcmdzLmFjdGlvbiBp
>> "%B64_FILE%" echo biAoInVwZGF0ZSIsICJ1cGRhdGUtY3VzdG9tIiwgImluc3RhbGwiKToKICAgICAgICAgICAgaWYg
>> "%B64_FILE%" echo bm90IG9zLnBhdGguaXNkaXIocmVwb19kaXIpOgogICAgICAgICAgICAgICAgZm9sZGVyID0gcGlj
>> "%B64_FILE%" echo a19mb2xkZXIoIkNo4buNbiB0aMawIG3hu6VjIHJlcG8gR2l0SHViIG15LWFpLXNpdGUiLCByZXBv
>> "%B64_FILE%" echo X2RpcikKICAgICAgICAgICAgICAgIGlmIG5vdCBmb2xkZXI6CiAgICAgICAgICAgICAgICAgICAg
>> "%B64_FILE%" echo cmFpc2UgUnVudGltZUVycm9yKCJDaMawYSBjaOG7jW4gdGjGsCBt4bulYyByZXBvLiIpCiAgICAg
>> "%B64_FILE%" echo ICAgICAgICAgICBjZmdbInJlcG9fZGlyIl0gPSBmb2xkZXIKICAgICAgICAgICAgICAgIHJlcG9f
>> "%B64_FILE%" echo ZGlyID0gZm9sZGVyCiAgICAgICAgICAgICAgICBzYXZlX2NvbmZpZyhjZmcpCgogICAgICAgIGlm
>> "%B64_FILE%" echo IGFyZ3MuYWN0aW9uID09ICJpbnN0YWxsIjoKICAgICAgICAgICAgaW5zdGFsbF90YXNrKGFyZ3Mu
>> "%B64_FILE%" echo YmF0KQogICAgICAgICAgICByZXR1cm4gMAoKICAgICAgICBpZiBhcmdzLmFjdGlvbiBpbiAoImNo
>> "%B64_FILE%" echo ZWNrIiwgInVwZGF0ZSIpOgogICAgICAgICAgICB5ZWFyLCBtb250aCA9IGN1cnJlbnRfcGVyaW9k
>> "%B64_FILE%" echo KCkKICAgICAgICBlbHNlOgogICAgICAgICAgICB5ZWFyLCBtb250aCA9IGFza19wZXJpb2QoKQoK
>> "%B64_FILE%" echo ICAgICAgICBpZiBhcmdzLmFjdGlvbiBpbiAoImNoZWNrIiwgImNoZWNrLWN1c3RvbSIpOgogICAg
>> "%B64_FILE%" echo ICAgICAgICBkaXJlY3RfY2hlY2soeWVhciwgbW9udGgpCiAgICAgICAgICAgIHJldHVybiAwCgog
>> "%B64_FILE%" echo ICAgICAgIGlmIGFyZ3MuYWN0aW9uIGluICgidXBkYXRlIiwgInVwZGF0ZS1jdXN0b20iKToKICAg
>> "%B64_FILE%" echo ICAgICAgICAgZGlyZWN0X3VwZGF0ZShyZXBvX2RpciwgeWVhciwgbW9udGgpCiAgICAgICAgICAg
>> "%B64_FILE%" echo IHJldHVybiAwCgogICAgICAgIHJldHVybiAwCiAgICBleGNlcHQgRXhjZXB0aW9uIGFzIGV4YzoK
>> "%B64_FILE%" echo ICAgICAgICBwcmludCgiXG5bTOG7lkldIiwgZXhjLCBmbHVzaD1UcnVlKQogICAgICAgIHByaW50
>> "%B64_FILE%" echo KCJMb2c6IiwgTE9HX0ZJTEUsIGZsdXNoPVRydWUpCiAgICAgICAgbG9nKGYiRVJST1I6IHtleGN9
>> "%B64_FILE%" echo IikKICAgICAgICByZXR1cm4gMQoKCmlmIF9fbmFtZV9fID09ICJfX21haW5fXyI6CiAgICBzeXMu
>> "%B64_FILE%" echo ZXhpdChtYWluKCkpCg==
python -c "import base64, pathlib, os; b=pathlib.Path(os.environ['B64_FILE']).read_text().replace('\n','').replace('\r','').strip(); pathlib.Path(os.environ['PY_MAIN']).write_bytes(base64.b64decode(b))"
exit /b %errorlevel%
