@echo off
setlocal EnableExtensions EnableDelayedExpansion
chcp 65001 >nul
title TTCO - Tim nguon ton kho Kho 1 = 1052.65 - v2

set "WORK_DIR=%~dp0"
set "PY_FILE=%WORK_DIR%ttco_find_kho1_1052_65_v2.py"
set "B64_FILE=%WORK_DIR%ttco_find_kho1_1052_65_v2.b64"

echo ============================================================
echo   TTCO - TIM NGUON TON KHO KHO 1 = 1.052,65 - V2
echo ============================================================
echo.
echo Ban v2 da sua:
echo - Khong dung TRY_CONVERT/TRY_CAST de tranh loi SQL Server cu.
echo - Sua loi TABLE_TYPE sai cho INFORMATION_SCHEMA.COLUMNS.
echo - Ket qua xuat dung vao thu muc chua file BAT, khong vao System32.
echo.
echo Ket qua se nam trong thu muc: ttco_check_output
echo.
pause

:WRITE_PY
> "%B64_FILE%" echo CiMgLSotIGNvZGluZzogdXRmLTggLSotCmltcG9ydCBjc3YKaW1wb3J0IG9zCmltcG9ydCByZQpp
>> "%B64_FILE%" echo bXBvcnQgc3VicHJvY2VzcwppbXBvcnQgc3lzCmZyb20gZGF0ZXRpbWUgaW1wb3J0IGRhdGV0aW1l
>> "%B64_FILE%" echo CmZyb20gcGF0aGxpYiBpbXBvcnQgUGF0aAoKU0VSVkVSID0gciJ0dXllbnRoYW5jdWFvbmcuY29t
>> "%B64_FILE%" echo LnZuLDUyMzc2IgpEQVRBQkFTRSA9ICJUVENPX1RIT05HS0UiClRBUkdFVF9WQUxVRSA9IDEwNTIu
>> "%B64_FILE%" echo NjUKVE9MRVJBTkNFID0gMC4wNQoKU0NSSVBUX0RJUiA9IFBhdGgoX19maWxlX18pLnJlc29sdmUo
>> "%B64_FILE%" echo KS5wYXJlbnQKIyBGaWxlIC5weSDEkcaw4bujYyBCQVQgZ2nhuqNpIG3DoyByYSBjw7luZyB0aMaw
>> "%B64_FILE%" echo IG3hu6VjIGNo4bupYSBCQVQsIG7Dqm4gb3V0cHV0IHPhur0gbuG6sW0gxJHDum5nIHRoxrAgbeG7
>> "%B64_FILE%" echo pWMgQkFULgpPVVRfRElSID0gU0NSSVBUX0RJUiAvICJ0dGNvX2NoZWNrX291dHB1dCIKT1VUX0RJ
>> "%B64_FILE%" echo Ui5ta2RpcihwYXJlbnRzPVRydWUsIGV4aXN0X29rPVRydWUpClNUQU1QID0gZGF0ZXRpbWUubm93
>> "%B64_FILE%" echo KCkuc3RyZnRpbWUoIiVZJW0lZF8lSCVNJVMiKQpPVVRfVFhUID0gT1VUX0RJUiAvIGYiY2hlY2tf
>> "%B64_FILE%" echo a2hvMV8xMDUyXzY1X3tTVEFNUH0udHh0IgpPVVRfQ1NWID0gT1VUX0RJUiAvIGYiY2hlY2tfa2hv
>> "%B64_FILE%" echo MV8xMDUyXzY1X3tTVEFNUH0uY3N2IgoKCmRlZiB3cml0ZShsaW5lPSIiKToKICAgIHByaW50KGxp
>> "%B64_FILE%" echo bmUpCiAgICB3aXRoIE9VVF9UWFQub3BlbigiYSIsIGVuY29kaW5nPSJ1dGYtOCIpIGFzIGY6CiAg
>> "%B64_FILE%" echo ICAgICAgZi53cml0ZShzdHIobGluZSkgKyAiXG4iKQoKCmRlZiBlbnN1cmVfcHlvZGJjKCk6CiAg
>> "%B64_FILE%" echo ICB0cnk6CiAgICAgICAgaW1wb3J0IHB5b2RiYyAgIyBub3FhCiAgICAgICAgcmV0dXJuCiAgICBl
>> "%B64_FILE%" echo eGNlcHQgRXhjZXB0aW9uOgogICAgICAgIHdyaXRlKCJDaMawYSBjw7MgcHlvZGJjLiDEkGFuZyB0
>> "%B64_FILE%" echo aOG7rSBjw6BpIHB5b2RiYy4uLiIpCiAgICAgICAgc3VicHJvY2Vzcy5jaGVja19jYWxsKFtzeXMu
>> "%B64_FILE%" echo ZXhlY3V0YWJsZSwgIi1tIiwgInBpcCIsICJpbnN0YWxsIiwgInB5b2RiYyJdKQoKCmRlZiBjb25u
>> "%B64_FILE%" echo ZWN0KCk6CiAgICBpbXBvcnQgcHlvZGJjCiAgICBjb25uX3N0ciA9ICgKICAgICAgICAiRFJJVkVS
>> "%B64_FILE%" echo PXtPREJDIERyaXZlciAxOCBmb3IgU1FMIFNlcnZlcn07IgogICAgICAgIGYiU0VSVkVSPXtTRVJW
>> "%B64_FILE%" echo RVJ9OyIKICAgICAgICBmIkRBVEFCQVNFPXtEQVRBQkFTRX07IgogICAgICAgICJUcnVzdGVkX0Nv
>> "%B64_FILE%" echo bm5lY3Rpb249eWVzOyIKICAgICAgICAiVHJ1c3RTZXJ2ZXJDZXJ0aWZpY2F0ZT15ZXM7IgogICAg
>> "%B64_FILE%" echo KQogICAgcmV0dXJuIHB5b2RiYy5jb25uZWN0KGNvbm5fc3RyLCB0aW1lb3V0PTE1KQoKCmRlZiBx
>> "%B64_FILE%" echo aWRlbnQobmFtZTogc3RyKSAtPiBzdHI6CiAgICByZXR1cm4gIlsiICsgc3RyKG5hbWUpLnJlcGxh
>> "%B64_FILE%" echo Y2UoIl0iLCAiXV0iKSArICJdIgoKCmRlZiBpc19udW1lcmljX3R5cGUodDogc3RyKSAtPiBib29s
>> "%B64_FILE%" echo OgogICAgcmV0dXJuIHN0cih0KS5sb3dlcigpIGluIHsKICAgICAgICAiaW50IiwgImJpZ2ludCIs
>> "%B64_FILE%" echo ICJzbWFsbGludCIsICJ0aW55aW50IiwgImRlY2ltYWwiLCAibnVtZXJpYyIsCiAgICAgICAgImZs
>> "%B64_FILE%" echo b2F0IiwgInJlYWwiLCAibW9uZXkiLCAic21hbGxtb25leSIKICAgIH0KCgpkZWYgc2FmZV9mbG9h
>> "%B64_FILE%" echo dCh2KToKICAgIHRyeToKICAgICAgICBpZiB2IGlzIE5vbmU6CiAgICAgICAgICAgIHJldHVybiBO
>> "%B64_FILE%" echo b25lCiAgICAgICAgcmV0dXJuIGZsb2F0KHYpCiAgICBleGNlcHQgRXhjZXB0aW9uOgogICAgICAg
>> "%B64_FILE%" echo IHJldHVybiBOb25lCgoKZGVmIGNhc3RfdG9fdGV4dF9zcWwoY29sOiBzdHIpIC0+IHN0cjoKICAg
>> "%B64_FILE%" echo ICMgS2jDtG5nIGTDuW5nIFRSWV9DT05WRVJUIHbDrCBTUUwgU2VydmVyL2NvbXBhdGliaWxpdHkg
>> "%B64_FILE%" echo bGV2ZWwgY+G7p2EgVFRDTyBjw7MgdGjhu4Mga2jDtG5nIGjhu5cgdHLhu6MuCiAgICByZXR1cm4g
>> "%B64_FILE%" echo ZiJDQVNUKHtxaWRlbnQoY29sKX0gQVMgTlZBUkNIQVIoMTAwKSkiCgoKZGVmIGNhc3RfdG9fZmxv
>> "%B64_FILE%" echo YXRfc3FsKGNvbDogc3RyKSAtPiBzdHI6CiAgICAjIEtow7RuZyBkw7luZyBUUllfQ0FTVCB2w6wg
>> "%B64_FILE%" echo U1FMIFNlcnZlci9jb21wYXRpYmlsaXR5IGxldmVsIGPDsyB0aOG7gyBraMO0bmcgaOG7lyB0cuG7
>> "%B64_FILE%" echo oy4KICAgIHJldHVybiBmIkNBU1Qoe3FpZGVudChjb2wpfSBBUyBGTE9BVCkiCgoKZGVmIG1haW4o
>> "%B64_FILE%" echo KToKICAgIGVuc3VyZV9weW9kYmMoKQogICAgaW1wb3J0IHB5b2RiYwoKICAgIHdyaXRlKCI9PT09
>> "%B64_FILE%" echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0i
>> "%B64_FILE%" echo KQogICAgd3JpdGUoIlRUQ08gLSBLSeG7gk0gVFJBIE5HVeG7kk4gVOG7kk4gS0hPIEtITyAxID0g
>> "%B64_FILE%" echo MS4wNTIsNjUgLSBWMiIpCiAgICB3cml0ZSgiPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
>> "%B64_FILE%" echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09IikKICAgIHdyaXRlKGYiU2VydmVyICAgOiB7
>> "%B64_FILE%" echo U0VSVkVSfSIpCiAgICB3cml0ZShmIkRhdGFiYXNlIDoge0RBVEFCQVNFfSIpCiAgICB3cml0ZShm
>> "%B64_FILE%" echo IlRoxrAgbeG7pWMgY2jhuqF5OiB7U0NSSVBUX0RJUn0iKQogICAgd3JpdGUoZiJHacOhIHRy4buL
>> "%B64_FILE%" echo IFRUQ09fQVBQIGLDoW86IHtUQVJHRVRfVkFMVUV9IikKICAgIHdyaXRlKGYiT3V0cHV0IFRYVDog
>> "%B64_FILE%" echo e09VVF9UWFR9IikKICAgIHdyaXRlKGYiT3V0cHV0IENTVjoge09VVF9DU1Z9IikKICAgIHdyaXRl
>> "%B64_FILE%" echo KCIiKQoKICAgIGNvbm4gPSBjb25uZWN0KCkKICAgIGN1ciA9IGNvbm4uY3Vyc29yKCkKICAgIHJl
>> "%B64_FILE%" echo c3VsdHMgPSBbXQoKICAgICMgMSkgS2nhu4NtIHRyYSB0cuG7sWMgdGnhur9wIENET1RIQU4gdGhl
>> "%B64_FILE%" echo byB04bqldCBj4bqjIGvhu7MuCiAgICB3cml0ZSgiMSkgS0nhu4JNIFRSQSBDRE9USEFOIFRIRU8g
>> "%B64_FILE%" echo VOG6pFQgQ+G6oiBL4buyIikKICAgIHdyaXRlKCItLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
>> "%B64_FILE%" echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0iKQogICAgdHJ5OgogICAgICAgIHNxbCA9
>> "%B64_FILE%" echo ICIiIgogICAgICAgIFNFTEVDVCBOYW1IVCwgVGhhbmdIVCwgTWFLaG8sIE1hVGhhbiwgU1VNKENB
>> "%B64_FILE%" echo U1QoVG9uQ0sgQVMgRkxPQVQpKSBBUyBUb25DSwogICAgICAgIEZST00gZGJvLkNET1RIQU4KICAg
>> "%B64_FILE%" echo ICAgICBXSEVSRSBDQVNUKE1hS2hvIEFTIE5WQVJDSEFSKDEwMCkpIElOIChOJzEnLCBOJzAxJywg
>> "%B64_FILE%" echo TidLaG8gMScpCiAgICAgICAgR1JPVVAgQlkgTmFtSFQsIFRoYW5nSFQsIE1hS2hvLCBNYVRoYW4K
>> "%B64_FILE%" echo ICAgICAgICBPUkRFUiBCWSBOYW1IVCBERVNDLCBUaGFuZ0hUIERFU0MsIE1hVGhhbjsKICAgICAg
>> "%B64_FILE%" echo ICAiIiIKICAgICAgICByb3dzID0gY3VyLmV4ZWN1dGUoc3FsKS5mZXRjaGFsbCgpCiAgICAgICAg
>> "%B64_FILE%" echo d3JpdGUoZiJT4buRIGTDsm5nIENET1RIQU4gS2hvIDE6IHtsZW4ocm93cyl9IikKICAgICAgICBm
>> "%B64_FILE%" echo b3IgciBpbiByb3dzWzoxMDBdOgogICAgICAgICAgICB2YWwgPSBmbG9hdChyLlRvbkNLIG9yIDAp
>> "%B64_FILE%" echo CiAgICAgICAgICAgIGxpbmUgPSBmIkNET1RIQU4gfCBOYW09e3IuTmFtSFR9IHwgVGhhbmc9e3Iu
>> "%B64_FILE%" echo VGhhbmdIVH0gfCBNYUtobz17ci5NYUtob30gfCBNYVRoYW49e3IuTWFUaGFufSB8IFRvbkNLPXt2
>> "%B64_FILE%" echo YWw6LC4yZn0iCiAgICAgICAgICAgIHdyaXRlKGxpbmUpCiAgICAgICAgICAgIHJlc3VsdHMuYXBw
>> "%B64_FILE%" echo ZW5kKHsKICAgICAgICAgICAgICAgICJzb3VyY2UiOiAiQ0RPVEhBTiIsCiAgICAgICAgICAgICAg
>> "%B64_FILE%" echo ICAic2NoZW1hIjogImRibyIsCiAgICAgICAgICAgICAgICAidGFibGUiOiAiQ0RPVEhBTiIsCiAg
>> "%B64_FILE%" echo ICAgICAgICAgICAgICAicGVyaW9kIjogZiJOYW1IVD17ci5OYW1IVH0gfCBUaGFuZ0hUPXtyLlRo
>> "%B64_FILE%" echo YW5nSFR9IiwKICAgICAgICAgICAgICAgICJraG9fY29sIjogIk1hS2hvIiwKICAgICAgICAgICAg
>> "%B64_FILE%" echo ICAgICJraG9fdmFsdWUiOiBzdHIoci5NYUtobyksCiAgICAgICAgICAgICAgICAidGhhbl9jb2wi
>> "%B64_FILE%" echo OiAiTWFUaGFuIiwKICAgICAgICAgICAgICAgICJ0aGFuX3ZhbHVlIjogc3RyKHIuTWFUaGFuKSwK
>> "%B64_FILE%" echo ICAgICAgICAgICAgICAgICJ2YWx1ZV9jb2wiOiAiVG9uQ0siLAogICAgICAgICAgICAgICAgInZh
>> "%B64_FILE%" echo bHVlIjogdmFsLAogICAgICAgICAgICAgICAgImRpZmZfdG9fMTA1Ml82NSI6IGFicyh2YWwgLSBU
>> "%B64_FILE%" echo QVJHRVRfVkFMVUUpLAogICAgICAgICAgICAgICAgIm5vdGUiOiAiQ0RPVEhBTiBncm91cGVkIGJ5
>> "%B64_FILE%" echo IE5hbUhULFRoYW5nSFQsTWFLaG8sTWFUaGFuIiwKICAgICAgICAgICAgfSkKICAgICAgICB3cml0
>> "%B64_FILE%" echo ZSgiIikKICAgIGV4Y2VwdCBFeGNlcHRpb24gYXMgZXhjOgogICAgICAgIHdyaXRlKGYiTOG7l2kg
>> "%B64_FILE%" echo a2nhu4NtIHRyYSBDRE9USEFOOiB7ZXhjfSIpCiAgICAgICAgd3JpdGUoIiIpCgogICAgIyAyKSBM
>> "%B64_FILE%" echo 4bqleSBkYW5oIHPDoWNoIGPhu5l0IMSRw7puZyBjw6FjaCwga2jDtG5nIGTDuW5nIFRBQkxFX1RZ
>> "%B64_FILE%" echo UEUgdHJvbmcgSU5GT1JNQVRJT05fU0NIRU1BLkNPTFVNTlMuCiAgICB3cml0ZSgiMikgUVXDiVQg
>> "%B64_FILE%" echo Q8OBQyBC4bqiTkcgQ8OTIEPhu5hUIEtITyBWw4AgQ+G7mFQgU+G7kCBMSeG7hlUiKQogICAgd3Jp
>> "%B64_FILE%" echo dGUoIi0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
>> "%B64_FILE%" echo LS0tLS0tLSIpCgogICAgY29sX3NxbCA9ICIiIgogICAgU0VMRUNUCiAgICAgICAgYy5UQUJMRV9T
>> "%B64_FILE%" echo Q0hFTUEsCiAgICAgICAgYy5UQUJMRV9OQU1FLAogICAgICAgIGMuQ09MVU1OX05BTUUsCiAgICAg
>> "%B64_FILE%" echo ICAgYy5EQVRBX1RZUEUKICAgIEZST00gSU5GT1JNQVRJT05fU0NIRU1BLkNPTFVNTlMgYwogICAg
>> "%B64_FILE%" echo SU5ORVIgSk9JTiBJTkZPUk1BVElPTl9TQ0hFTUEuVEFCTEVTIHQKICAgICAgICBPTiBjLlRBQkxF
>> "%B64_FILE%" echo X1NDSEVNQSA9IHQuVEFCTEVfU0NIRU1BCiAgICAgICBBTkQgYy5UQUJMRV9OQU1FID0gdC5UQUJM
>> "%B64_FILE%" echo RV9OQU1FCiAgICBXSEVSRSB0LlRBQkxFX1RZUEUgPSAnQkFTRSBUQUJMRScKICAgIE9SREVSIEJZ
>> "%B64_FILE%" echo IGMuVEFCTEVfU0NIRU1BLCBjLlRBQkxFX05BTUUsIGMuT1JESU5BTF9QT1NJVElPTjsKICAgICIi
>> "%B64_FILE%" echo IgogICAgY29scyA9IGN1ci5leGVjdXRlKGNvbF9zcWwpLmZldGNoYWxsKCkKCiAgICB0YWJsZXMg
>> "%B64_FILE%" echo PSB7fQogICAgZm9yIHNjaGVtYSwgdGFibGUsIGNvbCwgZHR5cGUgaW4gY29sczoKICAgICAgICB0
>> "%B64_FILE%" echo YWJsZXMuc2V0ZGVmYXVsdCgoc2NoZW1hLCB0YWJsZSksIFtdKS5hcHBlbmQoKGNvbCwgZHR5cGUp
>> "%B64_FILE%" echo KQoKICAgIGtob19wYXR0ZXJucyA9IHJlLmNvbXBpbGUociJeKE1hS2hvfEtob3xNYWt8TWFfS2hv
>> "%B64_FILE%" echo fElES2hvfEtob0lEKSR8S2hvIiwgcmUuSSkKICAgIHRoYW5fcGF0dGVybnMgPSByZS5jb21waWxl
>> "%B64_FILE%" echo KHIiKE1hVGhhbnxUZW5UaGFufExvYWlUaGFufFRoYW4pIiwgcmUuSSkKICAgIHZhbHVlX3BhdHRl
>> "%B64_FILE%" echo cm5zID0gcmUuY29tcGlsZShyIihUb258S2xnfEtMfEtob2lMdW9uZ3xMdW9uZ3xUYW58U0x8U29M
>> "%B64_FILE%" echo dW9uZ3xDdW9pfENLfE5oYXB8WHVhdCkiLCByZS5JKQogICAgcGVyaW9kX3BhdHRlcm5zID0gcmUu
>> "%B64_FILE%" echo Y29tcGlsZShyIl4oTmFtSFR8VGhhbmdIVHxOZ2F5SFR8TmdheXxOZ2F5Q1R8VGhhbmd8TmFtfENh
>> "%B64_FILE%" echo fEtpcCkkIiwgcmUuSSkKCiAgICBzY2FubmVkID0gMAogICAgc2tpcHBlZCA9IDAKCiAgICBmb3Ig
>> "%B64_FILE%" echo KHNjaGVtYSwgdGFibGUpLCB0YWJsZV9jb2xzIGluIHRhYmxlcy5pdGVtcygpOgogICAgICAgIGNv
>> "%B64_FILE%" echo bF9uYW1lcyA9IFtjIGZvciBjLCBfIGluIHRhYmxlX2NvbHNdCiAgICAgICAga2hvX2NvbHMgPSBb
>> "%B64_FILE%" echo YyBmb3IgYyBpbiBjb2xfbmFtZXMgaWYga2hvX3BhdHRlcm5zLnNlYXJjaChjKV0KICAgICAgICBp
>> "%B64_FILE%" echo ZiBub3Qga2hvX2NvbHM6CiAgICAgICAgICAgIGNvbnRpbnVlCgogICAgICAgIG51bV9jb2xzID0g
>> "%B64_FILE%" echo W2MgZm9yIGMsIHQgaW4gdGFibGVfY29scyBpZiBpc19udW1lcmljX3R5cGUodCkgYW5kIHZhbHVl
>> "%B64_FILE%" echo X3BhdHRlcm5zLnNlYXJjaChjKV0KICAgICAgICBpZiBub3QgbnVtX2NvbHM6CiAgICAgICAgICAg
>> "%B64_FILE%" echo IGNvbnRpbnVlCgogICAgICAgIHRoYW5fY29scyA9IFtjIGZvciBjIGluIGNvbF9uYW1lcyBpZiB0
>> "%B64_FILE%" echo aGFuX3BhdHRlcm5zLnNlYXJjaChjKV0KICAgICAgICBwZXJpb2RfY29scyA9IFtjIGZvciBjIGlu
>> "%B64_FILE%" echo IGNvbF9uYW1lcyBpZiBwZXJpb2RfcGF0dGVybnMuc2VhcmNoKGMpXQoKICAgICAgICBmb3Iga2hv
>> "%B64_FILE%" echo X2NvbCBpbiBraG9fY29sc1s6M106CiAgICAgICAgICAgIGZvciB2YWxfY29sIGluIG51bV9jb2xz
>> "%B64_FILE%" echo WzoyMF06CiAgICAgICAgICAgICAgICBzY2FubmVkICs9IDEKICAgICAgICAgICAgICAgIHRyeToK
>> "%B64_FILE%" echo ICAgICAgICAgICAgICAgICAgICBzZWxlY3RfZXh0cmEgPSBbXQogICAgICAgICAgICAgICAgICAg
>> "%B64_FILE%" echo IGdyb3VwX2V4dHJhID0gW10KICAgICAgICAgICAgICAgICAgICBleHRyYV9uYW1lcyA9IFtdCgog
>> "%B64_FILE%" echo ICAgICAgICAgICAgICAgICAgIGZvciBjIGluIHBlcmlvZF9jb2xzWzo1XSArIHRoYW5fY29sc1s6
>> "%B64_FILE%" echo M106CiAgICAgICAgICAgICAgICAgICAgICAgIHNlbGVjdF9leHRyYS5hcHBlbmQocWlkZW50KGMp
>> "%B64_FILE%" echo KQogICAgICAgICAgICAgICAgICAgICAgICBncm91cF9leHRyYS5hcHBlbmQocWlkZW50KGMpKQog
>> "%B64_FILE%" echo ICAgICAgICAgICAgICAgICAgICAgICBleHRyYV9uYW1lcy5hcHBlbmQoYykKCiAgICAgICAgICAg
>> "%B64_FILE%" echo ICAgICAgICAgZXh0cmFfc3FsID0gIiIKICAgICAgICAgICAgICAgICAgICBncm91cF9zcWwgPSAi
>> "%B64_FILE%" echo IgogICAgICAgICAgICAgICAgICAgIGlmIHNlbGVjdF9leHRyYToKICAgICAgICAgICAgICAgICAg
>> "%B64_FILE%" echo ICAgICAgZXh0cmFfc3FsID0gIiwgIiArICIsICIuam9pbihzZWxlY3RfZXh0cmEpCiAgICAgICAg
>> "%B64_FILE%" echo ICAgICAgICAgICAgICAgIGdyb3VwX3NxbCA9ICIsICIgKyAiLCAiLmpvaW4oZ3JvdXBfZXh0cmEp
>> "%B64_FILE%" echo CgogICAgICAgICAgICAgICAgICAgIGtob190ZXh0ID0gY2FzdF90b190ZXh0X3NxbChraG9fY29s
>> "%B64_FILE%" echo KQogICAgICAgICAgICAgICAgICAgIHZhbF9mbG9hdCA9IGNhc3RfdG9fZmxvYXRfc3FsKHZhbF9j
>> "%B64_FILE%" echo b2wpCgogICAgICAgICAgICAgICAgICAgIHNxbCA9IGYiIiIKICAgICAgICAgICAgICAgICAgICBT
>> "%B64_FILE%" echo RUxFQ1QgVE9QIDEwMAogICAgICAgICAgICAgICAgICAgICAgICB7cWlkZW50KGtob19jb2wpfSBB
>> "%B64_FILE%" echo UyBLaG9WYWx1ZQogICAgICAgICAgICAgICAgICAgICAgICB7ZXh0cmFfc3FsfSwKICAgICAgICAg
>> "%B64_FILE%" echo ICAgICAgICAgICAgICAgU1VNKHt2YWxfZmxvYXR9KSBBUyBDaGVja1ZhbHVlLAogICAgICAgICAg
>> "%B64_FILE%" echo ICAgICAgICAgICAgICBDT1VOVCgqKSBBUyBSb3dDb3VudAogICAgICAgICAgICAgICAgICAgIEZS
>> "%B64_FILE%" echo T00ge3FpZGVudChzY2hlbWEpfS57cWlkZW50KHRhYmxlKX0KICAgICAgICAgICAgICAgICAgICBX
>> "%B64_FILE%" echo SEVSRSB7a2hvX3RleHR9IElOIChOJzEnLCBOJzAxJywgTidLaG8gMScpCiAgICAgICAgICAgICAg
>> "%B64_FILE%" echo ICAgICAgR1JPVVAgQlkge3FpZGVudChraG9fY29sKX17Z3JvdXBfc3FsfQogICAgICAgICAgICAg
>> "%B64_FILE%" echo ICAgICAgIEhBVklORyBTVU0oe3ZhbF9mbG9hdH0pIElTIE5PVCBOVUxMCiAgICAgICAgICAgICAg
>> "%B64_FILE%" echo ICAgICAgT1JERVIgQlkgQUJTKFNVTSh7dmFsX2Zsb2F0fSkgLSA/KSBBU0M7CiAgICAgICAgICAg
>> "%B64_FILE%" echo ICAgICAgICAgIiIiCiAgICAgICAgICAgICAgICAgICAgcm93cyA9IGN1ci5leGVjdXRlKHNxbCwg
>> "%B64_FILE%" echo VEFSR0VUX1ZBTFVFKS5mZXRjaGFsbCgpCiAgICAgICAgICAgICAgICAgICAgaWYgbm90IHJvd3M6
>> "%B64_FILE%" echo CiAgICAgICAgICAgICAgICAgICAgICAgIGNvbnRpbnVlCgogICAgICAgICAgICAgICAgICAgIGZv
>> "%B64_FILE%" echo ciByIGluIHJvd3NbOjhdOgogICAgICAgICAgICAgICAgICAgICAgICB2YWwgPSBzYWZlX2Zsb2F0
>> "%B64_FILE%" echo KGdldGF0dHIociwgIkNoZWNrVmFsdWUiLCBOb25lKSkKICAgICAgICAgICAgICAgICAgICAgICAg
>> "%B64_FILE%" echo aWYgdmFsIGlzIE5vbmU6CiAgICAgICAgICAgICAgICAgICAgICAgICAgICBjb250aW51ZQoKICAg
>> "%B64_FILE%" echo ICAgICAgICAgICAgICAgICAgICAgIyBMxrB1IHThuqV0IGPhuqMgZMOybmcgZ+G6p24sIHbDoCBt
>> "%B64_FILE%" echo 4buZdCBz4buRIGTDsm5nIGTGsMahbmcgxJHhu4MgbmjDrG4gcXV5IGx14bqtdC4KICAgICAgICAg
>> "%B64_FILE%" echo ICAgICAgICAgICAgICAgZGlmZiA9IGFicyh2YWwgLSBUQVJHRVRfVkFMVUUpCiAgICAgICAgICAg
>> "%B64_FILE%" echo ICAgICAgICAgICAgIGlmIGRpZmYgPD0gMzAwIG9yICgwIDwgdmFsIDwgMTAwMDAwKToKICAgICAg
>> "%B64_FILE%" echo ICAgICAgICAgICAgICAgICAgICAgIHBlcmlvZCA9IFtdCiAgICAgICAgICAgICAgICAgICAgICAg
>> "%B64_FILE%" echo ICAgICB0aGFuID0gW10KICAgICAgICAgICAgICAgICAgICAgICAgICAgIGZvciBjIGluIHBlcmlv
>> "%B64_FILE%" echo ZF9jb2xzWzo1XToKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICBpZiBoYXNhdHRyKHIs
>> "%B64_FILE%" echo IGMpOgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICBwZXJpb2QuYXBwZW5kKGYi
>> "%B64_FILE%" echo e2N9PXtnZXRhdHRyKHIsIGMpfSIpCiAgICAgICAgICAgICAgICAgICAgICAgICAgICBmb3IgYyBp
>> "%B64_FILE%" echo biB0aGFuX2NvbHNbOjNdOgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIGlmIGhhc2F0
>> "%B64_FILE%" echo dHIociwgYyk6CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIHRoYW4uYXBwZW5k
>> "%B64_FILE%" echo KGYie2N9PXtnZXRhdHRyKHIsIGMpfSIpCgogICAgICAgICAgICAgICAgICAgICAgICAgICAgcmVz
>> "%B64_FILE%" echo dWx0cy5hcHBlbmQoewogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICJzb3VyY2UiOiAi
>> "%B64_FILE%" echo c2NhbiIsCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgInNjaGVtYSI6IHNjaGVtYSwK
>> "%B64_FILE%" echo ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAidGFibGUiOiB0YWJsZSwKICAgICAgICAg
>> "%B64_FILE%" echo ICAgICAgICAgICAgICAgICAgICAgICAicGVyaW9kIjogIiB8ICIuam9pbihwZXJpb2QpLAogICAg
>> "%B64_FILE%" echo ICAgICAgICAgICAgICAgICAgICAgICAgICAgICJraG9fY29sIjoga2hvX2NvbCwKICAgICAgICAg
>> "%B64_FILE%" echo ICAgICAgICAgICAgICAgICAgICAgICAia2hvX3ZhbHVlIjogc3RyKGdldGF0dHIociwgIktob1Zh
>> "%B64_FILE%" echo bHVlIiwgIiIpKSwKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAidGhhbl9jb2wiOiAi
>> "%B64_FILE%" echo IHwgIi5qb2luKHRoYW4pLAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICJ0aGFuX3Zh
>> "%B64_FILE%" echo bHVlIjogIiIsCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgInZhbHVlX2NvbCI6IHZh
>> "%B64_FILE%" echo bF9jb2wsCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgInZhbHVlIjogdmFsLAogICAg
>> "%B64_FILE%" echo ICAgICAgICAgICAgICAgICAgICAgICAgICAgICJkaWZmX3RvXzEwNTJfNjUiOiBkaWZmLAogICAg
>> "%B64_FILE%" echo ICAgICAgICAgICAgICAgICAgICAgICAgICAgICJub3RlIjogZiJSb3dDb3VudD17Z2V0YXR0cihy
>> "%B64_FILE%" echo LCAnUm93Q291bnQnLCAnJyl9IiwKICAgICAgICAgICAgICAgICAgICAgICAgICAgIH0pCiAgICAg
>> "%B64_FILE%" echo ICAgICAgICAgICBleGNlcHQgRXhjZXB0aW9uIGFzIGV4YzoKICAgICAgICAgICAgICAgICAgICBz
>> "%B64_FILE%" echo a2lwcGVkICs9IDEKICAgICAgICAgICAgICAgICAgICBjb250aW51ZQoKICAgIHJlc3VsdHNfc29y
>> "%B64_FILE%" echo dGVkID0gc29ydGVkKHJlc3VsdHMsIGtleT1sYW1iZGEgeDogeFsiZGlmZl90b18xMDUyXzY1Il0p
>> "%B64_FILE%" echo CgogICAgd3JpdGUoZiJT4buRIHBow6lwIHF1w6l0OiB7c2Nhbm5lZH0iKQogICAgd3JpdGUoZiJT
>> "%B64_FILE%" echo 4buRIHBow6lwIGLhu48gcXVhIGRvIGzhu5dpIGtp4buDdSBk4buvIGxp4buHdS9xdXnhu4FuOiB7
>> "%B64_FILE%" echo c2tpcHBlZH0iKQogICAgd3JpdGUoZiJT4buRIGvhur90IHF14bqjIHRodSDEkcaw4bujYzoge2xl
>> "%B64_FILE%" echo bihyZXN1bHRzX3NvcnRlZCl9IikKICAgIHdyaXRlKCIiKQogICAgd3JpdGUoIjMpIFRPUCA1MCBL
>> "%B64_FILE%" echo 4bq+VCBRVeG6oiBH4bqmTiAxLjA1Miw2NSBOSOG6pFQiKQogICAgd3JpdGUoIi0tLS0tLS0tLS0t
>> "%B64_FILE%" echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLSIpCgogICAg
>> "%B64_FILE%" echo Zm9yIGksIHIgaW4gZW51bWVyYXRlKHJlc3VsdHNfc29ydGVkWzo1MF0sIHN0YXJ0PTEpOgogICAg
>> "%B64_FILE%" echo ICAgIHdyaXRlKAogICAgICAgICAgICBmIntpOjAyZH0uIHtyWydzY2hlbWEnXX0ue3JbJ3RhYmxl
>> "%B64_FILE%" echo J119IHwgIgogICAgICAgICAgICBmIntyWydraG9fY29sJ119PXtyWydraG9fdmFsdWUnXX0gfCAi
>> "%B64_FILE%" echo CiAgICAgICAgICAgIGYie3JbJ3ZhbHVlX2NvbCddfT17clsndmFsdWUnXTosLjJmfSB8ICIKICAg
>> "%B64_FILE%" echo ICAgICAgICAgZiJM4buHY2g9e3JbJ2RpZmZfdG9fMTA1Ml82NSddOiwuMmZ9IHwgIgogICAgICAg
>> "%B64_FILE%" echo ICAgICBmIntyWydwZXJpb2QnXX0gfCB7clsndGhhbl9jb2wnXX0ge3JbJ3RoYW5fdmFsdWUnXX0g
>> "%B64_FILE%" echo fCB7clsnbm90ZSddfSIKICAgICAgICApCgogICAgd2l0aCBPVVRfQ1NWLm9wZW4oInciLCBuZXds
>> "%B64_FILE%" echo aW5lPSIiLCBlbmNvZGluZz0idXRmLTgtc2lnIikgYXMgZjoKICAgICAgICBmaWVsZG5hbWVzID0g
>> "%B64_FILE%" echo WwogICAgICAgICAgICAic291cmNlIiwgInNjaGVtYSIsICJ0YWJsZSIsICJwZXJpb2QiLCAia2hv
>> "%B64_FILE%" echo X2NvbCIsICJraG9fdmFsdWUiLAogICAgICAgICAgICAidGhhbl9jb2wiLCAidGhhbl92YWx1ZSIs
>> "%B64_FILE%" echo ICJ2YWx1ZV9jb2wiLCAidmFsdWUiLCAiZGlmZl90b18xMDUyXzY1IiwgIm5vdGUiCiAgICAgICAg
>> "%B64_FILE%" echo XQogICAgICAgIHcgPSBjc3YuRGljdFdyaXRlcihmLCBmaWVsZG5hbWVzPWZpZWxkbmFtZXMpCiAg
>> "%B64_FILE%" echo ICAgICAgdy53cml0ZWhlYWRlcigpCiAgICAgICAgZm9yIHIgaW4gcmVzdWx0c19zb3J0ZWQ6CiAg
>> "%B64_FILE%" echo ICAgICAgICAgIHcud3JpdGVyb3cocikKCiAgICB3cml0ZSgiIikKICAgIHdyaXRlKCI9PT09PT09
>> "%B64_FILE%" echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0tLS0tLS0tLS0tLS0iKQog
>> "%B64_FILE%" echo ICAgd3JpdGUoIkhPw4BOIFRIw4BOSCIpCiAgICB3cml0ZSgiPT09PT09PT09PT09PT09PT09PT09
>> "%B64_FILE%" echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09IikKICAgIHdyaXRlKGYiRmls
>> "%B64_FILE%" echo ZSBUWFQ6IHtPVVRfVFhUfSIpCiAgICB3cml0ZShmIkZpbGUgQ1NWOiB7T1VUX0NTVn0iKQogICAg
>> "%B64_FILE%" echo d3JpdGUoIiIpCiAgICB3cml0ZSgiQW5oIGfhu61pIGzhuqFpIHBo4bqnbiBUT1AgNTAga+G6v3Qg
>> "%B64_FILE%" echo cXXhuqMgZ+G6p24gMS4wNTIsNjUgbmjhuqV0LiIpCiAgICB3cml0ZSgiVMO0aSBz4bq9IGThu7Fh
>> "%B64_FILE%" echo IHbDoG8gYuG6o25nL2Phu5l0IMSRw7puZyDEkeG7gyBz4butYSBiYWNrZW5kL3NlcnZlci5weS4i
>> "%B64_FILE%" echo KQoKICAgIGNvbm4uY2xvc2UoKQoKCmlmIF9fbmFtZV9fID09ICJfX21haW5fXyI6CiAgICB0cnk6
>> "%B64_FILE%" echo CiAgICAgICAgbWFpbigpCiAgICBleGNlcHQgRXhjZXB0aW9uIGFzIGV4YzoKICAgICAgICB3cml0
>> "%B64_FILE%" echo ZSgiIikKICAgICAgICB3cml0ZSgiW0zhu5ZJXSAiICsgc3RyKGV4YykpCiAgICAgICAgd3JpdGUo
>> "%B64_FILE%" echo Iktp4buDbSB0cmEgbOG6oWkga+G6v3QgbuG7kWkgU1FMIFNlcnZlciwgT0RCQyBEcml2ZXIgMTgg
>> "%B64_FILE%" echo aG/hurdjIHF1eeG7gW4gdHJ1eSBj4bqtcCBEQi4iKQogICAgICAgIHN5cy5leGl0KDEpCg==
python -c "import base64, pathlib, os; b=pathlib.Path(os.environ['B64_FILE']).read_text().replace('\n','').replace('\r','').strip(); pathlib.Path(os.environ['PY_FILE']).write_bytes(base64.b64decode(b))"
if errorlevel 1 (
    echo [LOI] Khong tao duoc file Python tam.
    pause
    exit /b 1
)

python "%PY_FILE%"
echo.
pause
