@echo off
setlocal EnableExtensions EnableDelayedExpansion
chcp 65001 >nul
title TTCO FINAL G3_BC05A_2 to GitHub - v16

set "CONFIG_DIR=%LOCALAPPDATA%\TTCO_TonKho_Final_G3BC05A_To_GitHub"
set "PY_MAIN=%CONFIG_DIR%\TTCO_Final_G3BC05A_To_GitHub_v16.py"
set "B64_FILE=%CONFIG_DIR%\TTCO_Final_G3BC05A_To_GitHub_v16.b64"

if not exist "%CONFIG_DIR%" mkdir "%CONFIG_DIR%" >nul 2>&1

call :WRITE_PY
if errorlevel 1 (
    echo [LOI] Khong tao duoc file Python tam.
    pause
    exit /b 1
)

if /I "%~1"=="--auto" (
    python "%PY_MAIN%" --action update --bat "%~f0"
    exit /b %errorlevel%
)

:MENU
cls
echo ============================================================
echo      TTCO - LAY TON KHO TU BANG KET QUA CUOI TTCO_APP v16
echo ============================================================
echo Nguon dung theo SQL live bat duoc:
echo   TTCO_THONGKE.dbo.G3_BC05A_2_######
echo.
echo Khong lay:
echo   - Excel
echo   - CDOTHAN truc tiep
echo   - G3_BC05A_1_* trung gian
echo.
echo  [1] Cap nhat GitHub ngay
echo.
echo  [2] Kiem tra bang nguon va Kho 1 truoc khi up
echo.
echo  [3] Chon lai thu muc repo GitHub my-ai-site
echo.
echo  [4] Cai dat tu dong khi dang nhap Windows
echo.
echo  [5] Mo file log
echo.
echo  [0] Thoat
echo.
echo ============================================================
choice /C 123450 /N /M "Chon chuc nang [1/2/3/4/5/0]: "

if errorlevel 6 exit /b 0
if errorlevel 5 (
    python "%PY_MAIN%" --action open-log --bat "%~f0"
    goto MENU
)
if errorlevel 4 (
    python "%PY_MAIN%" --action install --bat "%~f0"
    pause
    goto MENU
)
if errorlevel 3 (
    python "%PY_MAIN%" --action config-repo --bat "%~f0"
    pause
    goto MENU
)
if errorlevel 2 (
    python "%PY_MAIN%" --action check --bat "%~f0"
    pause
    goto MENU
)
if errorlevel 1 (
    python "%PY_MAIN%" --action update --bat "%~f0"
    pause
    goto MENU
)

goto MENU

:WRITE_PY
> "%B64_FILE%" echo IyAtKi0gY29kaW5nOiB1dGYtOCAtKi0KaW1wb3J0IGFyZ3BhcnNlCmltcG9ydCBqc29uCmltcG9y
>> "%B64_FILE%" echo dCBvcwppbXBvcnQgcmUKaW1wb3J0IHN1YnByb2Nlc3MKaW1wb3J0IHN5cwpmcm9tIGRhdGV0aW1l
>> "%B64_FILE%" echo IGltcG9ydCBkYXRldGltZQpmcm9tIHBhdGhsaWIgaW1wb3J0IFBhdGgKClNFUlZFUiA9IHIidHV5
>> "%B64_FILE%" echo ZW50aGFuY3Vhb25nLmNvbS52biw1MjM3NiIKREJfUkVQT1JUID0gIlRUQ09fVEhPTkdLRSIKREJf
>> "%B64_FILE%" echo TUFTVEVSID0gIlRUQ09fUVRIVCIKClJFUE9fVVJMID0gImh0dHBzOi8vZ2l0aHViLmNvbS90dXll
>> "%B64_FILE%" echo bjExMDIvbXktYWktc2l0ZS5naXQiCkJSQU5DSCA9ICJtYWluIgpKU09OX1JFTCA9IG9zLnBhdGgu
>> "%B64_FILE%" echo am9pbigicHVibGljIiwgImRhdGEiLCAidG9uX2tob19sYXRlc3QuanNvbiIpClRBU0tfTkFNRSA9
>> "%B64_FILE%" echo ICJUVENPX1Rvbktob19GaW5hbF9HM0JDMDVBX1RvX0dpdEh1Yl9PbkxvZ29uIgoKQ09ORklHX0RJ
>> "%B64_FILE%" echo UiA9IFBhdGgob3MuZW52aXJvbi5nZXQoIkxPQ0FMQVBQREFUQSIsIHN0cihQYXRoLmhvbWUoKSkp
>> "%B64_FILE%" echo KSAvICJUVENPX1Rvbktob19GaW5hbF9HM0JDMDVBX1RvX0dpdEh1YiIKQ09ORklHX0ZJTEUgPSBD
>> "%B64_FILE%" echo T05GSUdfRElSIC8gImNvbmZpZy5qc29uIgpMT0dfRklMRSA9IENPTkZJR19ESVIgLyAiVFRDT19G
>> "%B64_FILE%" echo aW5hbF9HM0JDMDVBX1RvX0dpdEh1Yi5sb2ciCgpERVNLVE9QID0gUGF0aChvcy5lbnZpcm9uLmdl
>> "%B64_FILE%" echo dCgiVVNFUlBST0ZJTEUiLCBzdHIoUGF0aC5ob21lKCkpKSkgLyAiRGVza3RvcCIKQ0hFQ0tfRElS
>> "%B64_FILE%" echo ID0gREVTS1RPUCAvICJUVENPX0NIRUNLX0ZJTkFMX0czQkMwNUEiCgoKZGVmIGxvZyhtc2c6IHN0
>> "%B64_FILE%" echo cikgLT4gTm9uZToKICAgIENPTkZJR19ESVIubWtkaXIocGFyZW50cz1UcnVlLCBleGlzdF9vaz1U
>> "%B64_FILE%" echo cnVlKQogICAgd2l0aCBMT0dfRklMRS5vcGVuKCJhIiwgZW5jb2Rpbmc9InV0Zi04IikgYXMgZjoK
>> "%B64_FILE%" echo ICAgICAgICBmLndyaXRlKGYiW3tkYXRldGltZS5ub3coKTolWS0lbS0lZCAlSDolTTolU31dIHtt
>> "%B64_FILE%" echo c2d9XG4iKQoKCmRlZiBydW4oY21kLCBjd2Q9Tm9uZSwgY2hlY2s9VHJ1ZSk6CiAgICBwcmludCgi
>> "%B64_FILE%" echo XG4+ICIgKyAiICIuam9pbihjbWQpKQogICAgcCA9IHN1YnByb2Nlc3MucnVuKGNtZCwgY3dkPWN3
>> "%B64_FILE%" echo ZCkKICAgIGlmIGNoZWNrIGFuZCBwLnJldHVybmNvZGUgIT0gMDoKICAgICAgICByYWlzZSBSdW50
>> "%B64_FILE%" echo aW1lRXJyb3IoZiJM4buHbmggbOG7l2kgbcOjIHtwLnJldHVybmNvZGV9OiB7JyAnLmpvaW4oY21k
>> "%B64_FILE%" echo KX0iKQogICAgcmV0dXJuIHAucmV0dXJuY29kZQoKCmRlZiBlbnN1cmVfcHlvZGJjKCk6CiAgICB0
>> "%B64_FILE%" echo cnk6CiAgICAgICAgaW1wb3J0IHB5b2RiYyAgIyBub3FhCiAgICAgICAgcmV0dXJuCiAgICBleGNl
>> "%B64_FILE%" echo cHQgRXhjZXB0aW9uOgogICAgICAgIHByaW50KCJbSU5GT10gQ2jGsGEgY8OzIHB5b2RiYy4gxJBh
>> "%B64_FILE%" echo bmcgY8OgaSBweW9kYmMuLi4iKQogICAgICAgIHN1YnByb2Nlc3MuY2hlY2tfY2FsbChbc3lzLmV4
>> "%B64_FILE%" echo ZWN1dGFibGUsICItbSIsICJwaXAiLCAiaW5zdGFsbCIsICJweW9kYmMiXSkKCgpkZWYgY29ubmVj
>> "%B64_FILE%" echo dChkYj1EQl9SRVBPUlQpOgogICAgaW1wb3J0IHB5b2RiYwogICAgY29ubl9zdHIgPSAoCiAgICAg
>> "%B64_FILE%" echo ICAgIkRSSVZFUj17T0RCQyBEcml2ZXIgMTggZm9yIFNRTCBTZXJ2ZXJ9OyIKICAgICAgICBmIlNF
>> "%B64_FILE%" echo UlZFUj17U0VSVkVSfTsiCiAgICAgICAgZiJEQVRBQkFTRT17ZGJ9OyIKICAgICAgICAiVHJ1c3Rl
>> "%B64_FILE%" echo ZF9Db25uZWN0aW9uPXllczsiCiAgICAgICAgIlRydXN0U2VydmVyQ2VydGlmaWNhdGU9eWVzOyIK
>> "%B64_FILE%" echo ICAgICkKICAgIHJldHVybiBweW9kYmMuY29ubmVjdChjb25uX3N0ciwgdGltZW91dD0yMCkKCgpk
>> "%B64_FILE%" echo ZWYgcWlkZW50KG5hbWU6IHN0cikgLT4gc3RyOgogICAgcmV0dXJuICJbIiArIHN0cihuYW1lKS5y
>> "%B64_FILE%" echo ZXBsYWNlKCJdIiwgIl1dIikgKyAiXSIKCgpkZWYgbm9ybWFsaXplX3RleHQodik6CiAgICBpZiB2
>> "%B64_FILE%" echo IGlzIE5vbmU6CiAgICAgICAgcmV0dXJuICIiCiAgICBzID0gc3RyKHYpLnJlcGxhY2UoIlx4YTAi
>> "%B64_FILE%" echo LCAiICIpLnN0cmlwKCkKICAgIHMgPSByZS5zdWIociJccysiLCAiICIsIHMpCiAgICByZXR1cm4g
>> "%B64_FILE%" echo cwoKCmRlZiBub3JtYWxpemVfY29hbF9uYW1lKHYpOgogICAgcyA9IG5vcm1hbGl6ZV90ZXh0KHYp
>> "%B64_FILE%" echo CiAgICBzID0gcmUuc3ViKHIiKD9pKVxiMWNcYiIsICIxQyIsIHMpCiAgICBzID0gcmUuc3ViKHIi
>> "%B64_FILE%" echo KD9pKVxiOGNcYiIsICI4QyIsIHMpCiAgICByZXR1cm4gcwoKCmRlZiBjbGVhbl9udW1iZXIodik6
>> "%B64_FILE%" echo CiAgICBpZiB2IGlzIE5vbmU6CiAgICAgICAgcmV0dXJuIDAuMAogICAgdHJ5OgogICAgICAgIHJl
>> "%B64_FILE%" echo dHVybiBmbG9hdCh2KQogICAgZXhjZXB0IEV4Y2VwdGlvbjoKICAgICAgICByZXR1cm4gMC4wCgoK
>> "%B64_FILE%" echo ZGVmIGtob19zb3J0X2tleSh0ZW5fa2hvLCBtYV9raG8pOgogICAgdGV4dCA9IHRlbl9raG8gb3Ig
>> "%B64_FILE%" echo bWFfa2hvIG9yICIiCiAgICBtID0gcmUuc2VhcmNoKHIiKFxkKykiLCB0ZXh0KQogICAgbiA9IGlu
>> "%B64_FILE%" echo dChtLmdyb3VwKDEpKSBpZiBtIGVsc2UgOTk5OQogICAgdDQgPSAxIGlmICJUNCIgaW4gdGV4dC51
>> "%B64_FILE%" echo cHBlcigpIGVsc2UgMAogICAgcmV0dXJuIChuLCB0NCwgdGV4dCkKCgpkZWYgbG9hZF9jb25maWco
>> "%B64_FILE%" echo KToKICAgIENPTkZJR19ESVIubWtkaXIocGFyZW50cz1UcnVlLCBleGlzdF9vaz1UcnVlKQogICAg
>> "%B64_FILE%" echo aWYgQ09ORklHX0ZJTEUuZXhpc3RzKCk6CiAgICAgICAgdHJ5OgogICAgICAgICAgICByZXR1cm4g
>> "%B64_FILE%" echo anNvbi5sb2FkcyhDT05GSUdfRklMRS5yZWFkX3RleHQoZW5jb2Rpbmc9InV0Zi04IikpCiAgICAg
>> "%B64_FILE%" echo ICAgZXhjZXB0IEV4Y2VwdGlvbjoKICAgICAgICAgICAgcGFzcwogICAgcmV0dXJuIHsKICAgICAg
>> "%B64_FILE%" echo ICAicmVwb19kaXIiOiByIkQ6XFRUQ09fVG9uS2hvX0FwcF9SZXBvIiwKICAgIH0KCgpkZWYgc2F2
>> "%B64_FILE%" echo ZV9jb25maWcoY2ZnKToKICAgIENPTkZJR19ESVIubWtkaXIocGFyZW50cz1UcnVlLCBleGlzdF9v
>> "%B64_FILE%" echo az1UcnVlKQogICAgQ09ORklHX0ZJTEUud3JpdGVfdGV4dChqc29uLmR1bXBzKGNmZywgZW5zdXJl
>> "%B64_FILE%" echo X2FzY2lpPUZhbHNlLCBpbmRlbnQ9MiksIGVuY29kaW5nPSJ1dGYtOCIpCiAgICBsb2coZiJTQVZF
>> "%B64_FILE%" echo X0NPTkZJRyB7Y2ZnfSIpCgoKZGVmIHBpY2tfZm9sZGVyKHRpdGxlOiBzdHIsIGluaXRpYWw6IHN0
>> "%B64_FILE%" echo ciA9ICIiKSAtPiBzdHI6CiAgICB0cnk6CiAgICAgICAgaW1wb3J0IHRraW50ZXIgYXMgdGsKICAg
>> "%B64_FILE%" echo ICAgICBmcm9tIHRraW50ZXIgaW1wb3J0IGZpbGVkaWFsb2cKICAgICAgICByb290ID0gdGsuVGso
>> "%B64_FILE%" echo KQogICAgICAgIHJvb3Qud2l0aGRyYXcoKQogICAgICAgIHJvb3QuYXR0cmlidXRlcygiLXRvcG1v
>> "%B64_FILE%" echo c3QiLCBUcnVlKQogICAgICAgIGlmIG5vdCBpbml0aWFsIG9yIG5vdCBvcy5wYXRoLmlzZGlyKGlu
>> "%B64_FILE%" echo aXRpYWwpOgogICAgICAgICAgICBpbml0aWFsID0gciJEOlxUVENPX1Rvbktob19BcHBfUmVwbyIg
>> "%B64_FILE%" echo aWYgb3MucGF0aC5pc2RpcihyIkQ6XFRUQ09fVG9uS2hvX0FwcF9SZXBvIikgZWxzZSBzdHIoUGF0
>> "%B64_FILE%" echo aC5ob21lKCkpCiAgICAgICAgZm9sZGVyID0gZmlsZWRpYWxvZy5hc2tkaXJlY3RvcnkodGl0bGU9
>> "%B64_FILE%" echo dGl0bGUsIGluaXRpYWxkaXI9aW5pdGlhbCwgbXVzdGV4aXN0PUZhbHNlKQogICAgICAgIHJvb3Qu
>> "%B64_FILE%" echo ZGVzdHJveSgpCiAgICAgICAgcmV0dXJuIGZvbGRlciBvciAiIgogICAgZXhjZXB0IEV4Y2VwdGlv
>> "%B64_FILE%" echo biBhcyBleGM6CiAgICAgICAgcHJpbnQoZiJbQ+G6ok5IIELDgU9dIEtow7RuZyBt4bufIMSRxrDh
>> "%B64_FILE%" echo u6NjIHBvcHVwIGNo4buNbiB0aMawIG3hu6VjOiB7ZXhjfSIpCiAgICAgICAgcmV0dXJuIGlucHV0
>> "%B64_FILE%" echo KCJOaOG6rXAgxJHGsOG7nW5nIGThuqtuIHRoxrAgbeG7pWMgcmVwbzogIikuc3RyaXAoKS5zdHJp
>> "%B64_FILE%" echo cCgnIicpCgoKZGVmIGNvbW1hbmRfZXhpc3RzKG5hbWU6IHN0cikgLT4gYm9vbDoKICAgIHRyeToK
>> "%B64_FILE%" echo ICAgICAgICBzdWJwcm9jZXNzLnJ1bihbbmFtZSwgIi0tdmVyc2lvbiJdLCBzdGRvdXQ9c3VicHJv
>> "%B64_FILE%" echo Y2Vzcy5ERVZOVUxMLCBzdGRlcnI9c3VicHJvY2Vzcy5ERVZOVUxMKQogICAgICAgIHJldHVybiBU
>> "%B64_FILE%" echo cnVlCiAgICBleGNlcHQgRXhjZXB0aW9uOgogICAgICAgIHJldHVybiBGYWxzZQoKCmRlZiBlbnN1
>> "%B64_FILE%" echo cmVfZ2l0KCkgLT4gTm9uZToKICAgIGlmIGNvbW1hbmRfZXhpc3RzKCJnaXQiKToKICAgICAgICBy
>> "%B64_FILE%" echo ZXR1cm4KICAgIHByaW50KCJbQ+G6ok5IIELDgU9dIEtow7RuZyB0w6xtIHRo4bqleSBHaXQuIMSQ
>> "%B64_FILE%" echo YW5nIHRo4butIGPDoGkgR2l0IGLhurFuZyB3aW5nZXQuLi4iKQogICAgaWYgY29tbWFuZF9leGlz
>> "%B64_FILE%" echo dHMoIndpbmdldCIpOgogICAgICAgIHN1YnByb2Nlc3MucnVuKFsKICAgICAgICAgICAgIndpbmdl
>> "%B64_FILE%" echo dCIsICJpbnN0YWxsIiwgIi0taWQiLCAiR2l0LkdpdCIsICItZSIsICItLXNvdXJjZSIsICJ3aW5n
>> "%B64_FILE%" echo ZXQiLAogICAgICAgICAgICAiLS1zaWxlbnQiLCAiLS1hY2NlcHQtcGFja2FnZS1hZ3JlZW1lbnRz
>> "%B64_FILE%" echo IiwgIi0tYWNjZXB0LXNvdXJjZS1hZ3JlZW1lbnRzIgogICAgICAgIF0pCiAgICBpZiBub3QgY29t
>> "%B64_FILE%" echo bWFuZF9leGlzdHMoImdpdCIpOgogICAgICAgIHJhaXNlIFJ1bnRpbWVFcnJvcigiS2jDtG5nIHTD
>> "%B64_FILE%" echo rG0gdGjhuqV5IEdpdC4gSMOjeSBjw6BpIEdpdCBmb3IgV2luZG93cyBy4buTaSBjaOG6oXkgbOG6
>> "%B64_FILE%" echo oWkuIikKCgpkZWYgZW5zdXJlX3JlcG8ocmVwb19kaXI6IHN0cikgLT4gTm9uZToKICAgIHJlcG8g
>> "%B64_FILE%" echo PSBQYXRoKHJlcG9fZGlyKQogICAgaWYgKHJlcG8gLyAiLmdpdCIpLmlzX2RpcigpOgogICAgICAg
>> "%B64_FILE%" echo IHByaW50KGYiW09LXSBSZXBvIEdpdEh1YiBo4bujcCBs4buHOiB7cmVwb30iKQogICAgICAgIHJl
>> "%B64_FILE%" echo dHVybgogICAgcmVwby5ta2RpcihwYXJlbnRzPVRydWUsIGV4aXN0X29rPVRydWUpCiAgICBpZiBh
>> "%B64_FILE%" echo bnkocmVwby5pdGVyZGlyKCkpOgogICAgICAgIHJhaXNlIFJ1bnRpbWVFcnJvcihmIlRoxrAgbeG7
>> "%B64_FILE%" echo pWMgxJHDoyBjw7MgZmlsZSBuaMawbmcga2jDtG5nIGPDsyAuZ2l0OiB7cmVwb30uIEjDo3kgY2jh
>> "%B64_FILE%" echo u41uIMSRw7puZyByZXBvIGhv4bq3YyB0aMawIG3hu6VjIHLhu5duZy4iKQogICAgcnVuKFsiZ2l0
>> "%B64_FILE%" echo IiwgImNsb25lIiwgUkVQT19VUkwsIHN0cihyZXBvKV0pCgoKZGVmIGdldF9jb2x1bW5zKGN1ciwg
>> "%B64_FILE%" echo dGFibGVfbmFtZTogc3RyKToKICAgIHJvd3MgPSBjdXIuZXhlY3V0ZSgiIiIKICAgICAgICBTRUxF
>> "%B64_FILE%" echo Q1QgQ09MVU1OX05BTUUKICAgICAgICBGUk9NIElORk9STUFUSU9OX1NDSEVNQS5DT0xVTU5TCiAg
>> "%B64_FILE%" echo ICAgICAgV0hFUkUgVEFCTEVfU0NIRU1BPSdkYm8nIEFORCBUQUJMRV9OQU1FPT8KICAgICAgICBP
>> "%B64_FILE%" echo UkRFUiBCWSBPUkRJTkFMX1BPU0lUSU9OCiAgICAiIiIsIHRhYmxlX25hbWUpLmZldGNoYWxsKCkK
>> "%B64_FILE%" echo ICAgIHJldHVybiBbci5DT0xVTU5fTkFNRSBmb3IgciBpbiByb3dzXQoKCmRlZiBmaW5kX2xhdGVz
>> "%B64_FILE%" echo dF9maW5hbF90YWJsZSgpOgogICAgIiIiCiAgICBUVENPX0FQUCB04bqhbyBi4bqjbmcgdOG7lW5n
>> "%B64_FILE%" echo IGjhu6NwIGN14buRaSBk4bqhbmcgRzNfQkMwNUFfMl8jIyMjIyMuCiAgICBLaMO0bmcgbOG6pXkg
>> "%B64_FILE%" echo RzNfQkMwNUFfMV8qLCBraMO0bmcgbOG6pXkgRzNfQkMwNUFfMmFfKiwga2jDtG5nIGzhuqV5IEcz
>> "%B64_FILE%" echo X0JDMDVBXzJiXyosCiAgICBraMO0bmcgbOG6pXkgRzNfQkMwNUFfMl8jIyMjIyNfIyMjIyMjLgog
>> "%B64_FILE%" echo ICAgIiIiCiAgICBjb25uID0gY29ubmVjdChEQl9SRVBPUlQpCiAgICBjdXIgPSBjb25uLmN1cnNv
>> "%B64_FILE%" echo cigpCgogICAgcm93cyA9IGN1ci5leGVjdXRlKCIiIgogICAgICAgIFNFTEVDVCBuYW1lLCBjcmVh
>> "%B64_FILE%" echo dGVfZGF0ZSwgbW9kaWZ5X2RhdGUKICAgICAgICBGUk9NIHN5cy50YWJsZXMKICAgICAgICBXSEVS
>> "%B64_FILE%" echo RSBuYW1lIExJS0UgJ0czX0JDMDVBXzJfJScKICAgICAgICBPUkRFUiBCWSBjcmVhdGVfZGF0ZSBE
>> "%B64_FILE%" echo RVNDLCBtb2RpZnlfZGF0ZSBERVNDLCBuYW1lIERFU0MKICAgICIiIikuZmV0Y2hhbGwoKQoKICAg
>> "%B64_FILE%" echo IGNhbmRpZGF0ZXMgPSBbXQogICAgZm9yIHIgaW4gcm93czoKICAgICAgICBuYW1lID0gci5uYW1l
>> "%B64_FILE%" echo CiAgICAgICAgaWYgbm90IHJlLm1hdGNoKHIiXkczX0JDMDVBXzJfXGQrJCIsIG5hbWUpOgogICAg
>> "%B64_FILE%" echo ICAgICAgICBjb250aW51ZQogICAgICAgIGNvbHMgPSBzZXQoZ2V0X2NvbHVtbnMoY3VyLCBuYW1l
>> "%B64_FILE%" echo KSkKICAgICAgICByZXF1aXJlZCA9IHsiTWFLaG8iLCAiTWFUaGFuIiwgIlRvbkRLIiwgIk5oYXBU
>> "%B64_FILE%" echo SyIsICJYdWF0VEsiLCAiVG9uQ0sifQogICAgICAgIGlmIG5vdCByZXF1aXJlZC5pc3N1YnNldChj
>> "%B64_FILE%" echo b2xzKToKICAgICAgICAgICAgY29udGludWUKICAgICAgICBjYW5kaWRhdGVzLmFwcGVuZChyKQoK
>> "%B64_FILE%" echo ICAgIGNvbm4uY2xvc2UoKQoKICAgIGlmIG5vdCBjYW5kaWRhdGVzOgogICAgICAgIHJhaXNlIFJ1
>> "%B64_FILE%" echo bnRpbWVFcnJvcigKICAgICAgICAgICAgIktow7RuZyB0w6xtIHRo4bqleSBi4bqjbmcga+G6v3Qg
>> "%B64_FILE%" echo cXXhuqMgY3Xhu5FpIEczX0JDMDVBXzJfIyMjIyMjLiAiCiAgICAgICAgICAgICJIw6N5IG3hu58g
>> "%B64_FILE%" echo VFRDT19BUFAsIGLhuqVtIFhlbSBrcSDEkeG7gyB04bqhbyBi4bqjbmcga+G6v3QgcXXhuqMgdHLG
>> "%B64_FILE%" echo sOG7m2MgcuG7k2kgY2jhuqF5IGzhuqFpLiIKICAgICAgICApCgogICAgcmV0dXJuIGNhbmRpZGF0
>> "%B64_FILE%" echo ZXNbMF0ubmFtZSwgY2FuZGlkYXRlc1s6MTVdCgoKZGVmIHJlYWRfZmluYWxfcm93cyh0YWJsZV9u
>> "%B64_FILE%" echo YW1lOiBzdHIpOgogICAgY29ubiA9IGNvbm5lY3QoREJfUkVQT1JUKQogICAgY3VyID0gY29ubi5j
>> "%B64_FILE%" echo dXJzb3IoKQoKICAgIHNxbCA9IGYiIiIKICAgIFNFTEVDVAogICAgICAgIHIuTWFLaG8sCiAgICAg
>> "%B64_FILE%" echo ICAgQ09BTEVTQ0Uoay5UZW5LaG9Nb2ksIGsuVGVuS2hvLCByLk1hS2hvKSBBUyBUZW5LaG8sCiAg
>> "%B64_FILE%" echo ICAgICAgci5NYVRoYW4sCiAgICAgICAgQ09BTEVTQ0UodC5UZW5YSywgdC5UZW5UaGFuLCByLk1h
>> "%B64_FILE%" echo VGhhbikgQVMgVGVuVGhhbiwKICAgICAgICBDQVNUKElTTlVMTChyLlRvbkRLLCAwKSBBUyBGTE9B
>> "%B64_FILE%" echo VCkgQVMgVG9uREssCiAgICAgICAgQ0FTVChJU05VTEwoci5OaGFwVEssIDApIEFTIEZMT0FUKSBB
>> "%B64_FILE%" echo UyBOaGFwVEssCiAgICAgICAgQ0FTVChJU05VTEwoci5YdWF0VEssIDApIEFTIEZMT0FUKSBBUyBY
>> "%B64_FILE%" echo dWF0VEssCiAgICAgICAgQ0FTVChJU05VTEwoci5Ub25DSywgMCkgQVMgRkxPQVQpIEFTIFRvbkNL
>> "%B64_FILE%" echo LAogICAgICAgIENPQUxFU0NFKHQuVFRJTiwgTicnKSBBUyBUVElOX1RoYW4sCiAgICAgICAgQ09B
>> "%B64_FILE%" echo TEVTQ0Uoay5UVElOLCBOJycpIEFTIFRUSU5fS2hvCiAgICBGUk9NIGRiby57cWlkZW50KHRhYmxl
>> "%B64_FILE%" echo X25hbWUpfSByCiAgICBMRUZUIEpPSU4ge0RCX01BU1RFUn0uZGJvLkRNVEhBTiB0CiAgICAgICAg
>> "%B64_FILE%" echo T04gUlRSSU0oTFRSSU0odC5NYVRoYW4pKSA9IFJUUklNKExUUklNKHIuTWFUaGFuKSkKICAgIExF
>> "%B64_FILE%" echo RlQgSk9JTiB7REJfTUFTVEVSfS5kYm8uRE1LSE8gawogICAgICAgIE9OIFJUUklNKExUUklNKGsu
>> "%B64_FILE%" echo TWFLaG8pKSA9IFJUUklNKExUUklNKHIuTWFLaG8pKQogICAgV0hFUkUKICAgICAgICBJU05VTEwo
>> "%B64_FILE%" echo ci5NYUtobywgTicnKSA8PiBOJycKICAgICAgICBBTkQgSVNOVUxMKHIuTWFUaGFuLCBOJycpIDw+
>> "%B64_FILE%" echo IE4nJwogICAgICAgIEFORCBBQlMoQ0FTVChJU05VTEwoci5Ub25DSywgMCkgQVMgRkxPQVQpKSA+
>> "%B64_FILE%" echo IDAuMDAwMQogICAgT1JERVIgQlkKICAgICAgICBDT0FMRVNDRShrLlRUSU4sIE4nJyksCiAgICAg
>> "%B64_FILE%" echo ICAgQ09BTEVTQ0UodC5UVElOLCBOJycpLAogICAgICAgIHIuTWFLaG8sCiAgICAgICAgci5NYVRo
>> "%B64_FILE%" echo YW4KICAgICIiIgoKICAgIHJvd3MgPSBjdXIuZXhlY3V0ZShzcWwpLmZldGNoYWxsKCkKICAgIGNv
>> "%B64_FILE%" echo bm4uY2xvc2UoKQoKICAgIGRhdGEgPSBbXQogICAgZm9yIHJvdyBpbiByb3dzOgogICAgICAgIG1h
>> "%B64_FILE%" echo X2tobyA9IG5vcm1hbGl6ZV90ZXh0KHJvdy5NYUtobykKICAgICAgICB0ZW5fa2hvID0gbm9ybWFs
>> "%B64_FILE%" echo aXplX3RleHQocm93LlRlbktobykgb3IgbWFfa2hvCiAgICAgICAgbWFfdGhhbiA9IG5vcm1hbGl6
>> "%B64_FILE%" echo ZV90ZXh0KHJvdy5NYVRoYW4pCiAgICAgICAgdGVuX3RoYW4gPSBub3JtYWxpemVfY29hbF9uYW1l
>> "%B64_FILE%" echo KHJvdy5UZW5UaGFuKSBvciBtYV90aGFuCgogICAgICAgIHRvbl9kayA9IHJvdW5kKGNsZWFuX251
>> "%B64_FILE%" echo bWJlcihyb3cuVG9uREspLCAyKQogICAgICAgIG5oYXBfdGsgPSByb3VuZChjbGVhbl9udW1iZXIo
>> "%B64_FILE%" echo cm93Lk5oYXBUSyksIDIpCiAgICAgICAgeHVhdF90ayA9IHJvdW5kKGNsZWFuX251bWJlcihyb3cu
>> "%B64_FILE%" echo WHVhdFRLKSwgMikKICAgICAgICB0b25fY2sgPSByb3VuZChjbGVhbl9udW1iZXIocm93LlRvbkNL
>> "%B64_FILE%" echo KSwgMikKCiAgICAgICAgZGF0YS5hcHBlbmQoewogICAgICAgICAgICAiTWFLaG8iOiBtYV9raG8s
>> "%B64_FILE%" echo CiAgICAgICAgICAgICJUZW5LaG8iOiB0ZW5fa2hvLAogICAgICAgICAgICAia2hvIjogdGVuX2to
>> "%B64_FILE%" echo bywKICAgICAgICAgICAgIk1hVGhhbiI6IG1hX3RoYW4sCiAgICAgICAgICAgICJUZW5UaGFuIjog
>> "%B64_FILE%" echo dGVuX3RoYW4sCiAgICAgICAgICAgICJjb2FsIjogdGVuX3RoYW4sCiAgICAgICAgICAgICJUb25E
>> "%B64_FILE%" echo SyI6IHRvbl9kaywKICAgICAgICAgICAgIk5oYXBUSyI6IG5oYXBfdGssCiAgICAgICAgICAgICJY
>> "%B64_FILE%" echo dWF0VEsiOiB4dWF0X3RrLAogICAgICAgICAgICAiVG9uQ0siOiB0b25fY2ssCiAgICAgICAgICAg
>> "%B64_FILE%" echo ICJ0b24iOiB0b25fY2ssCiAgICAgICAgICAgICJ0dGNvQXBwIjogdG9uX2NrLAogICAgICAgICAg
>> "%B64_FILE%" echo ICAic291cmNlRm9ybXVsYSI6ICJUVENPX0FQUCBmaW5hbCB0YWJsZTogVG9uQ0siLAogICAgICAg
>> "%B64_FILE%" echo ICAgICAidHRpbktobyI6IG5vcm1hbGl6ZV90ZXh0KHJvdy5UVElOX0tobyksCiAgICAgICAgICAg
>> "%B64_FILE%" echo ICJ0dGluVGhhbiI6IG5vcm1hbGl6ZV90ZXh0KHJvdy5UVElOX1RoYW4pLAogICAgICAgIH0pCgog
>> "%B64_FILE%" echo ICAgZGF0YS5zb3J0KGtleT1sYW1iZGEgeDogKGtob19zb3J0X2tleSh4WyJUZW5LaG8iXSwgeFsi
>> "%B64_FILE%" echo TWFLaG8iXSksIHhbInR0aW5UaGFuIl0sIHhbIlRlblRoYW4iXSkpCiAgICByZXR1cm4gZGF0YQoK
>> "%B64_FILE%" echo CmRlZiBidWlsZF9wYXlsb2FkKCk6CiAgICB0YWJsZV9uYW1lLCBjYW5kaWRhdGVfdGFibGVzID0g
>> "%B64_FILE%" echo ZmluZF9sYXRlc3RfZmluYWxfdGFibGUoKQogICAgZGF0YSA9IHJlYWRfZmluYWxfcm93cyh0YWJs
>> "%B64_FILE%" echo ZV9uYW1lKQogICAgaWYgbm90IGRhdGE6CiAgICAgICAgcmFpc2UgUnVudGltZUVycm9yKGYiQuG6
>> "%B64_FILE%" echo o25nIHt0YWJsZV9uYW1lfSBraMO0bmcgY8OzIGTDsm5nIFRvbkNLIGjhu6NwIGzhu4cuIikKCiAg
>> "%B64_FILE%" echo ICB0b3RhbCA9IHJvdW5kKHN1bShmbG9hdChyWyJUb25DSyJdKSBmb3IgciBpbiBkYXRhKSwgMikK
>> "%B64_FILE%" echo ICAgIGtobzFfcm93cyA9IFsKICAgICAgICByIGZvciByIGluIGRhdGEKICAgICAgICBpZiByWyJU
>> "%B64_FILE%" echo ZW5LaG8iXS5zdHJpcCgpLmxvd2VyKCkgPT0gImtobyAxIiBvciByWyJNYUtobyJdLnN0cmlwKCkg
>> "%B64_FILE%" echo aW4gKCIxIiwgIjAxIikKICAgIF0KICAgIGtobzFfdG90YWwgPSByb3VuZChzdW0oZmxvYXQoclsi
>> "%B64_FILE%" echo VG9uQ0siXSkgZm9yIHIgaW4ga2hvMV9yb3dzKSwgMikKCiAgICBwYXlsb2FkID0gewogICAgICAg
>> "%B64_FILE%" echo ICJvayI6IFRydWUsCiAgICAgICAgIm1ldGEiOiB7CiAgICAgICAgICAgICJzb3VyY2UiOiAiVFRD
>> "%B64_FILE%" echo T19BUFBfU1FMX0ZJTkFMX0czX0JDMDVBXzIiLAogICAgICAgICAgICAiZGF0YWJhc2UiOiBEQl9S
>> "%B64_FILE%" echo RVBPUlQsCiAgICAgICAgICAgICJzb3VyY2VUYWJsZSI6IHRhYmxlX25hbWUsCiAgICAgICAgICAg
>> "%B64_FILE%" echo ICJtYXN0ZXJEYXRhYmFzZSI6IERCX01BU1RFUiwKICAgICAgICAgICAgInZlcnNpb24iOiAic3Fs
>> "%B64_FILE%" echo LWZpbmFsLWczYmMwNWEtdjE2IiwKICAgICAgICAgICAgInVwZGF0ZWRBdCI6IGRhdGV0aW1lLm5v
>> "%B64_FILE%" echo dygpLnN0cmZ0aW1lKCIlWS0lbS0lZCAlSDolTTolUyIpLAogICAgICAgICAgICAicm93Q291bnQi
>> "%B64_FILE%" echo OiBsZW4oZGF0YSksCiAgICAgICAgICAgICJ0b3RhbFRvbiI6IHRvdGFsLAogICAgICAgICAgICAi
>> "%B64_FILE%" echo a2hvMVRvdGFsIjoga2hvMV90b3RhbCwKICAgICAgICAgICAgImZvcm11bGEiOiAiVXNlIFRUQ09f
>> "%B64_FILE%" echo QVBQIGZpbmFsIHJlc3VsdCB0YWJsZSBUb25DSyBmcm9tIEczX0JDMDVBXzJfIyMjIyMjIiwKICAg
>> "%B64_FILE%" echo ICAgICAgICAgIm5vdGUiOiAiROG7ryBsaeG7h3UgbOG6pXkgdHLhu7FjIHRp4bq/cCB04burIGLh
>> "%B64_FILE%" echo uqNuZyBr4bq/dCBxdeG6oyBjdeG7kWkgbcOgIFRUQ09fQVBQIGTDuW5nIMSR4buDIFNFTEVDVCBo
>> "%B64_FILE%" echo aeG7g24gdGjhu4sgYsOhbyBjw6FvOyBraMO0bmcgZMO5bmcgRXhjZWwsIGtow7RuZyBkw7luZyBi
>> "%B64_FILE%" echo 4bqjbmcgRzNfQkMwNUFfMV8qIHRydW5nIGdpYW4uIiwKICAgICAgICAgICAgImNhbmRpZGF0ZVRh
>> "%B64_FILE%" echo YmxlcyI6IFsKICAgICAgICAgICAgICAgIHsKICAgICAgICAgICAgICAgICAgICAibmFtZSI6IHIu
>> "%B64_FILE%" echo bmFtZSwKICAgICAgICAgICAgICAgICAgICAiY3JlYXRlRGF0ZSI6IHN0cihyLmNyZWF0ZV9kYXRl
>> "%B64_FILE%" echo KSwKICAgICAgICAgICAgICAgICAgICAibW9kaWZ5RGF0ZSI6IHN0cihyLm1vZGlmeV9kYXRlKSwK
>> "%B64_FILE%" echo ICAgICAgICAgICAgICAgIH0KICAgICAgICAgICAgICAgIGZvciByIGluIGNhbmRpZGF0ZV90YWJs
>> "%B64_FILE%" echo ZXMKICAgICAgICAgICAgXSwKICAgICAgICB9LAogICAgICAgICJkYXRhIjogZGF0YSwKICAgICAg
>> "%B64_FILE%" echo ICAicm93cyI6IGRhdGEsCiAgICB9CiAgICByZXR1cm4gcGF5bG9hZCwga2hvMV9yb3dzCgoKZGVm
>> "%B64_FILE%" echo IHdyaXRlX2NoZWNrKCk6CiAgICBDSEVDS19ESVIubWtkaXIocGFyZW50cz1UcnVlLCBleGlzdF9v
>> "%B64_FILE%" echo az1UcnVlKQogICAgcGF5bG9hZCwga2hvMV9yb3dzID0gYnVpbGRfcGF5bG9hZCgpCiAgICBvdXQg
>> "%B64_FILE%" echo PSBDSEVDS19ESVIgLyBmImNoZWNrX2ZpbmFsX2czYmMwNWFfdjE2X3tkYXRldGltZS5ub3coKTol
>> "%B64_FILE%" echo WSVtJWRfJUglTSVTfS50eHQiCgogICAgd2l0aCBvdXQub3BlbigidyIsIGVuY29kaW5nPSJ1dGYt
>> "%B64_FILE%" echo OCIpIGFzIGY6CiAgICAgICAgZi53cml0ZSgiVFRDTyAtIEtJ4buCTSBUUkEgQuG6ok5HIEvhur5U
>> "%B64_FILE%" echo IFFV4bqiIENV4buQSSBHM19CQzA1QSAtIFYxNlxuIikKICAgICAgICBmLndyaXRlKCI9IiAqIDkw
>> "%B64_FILE%" echo ICsgIlxuIikKICAgICAgICBmLndyaXRlKGYiU291cmNlIHRhYmxlIDoge3BheWxvYWRbJ21ldGEn
>> "%B64_FILE%" echo XVsnc291cmNlVGFibGUnXX1cbiIpCiAgICAgICAgZi53cml0ZShmIlJvdyBjb3VudCAgICA6IHtw
>> "%B64_FILE%" echo YXlsb2FkWydtZXRhJ11bJ3Jvd0NvdW50J119XG4iKQogICAgICAgIGYud3JpdGUoZiJUb3RhbCB0
>> "%B64_FILE%" echo b24gICAgOiB7cGF5bG9hZFsnbWV0YSddWyd0b3RhbFRvbiddOiwuMmZ9XG4iKQogICAgICAgIGYu
>> "%B64_FILE%" echo d3JpdGUoZiJLaG8gMSB0b3RhbCAgOiB7cGF5bG9hZFsnbWV0YSddWydraG8xVG90YWwnXTosLjJm
>> "%B64_FILE%" echo fVxuIikKICAgICAgICBmLndyaXRlKCJcbkNhbmRpZGF0ZSB0YWJsZXM6XG4iKQogICAgICAgIGZv
>> "%B64_FILE%" echo ciB0IGluIHBheWxvYWRbIm1ldGEiXVsiY2FuZGlkYXRlVGFibGVzIl06CiAgICAgICAgICAgIGYu
>> "%B64_FILE%" echo d3JpdGUoZiItIHt0WyduYW1lJ119IHwgY3JlYXRlPXt0WydjcmVhdGVEYXRlJ119IHwgbW9kaWZ5
>> "%B64_FILE%" echo PXt0Wydtb2RpZnlEYXRlJ119XG4iKQogICAgICAgIGYud3JpdGUoIlxuS2hvIDEgcm93czpcbiIp
>> "%B64_FILE%" echo CiAgICAgICAgZm9yIHIgaW4ga2hvMV9yb3dzOgogICAgICAgICAgICBmLndyaXRlKAogICAgICAg
>> "%B64_FILE%" echo ICAgICAgICAgZiJNYUtobz17clsnTWFLaG8nXX0gfCBLaG89e3JbJ1RlbktobyddfSB8ICIKICAg
>> "%B64_FILE%" echo ICAgICAgICAgICAgIGYiTWFUaGFuPXtyWydNYVRoYW4nXX0gfCBUaGFuPXtyWydUZW5UaGFuJ119
>> "%B64_FILE%" echo IHwgIgogICAgICAgICAgICAgICAgZiJUb25ESz17clsnVG9uREsnXTosLjJmfSB8IE5oYXBUSz17
>> "%B64_FILE%" echo clsnTmhhcFRLJ106LC4yZn0gfCAiCiAgICAgICAgICAgICAgICBmIlh1YXRUSz17clsnWHVhdFRL
>> "%B64_FILE%" echo J106LC4yZn0gfCBUb25DSz17clsnVG9uQ0snXTosLjJmfVxuIgogICAgICAgICAgICApCgogICAg
>> "%B64_FILE%" echo cHJpbnQoZiJbT0tdIMSQw6MgeHXhuqV0IGZpbGUga2nhu4NtIHRyYToge291dH0iKQogICAgdHJ5
>> "%B64_FILE%" echo OgogICAgICAgIHN1YnByb2Nlc3MuUG9wZW4oWyJleHBsb3Jlci5leGUiLCBzdHIoQ0hFQ0tfRElS
>> "%B64_FILE%" echo KV0pCiAgICBleGNlcHQgRXhjZXB0aW9uOgogICAgICAgIHBhc3MKICAgIHJldHVybiBvdXQKCgpk
>> "%B64_FILE%" echo ZWYgd3JpdGVfanNvbihyZXBvX2Rpcjogc3RyKToKICAgIHBheWxvYWQsIGtobzFfcm93cyA9IGJ1
>> "%B64_FILE%" echo aWxkX3BheWxvYWQoKQoKICAgIGRlc3QgPSBQYXRoKHJlcG9fZGlyKSAvIEpTT05fUkVMCiAgICBk
>> "%B64_FILE%" echo ZXN0LnBhcmVudC5ta2RpcihwYXJlbnRzPVRydWUsIGV4aXN0X29rPVRydWUpCiAgICBkZXN0Lndy
>> "%B64_FILE%" echo aXRlX3RleHQoanNvbi5kdW1wcyhwYXlsb2FkLCBlbnN1cmVfYXNjaWk9RmFsc2UsIGluZGVudD0y
>> "%B64_FILE%" echo KSwgZW5jb2Rpbmc9InV0Zi04IikKCiAgICBwcmludCgiXG5bT0tdIMSQw6MgdOG6oW8gSlNPTiB0
>> "%B64_FILE%" echo 4buTbiBraG8gdOG7qyBi4bqjbmcga+G6v3QgcXXhuqMgY3Xhu5FpIFRUQ09fQVBQLiIpCiAgICBw
>> "%B64_FILE%" echo cmludChmIkZpbGUgSlNPTiA6IHtkZXN0fSIpCiAgICBwcmludChmIkLhuqNuZyBuZ3Xhu5NuOiB7
>> "%B64_FILE%" echo cGF5bG9hZFsnbWV0YSddWydzb3VyY2VUYWJsZSddfSIpCiAgICBwcmludChmIlPhu5EgZMOybmcg
>> "%B64_FILE%" echo ICA6IHtwYXlsb2FkWydtZXRhJ11bJ3Jvd0NvdW50J119IikKICAgIHByaW50KGYiVOG7lW5nIHTh
>> "%B64_FILE%" echo u5NuICA6IHtwYXlsb2FkWydtZXRhJ11bJ3RvdGFsVG9uJ106LC4yZn0iKQogICAgcHJpbnQoZiJU
>> "%B64_FILE%" echo 4buVbmcgS2hvIDE6IHtwYXlsb2FkWydtZXRhJ11bJ2tobzFUb3RhbCddOiwuMmZ9IikKCiAgICBw
>> "%B64_FILE%" echo cmludCgiXG5LaeG7g20gdHJhIEtobyAxOiIpCiAgICBpZiBraG8xX3Jvd3M6CiAgICAgICAgZm9y
>> "%B64_FILE%" echo IHIgaW4ga2hvMV9yb3dzOgogICAgICAgICAgICBwcmludCgKICAgICAgICAgICAgICAgIGYiICAt
>> "%B64_FILE%" echo IE1hVGhhbj17clsnTWFUaGFuJ119IHwgVGhhbj17clsnVGVuVGhhbiddfSB8ICIKICAgICAgICAg
>> "%B64_FILE%" echo ICAgICAgIGYiVG9uREs9e3JbJ1RvbkRLJ106LC4yZn0gfCBOaGFwVEs9e3JbJ05oYXBUSyddOiwu
>> "%B64_FILE%" echo MmZ9IHwgIgogICAgICAgICAgICAgICAgZiJYdWF0VEs9e3JbJ1h1YXRUSyddOiwuMmZ9IHwgVG9u
>> "%B64_FILE%" echo Q0s9e3JbJ1RvbkNLJ106LC4yZn0iCiAgICAgICAgICAgICkKICAgIGVsc2U6CiAgICAgICAgcHJp
>> "%B64_FILE%" echo bnQoIiAgLSBLaMO0bmcgdGjhuqV5IEtobyAxIHRyb25nIGLhuqNuZyBuZ3Xhu5NuLiIpCgogICAg
>> "%B64_FILE%" echo aWYgYWJzKHBheWxvYWRbIm1ldGEiXVsia2hvMVRvdGFsIl0gLSAxMDUyLjY1KSA+IDAuMToKICAg
>> "%B64_FILE%" echo ICAgICBwcmludCgiXG5bQ+G6ok5IIELDgU9dIFThu5VuZyBLaG8gMSBjaMawYSBraOG7m3AgMS4w
>> "%B64_FILE%" echo NTIsNjUuIikKICAgICAgICBwcmludCgiSMOjeSBt4bufIFRUQ09fQVBQLCBi4bqlbSBYZW0ga3Eg
>> "%B64_FILE%" echo xJHDum5nIG3DoG4gaMOsbmggdOG7k24ga2hvLCBy4buTaSBjaOG6oXkgbOG6oWkgbeG7pWMgMiBr
>> "%B64_FILE%" echo aeG7g20gdHJhLiIpCiAgICAgICAgd3JpdGVfY2hlY2soKQoKICAgIGxvZyhmIkNyZWF0ZWQgSlNP
>> "%B64_FILE%" echo TiBmcm9tIHtwYXlsb2FkWydtZXRhJ11bJ3NvdXJjZVRhYmxlJ119LCByb3dzPXtwYXlsb2FkWydt
>> "%B64_FILE%" echo ZXRhJ11bJ3Jvd0NvdW50J119LCBraG8xPXtwYXlsb2FkWydtZXRhJ11bJ2tobzFUb3RhbCddfSIp
>> "%B64_FILE%" echo CiAgICByZXR1cm4gZGVzdCwgcGF5bG9hZAoKCmRlZiBwdXNoX2dpdGh1YihyZXBvX2Rpcjogc3Ry
>> "%B64_FILE%" echo KToKICAgIGVuc3VyZV9naXQoKQogICAgZW5zdXJlX3JlcG8ocmVwb19kaXIpCgogICAgZGVzdCwg
>> "%B64_FILE%" echo cGF5bG9hZCA9IHdyaXRlX2pzb24ocmVwb19kaXIpCgogICAgcHJpbnQoIlxuxJBhbmcgY29tbWl0
>> "%B64_FILE%" echo L3B1c2ggbMOqbiBHaXRIdWIuLi4iKQogICAgcnVuKFsiZ2l0IiwgImNoZWNrb3V0IiwgQlJBTkNI
>> "%B64_FILE%" echo XSwgY3dkPXJlcG9fZGlyLCBjaGVjaz1GYWxzZSkKICAgIHJ1bihbImdpdCIsICJwdWxsIiwgIi0t
>> "%B64_FILE%" echo cmViYXNlIiwgIm9yaWdpbiIsIEJSQU5DSF0sIGN3ZD1yZXBvX2RpciwgY2hlY2s9RmFsc2UpCiAg
>> "%B64_FILE%" echo ICBydW4oWyJnaXQiLCAiYWRkIiwgSlNPTl9SRUxdLCBjd2Q9cmVwb19kaXIpCgogICAgZGlmZl9j
>> "%B64_FILE%" echo b2RlID0gc3VicHJvY2Vzcy5ydW4oWyJnaXQiLCAiZGlmZiIsICItLWNhY2hlZCIsICItLXF1aWV0
>> "%B64_FILE%" echo Il0sIGN3ZD1yZXBvX2RpcikucmV0dXJuY29kZQogICAgaWYgZGlmZl9jb2RlID09IDA6CiAgICAg
>> "%B64_FILE%" echo ICAgcHJpbnQoIltPS10gSlNPTiBraMO0bmcgdGhheSDEkeG7lWksIGtow7RuZyBj4bqnbiBwdXNo
>> "%B64_FILE%" echo LiIpCiAgICAgICAgbG9nKCJObyBjaGFuZ2VzLiIpCiAgICAgICAgcmV0dXJuCgogICAgbXNnID0g
>> "%B64_FILE%" echo IlVwZGF0ZSBUVENPIHRvbiBraG8gZnJvbSBmaW5hbCBTUUwgdGFibGUgIiArIGRhdGV0aW1lLm5v
>> "%B64_FILE%" echo dygpLnN0cmZ0aW1lKCIlWS0lbS0lZCAlSDolTTolUyIpCiAgICBydW4oWyJnaXQiLCAiY29tbWl0
>> "%B64_FILE%" echo IiwgIi1tIiwgbXNnXSwgY3dkPXJlcG9fZGlyKQogICAgcnVuKFsiZ2l0IiwgInB1c2giLCAib3Jp
>> "%B64_FILE%" echo Z2luIiwgQlJBTkNIXSwgY3dkPXJlcG9fZGlyKQoKICAgIHByaW50KCJcbj09PT09PT09PT09PT09
>> "%B64_FILE%" echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PSIpCiAgICBwcmlu
>> "%B64_FILE%" echo dCgiW09LXSDEkMODIEPhuqxQIE5I4bqsVCBHSVRIVUIgVEjDgE5IIEPDlE5HIikKICAgIHByaW50
>> "%B64_FILE%" echo KCI9PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
>> "%B64_FILE%" echo PT09PT0iKQogICAgbG9nKCJQdXNoIHN1Y2Nlc3MuIikKCgpkZWYgaW5zdGFsbF90YXNrKGJhdF9w
>> "%B64_FILE%" echo YXRoOiBzdHIpOgogICAgaWYgbm90IGJhdF9wYXRoIG9yIG5vdCBvcy5wYXRoLmlzZmlsZShiYXRf
>> "%B64_FILE%" echo cGF0aCk6CiAgICAgICAgcmFpc2UgUnVudGltZUVycm9yKCJLaMO0bmcgeMOhYyDEkeG7i25oIMSR
>> "%B64_FILE%" echo xrDhu6NjIGZpbGUgQkFUIMSR4buDIGPDoGkgdOG7sSDEkeG7mW5nLiIpCiAgICB0YXNrX2NtZCA9
>> "%B64_FILE%" echo IGYnIntiYXRfcGF0aH0iIC0tYXV0bycKICAgIHJ1bihbInNjaHRhc2tzIiwgIi9DcmVhdGUiLCAi
>> "%B64_FILE%" echo L1ROIiwgVEFTS19OQU1FLCAiL1RSIiwgdGFza19jbWQsICIvU0MiLCAiT05MT0dPTiIsICIvREVM
>> "%B64_FILE%" echo QVkiLCAiMDAwMTowMCIsICIvRiJdKQogICAgcHJpbnQoIltPS10gxJDDoyBjw6BpIHThu7EgxJHh
>> "%B64_FILE%" echo u5luZyBraGkgxJHEg25nIG5o4bqtcCBXaW5kb3dzLiIpCiAgICBwcmludCgiTMawdSDDvTogxJHh
>> "%B64_FILE%" echo u4Mgc+G7kSBsaeG7h3UgbeG7m2kgbmjhuqV0LCBUVENPX0FQUCBwaOG6o2kgdOG6oW8gYuG6o25n
>> "%B64_FILE%" echo IGvhur90IHF14bqjIGN14buRaSBHM19CQzA1QV8yXyMjIyMjIyB0csaw4bubYyDEkcOzLiIpCiAg
>> "%B64_FILE%" echo ICBsb2coZiJJbnN0YWxsIHRhc2s6IHt0YXNrX2NtZH0iKQoKCmRlZiBvcGVuX2xvZygpOgogICAg
>> "%B64_FILE%" echo Q09ORklHX0RJUi5ta2RpcihwYXJlbnRzPVRydWUsIGV4aXN0X29rPVRydWUpCiAgICBpZiBub3Qg
>> "%B64_FILE%" echo TE9HX0ZJTEUuZXhpc3RzKCk6CiAgICAgICAgTE9HX0ZJTEUud3JpdGVfdGV4dCgiQ2jGsGEgY8Oz
>> "%B64_FILE%" echo IGxvZy5cbiIsIGVuY29kaW5nPSJ1dGYtOCIpCiAgICBzdWJwcm9jZXNzLlBvcGVuKFsibm90ZXBh
>> "%B64_FILE%" echo ZC5leGUiLCBzdHIoTE9HX0ZJTEUpXSkKCgpkZWYgbWFpbigpOgogICAgcGFyc2VyID0gYXJncGFy
>> "%B64_FILE%" echo c2UuQXJndW1lbnRQYXJzZXIoKQogICAgcGFyc2VyLmFkZF9hcmd1bWVudCgiLS1hY3Rpb24iLCBj
>> "%B64_FILE%" echo aG9pY2VzPVsidXBkYXRlIiwgImNoZWNrIiwgImNvbmZpZy1yZXBvIiwgImluc3RhbGwiLCAib3Bl
>> "%B64_FILE%" echo bi1sb2ciXSwgcmVxdWlyZWQ9VHJ1ZSkKICAgIHBhcnNlci5hZGRfYXJndW1lbnQoIi0tYmF0Iiwg
>> "%B64_FILE%" echo ZGVmYXVsdD0iIikKICAgIGFyZ3MgPSBwYXJzZXIucGFyc2VfYXJncygpCgogICAgdHJ5OgogICAg
>> "%B64_FILE%" echo ICAgIGNmZyA9IGxvYWRfY29uZmlnKCkKCiAgICAgICAgaWYgYXJncy5hY3Rpb24gPT0gIm9wZW4t
>> "%B64_FILE%" echo bG9nIjoKICAgICAgICAgICAgb3Blbl9sb2coKQogICAgICAgICAgICByZXR1cm4gMAoKICAgICAg
>> "%B64_FILE%" echo ICBpZiBhcmdzLmFjdGlvbiA9PSAiY2hlY2siOgogICAgICAgICAgICB3cml0ZV9jaGVjaygpCiAg
>> "%B64_FILE%" echo ICAgICAgICAgIHJldHVybiAwCgogICAgICAgIGlmIGFyZ3MuYWN0aW9uID09ICJjb25maWctcmVw
>> "%B64_FILE%" echo byI6CiAgICAgICAgICAgIGZvbGRlciA9IHBpY2tfZm9sZGVyKCJDaOG7jW4gdGjGsCBt4bulYyBy
>> "%B64_FILE%" echo ZXBvIEdpdEh1YiBteS1haS1zaXRlIiwgY2ZnLmdldCgicmVwb19kaXIiKSBvciByIkQ6XFRUQ09f
>> "%B64_FILE%" echo VG9uS2hvX0FwcF9SZXBvIikKICAgICAgICAgICAgaWYgbm90IGZvbGRlcjoKICAgICAgICAgICAg
>> "%B64_FILE%" echo ICAgIHJhaXNlIFJ1bnRpbWVFcnJvcigiQ2jGsGEgY2jhu41uIHRoxrAgbeG7pWMgcmVwby4iKQog
>> "%B64_FILE%" echo ICAgICAgICAgICBjZmdbInJlcG9fZGlyIl0gPSBmb2xkZXIKICAgICAgICAgICAgc2F2ZV9jb25m
>> "%B64_FILE%" echo aWcoY2ZnKQogICAgICAgICAgICBwcmludChmIltPS10gxJDDoyBsxrB1IHJlcG86IHtmb2xkZXJ9
>> "%B64_FILE%" echo IikKICAgICAgICAgICAgcmV0dXJuIDAKCiAgICAgICAgcmVwb19kaXIgPSBjZmcuZ2V0KCJyZXBv
>> "%B64_FILE%" echo X2RpciIpIG9yIHIiRDpcVFRDT19Ub25LaG9fQXBwX1JlcG8iCiAgICAgICAgaWYgbm90IG9zLnBh
>> "%B64_FILE%" echo dGguaXNkaXIocmVwb19kaXIpOgogICAgICAgICAgICBmb2xkZXIgPSBwaWNrX2ZvbGRlcigiQ2jh
>> "%B64_FILE%" echo u41uIHRoxrAgbeG7pWMgcmVwbyBHaXRIdWIgbXktYWktc2l0ZSIsIHJlcG9fZGlyKQogICAgICAg
>> "%B64_FILE%" echo ICAgICBpZiBub3QgZm9sZGVyOgogICAgICAgICAgICAgICAgcmFpc2UgUnVudGltZUVycm9yKCJD
>> "%B64_FILE%" echo aMawYSBjaOG7jW4gdGjGsCBt4bulYyByZXBvLiIpCiAgICAgICAgICAgIGNmZ1sicmVwb19kaXIi
>> "%B64_FILE%" echo XSA9IGZvbGRlcgogICAgICAgICAgICByZXBvX2RpciA9IGZvbGRlcgogICAgICAgICAgICBzYXZl
>> "%B64_FILE%" echo X2NvbmZpZyhjZmcpCgogICAgICAgIGlmIGFyZ3MuYWN0aW9uID09ICJpbnN0YWxsIjoKICAgICAg
>> "%B64_FILE%" echo ICAgICAgaW5zdGFsbF90YXNrKGFyZ3MuYmF0KQogICAgICAgICAgICByZXR1cm4gMAoKICAgICAg
>> "%B64_FILE%" echo ICBpZiBhcmdzLmFjdGlvbiA9PSAidXBkYXRlIjoKICAgICAgICAgICAgcHVzaF9naXRodWIocmVw
>> "%B64_FILE%" echo b19kaXIpCiAgICAgICAgICAgIHJldHVybiAwCgogICAgICAgIHJldHVybiAwCiAgICBleGNlcHQg
>> "%B64_FILE%" echo RXhjZXB0aW9uIGFzIGV4YzoKICAgICAgICBwcmludCgiXG5bTOG7lkldIiwgZXhjKQogICAgICAg
>> "%B64_FILE%" echo IHByaW50KCJMb2c6IiwgTE9HX0ZJTEUpCiAgICAgICAgbG9nKGYiRVJST1I6IHtleGN9IikKICAg
>> "%B64_FILE%" echo ICAgICByZXR1cm4gMQoKCmlmIF9fbmFtZV9fID09ICJfX21haW5fXyI6CiAgICBzeXMuZXhpdCht
>> "%B64_FILE%" echo YWluKCkpCg==
python -c "import base64, pathlib, os; b=pathlib.Path(os.environ['B64_FILE']).read_text().replace('\n','').replace('\r','').strip(); pathlib.Path(os.environ['PY_MAIN']).write_bytes(base64.b64decode(b))"
exit /b %errorlevel%
