@echo off
setlocal EnableExtensions EnableDelayedExpansion
chcp 65001 >nul
title TTCO - Tim nguon ton kho Kho 1 = 1052.65 - v3

set "WORK_DIR=%~dp0"
set "PY_FILE=%WORK_DIR%ttco_find_kho1_1052_65_v3.py"
set "B64_FILE=%WORK_DIR%ttco_find_kho1_1052_65_v3.b64"

echo ============================================================
echo   TTCO - TIM NGUON TON KHO KHO 1 = 1.052,65 - V3
echo ============================================================
echo.
echo Ban v3 se xuat ket qua ra Desktop de de tim:
echo   Desktop\TTCO_CHECK_KHO1_1052_65
echo.
echo Sau khi chay xong, thu muc ket qua se tu mo len.
echo.
pause

:WRITE_PY
> "%B64_FILE%" echo CiMgLSotIGNvZGluZzogdXRmLTggLSotCmltcG9ydCBjc3YKaW1wb3J0IG9zCmltcG9ydCByZQpp
>> "%B64_FILE%" echo bXBvcnQgc3VicHJvY2VzcwppbXBvcnQgc3lzCmZyb20gZGF0ZXRpbWUgaW1wb3J0IGRhdGV0aW1l
>> "%B64_FILE%" echo CmZyb20gcGF0aGxpYiBpbXBvcnQgUGF0aAoKU0VSVkVSID0gciJ0dXllbnRoYW5jdWFvbmcuY29t
>> "%B64_FILE%" echo LnZuLDUyMzc2IgpEQVRBQkFTRSA9ICJUVENPX1RIT05HS0UiClRBUkdFVF9WQUxVRSA9IDEwNTIu
>> "%B64_FILE%" echo NjUKCiMgdjM6IGx1w7RuIHh14bqldCBr4bq/dCBxdeG6oyByYSBEZXNrdG9wIMSR4buDIGThu4Ug
>> "%B64_FILE%" echo dMOsbQpERVNLVE9QID0gUGF0aC5ob21lKCkgLyAiRGVza3RvcCIKT1VUX0RJUiA9IERFU0tUT1Ag
>> "%B64_FILE%" echo LyAiVFRDT19DSEVDS19LSE8xXzEwNTJfNjUiCk9VVF9ESVIubWtkaXIocGFyZW50cz1UcnVlLCBl
>> "%B64_FILE%" echo eGlzdF9vaz1UcnVlKQoKU1RBTVAgPSBkYXRldGltZS5ub3coKS5zdHJmdGltZSgiJVklbSVkXyVI
>> "%B64_FILE%" echo JU0lUyIpCk9VVF9UWFQgPSBPVVRfRElSIC8gZiJjaGVja19raG8xXzEwNTJfNjVfe1NUQU1QfS50
>> "%B64_FILE%" echo eHQiCk9VVF9DU1YgPSBPVVRfRElSIC8gZiJjaGVja19raG8xXzEwNTJfNjVfe1NUQU1QfS5jc3Yi
>> "%B64_FILE%" echo CgoKZGVmIHdyaXRlKGxpbmU9IiIpOgogICAgcHJpbnQobGluZSkKICAgIHdpdGggT1VUX1RYVC5v
>> "%B64_FILE%" echo cGVuKCJhIiwgZW5jb2Rpbmc9InV0Zi04IikgYXMgZjoKICAgICAgICBmLndyaXRlKHN0cihsaW5l
>> "%B64_FILE%" echo KSArICJcbiIpCgoKZGVmIGVuc3VyZV9weW9kYmMoKToKICAgIHRyeToKICAgICAgICBpbXBvcnQg
>> "%B64_FILE%" echo cHlvZGJjICAjIG5vcWEKICAgICAgICByZXR1cm4KICAgIGV4Y2VwdCBFeGNlcHRpb246CiAgICAg
>> "%B64_FILE%" echo ICAgd3JpdGUoIkNoxrBhIGPDsyBweW9kYmMuIMSQYW5nIHRo4butIGPDoGkgcHlvZGJjLi4uIikK
>> "%B64_FILE%" echo ICAgICAgICBzdWJwcm9jZXNzLmNoZWNrX2NhbGwoW3N5cy5leGVjdXRhYmxlLCAiLW0iLCAicGlw
>> "%B64_FILE%" echo IiwgImluc3RhbGwiLCAicHlvZGJjIl0pCgoKZGVmIGNvbm5lY3QoKToKICAgIGltcG9ydCBweW9k
>> "%B64_FILE%" echo YmMKICAgIGNvbm5fc3RyID0gKAogICAgICAgICJEUklWRVI9e09EQkMgRHJpdmVyIDE4IGZvciBT
>> "%B64_FILE%" echo UUwgU2VydmVyfTsiCiAgICAgICAgZiJTRVJWRVI9e1NFUlZFUn07IgogICAgICAgIGYiREFUQUJB
>> "%B64_FILE%" echo U0U9e0RBVEFCQVNFfTsiCiAgICAgICAgIlRydXN0ZWRfQ29ubmVjdGlvbj15ZXM7IgogICAgICAg
>> "%B64_FILE%" echo ICJUcnVzdFNlcnZlckNlcnRpZmljYXRlPXllczsiCiAgICApCiAgICByZXR1cm4gcHlvZGJjLmNv
>> "%B64_FILE%" echo bm5lY3QoY29ubl9zdHIsIHRpbWVvdXQ9MTUpCgoKZGVmIHFpZGVudChuYW1lOiBzdHIpIC0+IHN0
>> "%B64_FILE%" echo cjoKICAgIHJldHVybiAiWyIgKyBzdHIobmFtZSkucmVwbGFjZSgiXSIsICJdXSIpICsgIl0iCgoK
>> "%B64_FILE%" echo ZGVmIGlzX251bWVyaWNfdHlwZSh0OiBzdHIpIC0+IGJvb2w6CiAgICByZXR1cm4gc3RyKHQpLmxv
>> "%B64_FILE%" echo d2VyKCkgaW4gewogICAgICAgICJpbnQiLCAiYmlnaW50IiwgInNtYWxsaW50IiwgInRpbnlpbnQi
>> "%B64_FILE%" echo LCAiZGVjaW1hbCIsICJudW1lcmljIiwKICAgICAgICAiZmxvYXQiLCAicmVhbCIsICJtb25leSIs
>> "%B64_FILE%" echo ICJzbWFsbG1vbmV5IgogICAgfQoKCmRlZiBzYWZlX2Zsb2F0KHYpOgogICAgdHJ5OgogICAgICAg
>> "%B64_FILE%" echo IGlmIHYgaXMgTm9uZToKICAgICAgICAgICAgcmV0dXJuIE5vbmUKICAgICAgICByZXR1cm4gZmxv
>> "%B64_FILE%" echo YXQodikKICAgIGV4Y2VwdCBFeGNlcHRpb246CiAgICAgICAgcmV0dXJuIE5vbmUKCgpkZWYgY2Fz
>> "%B64_FILE%" echo dF90b190ZXh0X3NxbChjb2w6IHN0cikgLT4gc3RyOgogICAgcmV0dXJuIGYiQ0FTVCh7cWlkZW50
>> "%B64_FILE%" echo KGNvbCl9IEFTIE5WQVJDSEFSKDEwMCkpIgoKCmRlZiBjYXN0X3RvX2Zsb2F0X3NxbChjb2w6IHN0
>> "%B64_FILE%" echo cikgLT4gc3RyOgogICAgcmV0dXJuIGYiQ0FTVCh7cWlkZW50KGNvbCl9IEFTIEZMT0FUKSIKCgpk
>> "%B64_FILE%" echo ZWYgbWFpbigpOgogICAgZW5zdXJlX3B5b2RiYygpCgogICAgd3JpdGUoIj09PT09PT09PT09PT09
>> "%B64_FILE%" echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PSIpCiAgICB3cml0
>> "%B64_FILE%" echo ZSgiVFRDTyAtIEtJ4buCTSBUUkEgTkdV4buSTiBU4buSTiBLSE8gS0hPIDEgPSAxLjA1Miw2NSAt
>> "%B64_FILE%" echo IFYzIikKICAgIHdyaXRlKCI9PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
>> "%B64_FILE%" echo PT09PT09PT09PT09PT09PT09PT0iKQogICAgd3JpdGUoZiJTZXJ2ZXIgICA6IHtTRVJWRVJ9IikK
>> "%B64_FILE%" echo ICAgIHdyaXRlKGYiRGF0YWJhc2UgOiB7REFUQUJBU0V9IikKICAgIHdyaXRlKGYiR2nDoSB0cuG7
>> "%B64_FILE%" echo iyBUVENPX0FQUCBiw6FvOiB7VEFSR0VUX1ZBTFVFfSIpCiAgICB3cml0ZSgiIikKICAgIHdyaXRl
>> "%B64_FILE%" echo KCJL4bq+VCBRVeG6oiBT4bq8IFhV4bqkVCBSQSBERVNLVE9QOiIpCiAgICB3cml0ZShmIkZvbGRl
>> "%B64_FILE%" echo ciA6IHtPVVRfRElSfSIpCiAgICB3cml0ZShmIlRYVCAgICA6IHtPVVRfVFhUfSIpCiAgICB3cml0
>> "%B64_FILE%" echo ZShmIkNTViAgICA6IHtPVVRfQ1NWfSIpCiAgICB3cml0ZSgiIikKCiAgICBjb25uID0gY29ubmVj
>> "%B64_FILE%" echo dCgpCiAgICBjdXIgPSBjb25uLmN1cnNvcigpCiAgICByZXN1bHRzID0gW10KCiAgICB3cml0ZSgi
>> "%B64_FILE%" echo MSkgS0nhu4JNIFRSQSBDRE9USEFOIFRIRU8gVOG6pFQgQ+G6oiBL4buyIikKICAgIHdyaXRlKCIt
>> "%B64_FILE%" echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
>> "%B64_FILE%" echo LS0iKQogICAgdHJ5OgogICAgICAgIHNxbCA9ICIiIgogICAgICAgIFNFTEVDVCBOYW1IVCwgVGhh
>> "%B64_FILE%" echo bmdIVCwgTWFLaG8sIE1hVGhhbiwgU1VNKENBU1QoVG9uQ0sgQVMgRkxPQVQpKSBBUyBUb25DSwog
>> "%B64_FILE%" echo ICAgICAgIEZST00gZGJvLkNET1RIQU4KICAgICAgICBXSEVSRSBDQVNUKE1hS2hvIEFTIE5WQVJD
>> "%B64_FILE%" echo SEFSKDEwMCkpIElOIChOJzEnLCBOJzAxJywgTidLaG8gMScpCiAgICAgICAgR1JPVVAgQlkgTmFt
>> "%B64_FILE%" echo SFQsIFRoYW5nSFQsIE1hS2hvLCBNYVRoYW4KICAgICAgICBPUkRFUiBCWSBOYW1IVCBERVNDLCBU
>> "%B64_FILE%" echo aGFuZ0hUIERFU0MsIE1hVGhhbjsKICAgICAgICAiIiIKICAgICAgICByb3dzID0gY3VyLmV4ZWN1
>> "%B64_FILE%" echo dGUoc3FsKS5mZXRjaGFsbCgpCiAgICAgICAgd3JpdGUoZiJT4buRIGTDsm5nIENET1RIQU4gS2hv
>> "%B64_FILE%" echo IDE6IHtsZW4ocm93cyl9IikKICAgICAgICBmb3IgciBpbiByb3dzWzoxMDBdOgogICAgICAgICAg
>> "%B64_FILE%" echo ICB2YWwgPSBmbG9hdChyLlRvbkNLIG9yIDApCiAgICAgICAgICAgIHdyaXRlKGYiQ0RPVEhBTiB8
>> "%B64_FILE%" echo IE5hbT17ci5OYW1IVH0gfCBUaGFuZz17ci5UaGFuZ0hUfSB8IE1hS2hvPXtyLk1hS2hvfSB8IE1h
>> "%B64_FILE%" echo VGhhbj17ci5NYVRoYW59IHwgVG9uQ0s9e3ZhbDosLjJmfSIpCiAgICAgICAgICAgIHJlc3VsdHMu
>> "%B64_FILE%" echo YXBwZW5kKHsKICAgICAgICAgICAgICAgICJzb3VyY2UiOiAiQ0RPVEhBTiIsCiAgICAgICAgICAg
>> "%B64_FILE%" echo ICAgICAic2NoZW1hIjogImRibyIsCiAgICAgICAgICAgICAgICAidGFibGUiOiAiQ0RPVEhBTiIs
>> "%B64_FILE%" echo CiAgICAgICAgICAgICAgICAicGVyaW9kIjogZiJOYW1IVD17ci5OYW1IVH0gfCBUaGFuZ0hUPXty
>> "%B64_FILE%" echo LlRoYW5nSFR9IiwKICAgICAgICAgICAgICAgICJraG9fY29sIjogIk1hS2hvIiwKICAgICAgICAg
>> "%B64_FILE%" echo ICAgICAgICJraG9fdmFsdWUiOiBzdHIoci5NYUtobyksCiAgICAgICAgICAgICAgICAidGhhbl9j
>> "%B64_FILE%" echo b2wiOiAiTWFUaGFuIiwKICAgICAgICAgICAgICAgICJ0aGFuX3ZhbHVlIjogc3RyKHIuTWFUaGFu
>> "%B64_FILE%" echo KSwKICAgICAgICAgICAgICAgICJ2YWx1ZV9jb2wiOiAiVG9uQ0siLAogICAgICAgICAgICAgICAg
>> "%B64_FILE%" echo InZhbHVlIjogdmFsLAogICAgICAgICAgICAgICAgImRpZmZfdG9fMTA1Ml82NSI6IGFicyh2YWwg
>> "%B64_FILE%" echo LSBUQVJHRVRfVkFMVUUpLAogICAgICAgICAgICAgICAgIm5vdGUiOiAiQ0RPVEhBTiBncm91cGVk
>> "%B64_FILE%" echo IGJ5IE5hbUhULFRoYW5nSFQsTWFLaG8sTWFUaGFuIiwKICAgICAgICAgICAgfSkKICAgICAgICB3
>> "%B64_FILE%" echo cml0ZSgiIikKICAgIGV4Y2VwdCBFeGNlcHRpb24gYXMgZXhjOgogICAgICAgIHdyaXRlKGYiTOG7
>> "%B64_FILE%" echo l2kga2nhu4NtIHRyYSBDRE9USEFOOiB7ZXhjfSIpCiAgICAgICAgd3JpdGUoIiIpCgogICAgd3Jp
>> "%B64_FILE%" echo dGUoIjIpIFFVw4lUIEPDgUMgQuG6ok5HIEPDkyBD4buYVCBLSE8gVsOAIEPhu5hUIFPhu5AgTEnh
>> "%B64_FILE%" echo u4ZVIikKICAgIHdyaXRlKCItLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
>> "%B64_FILE%" echo LS0tLS0tLS0tLS0tLS0tLS0tLS0iKQoKICAgIGNvbF9zcWwgPSAiIiIKICAgIFNFTEVDVAogICAg
>> "%B64_FILE%" echo ICAgIGMuVEFCTEVfU0NIRU1BLAogICAgICAgIGMuVEFCTEVfTkFNRSwKICAgICAgICBjLkNPTFVN
>> "%B64_FILE%" echo Tl9OQU1FLAogICAgICAgIGMuREFUQV9UWVBFCiAgICBGUk9NIElORk9STUFUSU9OX1NDSEVNQS5D
>> "%B64_FILE%" echo T0xVTU5TIGMKICAgIElOTkVSIEpPSU4gSU5GT1JNQVRJT05fU0NIRU1BLlRBQkxFUyB0CiAgICAg
>> "%B64_FILE%" echo ICAgT04gYy5UQUJMRV9TQ0hFTUEgPSB0LlRBQkxFX1NDSEVNQQogICAgICAgQU5EIGMuVEFCTEVf
>> "%B64_FILE%" echo TkFNRSA9IHQuVEFCTEVfTkFNRQogICAgV0hFUkUgdC5UQUJMRV9UWVBFID0gJ0JBU0UgVEFCTEUn
>> "%B64_FILE%" echo CiAgICBPUkRFUiBCWSBjLlRBQkxFX1NDSEVNQSwgYy5UQUJMRV9OQU1FLCBjLk9SRElOQUxfUE9T
>> "%B64_FILE%" echo SVRJT047CiAgICAiIiIKICAgIGNvbHMgPSBjdXIuZXhlY3V0ZShjb2xfc3FsKS5mZXRjaGFsbCgp
>> "%B64_FILE%" echo CgogICAgdGFibGVzID0ge30KICAgIGZvciBzY2hlbWEsIHRhYmxlLCBjb2wsIGR0eXBlIGluIGNv
>> "%B64_FILE%" echo bHM6CiAgICAgICAgdGFibGVzLnNldGRlZmF1bHQoKHNjaGVtYSwgdGFibGUpLCBbXSkuYXBwZW5k
>> "%B64_FILE%" echo KChjb2wsIGR0eXBlKSkKCiAgICBraG9fcGF0dGVybnMgPSByZS5jb21waWxlKHIiXihNYUtob3xL
>> "%B64_FILE%" echo aG98TWFrfE1hX0tob3xJREtob3xLaG9JRCkkfEtobyIsIHJlLkkpCiAgICB0aGFuX3BhdHRlcm5z
>> "%B64_FILE%" echo ID0gcmUuY29tcGlsZShyIihNYVRoYW58VGVuVGhhbnxMb2FpVGhhbnxUaGFuKSIsIHJlLkkpCiAg
>> "%B64_FILE%" echo ICB2YWx1ZV9wYXR0ZXJucyA9IHJlLmNvbXBpbGUociIoVG9ufEtsZ3xLTHxLaG9pTHVvbmd8THVv
>> "%B64_FILE%" echo bmd8VGFufFNMfFNvTHVvbmd8Q3VvaXxDS3xOaGFwfFh1YXQpIiwgcmUuSSkKICAgIHBlcmlvZF9w
>> "%B64_FILE%" echo YXR0ZXJucyA9IHJlLmNvbXBpbGUociJeKE5hbUhUfFRoYW5nSFR8TmdheUhUfE5nYXl8TmdheUNU
>> "%B64_FILE%" echo fFRoYW5nfE5hbXxDYXxLaXApJCIsIHJlLkkpCgogICAgc2Nhbm5lZCA9IDAKICAgIHNraXBwZWQg
>> "%B64_FILE%" echo PSAwCgogICAgZm9yIChzY2hlbWEsIHRhYmxlKSwgdGFibGVfY29scyBpbiB0YWJsZXMuaXRlbXMo
>> "%B64_FILE%" echo KToKICAgICAgICBjb2xfbmFtZXMgPSBbYyBmb3IgYywgXyBpbiB0YWJsZV9jb2xzXQogICAgICAg
>> "%B64_FILE%" echo IGtob19jb2xzID0gW2MgZm9yIGMgaW4gY29sX25hbWVzIGlmIGtob19wYXR0ZXJucy5zZWFyY2go
>> "%B64_FILE%" echo YyldCiAgICAgICAgaWYgbm90IGtob19jb2xzOgogICAgICAgICAgICBjb250aW51ZQoKICAgICAg
>> "%B64_FILE%" echo ICBudW1fY29scyA9IFtjIGZvciBjLCB0IGluIHRhYmxlX2NvbHMgaWYgaXNfbnVtZXJpY190eXBl
>> "%B64_FILE%" echo KHQpIGFuZCB2YWx1ZV9wYXR0ZXJucy5zZWFyY2goYyldCiAgICAgICAgaWYgbm90IG51bV9jb2xz
>> "%B64_FILE%" echo OgogICAgICAgICAgICBjb250aW51ZQoKICAgICAgICB0aGFuX2NvbHMgPSBbYyBmb3IgYyBpbiBj
>> "%B64_FILE%" echo b2xfbmFtZXMgaWYgdGhhbl9wYXR0ZXJucy5zZWFyY2goYyldCiAgICAgICAgcGVyaW9kX2NvbHMg
>> "%B64_FILE%" echo PSBbYyBmb3IgYyBpbiBjb2xfbmFtZXMgaWYgcGVyaW9kX3BhdHRlcm5zLnNlYXJjaChjKV0KCiAg
>> "%B64_FILE%" echo ICAgICAgZm9yIGtob19jb2wgaW4ga2hvX2NvbHNbOjNdOgogICAgICAgICAgICBmb3IgdmFsX2Nv
>> "%B64_FILE%" echo bCBpbiBudW1fY29sc1s6MjBdOgogICAgICAgICAgICAgICAgc2Nhbm5lZCArPSAxCiAgICAgICAg
>> "%B64_FILE%" echo ICAgICAgICB0cnk6CiAgICAgICAgICAgICAgICAgICAgc2VsZWN0X2V4dHJhID0gW10KICAgICAg
>> "%B64_FILE%" echo ICAgICAgICAgICAgICBncm91cF9leHRyYSA9IFtdCgogICAgICAgICAgICAgICAgICAgIGZvciBj
>> "%B64_FILE%" echo IGluIHBlcmlvZF9jb2xzWzo1XSArIHRoYW5fY29sc1s6M106CiAgICAgICAgICAgICAgICAgICAg
>> "%B64_FILE%" echo ICAgIHNlbGVjdF9leHRyYS5hcHBlbmQocWlkZW50KGMpKQogICAgICAgICAgICAgICAgICAgICAg
>> "%B64_FILE%" echo ICBncm91cF9leHRyYS5hcHBlbmQocWlkZW50KGMpKQoKICAgICAgICAgICAgICAgICAgICBleHRy
>> "%B64_FILE%" echo YV9zcWwgPSAiLCAiICsgIiwgIi5qb2luKHNlbGVjdF9leHRyYSkgaWYgc2VsZWN0X2V4dHJhIGVs
>> "%B64_FILE%" echo c2UgIiIKICAgICAgICAgICAgICAgICAgICBncm91cF9zcWwgPSAiLCAiICsgIiwgIi5qb2luKGdy
>> "%B64_FILE%" echo b3VwX2V4dHJhKSBpZiBncm91cF9leHRyYSBlbHNlICIiCgogICAgICAgICAgICAgICAgICAgIGto
>> "%B64_FILE%" echo b190ZXh0ID0gY2FzdF90b190ZXh0X3NxbChraG9fY29sKQogICAgICAgICAgICAgICAgICAgIHZh
>> "%B64_FILE%" echo bF9mbG9hdCA9IGNhc3RfdG9fZmxvYXRfc3FsKHZhbF9jb2wpCgogICAgICAgICAgICAgICAgICAg
>> "%B64_FILE%" echo IHNxbCA9IGYiIiIKICAgICAgICAgICAgICAgICAgICBTRUxFQ1QgVE9QIDEwMAogICAgICAgICAg
>> "%B64_FILE%" echo ICAgICAgICAgICAgICB7cWlkZW50KGtob19jb2wpfSBBUyBLaG9WYWx1ZQogICAgICAgICAgICAg
>> "%B64_FILE%" echo ICAgICAgICAgICB7ZXh0cmFfc3FsfSwKICAgICAgICAgICAgICAgICAgICAgICAgU1VNKHt2YWxf
>> "%B64_FILE%" echo ZmxvYXR9KSBBUyBDaGVja1ZhbHVlLAogICAgICAgICAgICAgICAgICAgICAgICBDT1VOVCgqKSBB
>> "%B64_FILE%" echo UyBSb3dDb3VudAogICAgICAgICAgICAgICAgICAgIEZST00ge3FpZGVudChzY2hlbWEpfS57cWlk
>> "%B64_FILE%" echo ZW50KHRhYmxlKX0KICAgICAgICAgICAgICAgICAgICBXSEVSRSB7a2hvX3RleHR9IElOIChOJzEn
>> "%B64_FILE%" echo LCBOJzAxJywgTidLaG8gMScpCiAgICAgICAgICAgICAgICAgICAgR1JPVVAgQlkge3FpZGVudChr
>> "%B64_FILE%" echo aG9fY29sKX17Z3JvdXBfc3FsfQogICAgICAgICAgICAgICAgICAgIEhBVklORyBTVU0oe3ZhbF9m
>> "%B64_FILE%" echo bG9hdH0pIElTIE5PVCBOVUxMCiAgICAgICAgICAgICAgICAgICAgT1JERVIgQlkgQUJTKFNVTSh7
>> "%B64_FILE%" echo dmFsX2Zsb2F0fSkgLSA/KSBBU0M7CiAgICAgICAgICAgICAgICAgICAgIiIiCiAgICAgICAgICAg
>> "%B64_FILE%" echo ICAgICAgICAgcm93cyA9IGN1ci5leGVjdXRlKHNxbCwgVEFSR0VUX1ZBTFVFKS5mZXRjaGFsbCgp
>> "%B64_FILE%" echo CiAgICAgICAgICAgICAgICAgICAgaWYgbm90IHJvd3M6CiAgICAgICAgICAgICAgICAgICAgICAg
>> "%B64_FILE%" echo IGNvbnRpbnVlCgogICAgICAgICAgICAgICAgICAgIGZvciByIGluIHJvd3NbOjhdOgogICAgICAg
>> "%B64_FILE%" echo ICAgICAgICAgICAgICAgICB2YWwgPSBzYWZlX2Zsb2F0KGdldGF0dHIociwgIkNoZWNrVmFsdWUi
>> "%B64_FILE%" echo LCBOb25lKSkKICAgICAgICAgICAgICAgICAgICAgICAgaWYgdmFsIGlzIE5vbmU6CiAgICAgICAg
>> "%B64_FILE%" echo ICAgICAgICAgICAgICAgICAgICBjb250aW51ZQoKICAgICAgICAgICAgICAgICAgICAgICAgZGlm
>> "%B64_FILE%" echo ZiA9IGFicyh2YWwgLSBUQVJHRVRfVkFMVUUpCiAgICAgICAgICAgICAgICAgICAgICAgIGlmIGRp
>> "%B64_FILE%" echo ZmYgPD0gMzAwIG9yICgwIDwgdmFsIDwgMTAwMDAwKToKICAgICAgICAgICAgICAgICAgICAgICAg
>> "%B64_FILE%" echo ICAgIHBlcmlvZCA9IFtdCiAgICAgICAgICAgICAgICAgICAgICAgICAgICB0aGFuID0gW10KICAg
>> "%B64_FILE%" echo ICAgICAgICAgICAgICAgICAgICAgICAgIGZvciBjIGluIHBlcmlvZF9jb2xzWzo1XToKICAgICAg
>> "%B64_FILE%" echo ICAgICAgICAgICAgICAgICAgICAgICAgICBpZiBoYXNhdHRyKHIsIGMpOgogICAgICAgICAgICAg
>> "%B64_FILE%" echo ICAgICAgICAgICAgICAgICAgICAgICBwZXJpb2QuYXBwZW5kKGYie2N9PXtnZXRhdHRyKHIsIGMp
>> "%B64_FILE%" echo fSIpCiAgICAgICAgICAgICAgICAgICAgICAgICAgICBmb3IgYyBpbiB0aGFuX2NvbHNbOjNdOgog
>> "%B64_FILE%" echo ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIGlmIGhhc2F0dHIociwgYyk6CiAgICAgICAg
>> "%B64_FILE%" echo ICAgICAgICAgICAgICAgICAgICAgICAgICAgIHRoYW4uYXBwZW5kKGYie2N9PXtnZXRhdHRyKHIs
>> "%B64_FILE%" echo IGMpfSIpCgogICAgICAgICAgICAgICAgICAgICAgICAgICAgcmVzdWx0cy5hcHBlbmQoewogICAg
>> "%B64_FILE%" echo ICAgICAgICAgICAgICAgICAgICAgICAgICAgICJzb3VyY2UiOiAic2NhbiIsCiAgICAgICAgICAg
>> "%B64_FILE%" echo ICAgICAgICAgICAgICAgICAgICAgInNjaGVtYSI6IHNjaGVtYSwKICAgICAgICAgICAgICAgICAg
>> "%B64_FILE%" echo ICAgICAgICAgICAgICAidGFibGUiOiB0YWJsZSwKICAgICAgICAgICAgICAgICAgICAgICAgICAg
>> "%B64_FILE%" echo ICAgICAicGVyaW9kIjogIiB8ICIuam9pbihwZXJpb2QpLAogICAgICAgICAgICAgICAgICAgICAg
>> "%B64_FILE%" echo ICAgICAgICAgICJraG9fY29sIjoga2hvX2NvbCwKICAgICAgICAgICAgICAgICAgICAgICAgICAg
>> "%B64_FILE%" echo ICAgICAia2hvX3ZhbHVlIjogc3RyKGdldGF0dHIociwgIktob1ZhbHVlIiwgIiIpKSwKICAgICAg
>> "%B64_FILE%" echo ICAgICAgICAgICAgICAgICAgICAgICAgICAidGhhbl9jb2wiOiAiIHwgIi5qb2luKHRoYW4pLAog
>> "%B64_FILE%" echo ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICJ0aGFuX3ZhbHVlIjogIiIsCiAgICAgICAg
>> "%B64_FILE%" echo ICAgICAgICAgICAgICAgICAgICAgICAgInZhbHVlX2NvbCI6IHZhbF9jb2wsCiAgICAgICAgICAg
>> "%B64_FILE%" echo ICAgICAgICAgICAgICAgICAgICAgInZhbHVlIjogdmFsLAogICAgICAgICAgICAgICAgICAgICAg
>> "%B64_FILE%" echo ICAgICAgICAgICJkaWZmX3RvXzEwNTJfNjUiOiBkaWZmLAogICAgICAgICAgICAgICAgICAgICAg
>> "%B64_FILE%" echo ICAgICAgICAgICJub3RlIjogZiJSb3dDb3VudD17Z2V0YXR0cihyLCAnUm93Q291bnQnLCAnJyl9
>> "%B64_FILE%" echo IiwKICAgICAgICAgICAgICAgICAgICAgICAgICAgIH0pCiAgICAgICAgICAgICAgICBleGNlcHQg
>> "%B64_FILE%" echo RXhjZXB0aW9uOgogICAgICAgICAgICAgICAgICAgIHNraXBwZWQgKz0gMQogICAgICAgICAgICAg
>> "%B64_FILE%" echo ICAgICAgIGNvbnRpbnVlCgogICAgcmVzdWx0c19zb3J0ZWQgPSBzb3J0ZWQocmVzdWx0cywga2V5
>> "%B64_FILE%" echo PWxhbWJkYSB4OiB4WyJkaWZmX3RvXzEwNTJfNjUiXSkKCiAgICB3cml0ZShmIlPhu5EgcGjDqXAg
>> "%B64_FILE%" echo cXXDqXQ6IHtzY2FubmVkfSIpCiAgICB3cml0ZShmIlPhu5EgcGjDqXAgYuG7jyBxdWEgZG8gbOG7
>> "%B64_FILE%" echo l2kga2nhu4N1IGThu68gbGnhu4d1L3F1eeG7gW46IHtza2lwcGVkfSIpCiAgICB3cml0ZShmIlPh
>> "%B64_FILE%" echo u5Ega+G6v3QgcXXhuqMgdGh1IMSRxrDhu6NjOiB7bGVuKHJlc3VsdHNfc29ydGVkKX0iKQogICAg
>> "%B64_FILE%" echo d3JpdGUoIiIpCiAgICB3cml0ZSgiMykgVE9QIDUwIEvhur5UIFFV4bqiIEfhuqZOIDEuMDUyLDY1
>> "%B64_FILE%" echo IE5I4bqkVCIpCiAgICB3cml0ZSgiLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
>> "%B64_FILE%" echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tIikKCiAgICBmb3IgaSwgciBpbiBlbnVtZXJhdGUocmVz
>> "%B64_FILE%" echo dWx0c19zb3J0ZWRbOjUwXSwgc3RhcnQ9MSk6CiAgICAgICAgd3JpdGUoCiAgICAgICAgICAgIGYi
>> "%B64_FILE%" echo e2k6MDJkfS4ge3JbJ3NjaGVtYSddfS57clsndGFibGUnXX0gfCAiCiAgICAgICAgICAgIGYie3Jb
>> "%B64_FILE%" echo J2tob19jb2wnXX09e3JbJ2tob192YWx1ZSddfSB8ICIKICAgICAgICAgICAgZiJ7clsndmFsdWVf
>> "%B64_FILE%" echo Y29sJ119PXtyWyd2YWx1ZSddOiwuMmZ9IHwgIgogICAgICAgICAgICBmIkzhu4djaD17clsnZGlm
>> "%B64_FILE%" echo Zl90b18xMDUyXzY1J106LC4yZn0gfCAiCiAgICAgICAgICAgIGYie3JbJ3BlcmlvZCddfSB8IHty
>> "%B64_FILE%" echo Wyd0aGFuX2NvbCddfSB7clsndGhhbl92YWx1ZSddfSB8IHtyWydub3RlJ119IgogICAgICAgICkK
>> "%B64_FILE%" echo CiAgICB3aXRoIE9VVF9DU1Yub3BlbigidyIsIG5ld2xpbmU9IiIsIGVuY29kaW5nPSJ1dGYtOC1z
>> "%B64_FILE%" echo aWciKSBhcyBmOgogICAgICAgIGZpZWxkbmFtZXMgPSBbCiAgICAgICAgICAgICJzb3VyY2UiLCAi
>> "%B64_FILE%" echo c2NoZW1hIiwgInRhYmxlIiwgInBlcmlvZCIsICJraG9fY29sIiwgImtob192YWx1ZSIsCiAgICAg
>> "%B64_FILE%" echo ICAgICAgICJ0aGFuX2NvbCIsICJ0aGFuX3ZhbHVlIiwgInZhbHVlX2NvbCIsICJ2YWx1ZSIsICJk
>> "%B64_FILE%" echo aWZmX3RvXzEwNTJfNjUiLCAibm90ZSIKICAgICAgICBdCiAgICAgICAgdyA9IGNzdi5EaWN0V3Jp
>> "%B64_FILE%" echo dGVyKGYsIGZpZWxkbmFtZXM9ZmllbGRuYW1lcykKICAgICAgICB3LndyaXRlaGVhZGVyKCkKICAg
>> "%B64_FILE%" echo ICAgICBmb3IgciBpbiByZXN1bHRzX3NvcnRlZDoKICAgICAgICAgICAgdy53cml0ZXJvdyhyKQoK
>> "%B64_FILE%" echo ICAgIHdyaXRlKCIiKQogICAgd3JpdGUoIj09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
>> "%B64_FILE%" echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PSIpCiAgICB3cml0ZSgiSE/DgE4gVEjDgE5IIikK
>> "%B64_FILE%" echo ICAgIHdyaXRlKCI9PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
>> "%B64_FILE%" echo PT09PT09PT09PT09PT0iKQogICAgd3JpdGUoZiJGaWxlIFRYVDoge09VVF9UWFR9IikKICAgIHdy
>> "%B64_FILE%" echo aXRlKGYiRmlsZSBDU1Y6IHtPVVRfQ1NWfSIpCiAgICB3cml0ZSgiIikKICAgIHdyaXRlKCJBbmgg
>> "%B64_FILE%" echo Z+G7rWkgbOG6oWkgcGjhuqduIFRPUCA1MCBr4bq/dCBxdeG6oyBn4bqnbiAxLjA1Miw2NSBuaOG6
>> "%B64_FILE%" echo pXQuIikKICAgIHdyaXRlKCJUw7RpIHPhur0gZOG7sWEgdsOgbyBi4bqjbmcvY+G7mXQgxJHDum5n
>> "%B64_FILE%" echo IMSR4buDIHPhu61hIGJhY2tlbmQvc2VydmVyLnB5LiIpCgogICAgY29ubi5jbG9zZSgpCgogICAg
>> "%B64_FILE%" echo IyBN4bufIGZvbGRlciBvdXRwdXQgdOG7sSDEkeG7mW5nCiAgICB0cnk6CiAgICAgICAgc3VicHJv
>> "%B64_FILE%" echo Y2Vzcy5Qb3BlbihbImV4cGxvcmVyLmV4ZSIsIHN0cihPVVRfRElSKV0pCiAgICBleGNlcHQgRXhj
>> "%B64_FILE%" echo ZXB0aW9uOgogICAgICAgIHBhc3MKCgppZiBfX25hbWVfXyA9PSAiX19tYWluX18iOgogICAgdHJ5
>> "%B64_FILE%" echo OgogICAgICAgIG1haW4oKQogICAgZXhjZXB0IEV4Y2VwdGlvbiBhcyBleGM6CiAgICAgICAgd3Jp
>> "%B64_FILE%" echo dGUoIiIpCiAgICAgICAgd3JpdGUoIltM4buWSV0gIiArIHN0cihleGMpKQogICAgICAgIHdyaXRl
>> "%B64_FILE%" echo KCJLaeG7g20gdHJhIGzhuqFpIGvhur90IG7hu5FpIFNRTCBTZXJ2ZXIsIE9EQkMgRHJpdmVyIDE4
>> "%B64_FILE%" echo IGhv4bq3YyBxdXnhu4FuIHRydXkgY+G6rXAgREIuIikKICAgICAgICB0cnk6CiAgICAgICAgICAg
>> "%B64_FILE%" echo IHN1YnByb2Nlc3MuUG9wZW4oWyJleHBsb3Jlci5leGUiLCBzdHIoT1VUX0RJUildKQogICAgICAg
>> "%B64_FILE%" echo IGV4Y2VwdCBFeGNlcHRpb246CiAgICAgICAgICAgIHBhc3MKICAgICAgICBzeXMuZXhpdCgxKQo=
python -c "import base64, pathlib, os; b=pathlib.Path(os.environ['B64_FILE']).read_text().replace('\n','').replace('\r','').strip(); pathlib.Path(os.environ['PY_FILE']).write_bytes(base64.b64decode(b))"
if errorlevel 1 (
    echo [LOI] Khong tao duoc file Python tam.
    pause
    exit /b 1
)

python "%PY_FILE%"
echo.
echo Ket qua nam tai:
echo %USERPROFILE%\Desktop\TTCO_CHECK_KHO1_1052_65
echo.
start "" "%USERPROFILE%\Desktop\TTCO_CHECK_KHO1_1052_65"
pause
