@echo off
setlocal EnableExtensions EnableDelayedExpansion
chcp 65001 >nul
title TTCO - Bat SQL live khi bam Xem kq - v15

set "CONFIG_DIR=%LOCALAPPDATA%\TTCO_Capture_SQL_Live"
set "PY_MAIN=%CONFIG_DIR%\TTCO_Capture_SQL_Live_v15.py"
set "B64_FILE=%CONFIG_DIR%\TTCO_Capture_SQL_Live_v15.b64"

if not exist "%CONFIG_DIR%" mkdir "%CONFIG_DIR%" >nul 2>&1

call :WRITE_PY
if errorlevel 1 (
    echo [LOI] Khong tao duoc file Python tam.
    pause
    exit /b 1
)

cls
echo ============================================================
echo   TTCO - BAT TRUC TIEP CAU SQL KHI BAM XEM KQ - V15
echo ============================================================
echo.
echo Cach nay nhanh hon cach so sanh bang:
echo - Bat sys.dm_exec_requests va sys.dm_exec_query_stats.
echo - Ghi lai cau EXEC/SELECT ma TTCO_APP vua gui SQL Server.
echo.
echo Ket qua xuat ra:
echo   Desktop\TTCO_CAPTURE_SQL_LIVE
echo.
pause

python "%PY_MAIN%"
echo.
echo Ket qua nam tai:
echo %USERPROFILE%\Desktop\TTCO_CAPTURE_SQL_LIVE
echo.
start "" "%USERPROFILE%\Desktop\TTCO_CAPTURE_SQL_LIVE"
pause
exit /b 0

:WRITE_PY
> "%B64_FILE%" echo CiMgLSotIGNvZGluZzogdXRmLTggLSotCmltcG9ydCBjc3YKaW1wb3J0IG9zCmltcG9ydCByZQpp
>> "%B64_FILE%" echo bXBvcnQgc3VicHJvY2VzcwppbXBvcnQgc3lzCmltcG9ydCB0aW1lCmZyb20gZGF0ZXRpbWUgaW1w
>> "%B64_FILE%" echo b3J0IGRhdGV0aW1lCmZyb20gcGF0aGxpYiBpbXBvcnQgUGF0aAoKU0VSVkVSID0gciJ0dXllbnRo
>> "%B64_FILE%" echo YW5jdWFvbmcuY29tLnZuLDUyMzc2IgpEQVRBQkFTRSA9ICJUVENPX1RIT05HS0UiCgpVU0VSUFJP
>> "%B64_FILE%" echo RklMRSA9IFBhdGgob3MuZW52aXJvbi5nZXQoIlVTRVJQUk9GSUxFIiwgc3RyKFBhdGguaG9tZSgp
>> "%B64_FILE%" echo KSkpCkRFU0tUT1AgPSBVU0VSUFJPRklMRSAvICJEZXNrdG9wIgpPVVRfRElSID0gREVTS1RPUCAv
>> "%B64_FILE%" echo ICJUVENPX0NBUFRVUkVfU1FMX0xJVkUiCk9VVF9ESVIubWtkaXIocGFyZW50cz1UcnVlLCBleGlz
>> "%B64_FILE%" echo dF9vaz1UcnVlKQoKU1RBTVAgPSBkYXRldGltZS5ub3coKS5zdHJmdGltZSgiJVklbSVkXyVIJU0l
>> "%B64_FILE%" echo UyIpCk9VVF9UWFQgPSBPVVRfRElSIC8gZiJ0dGNvX3NxbF9saXZlX2NhcHR1cmVfe1NUQU1QfS50
>> "%B64_FILE%" echo eHQiCk9VVF9DU1YgPSBPVVRfRElSIC8gZiJ0dGNvX3NxbF9saXZlX2NhcHR1cmVfe1NUQU1QfS5j
>> "%B64_FILE%" echo c3YiCk9VVF9VTklRVUUgPSBPVVRfRElSIC8gZiJ0dGNvX3NxbF91bmlxdWVfdGV4dF97U1RBTVB9
>> "%B64_FILE%" echo LnR4dCIKCgpkZWYgd3JpdGUobGluZT0iIik6CiAgICBwcmludChsaW5lKQogICAgd2l0aCBPVVRf
>> "%B64_FILE%" echo VFhULm9wZW4oImEiLCBlbmNvZGluZz0idXRmLTgiKSBhcyBmOgogICAgICAgIGYud3JpdGUoc3Ry
>> "%B64_FILE%" echo KGxpbmUpICsgIlxuIikKCgpkZWYgd3JpdGVfdW5pcXVlKGxpbmU9IiIpOgogICAgd2l0aCBPVVRf
>> "%B64_FILE%" echo VU5JUVVFLm9wZW4oImEiLCBlbmNvZGluZz0idXRmLTgiKSBhcyBmOgogICAgICAgIGYud3JpdGUo
>> "%B64_FILE%" echo c3RyKGxpbmUpICsgIlxuIikKCgpkZWYgZW5zdXJlX3B5b2RiYygpOgogICAgdHJ5OgogICAgICAg
>> "%B64_FILE%" echo IGltcG9ydCBweW9kYmMgICMgbm9xYQogICAgICAgIHJldHVybgogICAgZXhjZXB0IEV4Y2VwdGlv
>> "%B64_FILE%" echo bjoKICAgICAgICB3cml0ZSgiQ2jGsGEgY8OzIHB5b2RiYy4gxJBhbmcgdGjhu60gY8OgaSBweW9k
>> "%B64_FILE%" echo YmMuLi4iKQogICAgICAgIHN1YnByb2Nlc3MuY2hlY2tfY2FsbChbc3lzLmV4ZWN1dGFibGUsICIt
>> "%B64_FILE%" echo bSIsICJwaXAiLCAiaW5zdGFsbCIsICJweW9kYmMiXSkKCgpkZWYgY29ubmVjdCgpOgogICAgaW1w
>> "%B64_FILE%" echo b3J0IHB5b2RiYwogICAgY29ubl9zdHIgPSAoCiAgICAgICAgIkRSSVZFUj17T0RCQyBEcml2ZXIg
>> "%B64_FILE%" echo MTggZm9yIFNRTCBTZXJ2ZXJ9OyIKICAgICAgICBmIlNFUlZFUj17U0VSVkVSfTsiCiAgICAgICAg
>> "%B64_FILE%" echo ZiJEQVRBQkFTRT17REFUQUJBU0V9OyIKICAgICAgICAiVHJ1c3RlZF9Db25uZWN0aW9uPXllczsi
>> "%B64_FILE%" echo CiAgICAgICAgIlRydXN0U2VydmVyQ2VydGlmaWNhdGU9eWVzOyIKICAgICkKICAgIGNvbm4gPSBw
>> "%B64_FILE%" echo eW9kYmMuY29ubmVjdChjb25uX3N0ciwgdGltZW91dD0xNSwgYXV0b2NvbW1pdD1UcnVlKQogICAg
>> "%B64_FILE%" echo cmV0dXJuIGNvbm4KCgpkZWYgbm9ybV9zcWwocyk6CiAgICBpZiBzIGlzIE5vbmU6CiAgICAgICAg
>> "%B64_FILE%" echo cmV0dXJuICIiCiAgICBzID0gc3RyKHMpLnJlcGxhY2UoIlxyIiwgIiAiKS5yZXBsYWNlKCJcbiIs
>> "%B64_FILE%" echo ICIgIikucmVwbGFjZSgiXHQiLCAiICIpCiAgICBzID0gcmUuc3ViKHIiXHMrIiwgIiAiLCBzKS5z
>> "%B64_FILE%" echo dHJpcCgpCiAgICByZXR1cm4gcwoKCmRlZiBjb21wYWN0KHMsIG49NTAwKToKICAgIHMgPSBub3Jt
>> "%B64_FILE%" echo X3NxbChzKQogICAgcmV0dXJuIHNbOm5dICsgKCIuLi4iIGlmIGxlbihzKSA+IG4gZWxzZSAiIikK
>> "%B64_FILE%" echo CgpkZWYgc2hvdWxkX2tlZXAoc3FsX3RleHQsIHN0YXRlbWVudF90ZXh0LCBwcm9ncmFtX25hbWUp
>> "%B64_FILE%" echo OgogICAgdGV4dCA9IChzcWxfdGV4dCBvciAiIikgKyAiICIgKyAoc3RhdGVtZW50X3RleHQgb3Ig
>> "%B64_FILE%" echo IiIpICsgIiAiICsgKHByb2dyYW1fbmFtZSBvciAiIikKICAgIHRleHRfbG93ID0gdGV4dC5sb3dl
>> "%B64_FILE%" echo cigpCgogICAgIyDGr3UgdGnDqm4gY8OhYyBjw6J1IGxpw6puIHF1YW4gYsOhbyBjw6FvL3Thu5Nu
>> "%B64_FILE%" echo IGtoby90aGFuL2toby4KICAgIGtleXdvcmRzID0gWwogICAgICAgICJnM19iYzA1IiwgImJjMDUi
>> "%B64_FILE%" echo LCAiY2RvdGhhbiIsICJ0b25jayIsICJ0b25kayIsICJuaGFwdGsiLCAieHVhdHRrIiwKICAgICAg
>> "%B64_FILE%" echo ICAic3BfdGtlIiwgInRrZV8iLCAidGhhbiIsICJraG8iLCAibWFraG8iLCAibWF0aGFuIiwKICAg
>> "%B64_FILE%" echo ICAgICAidGhhbnZhb3NhbmciLCAidGhhbnJhc2FuZyIsICJ0aGFubmhhcCIsICJ0aGFueHVhdCIs
>> "%B64_FILE%" echo ICJ0aGFuZ2lhb25oYW4iLAogICAgICAgICJ0aGFua3QiLCAidGhhbnRiZCIsICJ0aGFua2siCiAg
>> "%B64_FILE%" echo ICBdCiAgICByZXR1cm4gYW55KGsgaW4gdGV4dF9sb3cgZm9yIGsgaW4ga2V5d29yZHMpCgoKZGVm
>> "%B64_FILE%" echo IGNhcHR1cmVfYWN0aXZlX3JlcXVlc3RzKGN1cik6CiAgICBzcWwgPSAiIiIKICAgIFNFTEVDVAog
>> "%B64_FILE%" echo ICAgICAgIEdFVERBVEUoKSBBUyBjYXB0dXJlZF9hdCwKICAgICAgICByLnNlc3Npb25faWQsCiAg
>> "%B64_FILE%" echo ICAgICAgcy5ob3N0X25hbWUsCiAgICAgICAgcy5wcm9ncmFtX25hbWUsCiAgICAgICAgcy5sb2dp
>> "%B64_FILE%" echo bl9uYW1lLAogICAgICAgIERCX05BTUUoci5kYXRhYmFzZV9pZCkgQVMgZGJfbmFtZSwKICAgICAg
>> "%B64_FILE%" echo ICByLnN0YXR1cywKICAgICAgICByLmNvbW1hbmQsCiAgICAgICAgci5jcHVfdGltZSwKICAgICAg
>> "%B64_FILE%" echo ICByLnRvdGFsX2VsYXBzZWRfdGltZSwKICAgICAgICB0LnRleHQgQVMgc3FsX3RleHQsCiAgICAg
>> "%B64_FILE%" echo ICAgU1VCU1RSSU5HKAogICAgICAgICAgICB0LnRleHQsCiAgICAgICAgICAgIChyLnN0YXRlbWVu
>> "%B64_FILE%" echo dF9zdGFydF9vZmZzZXQgLyAyKSArIDEsCiAgICAgICAgICAgICgKICAgICAgICAgICAgICAgICgK
>> "%B64_FILE%" echo ICAgICAgICAgICAgICAgICAgICBDQVNFCiAgICAgICAgICAgICAgICAgICAgICAgIFdIRU4gci5z
>> "%B64_FILE%" echo dGF0ZW1lbnRfZW5kX29mZnNldCA9IC0xIFRIRU4gREFUQUxFTkdUSCh0LnRleHQpCiAgICAgICAg
>> "%B64_FILE%" echo ICAgICAgICAgICAgICAgIEVMU0Ugci5zdGF0ZW1lbnRfZW5kX29mZnNldAogICAgICAgICAgICAg
>> "%B64_FILE%" echo ICAgICAgIEVORCAtIHIuc3RhdGVtZW50X3N0YXJ0X29mZnNldAogICAgICAgICAgICAgICAgKSAv
>> "%B64_FILE%" echo IDIKICAgICAgICAgICAgKSArIDEKICAgICAgICApIEFTIHN0YXRlbWVudF90ZXh0CiAgICBGUk9N
>> "%B64_FILE%" echo IHN5cy5kbV9leGVjX3JlcXVlc3RzIHIKICAgIElOTkVSIEpPSU4gc3lzLmRtX2V4ZWNfc2Vzc2lv
>> "%B64_FILE%" echo bnMgcwogICAgICAgIE9OIHIuc2Vzc2lvbl9pZCA9IHMuc2Vzc2lvbl9pZAogICAgQ1JPU1MgQVBQ
>> "%B64_FILE%" echo TFkgc3lzLmRtX2V4ZWNfc3FsX3RleHQoci5zcWxfaGFuZGxlKSB0CiAgICBXSEVSRSByLnNlc3Np
>> "%B64_FILE%" echo b25faWQgPD4gQEBTUElECiAgICAgIEFORCBzLmlzX3VzZXJfcHJvY2VzcyA9IDEKICAgICIiIgog
>> "%B64_FILE%" echo ICAgcmV0dXJuIGN1ci5leGVjdXRlKHNxbCkuZmV0Y2hhbGwoKQoKCmRlZiBjYXB0dXJlX3JlY2Vu
>> "%B64_FILE%" echo dF9jYWNoZWQoY3VyKToKICAgICMgQuG6r3QgdGjDqm0gcGxhbiB24burYSBjaOG6oXkgZ+G6p24g
>> "%B64_FILE%" echo xJHDonkgdHJvbmcgdHLGsOG7nW5nIGjhu6NwIGPDonUgU1FMIGNo4bqheSBxdcOhIG5oYW5oLCBw
>> "%B64_FILE%" echo b2xsaW5nIHJlcXVlc3Qga2jDtG5nIGvhu4twIGLhuq90LgogICAgc3FsID0gIiIiCiAgICBTRUxF
>> "%B64_FILE%" echo Q1QgVE9QIDIwMAogICAgICAgIEdFVERBVEUoKSBBUyBjYXB0dXJlZF9hdCwKICAgICAgICBxcy5s
>> "%B64_FILE%" echo YXN0X2V4ZWN1dGlvbl90aW1lLAogICAgICAgIERCX05BTUUoc3QuZGJpZCkgQVMgZGJfbmFtZSwK
>> "%B64_FILE%" echo ICAgICAgICBxcy5leGVjdXRpb25fY291bnQsCiAgICAgICAgcXMudG90YWxfZWxhcHNlZF90aW1l
>> "%B64_FILE%" echo LAogICAgICAgIHN0LnRleHQgQVMgc3FsX3RleHQKICAgIEZST00gc3lzLmRtX2V4ZWNfcXVlcnlf
>> "%B64_FILE%" echo c3RhdHMgcXMKICAgIENST1NTIEFQUExZIHN5cy5kbV9leGVjX3NxbF90ZXh0KHFzLnNxbF9oYW5k
>> "%B64_FILE%" echo bGUpIHN0CiAgICBXSEVSRSBxcy5sYXN0X2V4ZWN1dGlvbl90aW1lID49IERBVEVBREQoTUlOVVRF
>> "%B64_FILE%" echo LCAtMTAsIEdFVERBVEUoKSkKICAgIE9SREVSIEJZIHFzLmxhc3RfZXhlY3V0aW9uX3RpbWUgREVT
>> "%B64_FILE%" echo QwogICAgIiIiCiAgICB0cnk6CiAgICAgICAgcmV0dXJuIGN1ci5leGVjdXRlKHNxbCkuZmV0Y2hh
>> "%B64_FILE%" echo bGwoKQogICAgZXhjZXB0IEV4Y2VwdGlvbjoKICAgICAgICByZXR1cm4gW10KCgpkZWYgbWFpbigp
>> "%B64_FILE%" echo OgogICAgd3JpdGUoIj09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
>> "%B64_FILE%" echo PT09PT09PT09PT09PT09PSIpCiAgICB3cml0ZSgiVFRDTyAtIELhuq5UIFRS4buwQyBUSeG6vlAg
>> "%B64_FILE%" echo Q8OCVSBTUUwgS0hJIELhuqRNIFhFTSBLUSBUVENPX0FQUCAtIFYxNSIpCiAgICB3cml0ZSgiPT09
>> "%B64_FILE%" echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
>> "%B64_FILE%" echo IikKICAgIHdyaXRlKCJDw6FjaCBkw7luZzoiKQogICAgd3JpdGUoIjEuIE3hu58gVFRDT19BUFAs
>> "%B64_FILE%" echo IHbDoG8gxJHDum5nIG3DoG4gaMOsbmggYsOhbyBjw6FvL3Thu5NuIGtoby4iKQogICAgd3JpdGUo
>> "%B64_FILE%" echo IjIuIMSQ4buDIGPhu61hIHPhu5UgbsOgeSBjaOG6oXkgdsOgIGNo4budLiIpCiAgICB3cml0ZSgi
>> "%B64_FILE%" echo My4gS2hpIHTDtGkgYsOhbywgc2FuZyBUVENPX0FQUCBi4bqlbSBYZW0ga3EgLyBs4bqleSBr4bq/
>> "%B64_FILE%" echo dCBxdeG6oy4iKQogICAgd3JpdGUoIjQuIMSQ4bujaSBUVENPX0FQUCBoaeG7h24gc+G7kSDEkcO6
>> "%B64_FILE%" echo bmcsIHLhu5NpIHF1YXkgbOG6oWkgY+G7rWEgc+G7lSBuw6B5IGNo4budIGvhur90IHRow7pjLiIp
>> "%B64_FILE%" echo CiAgICB3cml0ZSgiIikKICAgIHdyaXRlKCJN4bulYyB0acOqdTogYuG6r3QgdHLhu7FjIHRp4bq/
>> "%B64_FILE%" echo cCBjw6J1IEVYRUMvU0VMRUNUIG3DoCBUVENPX0FQUCBn4butaSBsw6puIFNRTCBTZXJ2ZXIuIikK
>> "%B64_FILE%" echo ICAgIHdyaXRlKCIiKQogICAgd3JpdGUoZiJPdXRwdXQgZm9sZGVyIDoge09VVF9ESVJ9IikKICAg
>> "%B64_FILE%" echo IHdyaXRlKGYiVFhUIGNow61uaCAgICAgOiB7T1VUX1RYVH0iKQogICAgd3JpdGUoZiJDU1YgICAg
>> "%B64_FILE%" echo ICAgICAgIDoge09VVF9DU1Z9IikKICAgIHdyaXRlKGYiU1FMIHVuaXF1ZSAgICA6IHtPVVRfVU5J
>> "%B64_FILE%" echo UVVFfSIpCiAgICB3cml0ZSgiIikKCiAgICBlbnN1cmVfcHlvZGJjKCkKICAgIGNvbm4gPSBjb25u
>> "%B64_FILE%" echo ZWN0KCkKICAgIGN1ciA9IGNvbm4uY3Vyc29yKCkKCiAgICAjIEtp4buDbSB0cmEgcXV54buBbiDE
>> "%B64_FILE%" echo keG7jWMgRE1WCiAgICB0cnk6CiAgICAgICAgY3VyLmV4ZWN1dGUoIlNFTEVDVCBUT1AgMSBzZXNz
>> "%B64_FILE%" echo aW9uX2lkIEZST00gc3lzLmRtX2V4ZWNfcmVxdWVzdHMiKS5mZXRjaGFsbCgpCiAgICBleGNlcHQg
>> "%B64_FILE%" echo RXhjZXB0aW9uIGFzIGV4YzoKICAgICAgICB3cml0ZSgiW0zhu5ZJXSBUw6BpIGtob+G6o24gU1FM
>> "%B64_FILE%" echo IGhp4buHbiB04bqhaSBraMO0bmcgY8OzIHF1eeG7gW4gxJHhu41jIHN5cy5kbV9leGVjX3JlcXVl
>> "%B64_FILE%" echo c3RzLiIpCiAgICAgICAgd3JpdGUoIkPhuqduIHF1eeG7gW4gVklFVyBTRVJWRVIgU1RBVEUgaG/h
>> "%B64_FILE%" echo urdjIGNo4bqheSB0csOqbiBtw6F5L3TDoGkga2hv4bqjbiBjw7MgcXV54buBbiBjYW8gaMahbi4i
>> "%B64_FILE%" echo KQogICAgICAgIHdyaXRlKCJDaGkgdGnhur90OiAiICsgc3RyKGV4YykpCiAgICAgICAgY29ubi5j
>> "%B64_FILE%" echo bG9zZSgpCiAgICAgICAgcmV0dXJuIDEKCiAgICBkdXJhdGlvbiA9IDEyMAogICAgaW50ZXJ2YWwg
>> "%B64_FILE%" echo PSAwLjEwCgogICAgd3JpdGUoIkNodeG6qW4gYuG7iyBi4bqvdCBTUUwgdHJvbmcgMTIwIGdpw6J5
>> "%B64_FILE%" echo LiIpCiAgICBpbnB1dCgiQuG6pW0gRW50ZXIg4bufIMSRw6J5LCBy4buTaSBOR0FZIEzhuqxQIFTh
>> "%B64_FILE%" echo u6hDIHNhbmcgVFRDT19BUFAgYuG6pW0gWGVtIGtxLi4uICIpCgogICAgd3JpdGUoIiIpCiAgICB3
>> "%B64_FILE%" echo cml0ZSgixJBBTkcgQuG6rlQgU1FMIExJVkUuLi4gQW5oIGjDo3kgYuG6pW0gWGVtIGtxIHRyw6pu
>> "%B64_FILE%" echo IFRUQ09fQVBQIG5nYXkgYsOieSBnaeG7nS4iKQogICAgd3JpdGUoIiIpCgogICAgcm93c19vdXQg
>> "%B64_FILE%" echo PSBbXQogICAgc2VlbiA9IHNldCgpCiAgICBzdGFydCA9IHRpbWUudGltZSgpCiAgICBsYXN0X3By
>> "%B64_FILE%" echo aW50ID0gc3RhcnQKCiAgICB3aGlsZSB0aW1lLnRpbWUoKSAtIHN0YXJ0IDwgZHVyYXRpb246CiAg
>> "%B64_FILE%" echo ICAgICAgdHJ5OgogICAgICAgICAgICByb3dzID0gY2FwdHVyZV9hY3RpdmVfcmVxdWVzdHMoY3Vy
>> "%B64_FILE%" echo KQogICAgICAgICAgICBmb3IgciBpbiByb3dzOgogICAgICAgICAgICAgICAgc3FsX3RleHQgPSBu
>> "%B64_FILE%" echo b3JtX3NxbChyLnNxbF90ZXh0KQogICAgICAgICAgICAgICAgc3RtdCA9IG5vcm1fc3FsKHIuc3Rh
>> "%B64_FILE%" echo dGVtZW50X3RleHQpCiAgICAgICAgICAgICAgICBwcm9ncmFtID0gbm9ybV9zcWwoci5wcm9ncmFt
>> "%B64_FILE%" echo X25hbWUpCiAgICAgICAgICAgICAgICBpZiBub3Qgc2hvdWxkX2tlZXAoc3FsX3RleHQsIHN0bXQs
>> "%B64_FILE%" echo IHByb2dyYW0pOgogICAgICAgICAgICAgICAgICAgIGNvbnRpbnVlCgogICAgICAgICAgICAgICAg
>> "%B64_FILE%" echo a2V5ID0gKHIuc2Vzc2lvbl9pZCwgc3FsX3RleHRbOjEwMDBdLCBzdG10WzoxMDAwXSkKICAgICAg
>> "%B64_FILE%" echo ICAgICAgICAgIGlmIGtleSBpbiBzZWVuOgogICAgICAgICAgICAgICAgICAgIGNvbnRpbnVlCiAg
>> "%B64_FILE%" echo ICAgICAgICAgICAgICBzZWVuLmFkZChrZXkpCgogICAgICAgICAgICAgICAgaXRlbSA9IHsKICAg
>> "%B64_FILE%" echo ICAgICAgICAgICAgICAgICAiY2FwdHVyZWRfYXQiOiBzdHIoci5jYXB0dXJlZF9hdCksCiAgICAg
>> "%B64_FILE%" echo ICAgICAgICAgICAgICAgInNlc3Npb25faWQiOiByLnNlc3Npb25faWQsCiAgICAgICAgICAgICAg
>> "%B64_FILE%" echo ICAgICAgImhvc3RfbmFtZSI6IG5vcm1fc3FsKHIuaG9zdF9uYW1lKSwKICAgICAgICAgICAgICAg
>> "%B64_FILE%" echo ICAgICAicHJvZ3JhbV9uYW1lIjogcHJvZ3JhbSwKICAgICAgICAgICAgICAgICAgICAibG9naW5f
>> "%B64_FILE%" echo bmFtZSI6IG5vcm1fc3FsKHIubG9naW5fbmFtZSksCiAgICAgICAgICAgICAgICAgICAgImRiX25h
>> "%B64_FILE%" echo bWUiOiBub3JtX3NxbChyLmRiX25hbWUpLAogICAgICAgICAgICAgICAgICAgICJzdGF0dXMiOiBu
>> "%B64_FILE%" echo b3JtX3NxbChyLnN0YXR1cyksCiAgICAgICAgICAgICAgICAgICAgImNvbW1hbmQiOiBub3JtX3Nx
>> "%B64_FILE%" echo bChyLmNvbW1hbmQpLAogICAgICAgICAgICAgICAgICAgICJjcHVfdGltZSI6IHIuY3B1X3RpbWUs
>> "%B64_FILE%" echo CiAgICAgICAgICAgICAgICAgICAgImVsYXBzZWRfbXMiOiByLnRvdGFsX2VsYXBzZWRfdGltZSwK
>> "%B64_FILE%" echo ICAgICAgICAgICAgICAgICAgICAic3RhdGVtZW50X3RleHQiOiBzdG10LAogICAgICAgICAgICAg
>> "%B64_FILE%" echo ICAgICAgICJzcWxfdGV4dCI6IHNxbF90ZXh0LAogICAgICAgICAgICAgICAgICAgICJzb3VyY2Ui
>> "%B64_FILE%" echo OiAiYWN0aXZlX3JlcXVlc3QiLAogICAgICAgICAgICAgICAgfQogICAgICAgICAgICAgICAgcm93
>> "%B64_FILE%" echo c19vdXQuYXBwZW5kKGl0ZW0pCiAgICAgICAgICAgICAgICB3cml0ZShmIltDQVBUVVJFRF0gc2Vz
>> "%B64_FILE%" echo c2lvbj17ci5zZXNzaW9uX2lkfSBkYj17aXRlbVsnZGJfbmFtZSddfSBwcm9ncmFtPXtwcm9ncmFt
>> "%B64_FILE%" echo fSBjbWQ9e2l0ZW1bJ2NvbW1hbmQnXX0iKQogICAgICAgICAgICAgICAgd3JpdGUoIiAgU1RNVDog
>> "%B64_FILE%" echo IiArIGNvbXBhY3Qoc3RtdCBvciBzcWxfdGV4dCwgODAwKSkKICAgICAgICBleGNlcHQgRXhjZXB0
>> "%B64_FILE%" echo aW9uIGFzIGV4YzoKICAgICAgICAgICAgd3JpdGUoIltXQVJOXSBM4buXaSBraGkgxJHhu41jIGFj
>> "%B64_FILE%" echo dGl2ZSByZXF1ZXN0czogIiArIHN0cihleGMpKQoKICAgICAgICBub3cgPSB0aW1lLnRpbWUoKQog
>> "%B64_FILE%" echo ICAgICAgIGlmIG5vdyAtIGxhc3RfcHJpbnQgPj0gNToKICAgICAgICAgICAgbGVmdCA9IGludChk
>> "%B64_FILE%" echo dXJhdGlvbiAtIChub3cgLSBzdGFydCkpCiAgICAgICAgICAgIHdyaXRlKGYiLi4uIMSRYW5nIGLh
>> "%B64_FILE%" echo uq90IFNRTCwgY8OybiB7bGVmdH0gZ2nDonksIMSRw6MgYuG6r3Qge2xlbihyb3dzX291dCl9IGPD
>> "%B64_FILE%" echo onUgbGnDqm4gcXVhbiIpCiAgICAgICAgICAgIGxhc3RfcHJpbnQgPSBub3cKCiAgICAgICAgdGlt
>> "%B64_FILE%" echo ZS5zbGVlcChpbnRlcnZhbCkKCiAgICB3cml0ZSgiIikKICAgIHdyaXRlKCLEkGFuZyDEkeG7jWMg
>> "%B64_FILE%" echo dGjDqm0gY2FjaGUgY8OidSBTUUwgY2jhuqF5IGfhuqduIMSRw6J5Li4uIikKICAgIHRyeToKICAg
>> "%B64_FILE%" echo ICAgICBjYWNoZWQgPSBjYXB0dXJlX3JlY2VudF9jYWNoZWQoY3VyKQogICAgICAgIGZvciByIGlu
>> "%B64_FILE%" echo IGNhY2hlZDoKICAgICAgICAgICAgc3FsX3RleHQgPSBub3JtX3NxbChyLnNxbF90ZXh0KQogICAg
>> "%B64_FILE%" echo ICAgICAgICBpZiBub3Qgc2hvdWxkX2tlZXAoc3FsX3RleHQsICIiLCAiIik6CiAgICAgICAgICAg
>> "%B64_FILE%" echo ICAgICBjb250aW51ZQogICAgICAgICAgICBrZXkgPSAoImNhY2hlIiwgc3FsX3RleHRbOjE1MDBd
>> "%B64_FILE%" echo KQogICAgICAgICAgICBpZiBrZXkgaW4gc2VlbjoKICAgICAgICAgICAgICAgIGNvbnRpbnVlCiAg
>> "%B64_FILE%" echo ICAgICAgICAgIHNlZW4uYWRkKGtleSkKICAgICAgICAgICAgaXRlbSA9IHsKICAgICAgICAgICAg
>> "%B64_FILE%" echo ICAgICJjYXB0dXJlZF9hdCI6IHN0cihyLmNhcHR1cmVkX2F0KSwKICAgICAgICAgICAgICAgICJz
>> "%B64_FILE%" echo ZXNzaW9uX2lkIjogIiIsCiAgICAgICAgICAgICAgICAiaG9zdF9uYW1lIjogIiIsCiAgICAgICAg
>> "%B64_FILE%" echo ICAgICAgICAicHJvZ3JhbV9uYW1lIjogIiIsCiAgICAgICAgICAgICAgICAibG9naW5fbmFtZSI6
>> "%B64_FILE%" echo ICIiLAogICAgICAgICAgICAgICAgImRiX25hbWUiOiBub3JtX3NxbChyLmRiX25hbWUpLAogICAg
>> "%B64_FILE%" echo ICAgICAgICAgICAgInN0YXR1cyI6ICIiLAogICAgICAgICAgICAgICAgImNvbW1hbmQiOiAiIiwK
>> "%B64_FILE%" echo ICAgICAgICAgICAgICAgICJjcHVfdGltZSI6ICIiLAogICAgICAgICAgICAgICAgImVsYXBzZWRf
>> "%B64_FILE%" echo bXMiOiByLnRvdGFsX2VsYXBzZWRfdGltZSwKICAgICAgICAgICAgICAgICJzdGF0ZW1lbnRfdGV4
>> "%B64_FILE%" echo dCI6ICIiLAogICAgICAgICAgICAgICAgInNxbF90ZXh0Ijogc3FsX3RleHQsCiAgICAgICAgICAg
>> "%B64_FILE%" echo ICAgICAic291cmNlIjogInF1ZXJ5X3N0YXRzX2NhY2hlIiwKICAgICAgICAgICAgICAgICJsYXN0
>> "%B64_FILE%" echo X2V4ZWN1dGlvbl90aW1lIjogc3RyKHIubGFzdF9leGVjdXRpb25fdGltZSksCiAgICAgICAgICAg
>> "%B64_FILE%" echo ICAgICAiZXhlY3V0aW9uX2NvdW50Ijogci5leGVjdXRpb25fY291bnQsCiAgICAgICAgICAgIH0K
>> "%B64_FILE%" echo ICAgICAgICAgICAgcm93c19vdXQuYXBwZW5kKGl0ZW0pCiAgICBleGNlcHQgRXhjZXB0aW9uIGFz
>> "%B64_FILE%" echo IGV4YzoKICAgICAgICB3cml0ZSgiW1dBUk5dIEtow7RuZyDEkeG7jWMgxJHGsOG7o2MgcXVlcnlf
>> "%B64_FILE%" echo c3RhdHMgY2FjaGU6ICIgKyBzdHIoZXhjKSkKCiAgICBjb25uLmNsb3NlKCkKCiAgICAjIEdoaSBD
>> "%B64_FILE%" echo U1YKICAgIGZpZWxkbmFtZXMgPSBbCiAgICAgICAgInNvdXJjZSIsICJjYXB0dXJlZF9hdCIsICJs
>> "%B64_FILE%" echo YXN0X2V4ZWN1dGlvbl90aW1lIiwgImV4ZWN1dGlvbl9jb3VudCIsCiAgICAgICAgInNlc3Npb25f
>> "%B64_FILE%" echo aWQiLCAiaG9zdF9uYW1lIiwgInByb2dyYW1fbmFtZSIsICJsb2dpbl9uYW1lIiwgImRiX25hbWUi
>> "%B64_FILE%" echo LAogICAgICAgICJzdGF0dXMiLCAiY29tbWFuZCIsICJjcHVfdGltZSIsICJlbGFwc2VkX21zIiwg
>> "%B64_FILE%" echo InN0YXRlbWVudF90ZXh0IiwgInNxbF90ZXh0IgogICAgXQogICAgd2l0aCBPVVRfQ1NWLm9wZW4o
>> "%B64_FILE%" echo InciLCBuZXdsaW5lPSIiLCBlbmNvZGluZz0idXRmLTgtc2lnIikgYXMgZjoKICAgICAgICB3ID0g
>> "%B64_FILE%" echo Y3N2LkRpY3RXcml0ZXIoZiwgZmllbGRuYW1lcz1maWVsZG5hbWVzKQogICAgICAgIHcud3JpdGVo
>> "%B64_FILE%" echo ZWFkZXIoKQogICAgICAgIGZvciByb3cgaW4gcm93c19vdXQ6CiAgICAgICAgICAgIHcud3JpdGVy
>> "%B64_FILE%" echo b3coe2s6IHJvdy5nZXQoaywgIiIpIGZvciBrIGluIGZpZWxkbmFtZXN9KQoKICAgICMgR2hpIHVu
>> "%B64_FILE%" echo aXF1ZSBTUUwgdGV4dAogICAgd3JpdGVfdW5pcXVlKCJUVENPIC0gVU5JUVVFIFNRTCBURVhUIENB
>> "%B64_FILE%" echo UFRVUkVEIikKICAgIHdyaXRlX3VuaXF1ZSgiPSIgKiAxMjApCiAgICB1bmlxdWVfc3FsID0gW10K
>> "%B64_FILE%" echo ICAgIGZvciByb3cgaW4gcm93c19vdXQ6CiAgICAgICAgc3FsX3RleHQgPSByb3cuZ2V0KCJzdGF0
>> "%B64_FILE%" echo ZW1lbnRfdGV4dCIpIG9yIHJvdy5nZXQoInNxbF90ZXh0Iikgb3IgIiIKICAgICAgICBpZiBub3Qg
>> "%B64_FILE%" echo c3FsX3RleHQ6CiAgICAgICAgICAgIGNvbnRpbnVlCiAgICAgICAgaWYgc3FsX3RleHQgbm90IGlu
>> "%B64_FILE%" echo IHVuaXF1ZV9zcWw6CiAgICAgICAgICAgIHVuaXF1ZV9zcWwuYXBwZW5kKHNxbF90ZXh0KQoKICAg
>> "%B64_FILE%" echo IGZvciBpLCBzcWxfdGV4dCBpbiBlbnVtZXJhdGUodW5pcXVlX3NxbCwgc3RhcnQ9MSk6CiAgICAg
>> "%B64_FILE%" echo ICAgd3JpdGVfdW5pcXVlKCIiKQogICAgICAgIHdyaXRlX3VuaXF1ZSgiPSIgKiAxMjApCiAgICAg
>> "%B64_FILE%" echo ICAgd3JpdGVfdW5pcXVlKGYie2k6MDNkfS4gU1FMIikKICAgICAgICB3cml0ZV91bmlxdWUoIi0i
>> "%B64_FILE%" echo ICogMTIwKQogICAgICAgIHdyaXRlX3VuaXF1ZShzcWxfdGV4dCkKCiAgICB3cml0ZSgiIikKICAg
>> "%B64_FILE%" echo IHdyaXRlKCI9PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
>> "%B64_FILE%" echo PT09PT09PT09PT0iKQogICAgd3JpdGUoIkhPw4BOIFRIw4BOSCBC4bquVCBTUUwgTElWRSIpCiAg
>> "%B64_FILE%" echo ICB3cml0ZSgiPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
>> "%B64_FILE%" echo PT09PT09PT09PT09IikKICAgIHdyaXRlKGYiU+G7kSBjw6J1IGxpw6puIHF1YW4gYuG6r3QgxJHG
>> "%B64_FILE%" echo sOG7o2M6IHtsZW4ocm93c19vdXQpfSIpCiAgICB3cml0ZShmIlRYVCBjaMOtbmggOiB7T1VUX1RY
>> "%B64_FILE%" echo VH0iKQogICAgd3JpdGUoZiJDU1YgICAgICAgOiB7T1VUX0NTVn0iKQogICAgd3JpdGUoZiJTUUwg
>> "%B64_FILE%" echo dW5pcXVlOiB7T1VUX1VOSVFVRX0iKQogICAgd3JpdGUoIiIpCiAgICB3cml0ZSgiQW5oIGfhu61p
>> "%B64_FILE%" echo IGzhuqFpIGZpbGUgU1FMIHVuaXF1ZSBob+G6t2MgVFhUIGNow61uaC4iKQogICAgd3JpdGUoIk7h
>> "%B64_FILE%" echo ur91IHPhu5EgY8OidSBi4bqvdCDEkcaw4bujYyA9IDAsIGPhuqduIGNo4bqheSBs4bqhaSB2w6Ag
>> "%B64_FILE%" echo YuG6pW0gWGVtIGtxIG5nYXkgc2F1IGtoaSBi4bqlbSBFbnRlciwiKQogICAgd3JpdGUoImhv4bq3
>> "%B64_FILE%" echo YyB0w6BpIGtob+G6o24gU1FMIGtow7RuZyBuaMOsbiB0aOG6pXkgc2Vzc2lvbiBj4bunYSBUVENP
>> "%B64_FILE%" echo X0FQUC4iKQoKICAgIHRyeToKICAgICAgICBzdWJwcm9jZXNzLlBvcGVuKFsiZXhwbG9yZXIuZXhl
>> "%B64_FILE%" echo Iiwgc3RyKE9VVF9ESVIpXSkKICAgIGV4Y2VwdCBFeGNlcHRpb246CiAgICAgICAgcGFzcwoKICAg
>> "%B64_FILE%" echo IHJldHVybiAwCgoKaWYgX19uYW1lX18gPT0gIl9fbWFpbl9fIjoKICAgIHN5cy5leGl0KG1haW4o
>> "%B64_FILE%" echo KSkK
python -c "import base64, pathlib, os; b=pathlib.Path(os.environ['B64_FILE']).read_text().replace('\n','').replace('\r','').strip(); pathlib.Path(os.environ['PY_MAIN']).write_bytes(base64.b64decode(b))"
exit /b %errorlevel%
