@echo off
setlocal EnableExtensions EnableDelayedExpansion
chcp 65001 >nul
title TTCO - Tim nguon ton kho Kho 1 = 1052.65

set "WORK_DIR=%~dp0"
set "PY_FILE=%WORK_DIR%ttco_find_kho1_1052_65.py"
set "B64_FILE=%WORK_DIR%ttco_find_kho1_1052_65.b64"

echo ============================================================
echo   TTCO - TIM NGUON TON KHO KHO 1 = 1.052,65 TRONG SQL DB
echo ============================================================
echo.
echo File nay se quet DB TTCO_THONGKE de tim bang/cot nao
echo dang co so lieu gan bang 1.052,65 cho Kho 1.
echo.
echo Ket qua xuat vao thu muc: ttco_check_output
echo.
pause

:WRITE_PY
> "%B64_FILE%" echo CiMgLSotIGNvZGluZzogdXRmLTggLSotCmltcG9ydCBjc3YKaW1wb3J0IG9zCmltcG9ydCByZQpp
>> "%B64_FILE%" echo bXBvcnQgc3VicHJvY2VzcwppbXBvcnQgc3lzCmZyb20gZGF0ZXRpbWUgaW1wb3J0IGRhdGV0aW1l
>> "%B64_FILE%" echo CmZyb20gcGF0aGxpYiBpbXBvcnQgUGF0aAoKU0VSVkVSID0gciJ0dXllbnRoYW5jdWFvbmcuY29t
>> "%B64_FILE%" echo LnZuLDUyMzc2IgpEQVRBQkFTRSA9ICJUVENPX1RIT05HS0UiClRBUkdFVF9LSE9fVEVYVCA9ICIx
>> "%B64_FILE%" echo IgpUQVJHRVRfVkFMVUUgPSAxMDUyLjY1ClRPTEVSQU5DRSA9IDAuMDUKCkJBU0VfRElSID0gUGF0
>> "%B64_FILE%" echo aC5jd2QoKQpPVVRfRElSID0gQkFTRV9ESVIgLyAidHRjb19jaGVja19vdXRwdXQiCk9VVF9ESVIu
>> "%B64_FILE%" echo bWtkaXIocGFyZW50cz1UcnVlLCBleGlzdF9vaz1UcnVlKQpPVVRfVFhUID0gT1VUX0RJUiAvIGYi
>> "%B64_FILE%" echo Y2hlY2tfa2hvMV8xMDUyXzY1X3tkYXRldGltZS5ub3coKTolWSVtJWRfJUglTSVTfS50eHQiCk9V
>> "%B64_FILE%" echo VF9DU1YgPSBPVVRfRElSIC8gZiJjaGVja19raG8xXzEwNTJfNjVfe2RhdGV0aW1lLm5vdygpOiVZ
>> "%B64_FILE%" echo JW0lZF8lSCVNJVN9LmNzdiIKCgpkZWYgd3JpdGUobGluZT0iIik6CiAgICBwcmludChsaW5lKQog
>> "%B64_FILE%" echo ICAgd2l0aCBPVVRfVFhULm9wZW4oImEiLCBlbmNvZGluZz0idXRmLTgiKSBhcyBmOgogICAgICAg
>> "%B64_FILE%" echo IGYud3JpdGUoc3RyKGxpbmUpICsgIlxuIikKCgpkZWYgZW5zdXJlX3B5b2RiYygpOgogICAgdHJ5
>> "%B64_FILE%" echo OgogICAgICAgIGltcG9ydCBweW9kYmMgICMgbm9xYQogICAgICAgIHJldHVybgogICAgZXhjZXB0
>> "%B64_FILE%" echo IEV4Y2VwdGlvbjoKICAgICAgICB3cml0ZSgiQ2jGsGEgY8OzIHB5b2RiYy4gxJBhbmcgdGjhu60g
>> "%B64_FILE%" echo Y8OgaSBweW9kYmMuLi4iKQogICAgICAgIHN1YnByb2Nlc3MuY2hlY2tfY2FsbChbc3lzLmV4ZWN1
>> "%B64_FILE%" echo dGFibGUsICItbSIsICJwaXAiLCAiaW5zdGFsbCIsICJweW9kYmMiXSkKCgpkZWYgY29ubmVjdCgp
>> "%B64_FILE%" echo OgogICAgaW1wb3J0IHB5b2RiYwogICAgY29ubl9zdHIgPSAoCiAgICAgICAgIkRSSVZFUj17T0RC
>> "%B64_FILE%" echo QyBEcml2ZXIgMTggZm9yIFNRTCBTZXJ2ZXJ9OyIKICAgICAgICBmIlNFUlZFUj17U0VSVkVSfTsi
>> "%B64_FILE%" echo CiAgICAgICAgZiJEQVRBQkFTRT17REFUQUJBU0V9OyIKICAgICAgICAiVHJ1c3RlZF9Db25uZWN0
>> "%B64_FILE%" echo aW9uPXllczsiCiAgICAgICAgIlRydXN0U2VydmVyQ2VydGlmaWNhdGU9eWVzOyIKICAgICkKICAg
>> "%B64_FILE%" echo IHJldHVybiBweW9kYmMuY29ubmVjdChjb25uX3N0ciwgdGltZW91dD0xNSkKCgpkZWYgcWlkZW50
>> "%B64_FILE%" echo KG5hbWU6IHN0cikgLT4gc3RyOgogICAgcmV0dXJuICJbIiArIHN0cihuYW1lKS5yZXBsYWNlKCJd
>> "%B64_FILE%" echo IiwgIl1dIikgKyAiXSIKCgpkZWYgaXNfbnVtZXJpY190eXBlKHQ6IHN0cikgLT4gYm9vbDoKICAg
>> "%B64_FILE%" echo IHJldHVybiB0Lmxvd2VyKCkgaW4gewogICAgICAgICJpbnQiLCAiYmlnaW50IiwgInNtYWxsaW50
>> "%B64_FILE%" echo IiwgInRpbnlpbnQiLCAiZGVjaW1hbCIsICJudW1lcmljIiwKICAgICAgICAiZmxvYXQiLCAicmVh
>> "%B64_FILE%" echo bCIsICJtb25leSIsICJzbWFsbG1vbmV5IgogICAgfQoKCmRlZiBzYWZlX2Zsb2F0KHYpOgogICAg
>> "%B64_FILE%" echo dHJ5OgogICAgICAgIGlmIHYgaXMgTm9uZToKICAgICAgICAgICAgcmV0dXJuIE5vbmUKICAgICAg
>> "%B64_FILE%" echo ICByZXR1cm4gZmxvYXQodikKICAgIGV4Y2VwdCBFeGNlcHRpb246CiAgICAgICAgcmV0dXJuIE5v
>> "%B64_FILE%" echo bmUKCgpkZWYgbWFpbigpOgogICAgZW5zdXJlX3B5b2RiYygpCiAgICBpbXBvcnQgcHlvZGJjCgog
>> "%B64_FILE%" echo ICAgd3JpdGUoIj09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
>> "%B64_FILE%" echo PT09PT09PT09PT09PSIpCiAgICB3cml0ZSgiVFRDTyAtIEtJ4buCTSBUUkEgTkdV4buSTiBU4buS
>> "%B64_FILE%" echo TiBLSE8gS0hPIDEgPSAxLjA1Miw2NSIpCiAgICB3cml0ZSgiPT09PT09PT09PT09PT09PT09PT09
>> "%B64_FILE%" echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09IikKICAgIHdyaXRlKGYiU2Vy
>> "%B64_FILE%" echo dmVyICAgOiB7U0VSVkVSfSIpCiAgICB3cml0ZShmIkRhdGFiYXNlIDoge0RBVEFCQVNFfSIpCiAg
>> "%B64_FILE%" echo ICB3cml0ZShmIktobyBj4bqnbiBraeG7g20gdHJhOiB7VEFSR0VUX0tIT19URVhUfSIpCiAgICB3
>> "%B64_FILE%" echo cml0ZShmIkdpw6EgdHLhu4sgVFRDT19BUFAgYsOhbzoge1RBUkdFVF9WQUxVRX0iKQogICAgd3Jp
>> "%B64_FILE%" echo dGUoZiJPdXRwdXQgVFhUOiB7T1VUX1RYVH0iKQogICAgd3JpdGUoZiJPdXRwdXQgQ1NWOiB7T1VU
>> "%B64_FILE%" echo X0NTVn0iKQogICAgd3JpdGUoIiIpCgogICAgY29ubiA9IGNvbm5lY3QoKQogICAgY3VyID0gY29u
>> "%B64_FILE%" echo bi5jdXJzb3IoKQoKICAgIHJlc3VsdHMgPSBbXQoKICAgICMgMSkgS2nhu4NtIHRyYSB0cuG7sWMg
>> "%B64_FILE%" echo dGnhur9wIENET1RIQU4gdGhlbyB04bqldCBj4bqjIGvhu7MuCiAgICB3cml0ZSgiMSkgS0nhu4JN
>> "%B64_FILE%" echo IFRSQSBDRE9USEFOIFRIRU8gVOG6pFQgQ+G6oiBL4buyIikKICAgIHdyaXRlKCItLS0tLS0tLS0t
>> "%B64_FILE%" echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0iKQogICAg
>> "%B64_FILE%" echo dHJ5OgogICAgICAgIHNxbCA9ICIiIgogICAgICAgIFNFTEVDVCBOYW1IVCwgVGhhbmdIVCwgTWFL
>> "%B64_FILE%" echo aG8sIE1hVGhhbiwgU1VNKENBU1QoVG9uQ0sgQVMgZmxvYXQpKSBBUyBUb25DSwogICAgICAgIEZS
>> "%B64_FILE%" echo T00gZGJvLkNET1RIQU4KICAgICAgICBXSEVSRSBUUllfQ09OVkVSVChudmFyY2hhcig1MCksIE1h
>> "%B64_FILE%" echo S2hvKSBJTiAoTicxJywgTicwMScpCiAgICAgICAgR1JPVVAgQlkgTmFtSFQsIFRoYW5nSFQsIE1h
>> "%B64_FILE%" echo S2hvLCBNYVRoYW4KICAgICAgICBPUkRFUiBCWSBOYW1IVCBERVNDLCBUaGFuZ0hUIERFU0MsIE1h
>> "%B64_FILE%" echo VGhhbjsKICAgICAgICAiIiIKICAgICAgICByb3dzID0gY3VyLmV4ZWN1dGUoc3FsKS5mZXRjaGFs
>> "%B64_FILE%" echo bCgpCiAgICAgICAgd3JpdGUoZiJT4buRIGTDsm5nIENET1RIQU4gS2hvIDE6IHtsZW4ocm93cyl9
>> "%B64_FILE%" echo IikKICAgICAgICBmb3IgciBpbiByb3dzWzo1MF06CiAgICAgICAgICAgIGxpbmUgPSBmIkNET1RI
>> "%B64_FILE%" echo QU4gfCBOYW09e3IuTmFtSFR9IHwgVGhhbmc9e3IuVGhhbmdIVH0gfCBNYUtobz17ci5NYUtob30g
>> "%B64_FILE%" echo fCBNYVRoYW49e3IuTWFUaGFufSB8IFRvbkNLPXtmbG9hdChyLlRvbkNLKTosLjJmfSIKICAgICAg
>> "%B64_FILE%" echo ICAgICAgd3JpdGUobGluZSkKICAgICAgICAgICAgZGlmZiA9IGFicyhmbG9hdChyLlRvbkNLKSAt
>> "%B64_FILE%" echo IFRBUkdFVF9WQUxVRSkKICAgICAgICAgICAgcmVzdWx0cy5hcHBlbmQoewogICAgICAgICAgICAg
>> "%B64_FILE%" echo ICAgInNvdXJjZSI6ICJDRE9USEFOIiwKICAgICAgICAgICAgICAgICJzY2hlbWEiOiAiZGJvIiwK
>> "%B64_FILE%" echo ICAgICAgICAgICAgICAgICJ0YWJsZSI6ICJDRE9USEFOIiwKICAgICAgICAgICAgICAgICJwZXJp
>> "%B64_FILE%" echo b2QiOiBmIntyLk5hbUhUfS17ci5UaGFuZ0hUfSIsCiAgICAgICAgICAgICAgICAia2hvX2NvbCI6
>> "%B64_FILE%" echo ICJNYUtobyIsCiAgICAgICAgICAgICAgICAia2hvX3ZhbHVlIjogc3RyKHIuTWFLaG8pLAogICAg
>> "%B64_FILE%" echo ICAgICAgICAgICAgInRoYW5fY29sIjogIk1hVGhhbiIsCiAgICAgICAgICAgICAgICAidGhhbl92
>> "%B64_FILE%" echo YWx1ZSI6IHN0cihyLk1hVGhhbiksCiAgICAgICAgICAgICAgICAidmFsdWVfY29sIjogIlRvbkNL
>> "%B64_FILE%" echo IiwKICAgICAgICAgICAgICAgICJ2YWx1ZSI6IGZsb2F0KHIuVG9uQ0spLAogICAgICAgICAgICAg
>> "%B64_FILE%" echo ICAgImRpZmZfdG9fMTA1Ml82NSI6IGRpZmYsCiAgICAgICAgICAgICAgICAibm90ZSI6ICJDRE9U
>> "%B64_FILE%" echo SEFOIGdyb3VwZWQgYnkgTmFtSFQsVGhhbmdIVCxNYUtobyxNYVRoYW4iLAogICAgICAgICAgICB9
>> "%B64_FILE%" echo KQogICAgICAgIHdyaXRlKCIiKQogICAgZXhjZXB0IEV4Y2VwdGlvbiBhcyBleGM6CiAgICAgICAg
>> "%B64_FILE%" echo d3JpdGUoZiJM4buXaSBraeG7g20gdHJhIENET1RIQU46IHtleGN9IikKICAgICAgICB3cml0ZSgi
>> "%B64_FILE%" echo IikKCiAgICAjIDIpIFTDrG0gY8OhYyBi4bqjbmcgY8OzIGPhu5l0IGtobyB2w6AgY+G7mXQgc+G7
>> "%B64_FILE%" echo kSBsaeG7h3UsIHTDrW5oIFNVTSB0aGVvIEtobyAxLgogICAgd3JpdGUoIjIpIFFVw4lUIEPDgUMg
>> "%B64_FILE%" echo QuG6ok5HIEPDkyBD4buYVCBLSE8gVsOAIEPhu5hUIFPhu5AgTEnhu4ZVIikKICAgIHdyaXRlKCIt
>> "%B64_FILE%" echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
>> "%B64_FILE%" echo LS0iKQoKICAgIGNvbF9zcWwgPSAiIiIKICAgIFNFTEVDVAogICAgICAgIFRBQkxFX1NDSEVNQSwK
>> "%B64_FILE%" echo ICAgICAgICBUQUJMRV9OQU1FLAogICAgICAgIENPTFVNTl9OQU1FLAogICAgICAgIERBVEFfVFlQ
>> "%B64_FILE%" echo RQogICAgRlJPTSBJTkZPUk1BVElPTl9TQ0hFTUEuQ09MVU1OUwogICAgV0hFUkUgVEFCTEVfVFlQ
>> "%B64_FILE%" echo RSBJUyBOVUxMIE9SIDE9MQogICAgT1JERVIgQlkgVEFCTEVfU0NIRU1BLCBUQUJMRV9OQU1FLCBP
>> "%B64_FILE%" echo UkRJTkFMX1BPU0lUSU9OOwogICAgIiIiCiAgICBjb2xzID0gY3VyLmV4ZWN1dGUoY29sX3NxbCku
>> "%B64_FILE%" echo ZmV0Y2hhbGwoKQoKICAgIHRhYmxlcyA9IHt9CiAgICBmb3Igc2NoZW1hLCB0YWJsZSwgY29sLCBk
>> "%B64_FILE%" echo dHlwZSBpbiBjb2xzOgogICAgICAgIHRhYmxlcy5zZXRkZWZhdWx0KChzY2hlbWEsIHRhYmxlKSwg
>> "%B64_FILE%" echo W10pLmFwcGVuZCgoY29sLCBkdHlwZSkpCgogICAga2hvX3BhdHRlcm5zID0gcmUuY29tcGlsZShy
>> "%B64_FILE%" echo Il4oTWFLaG98S2hvfE1ha3xNYV9LaG98SURLaG98S2hvSUQpJCIsIHJlLkkpCiAgICB0aGFuX3Bh
>> "%B64_FILE%" echo dHRlcm5zID0gcmUuY29tcGlsZShyIihNYVRoYW58VGVuVGhhbnxMb2FpVGhhbnxUaGFuKSIsIHJl
>> "%B64_FILE%" echo LkkpCiAgICB2YWx1ZV9wYXR0ZXJucyA9IHJlLmNvbXBpbGUociIoVG9ufFThu5NufEtsZ3xLTHxL
>> "%B64_FILE%" echo aG9pTHVvbmd8THVvbmd8VGFufFNMfFNvTHVvbmd8Q3VvaXxDSykiLCByZS5JKQoKICAgIHNjYW5u
>> "%B64_FILE%" echo ZWQgPSAwCiAgICBtYXRjaGVkID0gMAoKICAgIGZvciAoc2NoZW1hLCB0YWJsZSksIHRhYmxlX2Nv
>> "%B64_FILE%" echo bHMgaW4gdGFibGVzLml0ZW1zKCk6CiAgICAgICAgY29sX25hbWVzID0gW2MgZm9yIGMsIF8gaW4g
>> "%B64_FILE%" echo dGFibGVfY29sc10KICAgICAgICBraG9fY29scyA9IFtjIGZvciBjIGluIGNvbF9uYW1lcyBpZiBr
>> "%B64_FILE%" echo aG9fcGF0dGVybnMuc2VhcmNoKGMpXQogICAgICAgIGlmIG5vdCBraG9fY29sczoKICAgICAgICAg
>> "%B64_FILE%" echo ICAgY29udGludWUKCiAgICAgICAgbnVtX2NvbHMgPSBbYyBmb3IgYywgdCBpbiB0YWJsZV9jb2xz
>> "%B64_FILE%" echo IGlmIGlzX251bWVyaWNfdHlwZSh0KSBhbmQgdmFsdWVfcGF0dGVybnMuc2VhcmNoKGMpXQogICAg
>> "%B64_FILE%" echo ICAgIGlmIG5vdCBudW1fY29sczoKICAgICAgICAgICAgY29udGludWUKCiAgICAgICAgdGhhbl9j
>> "%B64_FILE%" echo b2xzID0gW2MgZm9yIGMgaW4gY29sX25hbWVzIGlmIHRoYW5fcGF0dGVybnMuc2VhcmNoKGMpXQog
>> "%B64_FILE%" echo ICAgICAgIHBlcmlvZF9jb2xzID0gW2MgZm9yIGMgaW4gY29sX25hbWVzIGlmIGMgaW4gKCJOYW1I
>> "%B64_FILE%" echo VCIsICJUaGFuZ0hUIiwgIk5nYXlIVCIsICJOZ2F5IiwgIk5nYXlDVCIsICJUaGFuZyIsICJOYW0i
>> "%B64_FILE%" echo KV0KCiAgICAgICAgZm9yIGtob19jb2wgaW4ga2hvX2NvbHNbOjJdOgogICAgICAgICAgICBmb3Ig
>> "%B64_FILE%" echo dmFsX2NvbCBpbiBudW1fY29sc1s6MTJdOgogICAgICAgICAgICAgICAgc2Nhbm5lZCArPSAxCiAg
>> "%B64_FILE%" echo ICAgICAgICAgICAgICB0cnk6CiAgICAgICAgICAgICAgICAgICAgc2VsZWN0X2V4dHJhID0gW10K
>> "%B64_FILE%" echo ICAgICAgICAgICAgICAgICAgICBncm91cF9leHRyYSA9IFtdCiAgICAgICAgICAgICAgICAgICAg
>> "%B64_FILE%" echo Zm9yIGMgaW4gcGVyaW9kX2NvbHNbOjRdICsgdGhhbl9jb2xzWzoyXToKICAgICAgICAgICAgICAg
>> "%B64_FILE%" echo ICAgICAgICAgc2VsZWN0X2V4dHJhLmFwcGVuZChxaWRlbnQoYykpCiAgICAgICAgICAgICAgICAg
>> "%B64_FILE%" echo ICAgICAgIGdyb3VwX2V4dHJhLmFwcGVuZChxaWRlbnQoYykpCgogICAgICAgICAgICAgICAgICAg
>> "%B64_FILE%" echo IGV4dHJhX3NxbCA9ICIiCiAgICAgICAgICAgICAgICAgICAgZ3JvdXBfc3FsID0gIiIKICAgICAg
>> "%B64_FILE%" echo ICAgICAgICAgICAgICBpZiBzZWxlY3RfZXh0cmE6CiAgICAgICAgICAgICAgICAgICAgICAgIGV4
>> "%B64_FILE%" echo dHJhX3NxbCA9ICIsICIgKyAiLCAiLmpvaW4oc2VsZWN0X2V4dHJhKQogICAgICAgICAgICAgICAg
>> "%B64_FILE%" echo ICAgICAgICBncm91cF9zcWwgPSAiLCAiICsgIiwgIi5qb2luKGdyb3VwX2V4dHJhKQoKICAgICAg
>> "%B64_FILE%" echo ICAgICAgICAgICAgICBzcWwgPSBmIiIiCiAgICAgICAgICAgICAgICAgICAgU0VMRUNUIFRPUCAy
>> "%B64_FILE%" echo MDAKICAgICAgICAgICAgICAgICAgICAgICAge3FpZGVudChraG9fY29sKX0gQVMgS2hvVmFsdWUK
>> "%B64_FILE%" echo ICAgICAgICAgICAgICAgICAgICAgICAge2V4dHJhX3NxbH0sCiAgICAgICAgICAgICAgICAgICAg
>> "%B64_FILE%" echo ICAgIFNVTShUUllfQ0FTVCh7cWlkZW50KHZhbF9jb2wpfSBBUyBmbG9hdCkpIEFTIENoZWNrVmFs
>> "%B64_FILE%" echo dWUsCiAgICAgICAgICAgICAgICAgICAgICAgIENPVU5UKCopIEFTIFJvd0NvdW50CiAgICAgICAg
>> "%B64_FILE%" echo ICAgICAgICAgICAgRlJPTSB7cWlkZW50KHNjaGVtYSl9LntxaWRlbnQodGFibGUpfQogICAgICAg
>> "%B64_FILE%" echo ICAgICAgICAgICAgIFdIRVJFIFRSWV9DT05WRVJUKG52YXJjaGFyKDUwKSwge3FpZGVudChraG9f
>> "%B64_FILE%" echo Y29sKX0pIElOIChOJzEnLCBOJzAxJywgTidLaG8gMScpCiAgICAgICAgICAgICAgICAgICAgR1JP
>> "%B64_FILE%" echo VVAgQlkge3FpZGVudChraG9fY29sKX17Z3JvdXBfc3FsfQogICAgICAgICAgICAgICAgICAgIEhB
>> "%B64_FILE%" echo VklORyBTVU0oVFJZX0NBU1Qoe3FpZGVudCh2YWxfY29sKX0gQVMgZmxvYXQpKSBJUyBOT1QgTlVM
>> "%B64_FILE%" echo TAogICAgICAgICAgICAgICAgICAgIE9SREVSIEJZIEFCUyhTVU0oVFJZX0NBU1Qoe3FpZGVudCh2
>> "%B64_FILE%" echo YWxfY29sKX0gQVMgZmxvYXQpKSAtID8pIEFTQzsKICAgICAgICAgICAgICAgICAgICAiIiIKICAg
>> "%B64_FILE%" echo ICAgICAgICAgICAgICAgICByb3dzID0gY3VyLmV4ZWN1dGUoc3FsLCBUQVJHRVRfVkFMVUUpLmZl
>> "%B64_FILE%" echo dGNoYWxsKCkKICAgICAgICAgICAgICAgICAgICBpZiBub3Qgcm93czoKICAgICAgICAgICAgICAg
>> "%B64_FILE%" echo ICAgICAgICAgY29udGludWUKCiAgICAgICAgICAgICAgICAgICAgZm9yIHIgaW4gcm93c1s6MTBd
>> "%B64_FILE%" echo OgogICAgICAgICAgICAgICAgICAgICAgICB2YWwgPSBzYWZlX2Zsb2F0KGdldGF0dHIociwgIkNo
>> "%B64_FILE%" echo ZWNrVmFsdWUiLCBOb25lKSkKICAgICAgICAgICAgICAgICAgICAgICAgaWYgdmFsIGlzIE5vbmU6
>> "%B64_FILE%" echo CiAgICAgICAgICAgICAgICAgICAgICAgICAgICBjb250aW51ZQogICAgICAgICAgICAgICAgICAg
>> "%B64_FILE%" echo ICAgICBkaWZmID0gYWJzKHZhbCAtIFRBUkdFVF9WQUxVRSkKICAgICAgICAgICAgICAgICAgICAg
>> "%B64_FILE%" echo ICAgIyBMxrB1IGPDoWMgZ2nDoSB0cuG7iyBn4bqnbiBob+G6t2MgY8OhYyBi4bqjbmcgY8OzIGto
>> "%B64_FILE%" echo 4bqjIG7Eg25nIGNhby4KICAgICAgICAgICAgICAgICAgICAgICAgaWYgZGlmZiA8PSAyMDAgb3Ig
>> "%B64_FILE%" echo dmFsID4gMDoKICAgICAgICAgICAgICAgICAgICAgICAgICAgIG1hdGNoZWQgKz0gMQogICAgICAg
>> "%B64_FILE%" echo ICAgICAgICAgICAgICAgICAgICAgcGVyaW9kID0gW10KICAgICAgICAgICAgICAgICAgICAgICAg
>> "%B64_FILE%" echo ICAgIHRoYW4gPSBbXQogICAgICAgICAgICAgICAgICAgICAgICAgICAgZm9yIGMgaW4gcGVyaW9k
>> "%B64_FILE%" echo X2NvbHNbOjRdOgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIGlmIGhhc2F0dHIociwg
>> "%B64_FILE%" echo Yyk6CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIHBlcmlvZC5hcHBlbmQoZiJ7
>> "%B64_FILE%" echo Y309e2dldGF0dHIociwgYyl9IikKICAgICAgICAgICAgICAgICAgICAgICAgICAgIGZvciBjIGlu
>> "%B64_FILE%" echo IHRoYW5fY29sc1s6Ml06CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgaWYgaGFzYXR0
>> "%B64_FILE%" echo cihyLCBjKToKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgdGhhbi5hcHBlbmQo
>> "%B64_FILE%" echo ZiJ7Y309e2dldGF0dHIociwgYyl9IikKCiAgICAgICAgICAgICAgICAgICAgICAgICAgICByZXN1
>> "%B64_FILE%" echo bHRzLmFwcGVuZCh7CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgInNvdXJjZSI6ICJz
>> "%B64_FILE%" echo Y2FuIiwKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAic2NoZW1hIjogc2NoZW1hLAog
>> "%B64_FILE%" echo ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICJ0YWJsZSI6IHRhYmxlLAogICAgICAgICAg
>> "%B64_FILE%" echo ICAgICAgICAgICAgICAgICAgICAgICJwZXJpb2QiOiAiIHwgIi5qb2luKHBlcmlvZCksCiAgICAg
>> "%B64_FILE%" echo ICAgICAgICAgICAgICAgICAgICAgICAgICAgImtob19jb2wiOiBraG9fY29sLAogICAgICAgICAg
>> "%B64_FILE%" echo ICAgICAgICAgICAgICAgICAgICAgICJraG9fdmFsdWUiOiBzdHIoZ2V0YXR0cihyLCAiS2hvVmFs
>> "%B64_FILE%" echo dWUiLCAiIikpLAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICJ0aGFuX2NvbCI6ICIg
>> "%B64_FILE%" echo fCAiLmpvaW4odGhhbiksCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgInRoYW5fdmFs
>> "%B64_FILE%" echo dWUiOiAiIiwKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAidmFsdWVfY29sIjogdmFs
>> "%B64_FILE%" echo X2NvbCwKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAidmFsdWUiOiB2YWwsCiAgICAg
>> "%B64_FILE%" echo ICAgICAgICAgICAgICAgICAgICAgICAgICAgImRpZmZfdG9fMTA1Ml82NSI6IGRpZmYsCiAgICAg
>> "%B64_FILE%" echo ICAgICAgICAgICAgICAgICAgICAgICAgICAgIm5vdGUiOiBmIlJvd0NvdW50PXtnZXRhdHRyKHIs
>> "%B64_FILE%" echo ICdSb3dDb3VudCcsICcnKX0iLAogICAgICAgICAgICAgICAgICAgICAgICAgICAgfSkKICAgICAg
>> "%B64_FILE%" echo ICAgICAgICAgIGV4Y2VwdCBFeGNlcHRpb246CiAgICAgICAgICAgICAgICAgICAgY29udGludWUK
>> "%B64_FILE%" echo CiAgICByZXN1bHRzX3NvcnRlZCA9IHNvcnRlZChyZXN1bHRzLCBrZXk9bGFtYmRhIHg6IHhbImRp
>> "%B64_FILE%" echo ZmZfdG9fMTA1Ml82NSJdKQoKICAgIHdyaXRlKGYiU+G7kSBwaMOpcCBxdcOpdDoge3NjYW5uZWR9
>> "%B64_FILE%" echo IikKICAgIHdyaXRlKGYiU+G7kSBr4bq/dCBxdeG6oyB0aHUgxJHGsOG7o2M6IHtsZW4ocmVzdWx0
>> "%B64_FILE%" echo c19zb3J0ZWQpfSIpCiAgICB3cml0ZSgiIikKICAgIHdyaXRlKCIzKSBUT1AgMzAgS+G6vlQgUVXh
>> "%B64_FILE%" echo uqIgR+G6pk4gMS4wNTIsNjUgTkjhuqRUIikKICAgIHdyaXRlKCItLS0tLS0tLS0tLS0tLS0tLS0t
>> "%B64_FILE%" echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0iKQoKICAgIGZvciBpLCBy
>> "%B64_FILE%" echo IGluIGVudW1lcmF0ZShyZXN1bHRzX3NvcnRlZFs6MzBdLCBzdGFydD0xKToKICAgICAgICB3cml0
>> "%B64_FILE%" echo ZSgKICAgICAgICAgICAgZiJ7aTowMmR9LiB7clsnc2NoZW1hJ119LntyWyd0YWJsZSddfSB8ICIK
>> "%B64_FILE%" echo ICAgICAgICAgICAgZiJ7clsna2hvX2NvbCddfT17clsna2hvX3ZhbHVlJ119IHwgIgogICAgICAg
>> "%B64_FILE%" echo ICAgICBmIntyWyd2YWx1ZV9jb2wnXX09e3JbJ3ZhbHVlJ106LC4yZn0gfCAiCiAgICAgICAgICAg
>> "%B64_FILE%" echo IGYiTOG7h2NoPXtyWydkaWZmX3RvXzEwNTJfNjUnXTosLjJmfSB8ICIKICAgICAgICAgICAgZiJ7
>> "%B64_FILE%" echo clsncGVyaW9kJ119IHwge3JbJ3RoYW5fY29sJ119IHtyWyd0aGFuX3ZhbHVlJ119IHwge3JbJ25v
>> "%B64_FILE%" echo dGUnXX0iCiAgICAgICAgKQoKICAgICMgQ1NWCiAgICB3aXRoIE9VVF9DU1Yub3BlbigidyIsIG5l
>> "%B64_FILE%" echo d2xpbmU9IiIsIGVuY29kaW5nPSJ1dGYtOC1zaWciKSBhcyBmOgogICAgICAgIGZpZWxkbmFtZXMg
>> "%B64_FILE%" echo PSBbCiAgICAgICAgICAgICJzb3VyY2UiLCAic2NoZW1hIiwgInRhYmxlIiwgInBlcmlvZCIsICJr
>> "%B64_FILE%" echo aG9fY29sIiwgImtob192YWx1ZSIsCiAgICAgICAgICAgICJ0aGFuX2NvbCIsICJ0aGFuX3ZhbHVl
>> "%B64_FILE%" echo IiwgInZhbHVlX2NvbCIsICJ2YWx1ZSIsICJkaWZmX3RvXzEwNTJfNjUiLCAibm90ZSIKICAgICAg
>> "%B64_FILE%" echo ICBdCiAgICAgICAgdyA9IGNzdi5EaWN0V3JpdGVyKGYsIGZpZWxkbmFtZXM9ZmllbGRuYW1lcykK
>> "%B64_FILE%" echo ICAgICAgICB3LndyaXRlaGVhZGVyKCkKICAgICAgICBmb3IgciBpbiByZXN1bHRzX3NvcnRlZDoK
>> "%B64_FILE%" echo ICAgICAgICAgICAgdy53cml0ZXJvdyhyKQoKICAgIHdyaXRlKCIiKQogICAgd3JpdGUoIj09PT09
>> "%B64_FILE%" echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PSIp
>> "%B64_FILE%" echo CiAgICB3cml0ZSgiSE/DgE4gVEjDgE5IIikKICAgIHdyaXRlKCI9PT09PT09PT09PT09PT09PT09
>> "%B64_FILE%" echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0iKQogICAgd3JpdGUoZiJG
>> "%B64_FILE%" echo aWxlIFRYVDoge09VVF9UWFR9IikKICAgIHdyaXRlKGYiRmlsZSBDU1Y6IHtPVVRfQ1NWfSIpCiAg
>> "%B64_FILE%" echo ICB3cml0ZSgiIikKICAgIHdyaXRlKCJBbmggbeG7nyBmaWxlIFRYVC9DU1YsIHTDrG0gZMOybmcg
>> "%B64_FILE%" echo bsOgbyBjw7MgVmFsdWUgZ+G6p24gxJHDum5nIDEwNTIuNjUgbmjhuqV0LiIpCiAgICB3cml0ZSgi
>> "%B64_FILE%" echo R+G7rWkgbOG6oWkgdMO0aSA1IGTDsm5nIMSR4bqndSBUT1Aga+G6v3QgcXXhuqMsIHTDtGkgc+G6
>> "%B64_FILE%" echo vSBz4butYSBiYWNrZW5kL3NlcnZlci5weSB0aGVvIMSRw7puZyBuZ3Xhu5NuIMSRw7MuIikKCiAg
>> "%B64_FILE%" echo ICBjb25uLmNsb3NlKCkKCgppZiBfX25hbWVfXyA9PSAiX19tYWluX18iOgogICAgdHJ5OgogICAg
>> "%B64_FILE%" echo ICAgIG1haW4oKQogICAgZXhjZXB0IEV4Y2VwdGlvbiBhcyBleGM6CiAgICAgICAgd3JpdGUoIiIp
>> "%B64_FILE%" echo CiAgICAgICAgd3JpdGUoIltM4buWSV0gIiArIHN0cihleGMpKQogICAgICAgIHdyaXRlKCJLaeG7
>> "%B64_FILE%" echo g20gdHJhIGzhuqFpIGvhur90IG7hu5FpIFNRTCBTZXJ2ZXIsIE9EQkMgRHJpdmVyIDE4IGhv4bq3
>> "%B64_FILE%" echo YyBxdXnhu4FuIHRydXkgY+G6rXAgREIuIikKICAgICAgICBzeXMuZXhpdCgxKQo=
python -c "import base64, pathlib, os; b=pathlib.Path(os.environ['B64_FILE']).read_text().replace('\n','').replace('\r','').strip(); pathlib.Path(os.environ['PY_FILE']).write_bytes(base64.b64decode(b))"
if errorlevel 1 (
    echo [LOI] Khong tao duoc file Python tam.
    pause
    exit /b 1
)

python "%PY_FILE%"
echo.
pause
